mitodl/micromasters

search/indexing_api.py, search/management/commands/recreate_index.py
None
Logs every chunk which is indexed to provide information on the progress of `recreate_index`
Run `./manage.py recreate_index` and verify that the output looks as expected.
=> Add logging for recreate_index

dashboard/serializers.py, dashboard/serializers_test.py, search/indexing_api.py, static/js/components/LearnerSearch.js, static/js/components/search/FinalGradeRangeAccessor.js, static/js/components/search/FinalGradeRangeFilter.js, static/scss/search-page.scss
Fix #1711
Add 'Final Grade' rangefilter to the 'Courses' filter.
Play with the Search filters. The FinalGrade range histogram will appear only if a course is selected and that course has 'paid' learners with final grades.
(Optional)
(Optional)
(Optional)
=> Final Grade Facet for Selected Course

static/js/components/LearnerSearch.js
closes #2856
This just passes a value of 0 for size to HierarchicalMenuFilter, which results in it showing all results (instead of the default, which is just the first? 20).
Go to the learner search page and confirm you can see all of the 'current residence' countries for your users.
=> fix bad searchkit default prop value

mail/permissions.py, mail/views_test.py, roles/permissions.py, static/js/components/Learner.js, static/js/components/LearnerChip.js, static/js/components/LearnerChip_test.js, static/js/components/LearnerInfoCard.js, static/js/components/LearnerInfoCard_test.js, static/js/components/PrivacyForm.js, static/js/containers/LearnerPage.js, static/scss/_button.scss, static/scss/profile.scss, static/scss/user-chip.scss
Closes #2196
- Adds the back-end functionality that will allow a paid learner to email another learner
- Replaces the email display on the profile page with an email link, which for now will only be seen by staff users
With a staff user, visit the profile of a user that has an email address and `Profile.email_optin=True`. Click the email link and make sure you can send a message. You can also use the learner mail view to send a learner-to-learner message since the link isn't viewable for other learners (yet). I'll post a code snippet to try out that email in the comments
`mail/permissions.py` and `static/js/components/LearnerInfoCard.js`
The email link is being hidden from other learners for now. We need to wait on the learner's search for learners issue …
=> Enabled learner-to-learner emails

search/api.py, search/api_test.py, search/connection.py, search/indexing_api.py, search/indexing_api_test.py, search/management/commands/clear_index.py
Fixes #2550
Does the reindex in a separate Elasticsearch index, then deletes the old one, recreates it with a mapping and replaces it with the temp index's documents. There is still a tiny amount of time where the old index will go away and come back (less than a second for 1400 documents on my computer), and there is still a risk of stale data if documents are modified during the reindex.
This PR also updates the indexing to check if the temp index exists, then update it if it does. This is to prevent stale data in the temp index from overwriting the current one.
Run a reindex and go to `/learners`. The list of learners should not change during the reindex.
=> Use temporary index during recreate_index

static/scss/search-page.scss
This PR fixes some problems with margins and padding in the search sidebar with the search facets.
Check to see that the layout is not broken, and that the code looks good.
**Before**
**After**
=> Fixes a problem with the margins in the search facets panel

static/js/components/email/EmailCompositionDialog.js, static/js/components/email/lib.js, static/js/containers/LearnerSearchPage_test.js, static/js/flow/emailTypes.js, static/js/lib/api.js, static/js/reducers/email.js, static/js/reducers/email_test.js, static/scss/email-composition-dialog.scss
Fixes #2707 
Adds the checkbox for sending emails automatically for the learner search page
On the learner search page click the checkbox and send an email. Look in your network tab and verify that `send_automatic_emails: true` was sent. Unclick the checkbox, send another email and verify that `send_automatic_emails: false` was sent.
Also open the other two email dialogs and verify that there is no checkbox at all for these two. One dialog is activated by clicking the 'send a message' link under the user chip, and the other one is the 'contact course team' link on the dashboard.
=> Add UI to send automatic emails for learner search

static/js/constants.js, static/js/lib/validation/profile.js, static/js/lib/validation/profile_test.js
Fixes #2837 
Adds validation to ensure `<`, `,` and `"` aren't allowed in names.
Try inputting the above chars into the romanized / non-romanized name fields
`static/js/lib/validation/profile.js`
=> Added validation for invalid name chars (#2837)

static/js/components/Navbar.js, static/js/components/Navbar_test.js, static/js/containers/LearnerPage_test.js, static/js/lib/roles.js, static/js/lib/roles_test.js
closes #2852
makes it so we only show the financial aid review page link to users with the appropriate permission.
make sure you have permissions for financial aid on a program. go anywhere in the site, and a link to the corresponding financial aid review page should show up.
get rid of that permission (or sign into a different account) and you shouldn't see the link any longer.
=> only show the user a link to the financial aid review page if they have the permission

static/js/components/LearnerSearch.js
This is a code improvement that will take us one step closer to resolving #2742.
Uses Searchkit's built-in functionality the way the framework expects to be used. There should be no user-visible changes as a result of this pull request.
Use the learner search. Type in prefixes of user first names and last names, and verify that you still get the results you expect. Note that this pull request will not work with combination prefixes. For example, if you have a user named "John Smith", then the queries "Jo" and "Smi" should return the user. However, the query "John Smi" is not expected to work. (That's the end goal of #2742.)
=> Improve searchkit query

cms/templates/cms/program_page.html
Part of #2462.
I found an image reference in our HTML template that wasn't being loaded from CloudFront. This pull request changes that template to load the image from CloudFront. There should be no user-visible impact to this pull request.
View the program page, and inspect the edX logo on the right sidebar, below the "More Info" box. It should load from CloudFront on the RC server, and on production.
=> Load the edX logo from CloudFront on the program page

cms/templates/cms/home_page.html, static/scss/dashboard.scss, static/scss/homepage.scss, static/scss/navbar.scss, static/scss/page-layout.scss, static/scss/search-page.scss, ui/templates/header.html
This PR fixes some layout issues, and makes several other small style tweaks to the app, and the marketing site (some on mobile only):
- Small change to arrow placement and opacity in the sidebar
- Changes the style of the "Dashboard" and "Sign Out" links to look like links, not buttons.
- Improves the layout of the quote section on the home page for mobile devices (images and text are centered on mobile).
- Slight change to font-size and font-weight for the user name in Learner search results
- Fixes padding in learner search sidenav when there are No hits 
- Slight tweak to .page-content top padding
- Fixed spacing between programs on mobile 
- Changed width (margins) of sub-banner text on mobile
Check the small changes and see that the layout still looks ok.
=> Various small style tweaks

static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js
Fixes #2870 
Adds restriction that financial aid must be in terminal state to see the pay now button
Get your dashboard to a state where there's the option to pay for a course in a financial aid program. Create a new financial aid with an income small enough to require manual approval. Submit the document sent date. The pay now button should be greyed out. In the UI or the shell approve the financial aid, then refresh the browser and the pay now button should be active again.
=> Restrict pay now button to when financial aid is in terminal state

selenium_tests/basic_test.py, static/js/containers/DashboardPage.js, static/js/dashboard_routes.js
Fixes #2878 
Fixes lifecycle handling in DashboardPage so the back button will work as expected
Click 'Pay now' and it should direct you to the order summary page. Press the back button and you should be back at the dashboard without an error.
=> Fixed lifecycle handling of DashboardPage to reload cleared items

dashboard/api.py, dashboard/api_edx_cache.py, dashboard/api_edx_cache_test.py, dashboard/api_test.py, dashboard/views.py, dashboard/views_test.py, static/js/components/ProgramEnrollmentDialog_test.js, static/js/components/StaffLearnerInfoCard_test.js, static/js/components/dashboard/CourseAction_test.js, static/js/components/dashboard/CourseListCard_test.js, static/js/components/dashboard/CourseRow_test.js, static/js/components/dashboard/CourseSubRow_test.js, static/js/components/dashboard/DashboardUserCard_test.js, static/js/components/dashboard/FinalExamCard_test.js, static/js/components/dashboard/FinancialAidCard_test.js, static/js/constants_test.js, static/js/containers/DashboardPage_test.js, static/js/containers/FinancialAidCalculator_test.js, static/js/containers/LearnerPage_test.js, static/js/factories/dashboard.js, static/js/flow/dashboardTypes.js, static/js/lib/coupon.js, static/js/lib/coupon_test.js, static/js/reducers/dashboard.js, static/js/reducers/dashboard_test.js, static/js/test_constants.js, static/js/util/test_utils.js, static/js/util/util_test.js
first part of #2181 
Changes tha data structure of the dashboard rest api and the JS code that uses it.
It also adds an extra key to the dashboard rest api response to specify if the edX cached data is fresh.
The dashboard REST API should not fail even if the backend edX instance is not available.
This is necessary to implement the message in the dashboard to specify if the cache has not been refreshed.
The dashboard should work as usual.
if you shut down the edX backend instance, the dashboard should still load.
`static/js/reducers/ashboard.js`
Most of the changes are in the JS tests because of the change in the structure of the response JSON coming from the REST API
=> Modified Dashboard REST API to include edx data freshness status

dashboard/api.py, dashboard/api_test.py, static/js/components/StaffLearnerInfoCard.js, static/js/components/StaffLearnerInfoCard_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/lib/sanctuary.js, static/js/lib/sanctuary_test.js
closes #2853 
If the user has a program average grade we'll show it on the staff view of the learner page.
Well, if you already have a program average grade it should show up on `/learner`. If you don't you should see `--` instead.
if you don't have a program average grade you can use my API mocking patch, here: https://github.com/aliceriot/mm_patches/blob/master/mock_api.patch
to get a dashboard (for 'Last Program') which includes the `grade_average` property. Or I suppose you could edit the relevant line in `dashboard/api.py` to just return a number.
=> show average grade on the staff view of learner page

.gitignore, dashboard/utils.py, search/management/commands/recreate_index.py
Fixes #2893
Optimizes two `QuerySet`s in `get_pearson_exam_status` that could be done in less queries and by fetching less data overall. Locally I found this to reduce time spent in that method by ~80% (1.6s -> 0.3s). This should regain some performance that was lost in reindexing and the dashboard api, although it was probably only noticeable in aggregate.
Be sure you can load the dashboard and run `./manage.py recreate_index`. Also run `./manage.py recreate_index --profile` and be sure that outputs a `.profile` file for you. `python -m pstats <filename>` if you want to interact with the results.
dashboard/utils.py
=> Optimized the exam status query in MMTrack

static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/scss/dashboard.scss
closes #2181 
adds an error message box in case the dashboard rest API returns that the edX cache is not fresh
stop the backend edX instance and refresh the dashboard (wait 6 minutes to be sure that the cache is not fresh any more)
`static/js/containers/DashboardPage.js`
=> Added message for failed edx cache refresh

search/indexing_api_test.py, search/signals.py
fixes https://github.com/mitodl/micromasters/issues/2521
- When role is created or deleted it reindexes es.
- open `http://192.168.99.100:8079/learners/` search a user.
- open `http://192.168.99.100:8079/admin/roles/role/` create staff access for that user on selected program.
-  refresh `http://192.168.99.100:8079/learners/` and search the same user. You will not find her because she is now staff. And we omit staff from the es results.
- open `http://192.168.99.100:8079/admin/roles/role/` and remove staff access for the same user on selected program.
-  refresh `http://192.168.99.100:8079/learners/` and search the same user. You will be able to see her now because she is not staff anymore.
@giocalitri @pdpinch
=> Reindexed search on adding or deleting user role

static/js/containers/LearnerPage.js, static/js/containers/LearnerPage_test.js
Fixes #2905 
Fixes #2907
Fixes handling of `FETCH_FAILURE` to prevent a refresh loop on dashboard error
On master, in `lib/api.js` have `getDashboard` return `Promise.reject()` then load the learner page. It should cause the loop. Switch to this branch and repeat the change to `lib/api.js` and the failure should only happen once.
=> Fix refresh loop on learner page

static/js/components/ProgressWidget.js, static/js/components/ProgressWidget_test.js, static/scss/_button.scss, static/scss/dashboard.scss
Fixes #2900 
Improves consistency and accessibility of disabled buttons in the application. Now all disabled buttons should have `$medgrey` background color, white text, and a "not allowed" cursor on hover.
Go to the dashboard for a financial aid program, before you've calculated your financial aid. Make sure that the disabled "pay now" buttons are consistent, as well as the disabled "Apply for Masters" button on the right side of the page. Check the screenshots to see what I mean.
=> Improve disabled UI buttons

static/js/containers/ProfileImage.js, static/js/containers/ProfileImage_test.js
Fixes #2912
Only renders `ProfileImageUploader` for the logged in user
Go to `/learners` and make sure there is more than one row in the learner view. Open the nav bar and click 'Edit Photo'. You should be able to upload a new photo.
=> Show image upload only for logged in user

static/js/actions/course_enrollments.js, static/js/actions/course_prices.js, static/js/actions/course_prices_test.js, static/js/actions/documents.js, static/js/actions/financial_aid.js, static/js/actions/index.js, static/js/actions/index_test.js, static/js/actions/programs.js, static/js/containers/App_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/containers/FinancialAidCalculator_test.js, static/js/containers/OrderSummaryPage.js, static/js/containers/test_util.js, static/js/flow/dashboardTypes.js, static/js/reducers/course_enrollments_test.js, static/js/reducers/course_prices.js, static/js/reducers/course_prices_test.js, static/js/reducers/dashboard.js, static/js/reducers/documents_test.js, static/js/reducers/financial_aid_test.js, static/js/reducers/index.js, static/js/reducers/index_test.js, static/js/reducers/programs_test.js, static/js/reducers/util.js
closes #2923 
This just refactors the frontend code for the course price API to support namespacing based on username.
To facilitate this I also moved the course price reducer into a separate file.
I think just make sure you can visit the dashboard page and order summary page, and that everything looks normal on them (and no runtime errors). If we get that and the tests are all passing I think we're good.
=> refactor course price actions and reducer

static/js/components/dashboard/CourseDescription.js, static/js/components/dashboard/CourseDescription_test.js
Fix #2916
Remove 'view on edx' link for courses for staff when viewing learners page.
As staff, go to view learner's page. Make sure there is a course with a valid edx link.
(Optional)
(Optional)
(Optional)
=> Removed 'view on edx' link for staff

profiles/models_test.py, seed_data/management/commands/attach_avatars.py, seed_data/management/commands/attach_avatars_test.py
None
Fixes the parameter used for `attach_avatars` and adds a test for the command
Run `./manage.py attach_avatars --username-prefix fake` to use robotic avatars on your fake users
=> Fix parameter in attach_avatars

grades/management/commands/check_final_grade_freeze_status.py, grades/management/commands/complete_course_run_freeze.py
fixes #2930
fixes a bug with the `gdm_grade_task_fail_bug` management command.
Submit a freeze task for a course run using the `freeze_final_grades`, then check the status with `gdm_grade_task_fail_bug`: it should not raise any more.
=> Fixed bug with gdm_grade_task_fail_bug management command

static/js/components/dashboard/CourseDescription.js, static/js/components/dashboard/CourseDescription_test.js
Fix #2917
Changed course description to show: Auditing or Paid
for both staff and learner views.
As a learner run management commands to set a course to different states, for example:
```
./manage.py alter_data set_to_enrolled --username=staff --program-title='Analog' --course-title='100' --audit
```
And check the dashboard to the course status (as a learner and as staff viewing learner's page).
=> Changed course description to show: Auditing or Paid

static/js/actions/course_enrollments.js, static/js/actions/course_enrollments_test.js, static/js/actions/course_prices.js, static/js/actions/ui.js, static/js/actions/ui_test.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseListCard_test.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/flow/dashboardTypes.js, static/js/reducers/course_prices.js, static/js/reducers/course_prices_test.js, static/js/reducers/dashboard.js, static/js/reducers/dashboard_test.js, static/js/reducers/index_test.js, static/js/reducers/ui.js, static/js/reducers/ui_test.js, static/scss/dashboard.scss
fixes https://github.com/mitodl/micromasters/issues/1445
- Show inline success message when user press enroll and pay later button,
- It also loads dashboard page without reloading whole page
- Open `http://192.168.99.100:8079/dashboard/` and press enroll and pay later.
=> Enroll and pay later: Load dashboard page without reloading

dashboard/api.py, dashboard/api_test.py, dashboard/serializers.py, dashboard/utils.py, dashboard/utils_test.py, exams/utils.py, grades/models.py, seed_data/management/commands/alter_data_test.py
No ticket. This is being done as part of the larger effort to clean up the dashboard API and MMTrack
Generally refactors the final grade-related code in `MMTrack`. More specifically:
- Does away with the exception-raising behavior related to fetching a final grade for a user's course run.
- Refactors several methods to use single database queries where they previously looped through course run id's and executed a query for each one.
- Fixes inconsistent function naming.
`alter_data` can be used to set course runs to be passed/failed, and can then be confirmed on the dashboard page
`dashboard/utils.py`
While working on #2890, I noticed a few code smells in `dashboard.utils.MMTrack` related to final grades. Some of the issues:
- `extract_final_grade` was using Django's `get`, which throws …
=> Cleaned up MMTrack final grade code

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, dashboard/utils_test.py, exams/utils.py, financialaid/serializers.py, financialaid/serializers_test.py, mail/permissions.py
Closes #2929
~~⚠️ Rebased on #2909 ⚠️~~
Cleans up more `dashboard.utils.MMTrack` code, building off of the work in #2909. The details about the fixes are in the #2929 issue description.
Test that changes to user course data result in the expected changes to the dashboard output. The `alter_data` management command can be used to this end (`manage.py alter_data examples`).
`dashboard/utils.py`
=> Cleaned up more MMTrack code

dashboard/serializers.py, dashboard/serializers_test.py, dashboard/utils.py
Related to #2939
Change the logic the search serializer for three facets ( courses, final grade, and semester) to use final grades and cached enrollments to identify all current and past enrollments for a user.
Users with no enrollment, but a final grade for a course should appear in the search results.
=> Update UserProgramSerializer to use current enrollments and existing grades

search/tasks.py, search/tasks_test.py
Fixes #2959 
Adds a couple `refresh_index` commands to flush updates to the index before we run percolate. This should make sure the program enrollment exists by the time we run percolate on it.
I don't think it's easy to reproduce. We will just need to keep an eye on sentry.
=> Add refresh_index to fix race condition with percolate

grades/models.py, grades/models_test.py
N/A
Fixes bug where a `grade_percentage` for a grade equal to 0 returns `None`
Create a final Grade with grade 0 and run the reindex
=> If you check for None values you need to be specific.

RELEASE.rst, dashboard/api.py, dashboard/api_test.py, dashboard/serializers.py, dashboard/utils.py, dashboard/utils_test.py, exams/utils.py, financialaid/serializers.py, financialaid/serializers_test.py, grades/models.py, mail/permissions.py, micromasters/settings.py, seed_data/management/commands/alter_data_test.py, static/js/components/OrderSummary.js
=> Release 0.53.5

financialaid/urls.py, financialaid/views.py, financialaid/views_test.py, micromasters/urls_test.py, static/js/actions/course_prices.js, static/js/lib/api.js, static/js/lib/api_test.js
closes #2933
this refactors the the course price API so that it isn't limited to just fetching information for the currently logged in user.
The dashboard and so on should work as normal.
=> refactor course price API to take a 'username' url parameter

backends/edxorg.py, backends/edxorg_test.py, backends/utils.py, dashboard/tasks.py, micromasters/settings.py, micromasters/urls.py, requirements.in, requirements.txt, runtime.txt
closes #2850
Switches to the new library for python social auth and removes the deprecated one.
Everything should keep working and the existing social auth should be left intact.
NOTE: I added an upgrade of the runtime of python to the latest version
=> Switched library for python social auth

runtime.txt
N/A/
Reverts the change of the python version for Heroku
Heroku should just stop screaming
=> Bringing back the runtime to python-3.5.2

search/api.py, search/api_test.py, search/exceptions.py
Fixes #2959 
Changes percolate to use the serialized document instead of a document id. This should allow the percolation to work even when the original document has not been fully indexed in Elasticsearch yet.
None, the bug cannot be easily reproduced.
=> Do percolate on document instead of document id

search/indexing_api.py, search/indexing_api_test.py, search/signals.py, search/tasks.py
Fixes #2718 
Removes signal and related task and functions for removing an enrollment from the index when a profile is deleted. We are currently not deleting profiles and it seems like this function is likely to fail since it looks up the enrollments in the database after the profile is already deleted.
None
=> Remove remove_user

static/js/components/ProgressWidget.js, static/js/components/ProgressWidget_test.js
fixes https://github.com/mitodl/micromasters/issues/2979
- removed `Apply for Master` and text from progress widget.
- go to /dashboard and see widget on the right side
@pdpinch
=> Progress widget: Removed apply for master button and text

profiles/models.py, profiles/models_test.py
Fixes #2998 
Handles case where main profile image is empty. If it's empty and `update_image=True`, the thumbnails will be empty too
Set a user's profile image to be empty using the shell with `update_image=True`, and verify that the main thumbnails are empty too (`image_small` and `image_medium`).
=> Set thumbnails to null if main image is null

requirements.in, requirements.txt
part of #2696
upgrades to Celery 3.1.25 as suggested in http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#step-1-upgrade-to-celery-3-1-25
Everything should just keep working as before
=> Upgraded celery to 3.1.25 as 1st step to migrate to celery 4

package.json, profiles/models.py, static/js/babelhook.js, static/js/components/LearnerSearch.js, static/js/components/email/AutomaticEmailOptions.js, static/js/components/search/EducationFilter.js, static/js/components/search/WorkHistoryFilter.js, static/js/containers/App_test.js, static/js/containers/DashboardPage_test.js, static/js/containers/LearnerPage_test.js, static/js/containers/LearnerSearchPage_test.js, static/js/containers/OrderSummaryPage_test.js, static/js/containers/SettingsPage_test.js, static/js/global_init.js, static/js/test_constants.js, yarn.lock
Fixes #2963 
Fixes #3009 
Uses a reverse nested aggregation to ensure that the education count is per person, not per education. It also fixes a problem with the searchkit id for the work history facet and fixes the tests to mock the elasticsearch responses properly.
For a user set up two `Employment` objects which are both current for the same company name (non-current employments are filtered out). Using the search box filter the name of the user so that they are the only user in the learner search page. Verify that the work history facet shows the employment for that user with a `(1)` in the name.
Do a similar thing for `Education` but with two `Education` objects for that user who have the same degree type. You should see `1` next to the degree type in the facet.
=> Use reverse nested aggregation for education and fix related tests

static/js/components/LearnerSearch.js, static/js/components/search/ModifiedSelectedFilter.js, static/js/constants.js
Fix #2964
Change the selected filter tag to display the filter name instead of the `field` prop.
Create SelectedFilter component to override the `SelectedFilters` component.
Go to learners search and select filters. Check the labels:
=> Search: Fix SelectedFilters titles

static/js/components/email/EmailCompositionDialog.js, static/js/components/email/EmailCompositionDialog_test.js, static/js/components/email/hoc.js, static/js/components/email/lib.js, static/js/flow/emailTypes.js, static/js/reducers/email.js, static/scss/_variables.scss, static/scss/email-composition-dialog.scss
fixes https://github.com/mitodl/micromasters/issues/2953
- Added filers selected on learners search to email composer as recipients
- Go to `/learners/` select filters and open `Email These Learners`.
=> Mail: displayed search filters as recipients

dashboard/serializers.py, dashboard/serializers_test.py, dashboard/utils.py, search/indexing_api.py, static/js/components/LearnerSearch.js, static/js/components/search/EducationFilter.js, static/js/components/search/FilterVisibilityToggle.js, static/js/components/search/NestedAggregatingMenuFilter.js, static/js/components/search/WorkHistoryFilter.js, static/js/containers/LearnerSearchPage_test.js, static/js/test_constants.js, static/scss/search-page.scss
Fixes #2942
Fixes the bug we had where search results were being filtered in ways that our users weren't expecting. Filters on our course enrollments were being treated as 'OR' filters rather than 'AND', and the number of results being reported was a count of the nested documents that matched rather than the number of users.
I'll add some detail here later, but in general, you want to get users into a state where there is a venn-diagram-like overlap between course enrollments based on course title, course payment statuses, and enrolled semesters.
Probably dashboard/serializers.py and static/js/components/search/NestedAggregatingMenuFilter.js
1. The per-course final grade histogram was removed and will be reimplemented in another issue.
1. The course payment status was moved to its own …
=> Fixed unexpected course enrollment counts/results in learners search

dashboard/utils.py, dashboard/utils_test.py
fixes #2995 
Changes the behavior of `mmtrack.has_paid` to handle the FA courses in the right way
Create a final grade with `course_run_paid_on_ed=True` for a course run in a FA program and verify that it is still not paid in the dashboard.
Adding an order and a line for the same course will turn the course to paid.
=> Modified the mmtrack has paid to better handle FA programs

tox.ini
Fixes #2983 
Removes `passenv = *` and whitelists the environment variables we pass in so that they only cover ones necessary for the tests to connect to services they need.
No manual testing needed
=> Add specific environment variables to tox.ini instead of using *

mail/serializers.py, mail/serializers_test.py, mail/urls.py, mail/views.py, mail/views_test.py, static/js/actions/automatic_emails.js, static/js/components/EmailCampaignsCard.js, static/js/components/EmailCampaignsCard_test.js, static/js/components/Navbar.js, static/js/components/Navbar_test.js, static/js/containers/AutomaticEmailPage.js, static/js/containers/AutomaticEmailPage_test.js, static/js/dashboard_routes.js, static/js/flow/emailTypes.js, static/js/flow/restTypes.js, static/js/flow/sanctuaryTypes.js, static/js/lib/redux_rest.js, static/js/lib/redux_rest_test.js, static/js/reducers/automatic_emails.js, static/js/reducers/automatic_emails_test.js, static/js/reducers/index.js, static/js/test_constants.js, static/js/util/test_utils.js, static/scss/automatic-emails.scss, static/scss/layout.scss, ui/url_utils.py
closes #3011
This
- adds a new page (at `/automaticemails`) which allows staff users to edit automatic emails that they created
- adds a link to the sidebar nav to this page, which appears if you are staff
- added some redirect protection, so that if you do not have a staff role you will be redirected away from the automatic emails page (even though the API wouldn't let you see anything anyway)
I think that's it!
Confirm the following things:
- a link to the email page shows up in the sidebar if you are staff, and not if you are a learner
- the automatic emails page shows any automatic emails you've created.
- the automatic emails page should show a placeholder message if you haven't yet created any.
- the automatic emails page should show a spinner while the GET request is in-flight
- …
=> add automatic email index page

Dockerfile, apt.txt
Part of #2674 
Upgrades postgres client. This is needed to fix the version incompatibility to do the database dump required in #2674 
NA
@aliceriot after this is merged can you update the relevant image in Docker hub?
=> Upgrade postgres-client

static/js/actions/course_enrollments.js, static/js/actions/course_prices.js, static/js/actions/dashboard.js, static/js/actions/email.js, static/js/actions/index.js, static/js/actions/profile.js, static/js/actions/programs.js, static/js/containers/App_test.js, static/js/containers/DashboardPage.js, static/js/lib/api.js, static/js/lib/api_test.js, static/js/lib/redux_rest.js, static/js/lib/sanctuary.js, static/js/lib/sanctuary_test.js
none
I was looking at a JavaScript error in Sentry this morning and I realized (after reading [this issue](https://github.com/facebook/react/issues/7617), among others) that our error handling for `Promises` is done incorrectly, in a way that can swallow errors and lead to some strange behavior.
In short, these two things are not equivalent:
```js
// pattern we have in our code a fair amount right now:
promise.then(success => {
doSomethingWithSuccess(success);
return Promise.resolve(success); // maybe, we don't always do this
}).catch(error => {
ohNoAnError(error); // :(
return Promise.reject();
};
// correct pattern
promise.then(success => {
doSomethingWithSuccess(success);
return Promise.resolve(success); // maybe, we don't always do this
}, error => {
ohNoAnError(error); // :(
return …
```
=> fix Promise error handling

selenium_tests/base.py, selenium_tests/pytest.ini
Fixes #2674 
Saves and restores the database after each selenium test. Running migrations from scratch takes roughly 30 seconds so this will greatly speed up selenium tests in the future.
Tests should pass. Selenium tests should be roughly 30 seconds faster than before.
This ignores the keepdb flag, see #3030 for that
=> Save database state during selenium tests

static/js/components/email/hoc.js, static/js/components/email/hoc_test.js
Fixes #3043 
Fixes null reference error when email dialog is rendered without a matching config
- Open an email dialog, either the course email dialog on the dashboard or one of the dialogs from the learner search page. 
- Close it, you don't need to enter any text or submit it
- Navigate to profile page by clicking the hamburger menu icon on the upper left and clicking 'My profile'. On master you should get an exception but in this PR it should behave as expected.
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/228916007/
=> Fixed handling of currently active email dialog on page without config

static/js/components/search/ModifiedSelectedFilter.js, static/js/constants.js
fixes https://github.com/mitodl/micromasters/issues/3037
Fixed a regression which is cased by https://github.com/mitodl/micromasters/issues/2942. So that selected search filter display fine.
- go to learners search page and select semester from facets.
@pdpinch
=> Fixed selected search filter label regression

static/js/components/LearnerSearch.js
Fixes #3040
Fixes the ordering of courses in the search facet
See details in comment
These courses were never actually being ordered by their position in the program. The order is (presumably) a result of the id's of the courses, which coincidentally matches an ordering based on the `Course.position_in_program` value. If we want to make this _actually_ order on `position_in_program`, we should do that in a separate issue (FYI @pdpinch)
=> Fixed faulty course ordering in search facet

static/js/components/EmailCampaignsCard.js, static/js/components/EmailCampaignsCard_test.js, static/js/components/email/constants.js, static/js/components/email/hoc.js, static/js/components/email/lib.js, static/js/components/email/lib_test.js, static/js/containers/AutomaticEmailPage.js, static/js/reducers/email.js, static/js/util/util.js, static/js/util/util_test.js, static/scss/automatic-emails.scss
closes #3028 
This adds the ability to edit the already-created automatic emails.
Make sure you have an automatic email, and to go `/automaticemails`. You should be able to click the 'edit' link and edit the subject or body of the email there.
=> add automatic email admin editing

static/js/components/Navbar.js, static/js/components/Navbar_test.js
fixes https://github.com/mitodl/micromasters/issues/3054
Hides menu icon when user is logged out
Open url `http://192.168.99.100:8079/learner/(user name)`
@pdpinch
=> Fixed menu icon display when user is logged out

static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js
fixes https://github.com/mitodl/micromasters/issues/2975
Fixes message on contact course dialog for non fa programs.
- open admin panel and add contact email to a course,
- then open dashboard and load the respective program
- click in contact course team link. Do this for programs with `financial aid` and  `no financial aid`
@pdpinch
=> Fixed course contact message for non fa courses

selenium_tests/base.py, selenium_tests/basic_test.py, static/js/components/ProgramFilter.js, static/js/containers/LearnerSearchPage_test.js
Fixes #3003
Changes `ProgramFilter` to use a `StatefulAccessor` which lets us propagate changes in the current enrollment to the state of the accessor when they happen. This lets us remove the workaround which calls `searchkit.resetState()`  which caused the existing query parameters to be removed.
Go to `/learners/?q=xyz` and verify that you see a text box with `xyz` in it. Click a facet then refresh the browser. It should remain selected after refresh. Switch programs and you should see the list of people change accordingly.
This changes the behavior where we clear the search when switching between programs. I'm not sure what the ideal is here so I just left it alone.
=> Preserve search URL on reload

cms/templates/cms/program_page.html
fixes https://github.com/mitodl/micromasters/issues/3045
Changes text on 'Future Semester Dates'.
Create a program page from CMS and add semester and publish it. Then go to that page and view 'Future Semester Dates' section.
@pdpinch
=> CMS: Text changes to 'Future Semester Dates' section

config/nginx.conf, config/nginx.conf.erb, micromasters/settings.py
fixes https://github.com/mitodl/micromasters/issues/2988
Fixes the max upload size of the file.
- Use max 25mb image or pdf and upload to `http://192.168.99.100:8079/cms/documents/multiple/add/`
@pdpinch
=> CMS: increased file upload size of a document

static/js/components/search/CustomNoHits.js, static/js/components/search/CustomNoHits_test.js
fixes https://github.com/mitodl/micromasters/issues/2182
- Show static error message in case of search error.
- Search some there where you are sure of no data
@pdpinch
=> Search: fixed error message, when there are no results

static/js/components/email/EmailCompositionDialog_test.js, static/js/components/email/lib.js
fixes https://github.com/mitodl/micromasters/issues/3071
Fixes regression of #2942, key if recipients object.  
select filter and open email dialog.
@pdpinch
=> [Regression] Fixed recipient keys on email composition dialog

static/js/components/dashboard/FinancialAidCard.js
fixes https://github.com/mitodl/micromasters/issues/2432
It fixes the issue on dashboard, which appears when you clear a date field using keyboard from FA calculator, when state is pending-doc. This is because date object is null at that time.
We dont need validation here because date widget is sticky, when u remove date and focus out the text field it automatically picks the current date.
- Go To dashboard, 
- Land to FA calculator with state pending doc. 
- Try to clear date using back space/delete
- See the console, there must be no error
- Focus out the text field, you will see the current date on it
@pdpinch
=> Fixed issue where date change is empty

seed_data/lib.py, seed_data/management/commands/alter_data.py, seed_data/management/commands/alter_data_test.py
Fixes #3072 
- Fixes the way that `alter_data` sets a user's payment status and grade for course runs
- Cleans up some docs
- Removes some obsolete functions
Run commands that change your user's payment/grading status in some course runs. Example commands:
```shell
alter_data set_to_enrolled --username=YOUR_USERNAME --course-title='Analog Learning 100' --audit
alter_data set_to_enrolled --username=YOUR_USERNAME --course-title='Analog Learning 100'
alter_data set_to_passed --username=YOUR_USERNAME --course-title='Analog Learning 100' --audit
```
Do this with both 'Analog Learning' (non-FA) and 'Digital Learning' courses
`alter_data.py`
=> Fixed alter_data payment and grade issues, and cleaned up docs

grades/management/commands/freeze_final_grades.py
N/A
fixes a management command that was not updated to call the celery task using the ID and not an object
run the management command: it should not raise a JSON serialization error
=> Fixed bug with freeze grade management command not using the right value in a call

docker-compose.yml, travis-docker-compose.yml
N/A, blocking deployments because failing Travis.
Fixes selenium tests that are failing Travis tests because new tags for the container got pushed.
If Travis passes, we're good.
:notes: Cause if you want it to pass you better put a pin on it. :notes:
=> Pin selenium container to a non-broken version

courses/factories.py
Fixes #3093
Increases the lowest `Program.price` the factory will generate so that the second generated `ProgramTier.discount_amount` will never be 0.
=> Fixed ProgramFactory price values (#3093)

static/js/components/dashboard/FinalExamCard.js, static/js/components/dashboard/FinalExamCard_test.js, static/scss/dashboard.scss
fixes https://github.com/mitodl/micromasters/issues/3086
- Updates Pearson TOS text on a dialog, see image below
- you must have `FEATURE_EXAMS=True` flag.
- and `program.pearson_exam_status=PEARSON_PROFILE_SCHEDULABLE` in `static/js/components/dashboard/FinalExamCard.js`
@pdpinch
=> Exams: Updated Pearson TOS text

financialaid/views.py, financialaid/views_test.py
fixes https://github.com/mitodl/micromasters/issues/1928
hid social icons and public things from footer of FA review
go to FA review form and see social icons are not available.
@pdpinch
=> Switched off is_public flag from financial_aid footer

static/scss/_variables.scss, static/scss/search-page.scss
On the learner search page:
- Slightly increases the size of the user image
- Slightly tightens row padding in search results
- changes font weight for facet options
- changes filter options background color to blue
See that the changes work.
=> Some small tweaks to visual styles

profiles/permissions.py, profiles/permissions_test.py, profiles/views_test.py
https://github.com/mitodl/micromasters/issues/2947#issuecomment-296650753
- Now non staff users can view  public_to_mm profiles, when they are enrolled in one of the programs where profile user is enrolled.
- Staff can already view profiles.
- Create a learner and try to view profile of other learner in same program.
- Create a learner and try to view profile of other learner in other program.
@pdpinch
=> Shown public_to_mm profiles when requesting user is enrolled in one of the programs where profile user is enrolled

mail/api.py, mail/utils.py, mail/utils_test.py
Related to #2949
Convert users inserted variables like `[PreferredName]` to mailgun recipient variables `%recipient.preferred_name%`
Send an email to your user (with your email address). Use [PreferredName] and [Email] in the header or body of the email. Make sure your variable `MAILGUN_RECIPIENT_OVERRIDE` is not set.
=> Mail: Filter recipient variables

static/scss/toast.scss
fixes https://github.com/mitodl/micromasters/issues/2725
CSS fix to align toast message to center.
Go to dashboard enroll in a course, you will get a message.
@pdpinch
=> Center align toast message

static/scss/email-composition-dialog.scss
fixes https://github.com/mitodl/micromasters/issues/3111
fixes the style of radio buttons on email dialog search.
Go to learners search page as staff and op email dialog
=> Firefox fixed email type radios

docker-compose.yml
None
Skips confirmation for the migrate command run when starting the web docker container.
Run `docker-compose up` and verify that the web container is up and running
=> Don't prompt for confirmation when running migrations locally

mail/api.py, mail/views.py, mail/views_test.py
Part of #2241 
Fixes a bug where `send_batch` was expecting email/context pairs but we were only sending the context.
With `MAILGUN_RECIPIENT_OVERRIDE` set, go to the learner search page. Send an email to some selection of users with the automatic option selected. Verify that you received an email with the list of emails that matches the search list (some may be missing if `email_optin` was false for that user)
=> Fix sending mails with automatic checked

exams/api.py, exams/api_test.py
Fixes #3133
Addresses a race condition where the signal that triggers on `ExamRun.post_save` incorrectly sets `ExamAuhorization.operation` to `ExamAuthorization.OPERATION_UPDATE` when they haven't been created yet.
- Ensure you have a user with that is paid and has a final grade for a course
- Create an exam run for that course, set schedule first date to now
- Run `exams.tasks.authorize_exam_runs()` and ensure you get an `ExamAuthorization and it keeps `operation == 'update'`
=> Fixed exam auth operation on exam run update (#3133)

courses/factories.py
Fixes #3113 
Converts the factory to use a sequence so the keys don't collide.
=> Fixed CourseRunFactory.edx_course_key against collisions (#3113)

exams/pearson/writers.py, exams/pearson/writers_test.py
Fixes #3142 
Adds this column back in but with an fixed empty string value
Tests should pass, this is simple enough change.
=> Fixed missing module column in exam auth export (#3142)

RELEASE.rst, courses/factories.py, exams/pearson/writers.py, exams/pearson/writers_test.py, micromasters/settings.py, tox.ini
=> Release 0.57.4

exams/api.py, exams/api_test.py
Fixes #3146 
Adds a check not to update `ExamAuthorizations` if the `ExamRun` is not currently schedulable.
If the tests pass, that's sufficient.
=> Fixed an issue with old ExamAuthorizations updating (#3146)

dashboard/api.py, dashboard/api_test.py
Fixes #3150 
Updates the function we use to show schedulable exams on dashboard to respect schedulable `ExamRun`s.
-  Ensure you have an `ExamProfile` record in `status=ExamProfile.PROFILE_SUCCESS` for your user.
- Be sure `FEATURE_EXAMS_CARD_ENABLED=True` in `.env`.
- Create 3 exam run for each of 3 different courses (past/present/future):
```python
from courses.models import Course
er1=ExamRunFactory.create(course=Course.objects.get(title='Digital Learning 100'))
er2=ExamRunFactory.create(course=Course.objects.get(title='Digital Learning 200'), scheduling_past=True)
er3=ExamRunFactory.create(course=Course.objects.get(title='Digital Learning 200'), scheduling_future=True)
ExamAuthorizationFactory.create(user=user, …
```
=> Fixed is_exam_schedulable to check schedule dates (#3150)

static/scss/program-page.scss
https://github.com/mitodl/micromasters/issues/2811
This is a very small css change, so that the h3 header styles are consistent on all tab pages. Currently, the H3 header on the FAQ page has a selector specifically for that page. This PR, makes the selector for H3 applicable to all tab pages.
To test this, create a new program page tab in the CMS. In the rich text editor, enter some text and make it an H3. See that this style matches the header style on the current program page FAQ tab.
=> Small css change to headers on tab pages

static/js/components/CourseEnrollmentDialog.js, static/js/components/CourseEnrollmentDialog_test.js, static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/containers/DashboardPage.js
fixes https://github.com/mitodl/micromasters/issues/3105
Redirects user to course enrollment page instead of progress summary for Non financial aid programs only.
- Set course enrollment url from admin panel to non FA course run.
- Go to non FA program on dashboard
- Click `pay now` button.
- You will be redirect to course enrollment page. 
@pdpinch
=> Bypassed order summary for non FA courses and redirect users to edX course enrollment page

static/js/components/dashboard/CourseGrade.js, static/js/components/dashboard/CourseGrade_test.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/scss/dashboard.scss
a temporary shim for part of #2792
this just implements a super basic display of the highest exam grade (per-course) on the dashboard.
Add an exam grade to a course you're enrolled in, and you should see it on the dashboard. Add two exams, and you should see the highest grade.
=> implement simple exam grade display

RELEASE.rst, exams/api.py, exams/signals.py, exams/signals_test.py, micromasters/settings.py, static/js/components/CourseEnrollmentDialog.js, static/js/components/CourseEnrollmentDialog_test.js, static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/containers/DashboardPage.js, static/scss/program-page.scss
=> Release 0.57.7

ecommerce/api_test.py, ecommerce/models.py, ecommerce/models_test.py, ecommerce/serializers_test.py
Fixes #3157 
Fails validation if the user creates a course run coupon.
Try to create a course run coupon in the Django admin or the Django shell. It should cause a validation error.
We shouldn't have any course run coupons and we don't have any plans to have them in the future, so this PR should cut down the number of edge cases we deal with.
=> Prevent course run coupons from being created

static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/components/dashboard/CourseSubRow.js, static/js/components/dashboard/CourseSubRow_test.js
Fixes #3176
Changes the message for FA courses when we have a final grade + exam.
- Create an enrollment, final grade, and proctored exam grade for a past course. Check the dashboard and be sure you see the expected message.
- Repeat the above for a current course.
=> Added temporary message for FA final grades (#3176)

static/js/constants.js
Part of #3095 
Adds a label for the selected facets component for "# of courses passed"
Go to learner search (Analog), filter on "# of courses passed" and be sure the label shows up on the selected filters bar under the search box.
=> Added label for num courses passed (#3095)

static/js/components/email/EmailCompositionDialog.js
closes #3181 
this fixes the check we do to see if we need to reload the email composition dialog body.
follow the steps for reproducing the bug in the attached issue on master. then switch to this branch, follow the same steps, and ensure it's fixed.
=> fix email composiition dialog body loading

static/js/components/search/EducationFilter.js
Fixes #3183 
Fixes an issue where SearchKit can send us error info in the bucket data (see ticket for details).
- Go to learner search
- Filter on education
- Filter on other criteria untli you get 0 results (search on a nonexistent name being easiest)
- Reload the page and verify you get the same UI and not the "There are no users in the Analog Learning program." error.
=> Fixed error with bucket reference (#3183)

static/js/components/CourseEnrollmentDialog.js, static/js/components/CourseEnrollmentDialog_test.js, static/js/components/OrderSummary.js, static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseListCard_test.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/js/components/dashboard/CourseSubRow.js, static/js/components/dashboard/CourseSubRow_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/containers/LearnerSearchPage_test.js, static/js/containers/OrderSummaryPage.js, static/js/flow/checkoutTypes.js, static/js/global_init.js
fixes https://github.com/mitodl/micromasters/issues/3105
- Redirect user to checkout instead of progress summary for `NON FA` programs. 
- Click `pay now` buttons for no fa course
@pdpinch
=> On pay now redirected users to checkout page instead of order summary for non FA programs

courses/serializers.py, courses/serializers_test.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/LearnerSearch.js, static/js/containers/LearnerSearchPage_test.js, static/js/factories/dashboard.js, static/js/flow/enrollmentTypes.js, static/js/reducers/programs.js, static/js/test_constants.js
Fixes #3095
Adds the number of courses to the `/programs` api so that the learner search can set a proper maximum range value, rather than depending on the seemingly flaky value in the first hit (which we could be nonexistent if zero results).
- Adjust the bounds of the '# of courses passed' range filter (I set it to 2-3)
- Select any one of the course title filters (I chose 'Digital Learning 100')
- Verify the range slider for '# of courses passed' is still present
=> Fixed # of Courses Passed facet disappearing (#3095)

dashboard/tasks.py, dashboard/tasks_test.py
Fix #2099
Exclude all inactive users from cached users.
Set your user to `is_active=False` and make sure that user is not being cached anymore.
=> Update edX cache only for active users

static/js/actions/course_enrollments.js, static/js/components/Toast.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/containers/LearnerPage_test.js, static/js/entry/zendesk_widget.js, static/js/util/util.js, static/js/util/util_test.js
None
Added a `wait` function which wraps around `setTimeout` and returns a promise which resolves when the time has elapsed.
Go to `/dashboard/?status=receipt&course_key=missing` and look at your network tab. Every three seconds there should be a dashboard refresh
=> Added wait function

static/js/containers/LearnerSearchPage_test.js
Fixes #3193 
Tests for the fix made in #3184. No matter what filters are enabled or what text is in the textbox we should not show an error screen
Revert the commit for #3184 and run the test locally. It should fail
=> Add test for filters being displayed when there are zero hits

static/scss/email-composition-dialog.scss
closes #3197
This is just some CSS to make the heading tags display normally-ish inside of the email composition dialog.
Make sure everything looks alright!
=> email composition dialog CSS fixes

cms/templates/cms/program_page.html, static/scss/program-page.scss, static/scss/public_style/bootstrap-extend.css
Fix #3173
Move the tabs on the program page above the hero image. Now the hero image is displayed only in the 'about' tab.
Go to the any program page. Play with the tabs.
=> Program Page: Move tabs to the top

static/js/components/LearnerSearch.js, static/js/components/search/EnabledSelectionRangeFilter.js, static/js/components/search/FilterVisibilityToggle.js, static/js/components/search/FilterVisibilityToggle_test.js, static/js/components/search/FinalGradeRangeFilter.js
Fixes #3095 
Adds logic to still show titles if the filter is selected when there are 0 results.
- Go to learner search
- Selected any combination of filters to get 0 results (hint: you can select filters that narrow your search down to 1 and then search for a nonmatching name to test all of them).
- Verify the facet titles remain
Known issue: #3187
=> Ensure facet titles for selected filters stay visible

static/js/actions/course_enrollments.js, static/js/actions/course_enrollments_test.js
None
Fixes the timeout for the enroll success message. It was 9 seconds but it was inadvertently changed to 900 milliseconds in https://github.com/mitodl/micromasters/pull/3195
Enroll in a course. The success message should stay up for about 9 seconds
=> Fix wait timeout

static/js/components/email/EmailCompositionDialog.js, static/js/components/email/EmailCompositionDialog_test.js, static/js/components/email/hoc.js
fixes https://github.com/mitodl/micromasters/issues/3182
it changes the label of edit email dialog which was previously `Send` but now it is renamed to `Save Changes`
Go to http://192.168.99.100:8079/automaticemails/ and try to edit email.
@pdpinch
=> Renamed send button to Save Changes on automatic email edit button

static/js/components/OrderSummary.js, static/js/components/OrderSummary_test.js
fixes https://github.com/mitodl/micromasters/issues/3125
Allow coupon without code display in order summary
Go to order summary on a course which has a coupon without code
@pdpinch
=> Shown Coupons without code on order summary page

static/js/components/dashboard/FinalExamCard.js, static/js/global_init.js, ui/utils.py, ui/views.py, ui/views_test.py
Fixes #3002 
Removes the feature flag and ensures the exam card is always visible.
Setup an exam authorization for yourself and ensure `FEATURE_EXAMS_CARD_ENABLED` is not in your `.env`. Verify the card still appears for you.
=> Removed EXAMS_CARD_ENABLED logic so card always shows (#3002)

static/scss/email-composition-dialog.scss
None
This tweaks the visual style of the email macros buttons on the Send Email form... 
and also tweaks the margins for the # of recipients text:
=> Small styling tweaks on the Send Email form

cms/models.py, courses/models.py, dashboard/tasks.py, dashboard/views_test.py, ecommerce/models.py, exams/factories.py, exams/pearson/utils_test.py, exams/tasks.py, financialaid/admin.py, financialaid/models.py, financialaid/serializers.py, financialaid/tasks.py, grades/admin.py, grades/models.py, grades/tasks.py, mail/admin.py, micromasters/celery.py, micromasters/settings.py, micromasters/utils.py, micromasters/utils_test.py, profiles/models.py, profiles/models_test.py, profiles/permissions.py, pylintrc, pytest.ini, roles/models.py, search/tasks.py, seed_data/lib.py, test_requirements.txt
Fixes #3230 
Upgrades pylint and fixes errors from new rules. This also changes pylintrc to treat warnings as errors and ignores warnings which are due to deprecation errors or due to the sftp exam code
N/A
=> Upgrade pylint, treat warnings as errors

mail/api.py, mail/api_test.py
Fixes #3239 
Changes the mail search filter to skip users where `Profile` is `None`. For the linked sentry issue there were two users who had two `User` objects each and only one had a `Profile`. I'm not sure what caused this but it seems like only the one with a `Profile` is valid.
For some fake user with a valid profile, create another `User` object with the same `email`. On master you should get a 500 error when attempting to send email, and the error should not be there in this branch.
=> Mail search now skips users without a profile

Dockerfile, runtime.txt, tox.ini, travis/Dockerfile-travis-web, travis/update-docker-hub.sh
Fixes #3226 
Upgrades heroku runtime and Docker enviornment to python 3.6.1
No changes should be seen in functionality
@aliceriot do we need to update the travis docker image after this PR?
=> Upgrade to python 3.6.1

micromasters/settings.py, seed_data/lib.py, seed_data/management/commands/alter_data.py, seed_data/management/commands/attach_avatars.py, selenium_tests/__init__.py, selenium_tests/apps.py, selenium_tests/base.py, selenium_tests/basic_test.py, selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3241
- Adds a management command to create screenshots of dashboard state. You will need to stop the watch container and run webpack to generate static assets just like if you were running selenium tests locally.
- Changes `get(...)` to use relative paths
- Changes list of examples in `seed_db` to a data structure to be reused in this management command
- Stop the webpack dev server
- Run webpack to generate static assets. From the README: `docker-compose run watch ./node_modules/webpack/bin/webpack.js --config webpack.config.prod.js --progress --bail`
- Run `./manage.py snapshot_dashboard_states`. It should take a minute or two and result in a bunch of `png` files in the `micromasters` directory corresponding to various dashboard states.
Also run `./manage.py alter_data examples` …
=> Added management command to take screenshots of dashboard states

selenium_tests/base.py
Fixes #3030 
Adds support for `keepdb` option to provide quicker running of local selenium tests.
Remove `--reuse-db` from `pytest.ini` and run the selenium tests. Then add it back and run the selenium tests again. The second time should be considerably faster, roughly 20 seconds.
There are also other minor changes meant to fix flaky tests
=> Handle reuse_db option for selenium tests

mail/serializers.py, mail/serializers_test.py, static/js/components/email/lib.js, static/js/components/email/lib_test.js, static/js/constants.js, static/js/flow/emailTypes.js, static/js/test_constants.js
fixes https://github.com/mitodl/micromasters/issues/3202
Adds filters/recipients to automatic email page
(Required)
- on learners search page select as much filters u can
- create an automatic email from learner search page.
- open the automatic email page and press edit 
- you will see the filters
=> Show recipients on email edit box

config/nginx.conf, config/nginx.conf.erb
In order to allow for a short URL to use in marketing material we are
adding support for the `mm` subdomain. This PR adds a redirect to the
full `micromasters` subdomain to address issues with things like the
OAUTH callback and any potential weirdness with cloudfront.
(Required)
Redirects `mm.mit.edu` to `micromasters.mit.edu`
Modify your /etc/hosts file to map `mm.mit.edu` to your localhost and try to visit that subdomain to verify that you get redirected to the production site.
(Optional)
(Optional)
(Optional)
(Optional)
=> Added redirect of mm.mit.edu to micromasters.mit.edu

selenium_tests/base.py, selenium_tests/management/commands/snapshot_dashboard_states.py
None, related to #3241 
- Runs the dashboard state collection in the test database instead of the regular database
- Also changes behavior to run against the webpack dev server. This requires the user to set `WEBPACK_DEV_SERVER_HOST` to the IP address of where their watch container runs
- Adds scenarios to take screenshots regarding exams, a mixed passed/failed set of runs on a course, and coupons
- Adds a dump of the dashboard API JSON alongside the screenshot
Run the management command and verify that your dev environment has not been affected
=> Use test database when running snapshot_dashboard_states

exams/management/commands/simulate_sftp_responses.py, exams/pearson/constants.py, exams/pearson/utils.py, exams/pearson/utils_test.py, exams/pearson/writers.py
Fixes #3251 
Fixes Pearson exam date parsing bug. Pearson has apparently been giving us 2 different datetime formats in exam results
Unit test passage is a good sign, but I'll post a code snippet below to show how I tested this manually
=> Fixed Pearson exam date parsing bug

travis/Dockerfile-travis-watch-build
none. 
This deletes `node_modules/` in `Dockerfile-travis-watch-build`. This dockerfile is used to build an image we push to docker hub to cache some of the build steps for getting the JavaScript envrionment set up (mainly it gives us yarn, a warm cache for yarn,  and an OS level dependency). The issue was coming up because we were leaving the `node_modules` directory around in this image, so that when we went to build the container for running the tests (using `Dockerfile-travis-watch`) we were running into a bug with yarn + node-sass, where yarn fails to rebuild the native extensions that sass uses when it should.
So! We now delete the `node_modules` directory from the `Dockerfile-travis-watch-build` image, so that when we run `yarn install --pure-lockfile` in `Dockerfile-travis-watch` …
=> fix node sass issues on travis

courses/factories.py, financialaid/factories.py, seed_data/management/commands/create_tiers.py
Fixes #3262
Fixes bug involving poorly configured TierPrograms used for testing (noticed primarily in the running of `seed_db`)
Unseed/seed the db, go to the dashboard, check out the tiers created for Digital Learning
`financialaid/factories.py`
I noticed this problem a while ago and created a small script in a Jupyter notebook that adjusted `TierProgram`s to be properly configured. I ported that over to `TierProgramFactory.create_properly_configured_batch`
=> Fixed bug involving poorly configured TierPrograms used for testing

backends/pipeline_api.py, backends/pipeline_api_test.py, static/js/components/LearnerInfoCard.js, static/js/components/LearnerInfoCard_test.js, static/js/components/PersonalForm.js, static/js/components/search/LearnerResult.js, static/js/components/search/LearnerResult_test.js, static/js/containers/LearnerPage.js, static/js/containers/ProfileImage.js, static/js/util/util.js, static/js/util/util_test.js, static/scss/user-page.scss
this closes #2879 
this changes some stuff around the preferred name to be in line with what the issue says.
we:
- pre-populate the preferred name field (at account creation) with `${first} ${last}`, where `first` and `last` are the user's first and last names on edX (currently we do the same thing, but with just the first name).
- change the behavior of the `getPreferredName` utility function to always prefer to return the preferred name, then, `${first} ${last}`, and then `username`
- display the preferred name instead of the legal name in searchkit results
- show the legal name (with a little informative message) on the learner page if the current user is a staff user
- I think that's it?
Make sure that the changes described above have actually been implemented! It's helpful to change …
=> implement new preferred name behavior

dashboard/utils.py, dashboard/utils_test.py, requirements.in, requirements.txt
Fix #2539
Change MMTrack `has_passing_certificate` to use `is_passing` property of the certificate coming from edx.
should be covered in dashboard/utils_test.py
=> Use is_passing in MMTrack

static/js/components/email/EmailCompositionDialog.js
fixes https://github.com/mitodl/micromasters/issues/3254
On chrome/firefox OSX, Email composer rich text editor was reversing first 2 characters, this occur on first time after opening email composer. After that it worked fine. 
I fixed that behaviour
go to email composer and type text like `hello world`
@pdpinch
=> Fixed mail dialog rich text editor jumbling up letters

selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3282 
It looks like the environment variables are ignored in the management command because `settings.py` was already imported before these variables were set. Instead `override_settings` is used to explicitly change the Django settings.
Run `./manage.py snapshot_dashboard_states --suffix contact_course` and verify that there are results in `/learners`.
=> Use test index for snapshot_dashboard_states

dashboard/utils.py, exams/api.py, exams/api_test.py, exams/models.py
Fixes #2286 
Adds a check to not generate more authorizations if a user has reached their limit of exam attempts for how many times they've paid.
The tests added should pass, otherwise you can test by:
For an FA course:
- Create an `ExamRun` for the course with all dates in the past.
- Create two `ExamRunAuthorization`s for the past `ExamRun`
- Create a second `ExamRun` for the course with `date_first_eligible` in the past and `date_last_eligible` in the future.
- Enroll in the current course run for that course
- Create a passing `FinalGrade` for the current course run of that course
- Verify you have no `ExamAuthorization` record for that course
- Pay for the course
- Verify do not have a third `ExamAuthorization` record for that course
=> Added check for exam attempts

selenium_tests/base.py, selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3277
- Adds screenshots for each financial aid state
- More descriptive filenames for other scenarios
- Take screenshot of entire page height
- Add `--mobile` flag to do mobile form factor screenshots
Run `./manage.py snapshot_dashboard_states --mobile`. There should be extra financial aid related screenshots, the filenames should be more descriptive than before and they should be suffixed with mobile. All screenshots should have a width of 480 pixels.
=> Add financial aid screenshots

app.json, docker-compose.yml, package.json, static/js/components/EducationForm.js, static/js/components/EmploymentForm.js, static/js/containers/LearnerPage_test.js, static/js/lib/location.js, static/js/lib/validation/profile.js, static/js/lib/validation/profile_test.js, static/js/util/profile_edit.js, static/js/util/profile_edit_test.js, static/js/util/test_utils.js, static/scss/geosuggest.scss, ui/views.py, yarn.lock
https://github.com/mitodl/micromasters/issues/2384
Replaces the city, state, and country input fields for the profile education and employment dialogs with a Geosuggest component input field.
Add and edit employment and education entries on your profile.  Start typing in a city (like 'Boston'), you should see some suggestions start to appear below the input field. Choose one and save.  Then go back to edit the entry and make sure that the value you selected is there.
(Optional)
(Optional)
(Optional)
(Optional)
=> Use Geosuggest React component for Profile education and employment forms

requirements.in, requirements.txt
N/A
Upgrades Wagtail to 1.10.1 as a requirement to upgrade Django to 1.11
We should check that the CMS works properly
=> Upgraded Wagtail to 1.10.1

seed_data/lib.py, seed_data/management/commands/alter_data.py
No tickets. Fixes 2 minor `alter_data` command issues
1. Sets a course end date for current/ongoing courses (front end logic was recently changed in a way that shows vague output when an end date isn't set)
1. For the given users, sets cached edX data expiration one month in the future each time the `alter_data` script is invoked. Up until now, changing enrollment information via `alter_data` would often be undone by the 5 minute automatic refresh of edX data.
1. Run this management command, replacing the username with your own, and the `course-title` to any course title you wish: 
```
./manage.py alter_data set_to_enrolled --username=USERNAME --course-title='Analog Learning 100' --grade=75
```
Visit `/dashboard` to see the course and make sure it is shown to be in progress.
1. Run the …
=> Fixed alter_data enrolled status and edX data freshness

grades/api.py, grades/api_test.py
fixes #3316
defaults the grade value to 0 (zero) in case the value coming from edx is a weird one (like an empty string)
Talk to me
=> Fixed bug with weird grades coming from edx

.gitignore, scripts/test/run_snapshot_dashboard_states.sh, selenium_tests/base.py, selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3321 
Fixes #3295 
- Stores results for `course_prices` and `coupons` REST APIs. These are also now stored as `json` files to allow easier parsing
- Added check so that if user runs the management command directly instead of via the script they will be told to use the script
- Outputs dashboard states in a separate directory `dashboard_states_output/`
Run `./scripts/test/run_snapshot_dashboard_states.sh`. The output should now be in a separate directory and there should be three json files per png file.
=> Add JSON output for course price and coupons API

micromasters/celery.py
The Sentry logger signal handler got set to match the app logging level which is causing
erroneous messages to be logged to Sentry.
N/A
Raises the logging level for Sentry messages in Celery tasks.
Verify that sentry log messages aren't being fired for non-error messages in Celery tasks.
(Optional)
(Optional)
(Optional)
(Optional)
=> Updated logging level for Sentry client in Celery

selenium_tests/management/commands/snapshot_dashboard_states.py
Related to #3340 
Changes `dashboard_snapshot_states` to create coupons for financial aid programs. Currently this creates coupons for a non-financial aid program, which is an invalid state since there can't be coupons in non-financial aid programs.
Run `./scripts/test/run_snapshot_dashboard_states.sh --match coupon` and look at the screenshots. Some values are incorrect, see #3342 for the issue to fix it.
=> Fix coupon selenium screenshots

ecommerce/api_test.py, ecommerce/factories.py, ecommerce/models.py, ecommerce/models_test.py, ecommerce/serializers_test.py, ecommerce/views_test.py
Fixes #3340 
Prevents coupons from being created for non-financial aid programs.
Create a coupon in the Django admin for a non-financial aid program and see the error message
=> Prevent users from creating coupons on non-financial aid programs

static/js/components/EducationForm.js, static/js/components/EmploymentForm.js, static/js/containers/LearnerPage_test.js, static/js/lib/location.js, static/js/lib/validation/profile.js, static/js/lib/validation/profile_test.js
https://github.com/mitodl/micromasters/issues/3348
Checks to see if the Google Maps API is loaded in the window. If it is, the GeoSuggest component is rendered.  If not, state and country dropdowns plus the city text field are rendered.
Edit/add an education and work history entry, you should get the geosuggest component. Temporarily comment out the script tag in base.html that loads Google Maps, then reload the page and repeat - should get the city field plus state/country dropdowns.
=> Use city, state, country fields if Google Maps API is unavailable

static/js/components/email/lib.js, static/js/containers/AutomaticEmailPage.js, static/js/containers/AutomaticEmailPage_test.js
closes #3350 
closes #3351 
this fixes the editing for automatic emails. basically, the ID was accidentally ommitted. that isn't great.
I added a test that should fail on master. But also, you should just confirm yourself that things aren't working on master. go to `/automaticemails` and try to edit one. When you click 'save' you should get an error in the JS console. The branch should restore the functionality.
To test that the test I added fails on master you can do:
```
git cc ap/fix-automatic-emails -- static/js/containers/AutomaticEmailPage_test.js
```
and confirm that there's a failing test. then check out my branch and confirm all tests are passing.
Also, for the 'toggling' functionality, confirm that you can toggle the 'active' state for any automatic email that shows up on the …
=> fix automatic email editing

static/js/lib/validation/profile.js, static/js/lib/validation/profile_test.js
closes #3360
this fixes the email validation so the user can save an email with a `mailto` link in it.
If you create an email and add a `mailto` link you should be able to save the email. You should still be unable to save a link which does not begin with `http|https` (e.g. `wikipedia.org/wiki/Potato`).
=> fix the email validation

selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3341 
Sets the hash seed for the faker library so it generates the same random-ish values each time
Run this command:
./scripts/test/run_snapshot_dashboard_states.sh --match 000
Then rename `output/dashboard_states` to `output/old`. Then rerun the above command. Look at the `png` file in the `old` directory, then look at the one in `dashboard_states`. They should be bit for bit identical
=> Use specific hash seed

selenium_tests/base.py, selenium_tests/basic_test.py
Fixes #3366 
Moves patching into the tests which require it. Also adds a `wait_for_server_thread` method which hackishly blocks until the server thread is available to handle new requests, to fix race conditions regarding patches.
N/A
=> Use local patches in selenium tests

static/js/lib/location_test.js, static/js/lib/validation/profile.js, static/js/lib/validation/profile_test.js, static/js/util/profile_edit.js, static/js/util/profile_edit_test.js
Closes https://github.com/mitodl/micromasters/issues/3369
Enables 'autoActivateFirstSuggest' on the React Geosuggest component and overrides its default 'onInputBlur' behavior so that it will geocode the text even if the user clicks save immediately after typing.
I also changed the validation message if the input is invalid/empty to 'City, state/territory, and country are required.'
Add/edit an education or employment entry.  In the location field, manually type a location like 'Boston, MA, USA'.  Then click the 'Save' button immediately afterward without clicking Tab or Enter.  You should not get a validation error message about the location.
=> Geocode location text when user clicks 'Save' immediately after typing location

selenium_tests/base.py, selenium_tests/redirect_test.py
Fixes #3380 
Adds a selenium test for the login redirect behavior. It makes sure that if the dashboard returns a 401 that we are redirected to the login page to reauthenticate
N/A
=> Add selenium test for login redirect on 401

micromasters/envs.py, micromasters/envs_test.py, micromasters/settings.py, micromasters/tests/test_settings.py
Fixes #3385 
Removes `get_var` and replaces it with `get_string`, `get_bool`, `get_int`, and `get_any` for feature flags and `get_list_of_str` for another special case. This removes the use of `literal_eval` in most cases which can cause some unexpected results for invalid input. 
Save this to a file `dump_settings.py` in the root of the repo:
import re
from django.conf import settings
def dump():
with open("out.txt", "w") as f:
for key in dir(settings):
if re.match('^[A-Z]', key):
f.write("{key}={value}\n".format(key=key, value=getattr(settings, key)))
Check out master and open the Django shell. Run `from dump_settings import dump` then `dump()`. Rename `out.txt` to `before.txt`.
Check out this branch and do this again. Compare `before.txt` to `out.txt` and make sure that all changes …
=> Replace get_var with more specific variants

static/js/factories/dashboard.js
N/A
This defines `course_end_date` for `makeRun` to avoid a race condition with `courseUpcomingOrCurrent` comparing now to now because we were passing `undefined` to `moment()`.
=> Specify course_end_date for makeRun

static/js/components/dashboard/FinancialAidCard.js, static/js/components/dashboard/FinancialAidCard_test.js
#3392
Changes wording for consistency with acceptance of both mailed and faxed financial aid documents.
Peer review, perhaps.
=> Make status text consistent with acceptance of faxed FA documents.

js_test.sh, package.json, yarn.lock
none
this updates `react-telephone-input` to the latest version. the most recent version fixes a warning we were seeing in the JS console, because previously it used `React.createClass`, which is a soon-to-be deprecated API. Now it is fixed, so we may upgrade and all that.
The tests should pass without error, and the telephone input component should behave as before.
=> upgrade react telephone input component

static/js/containers/AutomaticEmailPage_test.js, static/js/containers/DashboardPage_test.js, static/js/global_init.js, static/js/util/integration_test_helper.js
Fixes #3399
This is caused by a test in `DashboardPage_test.js` which didn't wait for all actions which were dispatched. This caused a fetch to happen after the sandbox was cleared, which meant that `fetchMock` handled it instead without any mock for that endpoint. This:
- fixes the test to listen for the additional actions
- Moves `fetchMock.restore()` into `global_init` `afterEach` so we aren't listening for actions in between tests anymore
- adds commented out code to aid in debugging this issue in the future
N/A
=> Fix JS race condition in tests

static/js/components/email/EmailCompositionDialog.js
fixes https://github.com/mitodl/micromasters/issues/3365
Fixed jumbled text when user use tab on email composer
go to email compose and use tab to set subject and body
> why we are using `state` on this screen, why not  use action to update email state?
=> Fixed jumbled text when entering text in search mail dialog in chrome

static/js/components/EducationForm.js, static/js/components/EmploymentForm.js, static/js/components/ErrorMessage_test.js, static/js/components/PersonalTab_test.js, static/js/containers/App_test.js, static/js/containers/LearnerPage_test.js, static/js/containers/ProfilePage_test.js, static/js/flow/profileTypes.js, static/js/lib/location.js, static/js/lib/location_test.js, static/js/util/ProfileFormFields.js, static/js/util/profile_edit.js, static/js/util/profile_edit_test.js, static/js/util/test_utils.js, ui/views.py, yarn.lock
Fixes https://github.com/mitodl/micromasters/issues/3409
Reverts address fields on education and employment forms to the original state and country dropdowns plus city text input.
Add or edit an education entry and employment entry on your profile page.  You should get dropdowns for state and country plus a text field for city.  Fill them in and save.  Then re-open to make sure the changes were saved correctly.
=> Remove geosuggest component, revert to dropdowns

static/js/containers/FinancialAidCalculator.js, static/js/containers/FinancialAidCalculator_test.js
fixes https://github.com/mitodl/micromasters/issues/3344
Remove a line of code which was casing to show income dialog twice.
Go to FA calculator and submit, a confirm dialog will appear. Submit it and you want see this dialog for second time.
@pdpinch
=> Fixed financial aid income dialog that was showing up twice

static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/courses/GradeDetailPopup.js, static/js/components/dashboard/courses/GradeDetailPopup_test.js, static/js/components/dashboard/courses/Grades.js, static/js/components/dashboard/courses/Grades_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/containers/LearnerPage.js, static/js/containers/LearnerPage_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/lib/grades_test.js, static/js/test_constants.js, static/scss/dashboard/grades.scss
closes #3353
this adds a detail display for the exam grades, which opens if you click on the 'over-all' exam grade. the edx grade detail display may be opened by clicking on that 'over-all' grade.
If you have a course with edX grades and also exam grades you should see both on either `/learner` or on the dashboard. clicking on the exam grade should open the detail display for that, and the same for the edx grade. the best grade for each should be highlighted with a check and a little mark saying 'Passed'.
=> Add exam grade detail display

dashboard/api.py, dashboard/api_test.py
fixes https://github.com/mitodl/micromasters/issues/3327
Added final grade in api when user is neither enrolled nor paid for course but he has a final grade in system, plus course deadline has passed
create a course in existing program who's deadline is passed and then create a final grade and check it in dashboard api
```url
http://192.168.99.100:8079/api/v0/dashboard/(username)/
```
@pdpinch
=> Dashboard API: displayed final grade for course with missed deadline status but user has final grades in system

.eslintrc, static/js/containers/DashboardPage_test.js, static/js/entry/zendesk_widget.js
None
Adds an eslint rule forbidding statements like `a = 3, b = 4`. Comma expressions within `let` are still allowed.
N/A
=> Add no-sequences eslint rule

static/js/components/CourseEnrollmentDialog.js, static/js/components/CourseEnrollmentDialog_test.js, static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js
Fix #3411
Remove the logic for disabling the Enroll button, enabling the user to get to the `CourseEnrollmentDialog`, where the user has the option of auditing the course while waiting for FA application to get approved.
Set a course in a program to `offered`. Set your FinancialAid to 'pending' or other `FA_PENDING_STATUSES`. And try to enroll in that course.
=> Allow user to enroll in a course if FA pending

cms/migrations/0004_create_homepage.py, cms/migrations/0006_change_homepage_title.py
No ticket
Fixes wagtail-related migrations so they're reversible
If you're OK nuking your CMS data, you can do this:
```
./manage.py migrate cms zero
./manage.py migrate cms
```
If you go to `/cms` after that, you should be able to click the "Pages" link and see the standard home page with the correct title
I was caught in migration hell yesterday trying to fix wagtail-related migrations. The point of this fix wasn't to make the two migrations perfectly reversible; the point was to get wagtail to stop complaining when rolling back those two migrations and to make the forward migrations idempotent
=> Fixed broken cms migrations

grades/factories.py, grades/management/commands/adjust_exam_grades_from_csv.py, grades/models.py, grades/models_test.py
Closes #3309 
Creates a management command that can adjust exam grades based on data in a csv
This gist will help: https://gist.github.com/gsidebo/8c3252a4d8f0b9f7bd67ffa3ba2782f6
It contains a script for ensuring that a set of users have exam grades, and an example csv for the grade adjustments. Once you have a set of users with exam grades, download that csv to your project root and change the `proctoredexam_id` column values to match the `ProctoredExamGrade.id` values for your users (the `user_id` column in this csv is ignored - the only column that matters for matching to our records is `proctoredexam_id`). Run the management command with this file (e.g.: `./manage.py adjust_exam_grades_from_csv "./test_grade_adjust.csv"`), then check the exam scores in the database to make sure that …
=> Created management command to make exam grade adjustments

selenium_tests/data_util.py
None
This changes the expiration date for user data to be further into the future. Since the data is not recreated each time the tests run if there's a backup database, the expiration date may pass which causes the tests to fail locally.
Run `./scripts/test/run_selenium_tests_dev.sh`, wait 10 minutes then run it again.
=> Fix selenium dashboard data expiration

dashboard/api_edx_cache.py, dashboard/tasks.py, dashboard/tasks_test.py, dashboard/views.py, ecommerce/api.py, profiles/api.py, profiles/api_test.py
fixed https://github.com/mitodl/micromasters/issues/3299
Allow users to have more the one social auth objects, previously application was throwing error when user have more the one social auth objects
- This PR changes the query on social auth table, Instead of looking for one object it filter out all objects of a user and the picks the latest.
- To test it create a duplicate social object you can create it manually, then see exceptions on console
- previously app was throwing exception when it was running `micromasters/dashboard/tasks.py`
- now it wont throw
- you will see dashboard like this
- switch to my branch `fix/aq/duplicate_social_auth` and things will be fine.
@pdpinch
=> Fixed issue when a user have more the one social auth objects

selenium_tests/management/commands/snapshot_dashboard_states.py
Fixes #3433 
Adds a `--learner` flag which makes the `run_snapshot_dashboard_states` command take screenshots of the learner info page, which also contains dashboard information.
Run `./scripts/test/run_snapshot_dashboard_states.sh --learner` and view the screenshots taken
=> Added --learner to take snapshots of learner info page

dashboard/tasks_test.py, dashboard/views_test.py, ecommerce/views_test.py, grades/api_test.py, micromasters/factories.py, micromasters/factories_test.py, micromasters/utils.py, micromasters/utils_test.py, profiles/api_test.py, profiles/factories.py, profiles/permissions_test.py, profiles/util_test.py, ui/views_test.py
Closes #3166 
Adds factories to produce social auth for Users, and changes a lot of test cases to use those factories
No manual testing needed
`micromasters/factories.py` and `profiles/factories.py`
- Here's some example usage for the new factories:
```python
SocialUserFactory.create(username='user_0', social_auth__provider='abc')
SocialProfileFactory.create(first_name='Joe', user__username='user_0', user__social_auth__provider='abc')
```
- There are a bunch of other test cases that manually add social_auth records on their own, but this PR has enough lines as it is
=> Added factories to produce social auth for Users

backends/urls.py, backends/views.py, micromasters/urls.py
Fixes #3432 
Logs out the user in the social auth `complete` view before they log in. The root cause of #3299 was that the new social auth object was created for a new edX account, but it was attached to the currently logged in user even if that user isn't necessarily related to the edX user.
- First, log out in MM and edX.
- Go to edX and create a user with username `social_auth_1` and email `social_auth_1@example.com`. Log in on MM. Don't worry about filling out the profile.
- Open the browser console and type `SETTINGS.user.username`. You should see `social_auth_1`.
- Log out on edX (but stay logged in on MM). Create a user with username `social_auth_2` and email `social_auth_2@example.com` on edX. On MM go to `/login/edxorg/`. You should see an empty profile.
- Open the browser …
=> Fix duplicate social auth creation during log in

dashboard/tasks.py, profiles/api.py, profiles/api_test.py
Related to #3299 
Changes behavior to raise an exception if there is more than one social auth per user. This should only be merged after #3444 is merged and the existing duplicate social auth accounts are removed.
N/A
=> Raise an exception if there are two social auth objects

RELEASE.rst, dashboard/tasks.py, micromasters/settings.py, profiles/api.py, profiles/api_test.py
=> Release 0.70.2

flow-typed/npm/redux-asserts_v0.x.x.js, static/js/store/configureStore.js, static/js/util/integration_test_helper.js
Fixes #3451 
Adds flow types for our `redux-asserts` library. It lets us make sure that the function in `listenForActions` doesn't have anything returned from it, for example
No testing needed
=> Added redux-asserts flow types

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, exams/api.py, exams/api_test.py, exams/models.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/lib/grades.js, static/js/lib/grades_test.js, static/scss/dashboard/course-status-messages.scss
Fix  #3441
Shows a different course status message based on the state of `ExamRun`s and grades for exams.
login as a learner enrolled in FA program like 'Digital Learning'. Run alter_data command for your user to have passed a course run:
`./manage.py alter_data set_past_run_to_passed --username username --course-title 'Digital Learning 100'`
Then in the django shell set up the exam:
```
c=Course.objects.filter(title='Digital Learning 100')[0]
exam_run=ExamRunFactory.create(course=c, authorized=True)
au=ExamAuthorizationFactory.create(user=user, course=c, exam_run=exam_run, status= 'success', …
```
=> Allow learners to pay for exam attempts

Dockerfile, docker-compose.yml, travis-docker-compose.yml
Fixes #3450 
Moves collectstatic step to docker-compose, which will allow us to do validation checks in `settings.py`
Clear `staticfiles` locally, restart docker-compose, then go to `/admin/` and verify that the page looks correct.
=> Move collectstatic into docker-compose

docker-compose.yml
None
Removes link between nginx and watch containers. At some point the nginx container talked to watch, but this was removed in favor of the browser talking directly to watch.
Site should work
=> Remove unused watch link from nginx container

static/js/containers/FinancialAidCalculator.js
Related to #3373
Fixes a null reference error. This usually only visible via selenium since `currentProgramEnrollment` will be set by `localStorage` after the first time the user visits the page.
Run `./scripts/test/snapshot_dashboard_states.sh --learner` and verify that no exception occurs
=> Fix occasional null reference error when running snapshot_dashboard_states

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix  #3455
Show the same course status message when user is auditing a course, independently of previous enrollments for that course.
Run
```
./manage.py alter_data set_past_run_to_passed --username staff --program-title Analog --course-title 100
./manage.py alter_data set_to_needs_upgrade --username staff --program-title Analog --course-title 100
```
You should be able to enroll in the course again.
=> Let user pay for a course if auditing

micromasters/settings.py, micromasters/test.py, test_requirements.txt
Fixes #2565 
I made a PR to add support for MIDDLEWARE in nplusone. That was merged and all other middleware classes we use are already compatible with MIDDLEWARE.
Run `docker-compose build` to update dependencies. Make sure the site is viewable locally and there are no errors.
=> Use MIDDLEWARE instead of MIDDLEWARE_CLASSES

package.json, yarn.lock
fixes #3430 
Uses mitodl/iso-3166-2.js with English names for Israel's districts. 
Go to the learner profile, change the country to Israel and confirm that the district names are in English, not Arabic or Hebrew. 
For the English names, see 
https://github.com/mitodl/iso-3166-2.js/blob/3466fbed3fe7b961d1548e4272b992f41f97677a/data.csv#L1851
There is a PR open on the upstream repository, but no one has responded to it.
See https://github.com/olahol/iso-3166-2.js/pull/20
=> use our fork of iso-3166-2.js with English names for Israel's districts

package.json, yarn.lock
fixes #3430 with an updated package instead of a fork
Upgrade iso-3166-2.js to 1.0.0 which includes English names for Israeli districts
This update includes a breaking change: failed lookups now return null instead of {}. Hopefully tests will pass. 
Go to the profile and set your country to be Israel. Confirm that the drop-down of states/territories has English names instead of Arabic of Hebrew.
=> upgrade iso-3166-2.js to 1.0.0

static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js
fixes https://github.com/mitodl/micromasters/issues/3496
Fixed upgrade deadline on leaners page, it was showing course end date which is wrong.
As staff user go to leaners page, you must be enroll in course
@pdpinch
=> Fixed course upgrade deadline on learners page

grades/api.py, grades/api_test.py, grades/management/commands/check_final_grade_freeze_status.py, grades/tasks.py, grades/tasks_test.py
Fix #2657
Counts the number of users where user authentication failed and completes the task in the next run of the task.
Make a past passed course run, set the freezable date
```from courses.models import *
course_run = CourseRun.objects.get(edx_course_key=course_key)
from datetime import timedelta
from micromasters.utils import now_in_utc
course_run.freeze_grade_date=now_in_utc()-timedelta(days=1)
course_run.save()
```
Try to freeze the grades.
=> Complete freeze final grades task when cache refresh fails

ecommerce/models.py, ecommerce/models_test.py
Fixes #3508 
Fixes a filter bug where the user id was compared with the coupon id. This caused some coupons to incorrectly be marked as already redeemed, preventing users from using them.
Talk to me
=> Filter on coupon id for automatic emails

app.json, discussions/utils.py, discussions/utils_test.py, discussions/views.py, micromasters/settings.py, requirements.in, requirements.txt
Part of #3479 
Adds `session_url` and `auth_url` to the JWT payload.
Add these settings to `.env` (in addition to the ones in #3504) and verify that `/discussions/` still redirects you to the discussions app:
```
MICROMASTERS_CORS_ORIGIN_WHITELIST=['localhost:8063']
```
=> Added endpoint urls to JWT payload

discussions/management/commands/backfill_discussion_users.py, discussions/tasks.py, discussions/tasks_test.py, test_requirements.txt
closes #3502
Adds a management command to submit an async task to create an OD user of each MM user with a profile that does not have a user on OD yet.
Run the management command to sync users.
=> Added management command to backfill discussion users

js_test.sh, package.json, static/js/global_init.js
none
what it says on the can
you should be able to do `npm run watch` in your docker container. the tests should run in watch mode, and should all be passing. everything else should be unchanged.
=> add package.json script for running JS tests in watch mode

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py
Related to #3233
Show certificate link for edx certificates for non FA courses.
Can test this only if there is a verified certificate on edx.
Can create a `CachedCertificate`:
```
cert_json = {
"username": username,
"course_id": course_key,
"certificate_type": "verified",
"is_passing": True,
"status": "downloadable",
"download_url": some_url,
"grade": "0.98"
}
CachedCertificate.deserialize_edx_data([cert_json])
```
=> See Certificates links for non FA courses

static/js/components/DiscussionCard.js, static/js/components/DiscussionCard_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/global_init.js, static/scss/discussion-card.scss, static/scss/layout.scss, ui/views.py, ui/views_test.py
first draft of #3476 
this adds a very simple card to the dashboard page that links the user over to discussions
if you open up the dashboard you should see something like this:
clicking on the link should open the discussions app in a new tab, and you should be signed in, able to post, comment, etc.
=> simple discussions link

static/js/flow/declarations.js, ui/views.py, ui/views_test.py
part of the work for #3476 
adds the open discussions redirect environment variable value to the SETTINGS object, so we can use that value on the frontend. For the recent posts component we need it so we know where to make the request.
Make sure that you have the env var set (`OPEN_DISCUSSIONS_REDIRECT_URL`) and open up `/dashboard`. Check that `SETTINGS.open_discussions_redirect_url` is the same string.
=> add the open discussions redirect URL to the SETTINGS object

discussions/views.py
Fixes #3533 
Adds a queryset to the create channel view since it's required by django-rest-framework. The queryset is not used for anything so it is an empty list.
Create a channel via the `/api/v0/channels/` rest API. You should get an error. Look in the heroku logs and verify that the error is not due to the lack of queryset.
=> Add queryset for create channel API

static/js/components/PersonalTab.js, static/js/containers/ProfileImage.js, static/js/containers/ProfileImage_test.js
Fixes #3544 
Fixes a console error when uploading the profile image
Go to `/profile` and upload an image. You should see a console error when on master but not on this branch
=> Remove afterImageUpload callback which was erroring and is unnecessary

conftest.py, discussions/api.py, discussions/api_test.py, discussions/conftest.py, discussions/exceptions.py, discussions/factories.py, discussions/serializers.py, discussions/signals_test.py, discussions/tasks.py, discussions/tasks_test.py, discussions/views_test.py, profiles/signals.py, search/api.py, search/api_test.py, search/tasks.py, search/tasks_test.py
Part of #3475
Adds contributors when a new channel is created, and synchronizes new contributors when the account is created or updated
Creating a channel should populate contributors based on the provided query:
- Seed your database using seed_db
- Go to `/learners`, open your network tab and execute some search targeting a handful of people with some substring of their name, for example `fl`. Copy the search query from the request.
- Go to `/api/v0/channels/` and fill out the form. Paste the query into the search query field. You should get a 201 with information about the new channel
- On open-discussions go to `/api/v0/channels/<channel_name>/contributors/` and verify that there are the right number of users (all the users in your search plus one for the API user)
When a user updates …
=> Add contributors when new channel is created

repl.py
Any opinions about this PR?
None
Adds a script `repl.py` which runs the Django shell with all models imported.
Run `docker-compose run web ./repl.py` and type `Role`. You should get the name of the model
=> Add shell with imported models

discussions/exceptions.py, discussions/views.py, discussions/views_test.py
Fixes #3550 
Updates /discussions/ view to fail hard when a JWT couldn't be generated.
Ensure your user has to `DiscussionUser` record and go to `/discussions/`. You should see an error page instead of a blank page.
=> Fixed discussions redirect to show user error page

README.md, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
fixes https://github.com/mitodl/micromasters/issues/3461
In this PR i am showing messages to learner who is enroll and paid the course. So that he can get an idea, what going on with exam
@pdpinch 
```python
from dashboard.models import CachedEnrollment
from dashboard.factories import CachedEnrollmentFactory
from ecommerce.factories import (OrderFactory, LineFactory)
from exams.factories import ExamAuthorizationFactory
from exams.factories import ExamProfileFactory
course = Course.objects.filter(title='Digital Learning 100')[0]
course_run = …
```
=> Added message for future scheduled exams for learners who haven't taken an exam yet

conftest.py, discussions/api_test.py, discussions/signals.py, discussions/signals_test.py, discussions/tasks_test.py, discussions/views_test.py
Fixes #3557 
Adds a `transaction.on_commit` to fix a race condition
I'm not sure how difficult this would be. I think the only way to know for sure is to keep an eye out for future exceptions like this
=> Use transaction.on_commit to fix a race condition

grades/tasks.py, grades/tasks_pytest_test.py
Fix #3579
Modifies `generate_course_certificates_for_fa_students` to generate MicromastersCourseCertificates only when exam grades are available.
Take a look at the test
=> Generate CourseCertificates only when exam grades are available

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, dashboard/utils_test.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/Grades.js, static/js/components/dashboard/courses/Grades_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/lib/grades.js, static/js/lib/grades_test.js
Fix #3492
Added overall final grade data to the dashboard API.
Set a past course run to passed and create an exam run with a passing exam grade. you should be able to see the final grade for course just as before.
=> Overall final grade for course

micromasters/settings.py
Fixes #3590 
Turns off `disable_existing_loggers` which allows celery logging to show up in the console. According to [this](https://docs.djangoproject.com/en/1.11/topics/logging/#configuring-logging) this having it set to true is usually not desirable. I feel like this was set to true originally just because it was the default value.
- Add a `raise Exception("test")` in `discussions/tasks.py` `sync_discussion_user`.
- Check out master, restart micromasters and run `profile.save()` on some profile of your choosing. You should see no message in the console.
- Check out this PR, restart micromasters and run `profile.save()`. You should now see the exception in the output.
This is the original PR which added this configuration, though there isn't much explanation here: …
=> Update logging configuration to show celery exceptions

micromasters/settings.py
Fixes #3593 
Staggers pearson sync tasks so they don't all try to access the SFTP server at the same time.
Celery worker should start up and reflect the updated crontabs in the log
=> Stagger SFTP operations to Pearson (#3593)

static/js/components/channels/withChannelCreateDialog.js, static/js/components/channels/withChannelCreateDialog_test.js
Fix #3582
Redirect to new channel after creating it
Create a new channel, when you click CREATE button the window should redirect to the new channel.
=> Redirect to new channel after creating it

app.json, micromasters/settings.py, micromasters/tests/test_settings.py, scripts/test/run_selenium_tests_dev.sh, scripts/test/run_selenium_tests_travis.sh, tox.ini
Fixes #3599 
Removes the invalid default value for `MAILGUN_URL` and checks that these variables are present in settings.py
Set the correct URL in your environment variable and send an email from the learner search page
=> Make MAILGUN_URL and MAILGUN_KEY required values

mail/api.py, mail/permissions.py, mail/urls.py, mail/views.py, mail/views_test.py
fixes https://github.com/mitodl/micromasters/issues/3549
Added a [webhook](https://documentation.mailgun.com/en/latest/user_manual.html#tracking-bounces) to raise exception when an email bounced
try to post to
http://192.168.99.100:8079/api/v0/mail/bounce_event/
**Method:** POST
**Content-Type:** application/x-www-form-urlencoded
**POST LOAD:** `event=bounced&recipient=my-course-contact-mail@mit.edu&error=Unable to view`
It will raise exception that you can check in senetry
see the api
@pdpinch
=> Raised an exception to sentry when course team e-mails fail

micromasters/settings.py
Related to #3591 
The root logging configuration was specified incorrectly. The `root` configuration is at a separate level from `handlers`: https://docs.python.org/2/library/logging.config.html#dictionary-schema-details
Run `docker-compose run ./repl.py`, type `import logging` and `logging.getLogger('ui.views').info('hello')`. You should see `hello` formatted like a logging message
=> Move root logger to proper place

static/js/containers/DashboardPage_test.js, static/js/reducers/discussions_frontpage.js
#3626 
the pagination changes for the frontpage API in OD modified the response. MM wasn't updated to account for that change, so this PR just makes the necessary change so that the discussion card works again in MM.
confirm that, with the latest `master` on both MM and OD running, the discussions card is broken (the response should authenticate and come back from OD ok, but MM expects the shape of the data to be different than what it is).
then check out this branch on MM and confirm it fixes the problem.
=> fix frontpage api

discussions/serializers.py, discussions/views_test.py, static/js/lib/validation/discussions.js, static/js/lib/validation/discussions_test.js, static/js/reducers/channel_dialog_test.js
Depends on https://github.com/mitodl/open-discussions/pull/254
Make public_description not required
Should be able to create a channel with empty description.
=> Allow empty public_description

static/js/components/dashboard/courses/GradeDetailPopup.js, static/js/components/dashboard/courses/GradeDetailPopup_test.js
Fix #3575
Change course status in GradeDetailPopup for `currently-enrolled` status to as Auditing
Use a management command to enroll your user in a course run.
```alter_data set_to_enrolled --username staff --course-title 'Analog Learning 100'```
=> Change course status in GradeDetailPopup to Auditing

discussions/api.py, discussions/api_test.py, discussions/serializers.py
Fixes https://github.com/mitodl/open-discussions/issues/258
Adds creator of the channel as a moderator immediately to prevent race condition
Create a channel. When you are redirected to the new channel you should see a no posts page and the page should successfully receive no posts from the API
=> Add creator as moderator

.flowconfig, static/js/components/ErrorMessage_test.js, static/js/components/Learner.js, static/js/components/StaffLearnerInfoCard.js, static/js/components/StaffLearnerInfoCard_test.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseRow.js, static/js/containers/LearnerPage.js, static/js/containers/LearnerPage_test.js, static/js/containers/LearnerSearchPage_test.js, static/js/flow/programTypes.js
Fixes #3608 
Clears the dashboard data when a user leaves learner page. This fixes the error caused by the consistency check for price calculation.
See repro steps in #3608
=> Fix error navigating between profile and learner search pages

package.json, static/js/entry/style.js, static/js/entry/style_public.js, webpack.config.dev.js, webpack.config.prod.js, webpack.config.shared.js, yarn.lock
Fixes #3485 
This sets up the extract-text-plugin so that production builds will have separate CSS files which will contain all style information. 
View the PR build, log in, and view the dashboard. Nothing should look odd
=> Split CSS into separate file for production

static/js/components/email/EmailCompositionDialog.js, static/js/components/email/EmailCompositionDialog_test.js, static/js/components/email/hoc.js, static/js/components/email/lib.js, static/js/flow/emailTypes.js
fixes https://github.com/mitodl/micromasters/issues/3606
removed email variables display from email composer for course team email only
Go to dashboard as non staff user
```python
from dashboard.models import CachedEnrollment
from dashboard.factories import CachedEnrollmentFactory
from ecommerce.factories import (OrderFactory, LineFactory)
from exams.factories import ExamAuthorizationFactory
from exams.factories import ExamProfileFactory
course_run = CourseRun.objects.get(edx_course_key='course-v1:MITx+Digital+Learning+100+Aug_2016')
order = OrderFactory.create(user=user, status='fulfilled', …
```
=> Removed recipient email variables from email composer

package.json, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/constants.js
Fix  #3516
Display payment deadline for course 
Use this command ```./manage.py alter_data set_past_run_to_passed --username staff --course-title 'Analog Learning 200' --audit```
You should be able to see the payment deadline
=> Add payment deadline to course status

dashboard/api_edx_cache.py, dashboard/api_edx_cache_test.py, dashboard/views_test.py, search/api.py, search/api_test.py, search/indexing_api.py, search/signals.py, search/tasks.py, search/tasks_test.py
Fixes #3634 
Reduces the number of reindexes and tasks triggered after reindexing
Make sure you have open-discussions set up and you have a channel created. Open your open-discussions logs in a terminal. In micromasters go to your profile and save it without making any changes. You should see only the update of the `api/v0/users/.../` endpoint.
Make a change to your profile and save it. You should see the update to the `api/v0/users/.../` endpoint but also `DELETE` or `POST` to the subscribers and contributors APIs.
=> Check if document needs updating before reindexing

app.json, micromasters/settings.py, micromasters/tests/test_settings.py
Fixes #2342
If the deployment is a PR build, use the PR build app name in place of the given `ELASTICSEARCH_INDEX` value which is just copied from `micromasters-ci`. This should prevent PR builds from overwriting the index of CI
In a Django shell verify that the `ELASTICSEARCH_INDEX` setting matches the name of the PR build.
=> Use HEROKU_APP_NAME as ELASTICSEARCH_INDEX value for PR builds

README.md, travis/Dockerfile-travis-watch, travis/Dockerfile-travis-watch-build, webpack_dev_server.sh
Fixes #3651 
Uses `yarn install --frozen-lockfile` which errors if an upgrade is needed
N/A
=> Use yarn install --frozen-lockfile to error if upgrade needed

static/js/components/EducationForm.js, static/js/components/EmploymentForm.js, static/js/containers/ProfilePage_test.js, static/scss/profile.scss
#3665 
This fixes a layout bug in Chrome where the radio buttons on the profile education and employment tabs were overlapping with the labels. 
I think this bug may have been introduced with the most recent version of Chrome, so it should be tested there. But if you have a not-up-to-date version of Chrome, test it there first, then update, then test again.
BUG:
FIX:
=> Fixes a layout fix with radio buttons on the profile pages in Chrome

requirements.in, requirements.txt, search/api.py
Fixes #3654 
Log a diff of the difference between the Elasticsearch document and the serialized enrollment
Make a change to a `Profile` and save it using `with mute_signals(post_save)` to prevent Elasticsearch from updating. In the Django shell run `profile.save()` and verify that you see a logging message with a diff of the field that was changed.
=> Log a diff of the ES document and serialized enrollment

Procfile, app.json
Fixes #3684 
Sets a default log level of `DEBUG` and uses the log level specified in an environment variable for use with celery so its messages can be logged
In the PR build, configure a `CourseRun` to have a `freeze_grade_date` in the future. Open a heroku shell and a heroku log being tailed in a separate terminal window. Run `freeze_course_run_final_grades(course_run_id)` (from `grades.tasks`). You should see an INFO message in the terminal window saying 'the grades course "..." cannot be frozen yet`
=> Use application log level for celery workers

discussions/api.py, discussions/api_test.py
N/A
This fixes edge cases where a user has no profile. This would only happen for admin users or simialr edge cases.
=> Fixed discussion user sync issue for users with no profile

micromasters/celery.py
None
Removes function referencing `settings.INSTALLED_APPS`. The Django docs say that `INSTALLED_APPS` should not be referenced, instead we should use `django.apps.apps`. However the Celery docs also say that all tasks in installed apps will be detected if the argument is blank, so we do not need to reference it at all.
In a shell get your user id, then run `search.tasks.index_users.delay([your_user_id])`. Look in the logs and verify that the task was started correctly.
=> Don't reference INSTALLED_APPS directly

docker-compose.travis.yml
None
Fixes docker-compose configuration to set env vars correctly on travis. Note that tox sets these env vars for web containers and the selenium container already has these set in `docker-compose.selenium.yml`.
There should be no celery container failure in the Travis logs
=> Fix celery env vars for travis

config/nginx.conf
None
Removes redirects for hosts which don't exist in the development environment and moves buffer settings to the http context so that they are correctly applied.
Note that this PR only affects the dev nginx configuration, the nginx.conf.erb file is not altered so there will be no change for production machines
Start it locally and verify that nothing looks broken.
=> Remove unused redirects for development nginx configuration, fix buffer settings

requirements.in, requirements.txt
none
fixes an issue where the dev environment python and web containers wouldn't build
you should be able to run `docker-compose build --no-cache web` without seeing any errors.
=> upgrade psycopg version to 2.7

dashboard/api.py, dashboard/api_test.py, dashboard/tasks.py, dashboard/tasks_test.py
Part of #3659 
Refactors code for the `batch_update_user_data` task. Additionally the locking code should be fixed. Neither change should affect behavior since this task is only run once every 6 hours.
Delete the `UserCacheRefreshTime` object for your user. Run the `batch_update_user_data` task. Verify that the logs say that the lock is released and that there is a new `UserCacheRefreshTime` object for your user.
=> Refactor batch_update_user_data, fix lock behavior

static/js/components/LearnerSearch.js, static/js/components/channels/ChannelCreateDialog_test.js, static/js/components/email/lib.js, static/js/components/search/ModifiedSelectedFilter.js, static/js/containers/LearnerSearchPage_test.js
fixes https://github.com/mitodl/micromasters/issues/3645
It fixes a bug where filters are assuming every two characters a country 
- Go to search and filter `http://192.168.99.100:8079/learners/?company_name[0]=ME`,
- it should show me in filter list.
@pdpinch
=> Fixed search do not expand every two-letter abbreviation into a country name

dashboard/api_test.py, discussions/tasks.py
Fixes #3691 
Adds the timeout param so that the lock expires if the worker crashes.
Run the following:
```python
from django.core.cache import caches
from discussions import tasks
redis= caches['redis'].client.get_client()
lock = tasks.tasks._get_sync_memberships_lock() 
lock.acquire()  # should return True
```
Verify the key is present with a value:
```python
redis.get(tasks.SYNC_MEMBERSHIPS_LOCK_NAME)
```
Wait 2 minutes, then the `get` again and verify the value `is None`
=> Added timeout to lock

grades/tasks.py, grades/tasks_pytest_test.py
None
Add a filter to `FinalGrade`s when creating `MicromastersCourseCertificate`. This will prevent the certificates creation before the freeze of final grades.
The test creates a final grade with `passed=True` and `status='pending'` and checks that no course certificate is created for it.
=> CourseCertificates: create if final grade is complete

static/js/entry/zendesk_widget.js
- fixes https://github.com/mitodl/micromasters/issues/3602#event-1308561463
- https://sentry.io/mit-office-of-digital-learning/micromasters/issues/361180415/events/8370678176/
It adds a checks/conditions to avoid rendering of zenDesk widget button logic, it happens when button is not loaded in document.
- I was not able to produce the issue, but try to refresh page and look for below exception on console.
```trace
TypeError
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```
@pdpinch
=> Fixed an exception, happens when ZenDesk floating widget is not loaded

static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
fixes https://github.com/mitodl/micromasters/issues/3688
It disables re enroll button and adds next enrollment start date for courses with future enrollment start date
- Go to admin dashboard then course and change the enrollment start date of run to some future date.
- open MM dashboard and check the re-enroll button it should be disable, and see the text with it, it shall have new enrollment start date
@pdpinch
=> Disable re-enroll button for courses with future enrollment start date

dashboard/tasks.py, dashboard/tasks_test.py, discussions/tasks.py, discussions/tasks_test.py, micromasters/locks.py, micromasters/locks_test.py
Part of #3659 
Refactors the redis lock code to be shared between `batch_user_update_tasks` and `sync_discussion_users`. There is no behavioral change yet
- pick a real user on your machine and delete the `UserCacheRefreshTime` for that user
- In `dashboard.api.refresh_user_data` add a `time.sleep(12345)` to the beginning of the function so it takes a really long time
- Run `batch_update_user_data.delay()` twice. The second time you should see 'Unable to acquire lock for batch_update_user_data'
=> Refactor celery locking

discussions/api.py, discussions/api_test.py, discussions/exceptions.py, discussions/views.py, discussions/views_test.py
Part of #3618 
Propagates the 409 response from open-discussions to micromasters. This is necessary for handling the error in the front end in a future PR
Attempt to create a channel that already exists. You should see a 409 response in the network tab
=> Propagate 409 response from open-discussions when creating a channel

backends/views.py, backends/views_test.py, dashboard/api.py, dashboard/api_test.py
Fix #2383 
Fix #2132
Count the number of authentication failures per student, and after the third one do not try to update cache for that user until that user logs in and updates the credentials.
Play around with making your user credentials invalid, and then calling `refresh_user_data`.
=> Count cache update failure for user

scripts/test/run_selenium_tests_dev.sh, scripts/test/run_snapshot_dashboard_states.sh, selenium_tests/util.py
None
Fixes error with `run_snapshot_dashboard_states.sh`. The layout of docker-compose files changed but this script was not updated accordingly
Run `./scripts/test/run_snapshot_dashboard_states.sh`
=> Fix run_snapshot_dashboard_states.sh to use new docker-compose files

static/scss/profile.scss, static/scss/user-page.scss
Closes #3699
This fixes an issue where the edit icons were not lining up correctly on the user profile.
See that the layout matches the screenshot below in mobile views.
=> This fixes a mobile layout issue with edit icons on profile page

static/scss/discussion-card.scss, static/scss/search-page.scss
This tweaks the padding in the Discussion card on the dashboard. The left-right padding was too wide, forcing line breaks where there shouldn't be any.
Just see that it looks ok.
=> Two small tweaks to padding

discussions/api.py, discussions/api_test.py, discussions/serializers.py, discussions/views_test.py, requirements.in, requirements.txt, static/js/components/channels/ChannelCreateDialog.js, static/js/components/channels/ChannelCreateDialog_test.js, static/js/components/channels/withChannelCreateDialog_test.js, static/js/flow/discussionTypes.js, static/js/lib/validation/discussions_test.js, static/js/reducers/channel_dialog.js, static/js/reducers/channel_dialog_test.js
Closes #3715 
Switches to the new field we're using for channel descriptions
Create a new channel using markdown in description, ensure this shows up in the channel sidebar once created.
=> Switched create channel to new description field

ecommerce/api.py, ecommerce/api_test.py
Fixes #3741 
Adds a check that the coupon can be applied to the course run whose price is being calculated. We already do this check when calculating the price but we did not do it when creating the `RedeemedCoupon` object
- Set up two courses to be offered in your program.
- Create a coupon via the shell, for example:
cr = CourseRun.objects.filter(title__startswith='Digital Learning 100').first()
Coupon.objects.create(content_object=cr.course, coupon_type=Coupon.STANDARD, amount_type=Coupon.FIXED_DISCOUNT, amount=25, coupon_code='xyz')
- Then go to http://your.local.micromasters:8079/dashboard/coupon=xyz. You should see a dialog saying that your coupon is applied. Click 'Enroll' then 'Pay Now' then 'Continue'. You should be redirected to Cybersource. You don't have to actually make a …
=> Don't create extra RedeemedCoupon objects if the coupon is not being applied

static/scss/program-page.scss
Fixes the line height of course names in the course description popover on program page. There are some other minor font tweaks.
See that the changes match the screenshots below
BEFORE:
AFTER:
=> Fixes the line height of course names in the course description popover on program page

grades/api.py, grades/api_test.py, grades/tasks_test.py
Fix #3735
Makes sure that the freeze_final_grades task chooses users to freeze based on `CachedEnrollment` and `CachedCurrentGrade` data. 
=> Freeze grades only for users that have cached current grade

static/js/store/configureStore.js
Fixes #2739 
It looks like the redux-localstorage middleware only persists changes to the redux state for every dispatch call, not necessary every action. By swapping the order of the middleware the thunk middleware handles async actions correctly. When the program enrollments are received they are now immediately serialized to localStorage, fixing the issue.
See the steps in #2739
=> Fix redux localstorage persistence

scripts/test/run_snapshot_learners_states.sh, selenium_tests/data_util.py, selenium_tests/management/commands/snapshot_learners_states.py
None
Takes snapshots of the learner search page using different URLs to provide different filters. This should make it easier to detect problems caused by a searchkit upgrade
Run `./scripts/test/run_snapshot_learners_state.sh`. You should get a successful exit code and some png files in the `output/learners_states` directory
=> Add command to create snapshots for learner search page

package.json, yarn.lock
closes #3730 
This upgrades the react-dropzone package to the latest version, to incorporate a bug fix for an issue we've been seeing with IE and Edge.
Make sure there are no regressions in the functionality of the drop zone (we use it just for uploading a profile image). If you have access to windows, see if you can repro the error on master on there and (hopefully) this should fix it.
=> bump react-dropzone version to latest

test_requirements.txt
N/A
Fixes lint failures locally
`tox` passes locally.
=> Pinned astroid to 1.5.3 to fix lints locally

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
Fix  #3720
Show on the dashboard course runs offered in the future with only fuzzy start date available.
Create an offered run:
```./manage.py alter_data set_to_offered --username username --course-title 'Digital Learning 300' --fuzzy --in-future```
Wipe out the enrollment start date and upgrade deadline for that course run, or set them to date in the future.
=> add status message for course run with fuzzy start date

courses/models.py, dashboard/api.py, dashboard/api_test.py
Fix #3737
This allows a learner to access the dashboard when enrolled in a course run without a start_date.
Enroll a learner in some course run, then delete the start date and set the fuzzy start date for that course run. You should be able to load the dashboard without errors.
=> Fix CourseRunStatus for course runs with fuzzy start date

discussions/views.py, discussions/views_test.py, static/js/actions/channels.js, static/js/actions/channels_test.js, static/js/components/channels/ChannelCreateDialog.js, static/js/components/channels/ChannelCreateDialog_test.js, static/js/components/channels/withChannelCreateDialog.js, static/js/components/channels/withChannelCreateDialog_test.js, static/js/containers/LearnerSearchPage.js, static/js/flow/discussionTypes.js, static/js/reducers/channel_dialog.js, static/js/reducers/channel_dialog_test.js
Fixes #3618 
This adds support for handling backend errors, specifically to handle the error that occurs when a channel with the channel name provided already exists. It also cleans up the `channelDialog` reducer as this reducer was pretty overloaded with unnecessary complexity we don't need here. Also cleaned up a few stray references to the email dialog.
Create a channel. Attempt to create another channel with the same name and verify you see the error displayed. You should be able to change the name to a non-conflicting one and continue creating the channel successfully.
=> Updated create channel UI to handle backend errors (#3618)

discussions/utils.py, discussions/utils_test.py, discussions/views.py, discussions/views_test.py
Fixes #3736 
Whenever a user goes to /discussions, we will now block and force creation of the discussion user. The reason to do this is to address a race condition between user signup and syncing on the new user.This only fixes the user issue, they would more than likely not see any channels, which we may have to fix separately.
To reliably reproduce, delete your discussion user and navigate to /discussions
=> Create DiscussionUser on attempted navigation to open-discussions

static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js
fixes https://github.com/mitodl/micromasters/issues/3722
Allow staff to see if leaner is authorize for exam or not
Authorize a learner, see this learner profile
```python
from exams.factories import ExamAuthorizationFactory
from exams.factories import ExamProfileFactory
course = Course.objects.filter(title='Digital Learning 100')[0]
exam_run=ExamRunFactory.create(course=course, authorized=True)
au=ExamAuthorizationFactory.create(user=user, course=course, exam_run=exam_run, status= 'success', exam_taken=False)
exam_profile= ExamProfileFactory.create(status='success', profile=user.profile)
``` …
=> Displayed learner's exam eligibility for staff on profile page

discussions/permissions.py, discussions/views_test.py, static/js/components/channels/ChannelCreateDialog.js, static/js/components/channels/ChannelCreateDialog_test.js
closes #3784 
This changes the permission for channel creation to just check if the user is a django superuser, instead of looking to see if they have a staff role on the program in question.
I also added a little thing to display the error that is returned by the backend if you try to create a channel but do not have permission.
Few things to check:
- if your django user has `is_superuser` you should be able to create a channel
- if you do not, you should see the above permission error when you try
um, that's it.
=> restrict channel creation to superusers

static/js/components/dashboard/courses/GradeDetailPopup.js, static/js/components/dashboard/courses/GradeDetailPopup_test.js
closes #3767 
this PR fixes the grade popup status messages, so that we better take in to account whether the user has paid for the course run in question or not.
See the issue for some more details.
If you have a course run, which you've paid for, you should see different messages for courses which you haven't yet passed or failed. If you have paid and you're enrolled in the course you should see 'In Progress (paid)'. If you have paid but you haven't yet enrolled you should see just 'Paid'. If you are enrolled but have not paid you should still see 'Auditing'.
=> fixing auditing status display for paid courses

backends/pipeline_api.py, backends/pipeline_api_test.py
fixes https://github.com/mitodl/micromasters/issues/3795
- it updates pipeline api so that user can update email from edx
- Login to admin site, go to users and change email
- On micromasters site logout user and login it,  and go to admin site email should be up to date
@pdpinch
=> Synchronized email address with email address from edX

codecov.yml
None
Disables the codecov status checks. Coverage will still get uploaded to codecov and I think codecov will still comment on the PR. This is needed to prevent failed code coverage from getting in the way of the automatic heroku deploys.
N/A
=> Turn off codecov status updates

dashboard/utils.py, dashboard/utils_test.py
Fix #3777
Changes the logic of count_courses_passed in MMTrack to count differently for financial aid programs. If a course has exam then existence of the CombinedFinalGrade counts, if the course doesn't have an exam then we check for a passing FinalGrade.
Set a course run to past_passed, create ExamRun, create CombinedFinalGrade.
Run recreate index.
You learner should appear in the search results when you slide the "# of courses passed" facet.
=> count_courses_passed for courses with exams

static/js/components/SkipFinancialAidDialog.js, static/js/components/dashboard/FinancialAidCard.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/lib/api.js, static/js/lib/api_test.js
closes #3803 
fixes a bug! the bug was due to our use of the `fetchJSONWithCSRF` function for skipping financial aid. The `fetchJSONWithCSRF` function assumes that the response has a JSON payload, and it tries to parse the payload. If it doesn't parse correctly it throws an error.
The `skipFinancialAid` endpoint doesn't return a JSON payload when it is `PATCH`'ed, so we were trying to parse JSON where there was none to be parsed. Anyway, this meant that basically after the request came back as a 200 but before the 'success' action could be dispatched to the redux store we were throwing an error in the `fetchJSONWithCSRF` function that was causing the failure-case toast message to pop-up.
So, to fix it I just changed the API function to use `fetchWithCSRF` instead, which doesn't assume the …
=> fix financial aid skip bug

search/api.py
Fixes #3817  
Uses percolate doc type 
You will not be able to test this manually, there is no ES instance available for the PR build during the upgrade.
After merging to master we should be able to verify the fix like this:
Open a shell and run
from search.api import *
from dashboard.models import *
from search.models import *
search_percolate_queries(ProgramEnrollment.objects.first().id, PercolateQuery.AUTOMATIC_EMAIL_TYPE)
You should not get any exception.
There are no tests because the tests run against an ES5 instance which doesn't support the legacy percolate doc type
=> Fix percolate doc type for legacy index

README.md, docker-compose.selenium.yml, scripts/test/run_selenium_tests_dev.sh, scripts/test/run_snapshot_dashboard_states.sh, scripts/test/run_snapshot_learners_states.sh
None
Adjusts dev selenium scripts to forward port 7000. When used in conjuction with a breakpoint this should allow developers to browse the machines with the test data loaded on it.
See instructions added to README
=> Forward port 7000 to allow inspection of selenium images

selenium_tests/management/commands/snapshot_dashboard_states.py
Fix #3825
Change the exam related states to use Digital Learning program.
Run `./scripts/test/run_snapshot_dashboard_states.sh --match "exam"` and see that the screenshots make sense.
=> Snapshots: Make exam related dashboard states use FA program

travis/update-docker-hub.sh
Related to https://github.com/mitodl/cookiecutter-djangoapp/pull/120
Updates `update_docker_hub.sh` to generate a new hash for each updated image
N/A
=> Update update_docker_hub.sh to use a new hash for each image

discussions/api.py, discussions/api_test.py, requirements.in, requirements.txt
fixes https://github.com/mitodl/micromasters/issues/3783
passes email address and email optin flag to OD user api
- set `-e git+https://github.com/mitodl/open-discussions-client.git@master#egg=open-discussions-client` in requirments
- You should be able to go to /discussions/ in MM and that view will force-create it
@pdpinch
=> When creating discussion user, added email address to OD

docker-compose.yml
Part of #2867 
Changes docker image to point to 5.6.6 instead of 5.5
Learner search page should still work locally. This should not affect production at all.
=> Upgrade local Elasticsearch to 5.6.6, same version used in production

selenium_tests/management/commands/snapshot_dashboard_states.py
None
Add exam states that have exam run attempts and exam run offerings.
Adds the following conditions:
- can schedule exam 
- the course has exam runs schedulable in the future
- has a failed exam grade 
Before you run this delete the `output/dashboard_states` folder.
Create the snapshots and take a look at the png files
`./scripts/test/run_snapshot_dashboard_states.sh`
This is the state where user has two failed exam grades
The learner has one failed exam grade and a schedulable exam run
=> Snapshot Dashboard States: add more exam states

docker-compose.yml, elastic/Dockerfile
Fixes #3835 
Updates Elasticsearch configuration files to use 512mb of memory instead of 2g
Nothing should break. You will need to run `./manage.py recreate_index` first since the existing container won't be preserved (I think)
=> Lower elasticsearch memory usage limit

selenium_tests/management/commands/snapshot_dashboard_states.py
None
Add a state where user failed a paid course run and there is another offered course run.
Look at the screenshot
=> Dashboard Snapshots: Add scenario for FA paid course run 

discussions/api.py, discussions/api_test.py, discussions/conftest.py, discussions/management/commands/backfill_discussion_users_with_email_optin.py, discussions/tasks.py, discussions/tasks_test.py
fixes https://github.com/mitodl/micromasters/issues/3785
adds a task to bulk update emails and email optin of all user, this might be one time task
- on MM you can make email optin = false from user profile page and save
- Run command `docker-compose run web ./manage.py backfill_discussion_users_with_email_optin`
- check the user profile in OD for update 
- also restart celery if you find any issue with my task
@pdpinch
=> Update emails and email optin flag of existing users in OD

dashboard/api.py, dashboard/api_test.py, dashboard/serializers.py, dashboard/utils.py, dashboard/utils_test.py, grades/api.py, grades/constants.py
Fix #3810
Change the serialization for enrollments to include the best passing grade for the course.
Run an alter data command for you learner to set few enrollments to 'passed', you can pass the desired grade as an argument. Then make sure the highest grade appears in the final grade facet.
=> Serialize best final grades for search

search/api.py, search/api_test.py
fixes https://github.com/mitodl/micromasters/issues/3694
It is using scan instead of execute to fetch search doc. This will help large window error.
- do some email configurations in .env
- go to learners page and send email to everyone
- All show go well
- you may also need to run `docker-compose run web ./manage.py recreate_index`, I dont know why but i had to run it
@pdpinch
=> Added scroll api to fetch search code

static/js/components/dashboard/courses/ProgressMessage_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
fixes https://github.com/mitodl/micromasters/issues/3807
it assumes that if `course_end_date` is null that means course is not end. Progress component was crashing without any trace when `course_end_date: null`.
- Checkout master branch.
- From admin dashboard create a current course course without end date
- pay for logged in user
- View progress page, you wont see paid message and course in progress message.
- Now checkout my branch, you will see course in progress and paid status
```python
from dashboard.factories import CachedEnrollmentFactory
from ecommerce.factories import (OrderFactory, LineFactory)
course = Course.objects.filter(title='Digital Learning …
```
=> Fixed end date issues on progress messages

conftest.py, courses/factories.py, courses/serializers.py, dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, discussions/api.py, exams/tasks.py, financialaid/views_test.py, grades/api.py, micromasters/utils.py, pylintrc, pytest.ini, requirements.in, requirements.txt, seed_data/management/commands/seed_db.py, selenium_tests/conftest.py, test_requirements.txt, ui/templatetags/render_bundle.py, ui/templatetags/render_bundle_test.py, ui/views_test.py
Part of #3746 
Updates pylint, fixes warnings, updates django-webpack-loader and finally removes the filter on all `DeprecationWarning`s, replacing it with more targeted filters.
=> Update pylint, django-webpack-loader and remove DeprecationWarning filter

selenium_tests/management/commands/snapshot_dashboard_states.py
None
This adds more states where user is enrolled in a Financial Aid program and has paid for a course but is not enrolled currently. The states include cases where there is a currently offered course run, offered in certain future, with fuzzy date, or not offered at all.
Delete the folder `output/dashboard_states`.
Run the command `./scripts/test/run_snapshot_dashboard_states.sh --match "paid_but"`
Look at the generated output images
=> Snapshots: Add more PAID_BUT_NOT_ENROLLED states for FA program

static/js/components/dashboard/FinancialAidCard_test.js, static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js, static/js/constants.js
closes #3866 
This changes the date formatting for the dashboard stuff so we don't do `MM/DD/YYYY` format (which is not a standard format internationally) and we instead go for a thing like `March 14, 2014`.
Dates should all be formatted with the full, written month as above. The changed formatting shouldn't (I think) cause any spacing / layout issues, but probably good to check that too.
=> fix date formatting to be less US-centric

selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix #3862
Shows the link to certificate for a course if user has it.
Also, fixed a bug where the message about exam was shown even if course didn't have an exam.
Delete folder `output/dashboard_states`
Run ./scripts/test/run_snapshot_dashboard_states.sh --match "taking_again"
Take a look the output
=> Dashboard: show certificate if user has it

static/scss/profile.scss
#3368 
This fixes a layout problem in mobile devices where the edit icons on the profile page were overlapping with the center column text. I fixed this by adding flex layout to the columns.
See that it does not overlap in chrome, firefox, or safari on mobile.
=> Fixes overlapping icons on Profile page

selenium_tests/management/commands/snapshot_dashboard_states.py, selenium_tests/management/commands/snapshot_learners_states.py
Related to #3855
Fixed the bug where ALLOWED_HOSTS does not get overridden for dashboard and learner states tests.
Running `./scripts/test/run_snapshot_dashboard_states.sh` should run successfully
=> Override ALLOWED_HOSTS for snapshot states tests

dashboard/tasks.py, micromasters/settings.py
Fixes #3867 
Adds an environment variable to allow throttling of the batch user updates
Set the environment variable to something like `10/m` and run `dashboard.tasks.batch_update_user_data.delay()`. No errors should occur
=> Make environment variable to control batch update throttling

.gitignore
I'm not sure if we upgraded a version or what, but I've just noticed this new directory being written.
=> add .pytest_cache to gitignore

dashboard/api.py, dashboard/api_test.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
closes #3780 
If the user passed a course, we show them a little 'view certificate' link. However, in addition to this we'd like to give them the option to re-enroll in the course. This adds that option.
I discovered that the backend code for the dashboard API was set up to not return future course runs, in the case where the user already has a passing final grade on a past run. So, in order to get around that, I needed to make a small change to the dashboard API code, so that even if the user passes it will still return a future enrollable run (so we have something on the frontend in which we can enroll the user).
Get a course set up with two course runs, one, in the past, where you have a certificate and `STATUS_PASSED` and so on, and one, open for enrollment now, where you do not have …
=> add reenroll button

mail/utils.py, mail/views.py, mail/views_test.py
Fix #3806
Add a footer to emails
Try to send an email to your student account through the search results, the email that you receive should have a footer.
=> Add email footer

financialaid/serializers.py, financialaid/serializers_test.py, profiles/util.py, profiles/util_test.py, static/js/actions/financial_aid.js, static/js/containers/DashboardPage.js
fixes https://github.com/mitodl/micromasters/issues/3607
it fixes `api/v0/financial_aid_request/` api to move user to profile wizard if country is missing
- open a tab and type:
```python
docker-compose run web ./manage.py shell
u = User.objects.get(id=122)
u.profile.country = None
u.profile.save()
u.profile.country == None
```
- with out refreshing dashboard page , submit income
@pdpinch
=> Redirect user to profile wizard if residence is missing

seed_data/management/commands/alter_data.py, selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Related to #3545
Add more states for failed course run state with other course runs offered in the future.
Run ./scripts/test/run_snapshot_dashboard_states.sh --match "paid_failed"
Here are some of the states:
This is a state with course runs in the future and fuzzy enrollment dates (both types exist).
With currently enrollable run
Course run with fuzzy start date
No more course runs
=> Snapshots: add more failed course states

selenium_tests/management/commands/snapshot_dashboard_states.py
Related to #3901
Add dashboard states for user that passed a course, has a certificate, and we show re-enroll link.
Run `./scripts/test/run_snapshot_dashboard_states.sh --match "create_passed"` and look at the output folder.
=> Add states for View Certificate and re-enroll

uwsgi.ini
#3453 
uWSGI allocates a default buffer size of 4096 for request headers. When using the preview functionality the header is much larger than that buffer size so we raise a 502 error due to uWSGI failing to process the request. Increasing the buffer size allows for larger header values, preventing the failure on draft previews.
Set this value in uWSGI and generate a large diff in Wagtail, then try to view the preview.
uwsgi.ini
=> Increased the buffer size in uWSGI to address wagtail preview issue

mail/utils.py
Fix #3806 
Add postal address to email footer
Try to send an email to your student account through the search results, the email that you receive should have a footer.
=> Add postal address to email footer

cms/models.py, ui/templates/footer.html, ui/views_test.py
fixes https://github.com/mitodl/micromasters/issues/3891
invokes help widget on contact us link click.
Go to footer and click contact us
@pdpinch
=> Added contact us link on mm footer

mail/views.py, mail/views_test.py
closes #3851 
This PR makes it so that sending a search result email doesn't result in a failure redux action being dispatched. This was happening because the frontend was expecting a valid JSON payload in the response, but the backend wasn't keeping up it's end of the (read the issue for some specifics).
On master send a learner search email. Confirm that the email works and goes through, but that you see the `SEND_EMAIL_FAILURE` action get dispatched in the JS console.
Then checkout this branch and do the same thing. Confirm that it doesn't dispatch the failure action.
=> fix learner search email send error

test_requirements.txt
General, no specific ticket.
Sanitizes requirements files for pip 10.
Just ensure that travis builds complete.
Motivation: Tox pulls the latest pip when it creates a virtualenv. So, we have to satisfy whatever version of pip it will pull. Since mid-April, it will pull pip 10, which no longer accepts `git+https://....#egg` requirement specs w/out a leading `-e ...`
I haven't found a way to pin pip versions for tox :(
=> sanitize requirements per pip 10

static/scss/homepage.scss
None
This changes the programs grid on the micromasters homepage from a 3 column layout to a 2 or 4 column layout depending on the width of the browser. At small widths it is 1 column, at >992 px it is 2 columns. At 1600px+ it is 4 columns.
See that it works
=> change grid from 3 columns to 2 or 4 depending on width

cms/templates/cms/program_page.html, static/js/components/CourseListWithPopover.js, static/js/entry/public.js
Fix #3945 
If the program doesn't have courses to list don't show the grey box with title Courses.
Look at program page with courses and without.
=> Program Page: remove empty courses box

courses/admin.py
fixes #3940 
makes the admin list view for courseruns a little more convenient to use:
- displays all course run dates
- makes the date editable in list view
- adds program and course filters to the courserun list
View /admin/courses/courserun/
You may also want to set the course_number of a few courses (seed_db doesn't do this)
We're currently scheduling course runs 2-3 years into the future, with 2-3 runs per year. Since we (still) don't have a reliable source for this data, I have to enter it by hand.
=> display courserun dates in admin list view; make them editable

test_requirements.txt
Related to #3937 
A later version of pytest has a dependency ordering issue (or more likely our code does). For now just pin it to the same version used on Travis.
Run `./scripts/test/run_snapshot_dashboard_states.sh`
=> Pin pytest to fix selenium issues

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
fixes https://github.com/mitodl/micromasters/issues/3406
fixes a special case when there is only one future/current run in the course and status is`missed-deadline`. This PR restrict user to pay and resume course in this state.
- run ./scripts/test/run_snapshot_dashboard_states.sh --match 009
- create a course with one run and make start, due, enrollment dates null and set upgrade deadline to past date and see dashboard there should be no payment button.
@pdpinch
=> Fixed status message of current/future course when status is missed upgrade deadline

static/scss/_variables.scss, static/scss/homepage.scss, static/scss/program-page.scss
closes #3961
Now that we have 4 MM programs, we have switched from a 3 column layout to a 2 or 4 column layout, depending on the browser width. This change was made when the new program page launched, but in the 2 column layout, the thumbnails are too wide and tight on the page. This issue decreases the width of the columns in the 2-column layout.
In addition, I got rid of the "vh"-unit font-sizing at large browser widths because it looked awkward.
See that nothing breaks at various layouts.
=> Style and layout tweaks to Micromasters program pages

app.json
fixes https://github.com/mitodl/micromasters/issues/3918
```cli
heroku stack:set heroku-16 -a <app name>
git commit --allow-empty -m "Upgrading to heroku-16"
git push heroku master
```
https://devcenter.heroku.com/articles/heroku-16-stack#upgrading-an-app-to-heroku-16
> To upgrade via the Heroku Dashboard, navigate to your app settings page. Click the Upgrade Stack > button. Confirm that you want to upgrade, which will set the stack to the latest version. You will see > that the stack upgrade is pending; the upgrade with take affect on the next deploy.
I dont have permission but admin need to go to app (lets say micromasters-ci) settings and
inside info section press the button
cc @mitodl/devops 
it updates heroku stack.
see the heroku version of this PR
@pdpinch
=> Updated heroku stack in app.js file

static/js/containers/App.js, static/scss/toast.scss
Closes #3894
This fixes the layout of the toast message that has a title. For this particular message I removed the title, but for other toast messages with a title (h1) I removed display: flex, and that fixed the layout. I also did small tweaks to the font and margins.
Cause the toast message to appear, and see that the layout looks correct
=> Fixes toast layout issue

static/scss/homepage.scss
Closed #3965
This fixed a bug on the ipad, where the hero image was not displaying correctly on the micromasters homepage. There is a bug with mobile browsers that disable the background:fixed style. So I got rid of that style for the hero image.
This should be tested on the ipad. You can look at the micromasters home page in Safari to see the current problem.
=> Fixed ipad layout bug with background-attachment: fixed

app.json, micromasters/settings.py
https://github.com/mitodl/micromasters/issues/3943
https://github.com/wagtail/wagtail/issues/4512
https://github.com/wagtail/wagtail/pull/4502#issuecomment-386641100
it fixes an issue which appears when user re uploads exact same file on edit file. App was delete that file all together which was casing issue/exception mention on #4512
1. Login as admin (super user)
2. Go to documents and add a document lets say `x.pdf`
3. After uploading document go back to document listing page
4. Select the document from list that you just added
5. On edit page upload same document (exact same document) and press save
6. You will be navigate to the document listing page
7. Click edit on header notification or click same document that you just update
- User should be able to download file that we just …
=> Fixed document deletion issue appears when user upload exact same document in edit view

grades/management/commands/check_final_grade_freeze_status.py
None
There are users that un-enrolled from course run and have CachedEnrollment, but do not have CachedCurrentGrade, we do not want to count them in the process of freezing grades.
In the status massage reports the number of enrollments intersected with current grades.
Run this command for a frozen run:
`python manage.py check_final_grade_freeze_status <edx_course_key>`
=> Check freeze status show correct enrollment numbers

requirements.in, requirements.txt
Fixes #3928
Updates edx-api-client which now has a default 25 second timeout. This will result in sentry errors when the timeout is reached instead of silent heroku disconnects
=> Update edx-api-client to 0.5.0

dashboard/serializers.py, dashboard/serializers_test.py, search/indexing_api.py, search/indexing_api_test.py, static/js/components/LearnerSearch.js, static/js/components/channels/ChannelCreateDialog_test.js, static/js/components/email/EmailCompositionDialog_test.js, static/js/components/email/lib_test.js, static/js/components/search/FilterVisibilityToggle.js, static/js/components/search/FinalGradeRangeFilter.js, static/js/components/search/NestedAggregatingMenuFilter.js, static/js/components/search/util.js, static/js/constants.js, static/js/containers/LearnerSearchPage_test.js, static/js/test_constants.js
Fix #3840
Serialize  all semester enrollments for users that took the same course multiple times in different semesters.
Have your user enrolled in the same course multiple times, with paid/audited variation. When the user comes up in the search all semesters that the user was enrolled in show up in the Semester facet.
=> Serialize all semesters enrolled

micromasters/settings.py, micromasters/urls.py, requirements.in, requirements.txt, ui/templates/base.html
fixes https://github.com/mitodl/micromasters/issues/3329
You can masquerade login user with you super admin credentials 
- GO to http://192.168.99.100:8079/admin/auth/user/
- You will see buttons `Login as`
- click button, you will be taken to new tab with that person login
you can use these URLs for masquerade 
```
/hijack/<user id>
/hijack/username/<username>
/hijack/email/<user email>
```
- open this link in browser http://192.168.99.100:8079/hijack/username/<username how you want to see in action>
- It will take you to admin site login, user super admin credentials.
- Then you will be redirect to Micromasters app
cc @pdpinch 
- http://192.168.99.100:8079/hijack/email/satff@example.com
- <img width="639" alt="screen shot 2018-05-25 at 6 11 12 pm" …
=> Added django-hijack for user masquerading

grades/api.py, grades/api_test.py
Related to #3968
2 things:
Add info about what course was being processed when 'InvalidCredentialStored' is thrown.
Add users that don't have current grade to the cached users list, then the next time the task is run it will be able to set the status to COMPLETE, if no other errors occur.
Create a CachedEnrollment but no CachedCurrentGrade for a user and try to freeze grades for that course. The second time you run it should say `Final grades for course <edx_course_key> are complete`.
=> Add users missing grades to the cached list

dashboard/serializers.py, dashboard/serializers_test.py, search/indexing_api.py, search/indexing_api_test.py
Related to #3963
This PR adds the 'enrollments' serialization to avoid conflicts with the percolate queries currently on RC.
The tests should pass.
=> First step to update percolate queries that use enrollments nested field

static/js/components/ProfileImageUploader.js, static/scss/profile-image-uploader.scss, static/scss/profile-image.scss, static/scss/responsive-styles.scss
#3992
This fixes a layout and copy issue in the profile image uploader on mobile. The profile image uploader on mobile currently has a clunky layout with no left/right margins. Also the copy is wrong, as it says to "drag a photo" into the box, which is impossible on mobile.
See that it looks correct as in the screenshot above.
=> Fix profile image upload layout on mobile

dashboard/serializers.py, dashboard/serializers_test.py, search/indexing_api.py, search/indexing_api_test.py
Fix https://sentry.io/mit-office-of-digital-learning/micromasters/issues/564282932/
Some percolate queries use filter on the semester. This PR adds the semester field to enrollments.
=> Fix index error for field program.enrollments.semester

static/js/components/LearnerSearch.js
N/A
- It fixes a regression where semester facet is not disabling when courses are select and vise versa
- Go to learner search as staff
- Select one or all semesters then see course faces must be disable 
- Select a course then see semester facet must be disbale
@pdpinch @annagav
=> Fixed regression on semester facet front end side

dashboard/api.py, dashboard/api_test.py, selenium_tests/management/commands/snapshot_dashboard_states.py
fixes https://github.com/mitodl/micromasters/issues/3322
- When user has failed edX course and missed deadline. Instead of showing upgrade show user re-enroll of future run exist otherwise show him message that he failed course 
- From admin dashboard create FinalGrade of user `Foo`. with score 0.0 and not passed
- pick single run course
- Go to shell and do `docker-compose run web ./manage.py shell`
- Run below script
```PYTHON
from courses.models import CourseRun
from dashboard.factories import CachedEnrollmentFactory
user = User.objects.get(username='foo')
course_run = CourseRun.objects.get(edx_course_key='course-v1:MITx+Digital+Learning+100+Aug_2016')
CachedEnrollmentFactory.create(user=user, …
```
=> Do not show upgrade button when learner has fail edX course

cms/templates/cms/program_page.html, static/scss/_variables.scss, static/scss/program-page.scss
Closes #4012
This fixes two bugs on the program page. The first one is that a small box shows up in the top tabs when you hover over the tabs. The other one was a weird bug where "richtext" was being applied to the Program Page link in wagtail, which was causing some weird formatting issues.
See that the problems no longer happen
=> Fixing 2 layout bugs in Micromasters Program page

discussions/api.py, discussions/api_test.py
https://github.com/mitodl/open-discussions/issues/783 (3rd checkbox)
If `FEATURE_OPEN_DISCUSSIONS_USER_SYNC` is `True` or `None`, update the discussions profile when the Micromasters profile is updated.  If set to `False`, do not update.
- Set `FEATURE_OPEN_DISCUSSIONS_USER_SYNC=False` in your `.env` file
- Log in as a new user in Micromasters, fill in the required blanks, then go to 'View Discussions' link from the dashboard.
- In a discussions shell:
```python
from profiles.models import Profile
Profile.objects.first().name
```
- The full name should be the same as the first + last name in Micromasters
- In Micromasters, edit your profile and change your first or last name.
- In a discussions shell:
```python
Profile.objects.first().name
```
- The profile name should be unchanged …
=> Use flag to determine if discussions user should be updated

static/scss/general-styles.scss, static/scss/program-page.scss
Closes #4014
This PR sets sensible header sizes and margins for the program pages. There are now H2, H3, and H4 header sizes with appropriate margins. Top margins are set to zero for the first child element so that headers at the top of the page will be correctly aligned. This also decreases the margins for list items, and sets a bigger bottom margin for the ul element. 
Create a program page with different size headers, and paragraphs, and lists.See that the headers on the page match the screenshot below.
=> Fix fonts and spacing on program pages

discussions/tasks.py, micromasters/settings.py, requirements.in, requirements.txt
Related to https://github.com/mitodl/cookiecutter-djangoapp/pull/131
Fixes error and exception sentry reporting. The sentry handler needs to be part of the logging in order to handle explicit error and exception logging (unhandled exceptions are taken care of in the middleware I think). More info: https://docs.sentry.io/clients/python/integrations/django/#integration-with-logging
Celery exception reporting also isn't working with `get_task_logger` for some reason. I replaced it with `logging.getLogger` like we do everywhere else.
There are also a few unrelated dependency upgrades.
Run a shell in the heroku PR build and type `logging.getLogger().error("testing")`. You should see a new sentry exception with that text.
To test the celery exception reporting shell into the heroku PR build and …
=> Fix sentry error/exception logging

selenium_tests/management/commands/snapshot_dashboard_states.py
Related to #4004
Add a dashboard state where user has failed a course, and wants to enroll again but personal course price still pending.
Run scripts/test/run_snapshot_dashboard_states.sh --match "failed_and_pending"
=> Add dashboard state: failed and pending price

exams/api.py, exams/api_test.py
fixes https://github.com/mitodl/micromasters/issues/3990
It skips authorization creation of inactive user
- create in active user,
- create exam run
- pay (full fill order) for user
- you will not see him authorize 
@pdpinch
=> Skip exam authorization for inactive user

Dockerfile
N/A
Pins dockerfile to pytohn 3.6.4 since 3.6.5 has broken apt packages
`docker-compose build --no-cache web` should succeed
=> Pinned Dockerfile to python:3.6.4

selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix #4025
Displays both messages about enrolling in a future run, and about not passed exams, including the case where the user needs to pay for another attempt.
Run  `scripts/test/run_snapshot_dashboard_states.sh --match "exam"`. Take a look at snapshots with the name variations that include:
"is_offered": another run is offered, user can enroll,
"can_schedule": there is another exam run,
"has_to_pay": the user exceeded the number of attempts, has two failed exam grades.
=> Show exam message even when has enrollable runs

selenium_tests/management/commands/snapshot_dashboard_states.py
Related to #4026
Add exam states when course end date is in the future (course in-progress). 
Run `scripts/test/run_snapshot_dashboard_states.sh --match 'create_exams_current'`
I decided to make this a separate PR so that it is easier to compare these new states on master branch.
There are states that have wrong messages that I will be fixing in PR #4032.
=> Add exam states where course is in progress

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js
Fix #4025
Changes the logic of messages for course that is still in progress.
Because the way the logic tree was constructed I had to refactor many of the exam messages out, and as part of that change some other messages got changed.
Main changes include:
- States for courses with end date in the future with exams (they were not handled correctly almost all of them are now changed)
- In non-FA program if the user passed the course, but didn't get the certificate yet, there was a message "You passed the course.". I extended this message to be shown for FA course with exams, when user passed the course and passed the exam, but did not get a certificate yet.
- Removed "The edX course is complete, but you need to pass the final exam." It did not contain any information about upcoming exams. …
=> Message about exam when course run in progress

cms/templates/cms/program_page.html
one way to fix #4042 
Adds a `<br />` tag to the h1 on the program page after "MicroMasters program in"
=> add line break in title

static/js/components/LearnerSearch.js, static/js/components/search/CustomRefinementListFilter.js, static/js/components/search/FilterVisibilityToggle.js, static/js/components/search/NestedAggregatingMenuFilter.js
Fix #4009
make RefinementListFilter use reverse nested aggregation to count users for semester enrollment.
Make a user enrolled in two different course runs in the same semester.
=> Fix semester user count bug

app.json, micromasters/settings.py
fixes https://github.com/mitodl/micromasters/issues/4007
fixes https://github.com/mitodl/micromasters/issues/3453
fixes https://github.com/mitodl/micromasters/issues/3982
It suggest to set `SESSION_ENGINE='django.contrib.sessions.backends.cache'`
login to wagtail and pre page with big tests
@pdpinch
=> Loading session engine from env var

courses/admin.py
fixes #4057
in the course admin list view:
1. add course_number
2. allow filtering by program 
Got to /admin/courses/course and confirm that you can filter by program and see a column of course numbers. Note that the `seed_data` script doesn't create course numbers. If you haven't created your own, they will all display `-`
We're up to 4 programs now, with 24 courses. This will help me find things more quickly.
=> add course_number & allow filtering by program in course admin list view

static/js/components/EducationForm.js, static/js/components/EmploymentForm.js, static/js/containers/LearnerPage_test.js
fixes https://github.com/mitodl/micromasters/issues/3118
This PR fixes makes:
- Each modal with a single title.
- The title will include the type of degree being added/edited. 
Go to profile page and add/edit degree and employment
@pdpinch 
- <img width="749" alt="screen shot 2018-07-09 at 4 41 07 pm" src="https://user-images.githubusercontent.com/10431250/42448573-0074ce1c-8397-11e8-9721-8e064697c77f.png">
- <img width="777" alt="screen shot 2018-07-09 at 4 41 16 pm" src="https://user-images.githubusercontent.com/10431250/42448574-00a505b4-8397-11e8-9e52-f3f6ac08f238.png">
- <img width="803" alt="screen shot 2018-07-09 at 4 41 23 pm" src="https://user-images.githubusercontent.com/10431250/42448576-00d21b9e-8397-11e8-8e50-c853229a4ec8.png">
- <img width="801" alt="screen shot 2018-07-09 …
=> Fixed education and employment dialog titles

dashboard/api.py, selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
Fix #4034
Change the message for FA course when user has paid but has not been enrolled in any course run.
Run `scripts/test/run_snapshot_dashboard_states.sh` make sure that `paid_but_not_enrolled` states make sense, and other states haven't changed.
=> Status message for paid but not enrolled

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix #4025
Show message about exams even when user has passed exam.
(Required)
Run `./scripts/test/run_snapshot_dashboard_states.sh  --match exams`
=> Offer to pay again for exam when already passed

dashboard/api.py, dashboard/api_test.py, selenium_tests/management/commands/snapshot_dashboard_states.py
fixes https://odl.zendesk.com/agent/tickets/19315
fixes #4064
- There was two runs sorted reverse/decending. 
- First run is future and some how enrolled and paid and status of second run is [CourseStatus.WILL_ATTEND](https://github.com/mitodl/micromasters/blob/master/dashboard/api.py#L388)
- Second run is currently enrolled and paid 
- Because of this current run was skipped.
**Run command:** `./scripts/test/run_snapshot_dashboard_states.sh --match create_paid_enrolled_currently_with_future_run` on my changes and on master
```
"runs": [
{
"id": 20,
"course_id": "course:/v1/iure-animi-eveniet",
"title": "CourseRun Minus eveniet qui saepe voluptatum.",
"status": "will-attend",
"has_paid": true,
"position": 1,
"course_start_date": "2018-08-05T17:16:03.273534Z",
"course_end_date": …
```
=> Fixed missing run issue on production

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
fixes https://github.com/mitodl/micromasters/issues/4025
adds payment button to has_to_pay courses
run `./scripts/test/run_snapshot_dashboard_states.sh --match=create_exams_current_edx_✔_exam_✔`
@pdpinch
=> Show payment button when user has to pay

mail/urls.py, mail/utils.py, mail/views.py, mail/views_test.py, profiles/views.py, profiles/views_test.py
fixes https://github.com/mitodl/micromasters/issues/3917
- If email-optin is updated to False then it adds user to mailgun unsub list.
- User  will not receive any email from MM mailgun address.
- **Question:** Is discussion uses MM mailgun address? Should it be block?
-  If email-optin is updated to True then it removes user from mailgun unsub list.
**To enable/disable unsubscribes:**
- Enable unsubscription feature for your domain.
- Remove text in the html and text footer templates so they won’t be appended automatically.
- Insert a variable in the html and text bodies of your email when you need unsubscribe links.
- This variable will be replaced by the corresponding unsubscribe link.
https://documentation.mailgun.com/en/latest/user_manual.html#tracking-unsubscribes
**Also set the …
=> Added mailgun unsub user support

discussions/api.py, discussions/api_test.py, discussions/factories.py, discussions/signals.py, discussions/signals_test.py, discussions/tasks.py, discussions/tasks_test.py
fixes https://github.com/mitodl/micromasters/issues/3613
- Adds user as moderator when staff role is added
- Remove user as moderator when staff role is delete
Try to add and remove user an see state op OD
@pdpinch
=> Update user as moderator when staff role is added or removed

discussions/api.py, discussions/api_test.py, requirements.in, requirements.txt
Part of #4074 
This updates our APIs to start sending the username to discussions so we can send this in the JWT
Be sure to `docker-compose build web`
Verify you can create and update users and you get the correct `UserSocialAuth` records in discussions (uid == MM username)
=> Updated odc and switched to passing user.username

mail/urls.py, mail/utils.py, mail/views.py, mail/views_test.py, profiles/views.py, profiles/views_test.py
This reverts commit f6580833d8bfe3addba9f76558fa15241ef6f29e.
Fixes #4091 
Fixes a breakage of the profile api
1. Confirm you can register a new user and complete the profile
2. Confirm you can update an existing users profile and the changes stick without error
=> Revert "Added mailgun unsub feature (#4051)"

roles/admin.py
fixes #4087 
Changes the user field in the roles admin from a drop-down to a raw id. 
Now the page won't try to load a list of 30k+ usernames. 
Go to /admin/roles/role/add and confirm that User is a input field now instead of a drop-down.
=> use the raw id for user in admin instead of drop-down

app.json
none
stops required SESSION_ENGINE for new apps
Does the review application for this PR build? Or, at least, does it fail somewhere else than on a missing value for SESSION_ENGINE?
=> SESSION_ENGINE is not a required setting

ecommerce/api.py, ecommerce/api_test.py
fixes https://github.com/mitodl/micromasters/issues/4029
When user is already enroll in course do not try to call enroll api. Because it was casing exception. see trace in issue
- enroll user
- pay for course
- it should not trow exception
@pdpinch
=> Only try to enroll learner if learner isn't already enrolled

mail/api.py, mail/api_test.py, mail/urls.py, mail/utils.py, mail/views.py, mail/views_test.py, profiles/views.py, profiles/views_test.py
fixes https://github.com/mitodl/micromasters/issues/3917
- If email-optin is updated to False then it adds user to mailgun unsub list.
- User  will not receive any email from MM mailgun address.
- **Question:** Is discussion uses MM mailgun address? Should it be block?
-  If email-optin is updated to True then it removes user from mailgun unsub list.
**To enable/disable unsubscribes:**
- Enable unsubscription feature for your domain.
- Remove text in the html and text footer templates so they won’t be appended automatically.
- Insert a variable in the html and text bodies of your email when you need unsubscribe links.
- This variable will be replaced by the corresponding unsubscribe link.
https://documentation.mailgun.com/en/latest/user_manual.html#tracking-unsubscribes
**Also set the …
=> Added mailgun unsub user support 

micromasters/settings.py
Fix #4090
Lets set SESSION_COOKIE_NAME so that we can invalidate existing session cookies by changing the name.
Make sure nothing breaks.
=> Expose SESSION_COOKIE_NAME as env variable

discussions/api.py, discussions/api_test.py
Fixes #4082 
Make the feature flag for update syncing separate from the flag for all syncing.
Toggle the flag to false in `.env`, verify a profile update does not trigger an update call to OD.
=> Renamed FF for syncing updates to a separate one

grades/tasks.py
Fix #4063
Removes call to ready() to avoid `Never call result.get() within a task!`.
Pick a course run you are going to test with and set the freeze grades deadline to now. Enroll your user in the course run.
Create cached info:
```
from dashboard.factories import *
CachedEnrollmentFactory.create(user=user, course_run=course_run, verified=True)
CachedCurrentGradeFactory.create(user=user, course_run=course_run)
```
To check that your user is ready to be frozen run:
```
from grades.tasks import *
api.get_users_without_frozen_final_grade(course_run).values_list('id', flat=True)
```
Call the task:
```
freeze_course_run_final_grades.delay(course_run.id)
```
Check on the freezing status:
```
./manage.py check_final_grade_freeze_status <edx_course_key>
```
Make sure you can reproduce this error …
=> Remove call to ready()

selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/test_util.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
Fix https://odl.zendesk.com/agent/tickets/20106
fixes #4117
Two main fixes:
- In the situation where user has passed a course but did not pay, the course run status is `CAN_UPGADE` or `MISSED_DEADLINE`. The existing code would only check for PASSED status, which happens only when user has paid.
- If a user passed a course and then failed it, the most recent one will be returned first, and the status messages would be calculated incorrectly for the overall status of the course.
The changes are made on the assumption that the backend returns status PASSED only for paid courses, and for any course run that is/was audited the status would be CAN_UPGRADE, MISSED_DEADLINE, or NOT_PASSED.
Run `scripts/test/run_snapshot_dashboard_states.sh`
=> Audited passed, then audited failed course

dashboard/api.py, dashboard/api_test.py, exams/models.py, selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js
Fix #3680
Add new states for `missed-deadline` status if exams are present.
Run 
`scripts/test/run_snapshot_dashboard_states.sh --match "create_passed_missed_payment_for_exam"`
=> Offer to pay after missed deadline

ecommerce/admin.py
none
adds search and filter to the coupon admin. 
I wish I could add searching and filtering by course title, but that was going to require research that I didn't have time for. 
Make a couple of coupons. Take a look at /admin/ecommerce/coupon
I'm adding this so that when the DEDP team gives me a list of coupon codes to disable, I can search for them easily.
=> add search and filter to coupon admin

static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js
Related to #4116 
Updates the progress message to give appropriate message to auditing learners. When learner audited the course and passed it, the status of course run will never be `STATUS_PASSED`, the possible values can only be `STATUS_MISSED_DEADLINE` or `STATUS_CAN_UPGRADE`.
Create a passed audited course for user, and a failed audited course that is more recent. Similar to the selenium test in #4116. Look at the ProgressMessage from staff view. It should say that the user passed but did not pay for the course.
=> Update progress message for staff

profiles/admin.py
none
adds search and filter to the coupon admin. 
I wish I could add searching and filtering by course title, but that was going to require research that I didn't have time for. 
Take a look at /admin/profiles/profile/ -- it should:
This will make it easier to find learner's profiles, particularly when they need to be manually opted out of email.
=> add search and filter to profile admin; use raw id instead of drop-down

app.json, backends/urls.py, micromasters/settings.py, ui/templates/oauth_maintenance.html, ui/urls.py, ui/views.py
Fix #4131
If the flag `OAUTH_MAINTENANCE_MODE ` is on redirect to a page with the message.
Set env var `OAUTH_MAINTENANCE_MODE` and try to login.
=> Oauth maintenance page on login

grades/admin.py
none
Adds an admin for MicromastersCourseCertificate
- create some course certificates
- checkout the admin at /admin/grades/micromasterscoursecertificate/
- the list view should include the username and creation date
- you should be able to filter on course name
- you should be able to search on email address or username
=> improve certificates admin

static/js/components/LearnerInfoCard.js, static/js/components/LearnerInfoCard_test.js, static/scss/user-page.scss
fixes https://github.com/mitodl/micromasters/issues/4113
- Displays student id on learners profile page for staff only.
- Login as staff and view profile of learner
- Login as student and view profile
@pdpinch
=> Added student id on learners page for staff only use

dashboard/serializers.py, dashboard/serializers_test.py, dashboard/urls.py, dashboard/views.py, dashboard/views_test.py, mail/utils_test.py, search/api_test.py, static/js/actions/programs.js, static/js/actions/programs_test.js, static/js/actions/ui.js, static/js/actions/ui_test.js, static/js/components/ErrorMessage_test.js, static/js/components/LeaveProgramWizard.js, static/js/components/LeaveProgramWizard_test.js, static/js/containers/DashboardPage.js, static/js/containers/DashboardPage_test.js, static/js/containers/SettingsPage.js, static/js/containers/SettingsPage_test.js, static/js/factories/dashboard.js, static/js/flow/enrollmentTypes.js, static/js/lib/api.js, static/js/lib/api_test.js, static/js/reducers/ui.js, static/js/reducers/ui_test.js, static/scss/_variables.scss, static/scss/navbar.scss, static/scss/profile.scss
fixes https://github.com/mitodl/micromasters/issues/4056
It adds a wizard to unenroll from one or many programs. And update UI on unenroll.
- Enroll programs one or many
- Go to settings and click unenroll link
- then select program(s)
- check dashboard
- when no program left i.e you unenroll all, check new card on dashboard with enroll link
@pdpinch 
-  <img width="825" alt="screen shot 2018-08-03 at 5 25 22 pm" src="https://user-images.githubusercontent.com/10431250/43642760-41d601f0-9742-11e8-9523-8b3a85c3403f.png">
- ![screen shot 2018-08-02 at 3 07 14 pm](https://user-images.githubusercontent.com/10431250/43577621-c7687772-9665-11e8-99d4-3a315c292401.png)
-  <img width="650" alt="screen shot 2018-08-02 at 3 02 58 pm" src="https://user-images.githubusercontent.com/10431250/43577405-2fa …
=> Added unenroll program(s) feature

discussions/views.py
Fix #4154
Set max age for discussions JWT cookie.
Make sure the cookie expiry is set correctly.
=> Set discussions JWT cookie max age

profiles/management/commands/retire_users.py, profiles/management/commands/retire_users_test.py
fixes https://github.com/mitodl/micromasters/issues/4139
Adds a command which retire user(s) from MM
- `docker-compose run web ./manage.py retire_users`
- `docker-compose run web ./manage.py retire_users --user=`
- `docker-compose run web ./manage.py retire_users --user=fake.raul.ramirez`
- `docker-compose run web ./manage.py retire_users --user=fake.raul.ramirez --user=fake.hector.ramos`
- `docker-compose run web ./manage.py retire_users --user=foo`
@pdpinch
=> Added command to retire user

dashboard/api.py, dashboard/api_test.py
And edge case where a production user cannot see course is `course list` near `schedule exam` button. He is eligible for past authorized exam run but exam run is not schedulable.
fixes https://github.com/mitodl/micromasters/issues/4137
- Adds future exam run along with current scheduling ones in determining weather course `can_schedule_exam` or not.
- Before this PR we determine it but only current scheduling  exam run
- But on the other hand we determine `pearson_exam_status` of a program `schedulable` only on the base of future run. Which was creating an edge case where user had no `can_schedule_exam` on course but on program he had status `pearson_exam_status="schedulable"`.
```python
from exams.factories import ExamProfileFactory
from …
```
=> Added future examruns check with current scheduling ones for calculating can_schedule_exam for a course

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
none yet
- adds a word that was missing from the dashboard message
- makes the message work for all learners, whether or not they've passed the course
- waiting on a new dashboard test state from @annagav 
- Needs a screenshot
=> make the missed payment deadline message work for all learners

static/scss/dashboard/grade-detail-popup.scss
fixes https://github.com/mitodl/micromasters/issues/4158
Fix padding issue on grad popup
* Add couple of proctor exam grads
* Click on exam grads from dashboard
=> fix css issue on dashboard gradding popup

static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
fixes [4177](https://github.com/mitodl/micromasters/issues/4177)
Add coupon message on dashboard.
- Create a coupon for a course in MM admin
- Apply coupon and you will see the message.
- For details about coupons please see https://github.com/mitodl/micromasters/pull/4181
**Dashboard without message**
**Dashboard with message**
=> add coupon message on dashboard

grades/management/commands/adjust_exam_grades_from_csv.py
Fixes #4169 
Add support for csv instead of tsv in `adjust_exam_grades_from_csv` command.
https://github.com/mitodl/micromasters/blob/master/grades/README.md
=> add support for csv, remove delimeter used for tsv

search/api.py, search/api_test.py, search/indexing_api.py
Fixes #4188 
Modifies `search.api.populate_query_memberships` to skip inactive users.
Modifies `search.api._search_percolate_queries` to gracefully handle users with missing profiles
Modifies `search.indexing_api.serialize_program_enrolled_user` to log an exception if a user has no profile.
For a given program, inactivate a user and add a user without a profile or delete the profile of an existing user in the program.
Create a new channel for the program.  The channel should be created successfully, with all contributors and moderators added (minus inactive user and user without profile).
You can also run the `populate_query_memberships` manually for the channel's `PercolateQuery` and make sure it finishes successfully.
=> Handle users who are inactive or have no profiles during populate_query_memberships

grades/README.md
related to #4217 
fixes #4220
Updates the section on importing grades in the README
Read the changes. Imagine you are looking at these instructions in 6 months. Will they still make sense? Will you be tempted into releasing the grades before the faculty review (like I was)?
See https://odl.zendesk.com/agent/tickets/23791
=> clarify review steps before adjusted grades are imported

selenium_tests/management/commands/snapshot_dashboard_states.py, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/util.js
Fix #4192
In the first ticket of the issue the user had a passed and failed course runs, where the failed course run appears first in the api response. `StatusMessages` logic was based on the first course run to provide appropriate messages.
This PR changes the logic to be checking for any passing course runs to offer information about exams.
Run the test
```scripts/test/run_snapshot_dashboard_states.sh --match "two_no_show_exam_attempts"```
Before:
After:
=> Fix exam messages when user has failed and passed course runs

static/js/entry/public.js
Fixes #4248 
Show login dialog at the start, if user is not logged in.
- Logout from micromaster
- Hit any of the following URLs, you will see login/signup popup.
- http://0.0.0.0:8079/dashboard
- http://0.0.0.0:8079/learners
- Signup will not be shown on home page 
- https://0.0.0.0:8079
=> show signup dialog on start

backends/pipeline_api.py, backends/pipeline_api_test.py, backends/views.py, discussions/views.py
fixes #4190 
User will redirect to correct `next` url even if they are already logged in to MM.
* Log out of discussions, micromasters, and edx
* navigate to `/login/edxorg/?next=/discussions/` in micromasters
* entering credentials in edx
you should be redirected to discussions (via micromasters)
* Now, with active logged-in sessions, navigate _again_ to  `/login/edxorg/?next=/discussions/` in micromasters, again you should redirected to `/discussion`
=> fix `next` parameter issue for /discussions

ecommerce/admin.py
None
on the order admin you can now:
- search by username and email
- filter by status
- view creation date, course key 
go to /admin/ecommerce/order and search on a username or email.
=> add search, filter and fields to order admin list view

certificates/views.py
Fix #4260
Change the `Date Earned` date in the learner record to be the created date.
=> Show Created Date in Grade Records

grades/api.py, grades/api_test.py, grades/management/commands/generate_program_letter.py, grades/signals.py, grades/signals_test.py
Fixes #4285
Fixes logic for program commendation letter creation. Previously it would only create letters for FA programs
- Add passing FinalGrades for a CourseRuns for your user in a Program (in addition to all the setup steps outlined in the previous commendation letter PR). The signal should generate the letter
- Delete that letter object, then run the management command. The letter should be generated again
=> Fixed logic for program commendation letter creation

cms/templates/cms/home_page.html
Fixes #4299 
Remove text "0 courses" from home page.
**OLD:**
**NEW**
=> remove "0 courses" from home page

courses/serializers.py, courses/serializers_test.py, courses/urls.py, courses/views.py, courses/views_test.py
#4311 
This PR adds a course_run api endpoint, a new serializer, and associated tests to the courses app.
The new endpoint can be hit manually (`api/v0/courseruns/`).
=> Adds viewset for courseruns API, required serializer, and related tests

docker-compose.yml, elastic/Dockerfile, requirements.in, requirements.txt, search/api.py, search/api_test.py, search/indexing_api.py, search/indexing_api_test.py, travis/Dockerfile-travis-watch, travis/Dockerfile-travis-web
Fixes #3748 
Bump elastic search version to 6.
Search should work in the app.
=> bump elasticsearch version

static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js
N/A
Remove passed from course progress for staff view
Create a user that audited a course run with a failing grade, and the user's page through a staff account.
=> remove passed from course progress for staff view

docker-compose.yml, elastic/Dockerfile, requirements.in, requirements.txt, search/api.py, search/api_test.py, search/indexing_api.py, search/indexing_api_test.py, travis/Dockerfile-travis-watch, travis/Dockerfile-travis-web
This reverts commit e890c10a1025fd5cdb450d48aa82a3d69314d318, reversing
changes made to 307ad527bd0857c9c23c10bd45858693aea37a78.
Output of the command `git revert -m 1 e890c10`
Fixes #4318 
Reverts the ES upgrade until we can plan/test the upgrade path.
You should be able to reindex and the app should still work
=> Revert "bump elasticsearch version (#4303)"

static/js/components/dashboard/courses/ProgressMessage_test.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/components/dashboard/courses/util.js, static/js/components/dashboard/courses/util_test.js
https://odl.zendesk.com/agent/tickets/29299
Fix the status message when the course ended but has not been frozen yet, and status is 'currently-enrolled' in the learner dashboard as well as the instructor view of the learner's page.
The bug occurred when there are two course runs one is `missed-deadline`, and the other `currently-enrolled` with course_end_date in the past.
The dashboard api assigns a status of `currently-enrolled` to a course that already ended, but has no frozen grades. This was causing a bug in `StatusMessages.js`. The function `courseUpcomingOrCurrent` considered a course current only based on the end date. I changed the functionality to consider the status of the course run as well.
=> fix dashboard message for past end date course run

static/js/containers/App.js
Fix #4304
Remove the `then` clause since `startProfileEdit` does not return a promise.
This change was originally introduced in https://github.com/mitodl/micromasters/pull/4294
Go to `/personal/profile` and try to submit the form.
=> Fix fetch user profile

.flowconfig, package.json, yarn.lock
Fixing vulnerable dependency: `js-yaml`
Updates `css-loader` that was requiring js-yaml 3.7.0.
Everything should work!
=> Upgrading css-loader to get rid of js-yaml@3.7.0

ui/templates/verify_email.html
Fix #4339
Update the message with a new support email, to contact edX directly.
register for a new account and see the page that asks you to verify the email.
=> Verification email not sent email edx

dashboard/api.py, dashboard/api_test.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/ProgressWidget.js, static/js/components/ProgressWidget_test.js, static/js/components/StaffLearnerInfoCard.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/test_constants.js, static/js/util/util.js, static/js/util/util_test.js, static/scss/dashboard/course-row.scss
Related to #4251
Adding elective courses to the learner dashboard.
Create a passing grade for a course and pay for it to see the progress widget circle fill up:
```
final_grade = FinalGradeFactory.create(user=user, course_run=course_run, passed=True, status='complete', grade=0.8)
CourseRunGradingStatus.objects.create(course_run=course_run, status='complete')
set_course_run_to_paid(user, course_run)
```
=> Learner dashboard: elective courses

package.json, yarn.lock
Fixing Security alert
Upgrade node-sass, that gets rid of the dependency for lodash.mergewith
=> Upgrade node-sass to 4.12.0

courses/views.py
N/A
Makes the courserun api public again
- ensure you're logged out
- ensure http://mm.odl.local:8079/api/v0/courseruns/ doesn't issue a 4xx error
=> Re-remove course run api permissions

courses/catalog_serializers.py, courses/catalog_serializers_test.py, courses/serializers.py, courses/serializers_test.py
Closes #4410
Makes program URL absolute in API results
Check the following and make sure the "url" field is absolute and not relative:
- `/api/v0/catalog`
- `/api/v0/programs`
Based on xPro PR https://github.com/mitodl/mitxpro/pull/1155
=> Absolute program page URL

courses/catalog_serializers.py, courses/catalog_serializers_test.py, courses/views_test.py, micromasters/test_utils.py, micromasters/test_utils_test.py
Fixes #4406 
Fixes #4418 
Calculates instructors, total price, some date fields and renders them in the catalog API
Go to `/api/v0/catalog/` and verify that everything looks right. The `total_price` field should be a string representing a cost value with the number of courses times the price per course. The dates should be ISO-8601 formatted strings, or None if the date is null or if no course runs are unexpired.
=> Add instructors, price, start_date, end_date, and enrollment_start to catalog API

static/js/components/ProfileProgressControls.js, static/js/containers/ProfileFormContainer.js
Fixes #4356
Fixes the rejection of a promise to reject with a string reason instead of an errors object.
The `Promise.reject()` API takes a string, not an object, which is why we're getting this error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject
- On master, start to register with a new user. On the first page, click "Next" without filling out any fields, note that you get an error logged to the console.
- In this branch, do the same, you should no longer see the error and you should still be able to complete registration
=> Fix Non-Error exception issue

selenium_tests/basic_test.py, static/js/components/CourseListItemWithPopover.js, static/scss/_variables.scss, static/scss/dashboard/course-row.scss, static/scss/program-page.scss
Fix #4427
Redesign of elective tags for courses.
Set up the program page to have electives. Check the program page in the course widget for new electives labels.
=> New Elective tags for program page

config/nginx.conf.erb
Related to a ServiceNow Ticket # INC0336006 
Adds a redirect from `mmfin.mit.edu` to `micormasters.mit.edu/fin`. We already got and applied a new cert for mm that includes the mmfin as a SAN.
=> Added mmfin redirect

cms/templates/cms/benefits_page.html
Fixes #4451 
fix background image on benefits page
the image on the benefits page should load correctly.
=> fix background img on benefits page

static/js/components/CourseListItemWithPopover.js, static/scss/dashboard/course-row.scss, static/scss/program-page.scss
fix  #4459
Up date styles for course titles, some of the styles overlap with course styles on the dashboard page. 
Also removed the padding for enrollment information if there are no electives.
=> Fix styling of the Courses on program page

cms/models.py, cms/templates/cms/program_page.html
Fixes https://github.com/mitodl/micromasters/issues/4468
Add a check to remove for instructors carousel from the course team tab page.
- Create a program
- Add faculty members
- Add a child page `course team tab page`
- Render program page, you should see instructors carousel on the program page
- Goto course team tab page, you should not see instructors carousel on the program page
=> remove instructors carousel from course team tab page.

exams/api.py, exams/api_test.py, exams/tasks.py, exams/tasks_test.py
Fix Sentry issue https://sentry.io/organizations/mit-office-of-digital-learning/issues/1143927971/?project=104497&query=is%3Aunresolved+&statsPeriod=14d
Splitting exam authorization task into smaller subtasks
=> Splitting exam authorization task into smaller subtasks

certificates/views.py, courses/serializers.py, courses/serializers_test.py, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/CourseRow_test.js, static/scss/dashboard/course-row.scss, ui/templates/grade_record.html
Fix #4484
Add the missing styles to the elective tags.
Test with a program that has elective courses
In the dashboard, the list of courses should be labeled accordingly:
=> Dashboard: fix elective tags

exams/signals.py, grades/api.py, grades/api_test.py, grades/signals.py, grades/signals_test.py
Fix #4403
Add a signal to ExamRun, when it gets updated, find all existing `CombinedFinalGrade`s and update them.
Have a learner with a passing exam grade and a passing final grade. The CombinedFinalGrade should get created with regular task. 
Then later create another exam run for that course, and a passing exam grade. Then set the date for grades available on ExamRun, and the combined grade should get updated.
=> Update CombinedFinalGrades when exam run gets updated

.flowconfig, package.json, yarn.lock
Fix #4496
Upgrade `nyc`. This version doen't require `handlebars` anymore.
=> Update nyc to 15.0.0

package.json, yarn.lock
Fixing this alert https://github.com/mitodl/micromasters/network/alert/yarn.lock/tar/open
Upgrade node-sass to bump up tar to 2.2.2
┆Issue is synchronized with this [Trello card](https://trello.com/c/ZzREVK3w) by [Unito](https://www.unito.io/learn-more)
=> Upgrade node-sass to bump up tar to 2.2.2

requirements.in, requirements.txt
Works around https://github.com/andymccurdy/redis-py/issues/1274#issuecomment-580897258
https://sentry.io/organizations/mit-office-of-digital-learning/issues/1549202925/?project=159445
Fixes `wrong number of arguments for AUTH` exception
Merge, then recreate the release candidate. Sentry should stop recording those errors.
=> Downgrade redis to workaround

static/scss/homepage.scss
None
Fix styling issue for mobile home view
checkout the home page in mobile view
After:
Before:
=> Mobile Home View: fix header name

profiles/management/commands/retire_users.py, profiles/management/commands/retire_users_test.py
#4525 / https://trello.com/c/H0CezVHG/26-retire-users-by-email-address-in-addition-to-username
fixes #4525 
Run the retire user management command with the email.
`docker-compose exec web ./manage.py retire_users --user={email}`
=> Retire users by email

static/js/containers/SendGradesDialog.js, static/js/util/util.js
none
this fixes an issue we noticed today. George found the issue, but we don't know why it's an issue!
Anyhow, for some reason having an import into `util/util.js` from a component doesn't seem to work. I have a few theories as to why while I'll try out later, this will at least get local development working again.
`/profile/personal` should load instead of erroring.
=> fix issue with /profile/personal not loading

cms/views.py, cms/views_test.py, micromasters/urls.py, selenium_tests/redirect_test.py
#684 / https://trello.com/c/QOR6q3J1/307-cms-hide-change-forgotten-password-link-in-wagtail
fixes #684
Just visit 
- http://mm.odl.local:8079/cms/login
- http://mm.odl.local:8079/cms/password_reset
It will redirect to the site home page.
(Optional)
(Optional)
(Optional)
(Optional)
=> Redirect cms login and forgot password pages to our site login page

cms/templates/cms/program_page.html
[Ticket](https://trello.com/c/qG78Fr5m/363-css-regression-youtube-videos-should-be-column-width)
#4581 
Adds javascript code to the program page template to fix styles on video embeds within rich text fields. This cannot be done simply by adding CSS because we're not using Wagtail Streamfield correctly and all the content (text and embeds) are coming from a rich text field. This requires selecting the correct elements from the markup and updating CSS at runtime.
Create a program page and add an embed in the description. Verify that the embed is full-width for the column.
Before
After
=> Youtube embed should be column width - #4581

static/js/components/dashboard/FinalExamCard.js, static/scss/final-exam-card.scss
[Ticket](https://trello.com/c/S7ayTeW3/356-css-bug-mouseover-highlight-squished)
#4574 
Updates the css to vertically center and properly size the edit button (plus the hover highlight) on proctored final exam card on the dashboard.
Have a user eligible for a proctored exam, visit the dashboard to view the updated UI.
Instructions in here for proctored exam eligibility setup: https://github.com/mitodl/micromasters/pull/2492
=> Mouseover highlight squished fix - #4574

cms/models.py
#4563 
Modifies inline edited models to use `panels` instead of `content_panels`. This gets rid of warnings from Wagtail.
Go to the CMS and edit different pages. Functionality and UI should remain the same while there should be no more warnings.
=> Warnings related to wagtail upgrade - #4563

micromasters/sentry.py
#4522, https://trello.com/c/NY9pgeqJ/23-configure-sentrys-python-sdk-to-not-capture-systemexit
fixes #4522, Configure sentry's python SDK to not capture SystemExit
Just keep running the app, it should keep creating events in Sentry and the app should not keep running
=> Configure sentry's python sdk to not capture SystemExit

uwsgi.ini
https://trello.com/c/upfutK0A/44-update-all-uwsgi-configs-with-recommendations-from-bloomberg-article
Removes uWSGI strict mode directive. We will re-introduce it after renaming some of the environment variables that appear in `uwsgi.ini`.
This is problematic: https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables
... Config variables are automatically assigned for env vars that start with `UWSGI_`. With strict mode on, bogus config setting names raise errors.
We've already tested it in a local environment, removing `strict = true` and observing that an error goes away.
=> Temporarily remove uwsgi strict mode

package.json, static/js/lib/validation/profile_test.js, test_requirements.txt, yarn.lock
closes #4620 
just bumps up the phone number validation lib we're using to the latest version. We were using a fairly old version, and we had some users having issues where valid phone numbers were being marked as invalid (particularly ones from Vietnam).
I also added a regression test that exposed the issue and is fixed by the dependency upgrade.
confirm that you can get past the first screen of the profile flow with a Vietnamese phone number like '+84-03-6123-4567'. Also confirm on master that you cannot do so.
=> fix phone number issues (came up w/ Vietnamese numbers)

static/scss/_button.scss
Fix https://trello.com/c/a06fND6x/389-css-bug-schedule-an-exam-button-is-too-tall
Fix the size of the SCHEDULE EXAM button
Set up your dashboard, so that you enrolled in a course or you passed a course. You can use the `alter_data` management command to set that up.  Then create an available exam for scheduling:
```
course = Course.objects.filter(title='Digital Learning 200')[0]
exam_run = ExamRunFactory.create(course=course, authorized=True)
user = User.objects.filter(username='student10')[0]
au=ExamAuthorizationFactory.create(user=user, course=course, exam_run=exam_run, status= 'success', exam_taken=True)
exam_profile= …
```
=> Fix the size of the SCHEDULE EXAM button

app.json, micromasters/settings.py, search/indexing_api.py
fixes: #4643 
`search.indexing_api.clear_and_create_index` should specify a configurable shard count when creating a new index, instead of settling for Elasticsearch's default.
=> asadiqbal08/mm Shard Count while creating index

static/js/util/profile_edit.js
fixes https://github.com/mitodl/micromasters/issues/4638
It restricts users from entering non-Latin names in their profiles.
1) Create a new account
2) Proceed to the first profile page, at /profile/personal
3) Enter non-Latin characters into the first name field. An emoji like 👍 will work.
4) The form expands to display the romanized name fields so the user can enter alternate names
5) Enter non-Latin characters into the Romanized fields.
6) Tab out of the romanized field. You should see a red underline indicating the validation didn't pass
7) Update the first name field to remove the emoji.
8) Submit the form by clicking the Next button 
You will observe that it's not getting submitted until you remove non-Latin character from romanized fields.
Current Scenario: When a user enters a …
=> enhance validations for romanized fields

static/js/util/profile_edit.js
fixes: #4649 
maxLength attribute is not setting properly over the address field. Set it there so characters would not exceed to maxLength.
- Visit /profile/personal/ page in mm.
- Add some text in address field, Address should be limit to 100 characters at max.
=> asadiqbal08/mm-Limit the address field to 100 characters long.

exams/management/commands/populate_edx_exam_coupons.py
none
The coupon report file from edx have a new pattern for exam-course code in the 'Catalog Query` column. 
This PR updates the management command for parsing the coupon codes, with a new regex to parse the course code.
Run the management command with new coupon file.
=> Updating the regex for parsing course codes from coupon report

ui/templates/social_buttons.html
https://github.com/mitodl/micromasters/issues/4673
Removes google plus button from the footer
Just go to any page in MM which shows footer, you will observe that the google-plus button is removed.
Desktop Before:
Desktop After:
Mobile Before:
Mobile After:
=> Remove google plus share button from footer

grades/admin.py
Fixes #4676 
It adds a Django admin filter of `course run` for `Final Grade`
go to `admin/grades/finalgrade/` in `Micromasters` and verify if you have course run filter there and it works fine by selecting a run.
Micromasters django admin.
=> Django Admin: Added course run filter on final grades

.github/workflows/scanning.yml, .zap/rules.tsv
Add [OWASP ZAP](https://www.zaproxy.org/getting-started/) ["baseline"](https://github.com/marketplace/actions/owasp-zap-baseline-scan) and ["full"](https://github.com/marketplace/actions/owasp-zap-full-scan) scans on a schedule, with Github actions.
These are run on a schedule, not in response to code commits, in order to catch vulnerabilities that are announced in between code updates. A couple of tests are ignored which we have found generate false positives too often.
=> Add OWASP ZAP scanning with Github action

.github/workflows/scanning.yml
In the "scanning.yml" workflow, add '@ref' notation to the 'uses' properties. This is required by Github and we are getting errors without them. I'm adding '@master' to the zaproxy actions in order to get the latest vulnerability definitions without having to update this file whenever they do a new release.
The Github documentation that I read yesterday said they "strongly recommend" the `@ref` syntax, not that it's required, but apparently it is.
=> Add git ref to Github action 'uses' specifier

seed_data/management/commands/seed_db.py, seed_data/management/commands/seed_db_test.py, seed_data/management/programs.json
Fixes #4438 
It adds `Elective Sets` and `Elective Courses` in our `seed_db` command.
**Note:** I've just added elective sets and courses for one program(`Digital Learning`) just so we have all relevant data(Programs with electives and without electives) available after seed. 
- Run `docker-compose run web ./manage.py seed_db --staff-user='<username>'`
- See that there are elective sets and courses added (You can verify via Django admin and opening Digital Learning program)
We had `seed_db` before we implemented the electives feature so, and it didn't have the functionality to add elective sets and courses which is addressed in this PR now.
=> Added elective sets and courses in seed_db command

exams/api.py, exams/management/commands/populate_edx_exam_coupons.py
none
This modifies the management command to run with any size coupon files.
Also it changes the the creation of the `ExamAuthorization`(s) to set the status for `SUCCESS` since we don't consult with Pearson anymore.
Run `./manage.py populate_edx_exam_coupons <coupons-report.csv>` 
Check the dashboard to see the link to edx to register for exam in that course.
=> Let the exam coupon command run many times

exams/api.py, exams/api_test.py, exams/signals.py, exams/tasks.py, exams/tasks_test.py
none 
This tasks used to run when ExamRun would get updated. It would go through all the exam authorization and set them to PENDING. I think this was done to sync authorizations with pearson. 
nothing should break. Make sure this task wasn't used for anything else other than syncing with pearson.
=> Remove update_exam_run task

dashboard/api.py, dashboard/api_test.py
none
Dashboard program info for a course should return authorizations that have coupons only.
Take a look at
Testing in django shell:
```
exam_run_past = ExamRunFactory.create(course=course, authorized=True, scheduling_past=True)
exam_run_current = ExamRunFactory.create(course=course, authorized=True, scheduling_past=False, scheduling_future=False)
user = User.objects.get(username='username)
exam_profile= ExamProfileFactory.create(status='success', profile=user.profile)
au_1=ExamAuthorizationFactory.create(user=user, course=course, exam_run=exam_run, status= 'success') …
```
=> Dashboard program info: filter exam authorizations with coupons

Procfile, docker-compose.yml, micromasters/celery.py
fixes #4692
make separate celery queue for edx dashboard update tasks
```
(base)  ✘ /micromasters/  docker-compose exec web python manage.py shell
Python 3.7.6 (default, Feb  2 2020, 09:00:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from dashboard.tasks import batch_update_user_data
In [2]: batch_update_user_data.apply_async(queue='dashboard')
Out[2]: <AsyncResult: ceef2ec5-3327-4366-b30e-393fd5635c01>```
=> make separate celery queue for edx dashboard update tasks

courses/admin.py
Fixes #4606 
It adds a search filter by course id on `Django admin's` CourseRun model/page.
- Open admin like `/admin/courses/courserun/?q=course-v1:MITx+15.415.1x+1T2020` and this should resolve to the course run associated with this ID.
- Micromasters admin.
=> Added course run search in admin based on edx course key

Dockerfile
Part of #4695
Pins the debian version of the python docker container. In practice most of we were probably already running this.
`docker-compose build`, then smoke test the app (login, upload a profile picture)
=> Pin Dockerfile to 3.7-buster

exams/management/commands/import_edx_exam_grades.py
none
handle username does not exist when processing the task import_edx_exam_grades
=> Import edx grades: handle username does not exist

exams/management/commands/import_edx_exam_grades.py
Fix #4756
Update the management command to ignore records that do not have a score.
Run the management command:
```./manage.py import_edx_exam_grades <file>```
=> Import exam grades: ignore no score rows

.github/workflows/ci.yml, Dockerfile, scripts/test/run_selenium_tests_travis.sh, selenium_tests/redirect_test.py, travis/Dockerfile-travis-watch
Fixes #4728 
Adds steps to run selenium tests in github actions
Check that selenium tests ran successfully in github actions
=> Add selenium to github actions

app.json, cms/models.py, cms/templates/cms/benefits_page.html, micromasters/settings.py
fixes #4758 
CMS: add Hubspot form to Benefits page template for `/orgainzations/` link
Just create the benefits page with organizations slug
**Organizations Page**
**Benefits Page**
=> CMS: add Hubspot form to Benefits page template for organizations link

static/scss/homepage.scss, static/scss/program-page.scss
#4779 
- Removes the background from the FAQ content panel
- Removes the tab underlines on Program page
- Add and FAQ page in a Program through CMS
- Open program page in the web app
- Check the background color on FAQs it should be white
- Check the Tabs, their text shouldn't be underlined
We recently did major design changes in the HomePage for which you can have a context thrugh this PR https://github.com/mitodl/micromasters/pull/4749
=> Fixed FAQ background & link underline decoration

micromasters/settings.py, micromasters/tests/test_settings.py, requirements.in, requirements.txt
#4753 
Upgrades deprecating `boto` to `boto3`
To test it manually we might need to do A/B testing and see nothing broke after this change. More critical parts on the testing would be the ones actually using boto, In our case it could be wagtail.
(Copied from the main issue) 
>`boto` is unmaintained and hasn't been updated in over 2 years. It's also now caused the warning
=> Upgrading boto to boto3

static/scss/homepage.scss, static/scss/program-page.scss
#4801 
[`Invision link`](https://projects.invisionapp.com/share/YFZ4N7KMWT3#/screens/435513872_Homepage_V2) for HomePage
Fixes the FAQ background color discrepancy in the program and homepage.
- Check that the FAQ section on the HomePage has a background (`#EBECED`)
- Check the FAQs tab on the program page doesn't have a grey background.
In PR #4781 we removed the background color on the Program FAQ page, a regression that had been introduced by the home page update PR #4749.
While fixing that we somehow missed the color on the homepage since the SCSS for both had the same class names for FAQs and its background removal got overridden on the homepage too.
**Home Page(Desktop)**
**Home Page(Mobile)**
**Program Page(Desktop)**
**Program Page(Mobile)**
I wish I could find a very relevant one …
=> Fixed the FAQ background regression

static/js/components/dashboard/courses/GradeDetailPopup.js, static/js/lib/api_test.js
Fix #4795
Removes text about pearson test on the dashboard, and a test.
This should effect the user dashboard, where the user clicks on the test score to view their attempts.
Where to find the text: In the course row the user has a little box with the exam grade. If the user clicks on that box with the grade, then a little popup opens up with the list of all the exam attempts and grades for that course.
=> Removing some pearson text

static/js/entry/style_certificate.js, static/scss/certificate.scss, static/scss/layout.scss, ui/templates/certificate.html, webpack.config.shared.js
https://github.com/mitodl/micromasters/issues/4788
It bundles and serves certificate.scss separately only on certificate page.
PRs like https://github.com/mitodl/micromasters/pull/4802 are increasing the size of css bundle considerably, while they only get used on the certificate-page. Serving this separately will reduce bundle size and optimize ranking on google lighthouse as it has negative points for downloading unused css.
Create a certificate and see if the css gets loaded correctly. You can verify it through the Network tab of your browser, it will be showing by the name of `style_certificate`.
(Optional)
=> Optimization: serve certificate related css separately

static/scss/certificate.scss, ui/templates/certificate.html
https://github.com/mitodl/micromasters/issues/4788
add support for 4 signatories in certificate design, previously the design started to break at 4.
Create a certificate with 4 signatories and see if the print works well.
=> add support for multiple signatories in certificate design

financialaid/admin.py
#4826 
Adds the user field to the `raw_id_fields` in FinancialAidAdmin.
Visit FinancialAidAdmin in Django, and check that don't see a dropdown for the user, instead, we should see a search icon which then opens a new window and loads the UserAdmin page to select user.
=> Adding user to raw fields in FinancialAidAdmin

financialaid/management/commands/migrate_finaid_program_tiers.py
Fix #4823
Adds a management command for finding all financial aid objects that have outdated program tiers and updating them with new ones.
Try to reproduce the bug as described in the issue. 
Then create new tier_program with the same income_threshold as the one you were testing with. Then run the management command `./manage.py  migrate_finaid_program_tiers`
=> Update existing FAs with current tier programs

static/js/components/OrderSummary.js
#4825 
- Adds an error message along with support link in case of API failure on the Order Summary page, Previously there was no error shown in case of failure
The steps to reproduce this are explained in detail in https://github.com/mitodl/micromasters/issues/4823.
**Desktop**
**Mobile**
=> Show an error message on checkout request failure

static/js/containers/OrderSummaryPage.js, static/js/entry/public.js
- https://github.com/mitodl/micromasters/issues/4834
- https://github.com/mitodl/micromasters/issues/4835
- https://github.com/mitodl/micromasters/issues/4614
- Fixes an undefined payload error in case of checkout API failure response
- Adds a polyfill & Fixes IE 11.0 error on property method forEach on the program page
- To reproduce and test checkout error you can follow the steps defined in https://github.com/mitodl/micromasters/issues/4823, On the order summary page, when you click `Continue` you'll see the error logged in the console in case of 400 API response.
- To reproduce the forEach property error, you'll need to open any program page which has rich text in it. Open the page in IE 11.0 and you'll see the error logged in the console.
**Note:**
I've run the seed commands and …
=> Fix sentry Errors -- typeError on Checkout & IE 11.0 forEach error

dashboard/api.py, dashboard/api_test.py, exams/models.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js
Fix #4824
Updates the some logic regarding the exam message when the user missed deadline to pay for the course. 
Set up a course
`./manage.py alter_data set_to_needs_upgrade --username <username> --course-title 'Digital Learning 100' --missed-deadline
`
Then set up an ExamRun that happens the same term as the course run.
You should get a message like this:
And if you create another ExamRun in the future, then:
=> Missed deadline message for exams

dashboard/utils.py, exams/api.py, exams/api_test.py, exams/utils.py, exams/utils_test.py
Depends on #4841 
Restrict exam authorization if user missed payment deadline
Set a course to enrolled but needs to pay using the alter_date management command:
`./manage.py alter_data set_to_needs_upgrade --username <username> --course-title 'Digital Learning 100' --missed-deadline
`
Then create exam runs, but not exam authorization since user gets authorized only once they paid for the course.
```
exam_run = ExamRunFactory.create(course=course, authorized=True, scheduling_past=False, scheduling_future=False)
```
This will create an exam that that is schedulable now. Which means that once there is a payment the user will get authorized for the exam run.
This restriction applies only user pays for current course run:
find the course run for which your user is auditing(it was printed out …
=> Restrict exam authorization if user missed payment deadline

cms/models.py
None
Adds a course panel to CourseCertificateSignatories
Go to cms to edit the program page, and try to add course certificate signatories to the program, you should see an option to select a course.
=> Adding course option to CourseCertificateSignatories

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Zendesk issue https://odl.zendesk.com/agent/tickets/93435
Add information about upcoming exam if the user failed and has an attempt to take the exam again.
Run this management command:
`alter_data set_past_run_to_passed --username <username> --program-title Digital --course-title 100 `
In django shell:
```course = Course.objects.get(title='Digital Learning 100')
user = User.objects.get(username='username')
exam_profile= ExamProfileFactory.create(status='success', profile=user.profile)
exam_run = ExamRunFactory.create(course=course, authorized=True, scheduling_past=True)
au=ExamAuthorizationFactory.create(user=user, course=course, exam_run=exam_run, status= 'success', exam_taken=True)
exam_grade = ProctoredExamGradeFactory.create(user=user, course=course, exam_run=exam_run, passed=False, …
```
=> Add a case when user failed exam but has another attempt

dashboard/api.py, dashboard/api_test.py, static/js/actions/ui.js, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseRow.js, static/js/components/dashboard/ExamEnrollmentDialog.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/containers/DashboardPage.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js, static/js/reducers/ui.js
Fix #4815
Add a confirmation dialog when the user goes to register for an exam on edx. To register for an exam the user has to follow the link to edx and enroll in the the exam-course on edx. 
The Dialog would warn the user that registering for an exam is going to use their only attempt to take the exam.
Set up a course that your user has paid for and has passed. You can use the alter_data management command:
`./manage.py alter_data set_past_run_to_passed --username username  --program-title Digital --course-title 100`
create and exam run, an exam authorization, exam profile, and exam coupon for  the user to use:
```
exam_run = ExamRunFactory.create(course=course, authorized=True, scheduling_past=False, scheduling_future=False) …
```
=> Adding a dialog for exam enrollment confirmation

dashboard/api.py, dashboard/api_test.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js
Fix #4845
Updating the exam authorization message, when the exam is currently schedulable
Set up a course that your user has paid for and has passed. You can use the alter_data management command:
`./manage.py alter_data set_past_run_to_passed --username username --program-title Digital --course-title 100`
create and exam run, an exam authorization, exam profile, and exam coupon for the user to use:
```
exam_run = ExamRunFactory.create(course=course, authorized=True, scheduling_past=False, scheduling_future=False)
au=ExamAuthorizationFactory.create(user=user, course=course, exam_run=exam_run, status= 'success')
exam_profile= ExamProfileFactory.create(status='success', profile=user.profile) …
```
=> Exam message for current exam run

exams/management/commands/populate_edx_exam_coupons.py
Ran into an error while populating edx exam coupons, there are 2 courses with number 14.310
Updates the command to check for a x after the course number.
Run the command:
./manage.py populate_edx_exam_coupons <file>
ask me for an example file
=> Populate exam coupons:look for more specific course number

Procfile
N/A
N/A
This wraps the workers with `newrelic-admin run-program`, so that the worker stats get reported to newrelic.
N/A, since it needs to be run on heroku.
=> Enable newrelic on workers

cms/templates/cms/benefits_page.html, cms/templates/cms/home_page.html, cms/templates/cms/program_page.html, financialaid/templates/review_financial_aid.html, ui/templates/dashboard.html, ui/templates/faqs.html
#4887 
Adds link to Zendesk's HelpCenter(FAQ)
Pages that this PR adds the FAQ section to:
- Benefits Page (Main/HomeScreen). (this is usually accessed at `/benefits`)
- Program Page(s)/Tab(s) (This includes all the tabs that show under a program)
- Dashboard Page (`/dashboard`)
- Order Summary (`/order_summary/?<course_key>`)
- Learners Page (`/learners`)
- Settings Page (`/settings`)
- Profile Page (`/learner/<username>`)
- Financial Aid Admin/submissions Page (`/financial_aid`)
Check that the FAQ show just above footer on all the aforementioned pages just above And the FAQ link is functional.
(Optional)
(Optional)
**Program Page**
**Program Page without Instructors**
**Program FAQ's Tab/Page**
**Benefits Page**
**Dashboard**
**Order Summary Page**
**Learners Page**
**Home Page**
**Email …
=> Adding common FAQ section for Zendesk 

static/js/components/Navbar.js, static/js/components/Navbar_test.js, ui/templates/header.html
fixes #4888 
- In the user menu, display a link to "Dashboard" above the link to "Learners"
- on the homepage, change the dashboard link from '/learners' to '/dashboard' 
Just visit the user menu
=> Link to Learner Dashboard for staff

.github/workflows/ci.yml
N/A
Updates github action ci.yml to allow codecov to fail softly.
Github actions should succeed, especially if the codecov upload fails.
=> don't fail CI if codecov upload fails

requirements.in, requirements.txt
Alert: https://github.com/mitodl/micromasters/security/dependabot/requirements.txt/urllib3/open
- Updates a transitive dependency `urllib3` to version `1.26.5` as suggested by a security alert
- In other to do the above we had to update `boto3` and `requests` as well. (So, here they are upgraded as well)
Check basic file uploads or any functionality dependent on `boto3 and requests`
=> upgrade urllib3==1.26.5 through boto3 and requests

certificates/views.py, dashboard/views.py
self.request.META.get("REQUEST_SCHEME") doesn't work on HTTPS servers, so feature started breaking on RC.
It uses request.build_absolute_uri which solves the problem
=> hotfix: change absolute url creation mechanism

mail/views.py
Previously we had only one URL for program records (`/records/programs/HASH`) so that same URL was used by the learner to look at his records and the same was shared across schools.
But now, we have two different record URLs and I saw that the old one was being used for sharing records through emails although it's not public anymore.
This PR will replace the new sharable link with the old link.
Try sending a record sharing email through `/records/programs` page
=> fix: change sharable record url

package.json, yarn.lock
https://github.com/mitodl/micromasters/issues/4952
Upgrade trim-newlines to v3.0.1
Just check everything is working, specifically webpack build compilations
`node-sass` requires `meow` and `meow` requires `trim-newlines`. To upgrade `trim-newlines` the ideal way is to upgrade node-sass from 5.0.0 to 6.0.0 but that requires the node version from 10 to be upgraded to >12. Even if we upgrade the node version we have to upgrade a lot of other dependencies as well.
That's why we have to use resolution for now.
=> Upgrade trim-newlines to v3.0.1

package.json, yarn.lock
Alert: https://github.com/mitodl/micromasters/security/dependabot/yarn.lock/normalize-url/open
- Upgrades the package `mini-css-extract-plugin` from `0.0.9` to the required version `1.1.2` in order to resolve the alert regarding `normalize-url`
- Check that webpack is working fine
- Overall website is working fine with proper CSS styling
=> build: bump mini-css-extract-plugin from 0.9.0 to 1.1.2 to fix normalize-url alert

package.json, yarn.lock
#4956 
- Upgrades all the `glob-parent` versions to use from  `5.1.2` in order to fix the alert
- Adds a resolution for `chokidar": ^3.4.3` only for `watchpack/webpack-chokidar2`, if we don't add this resolution we'll have to migrate the whole `webpack` from 4 to 5.
- Check the CI
- Check the webpack build is successful
- Good to run and go through the ap in general
=> Upgrade glob-parent to 5.1.2 through webpack and babel-plugin-istanbul

static/js/components/FacultyCarousel.js, static/scss/program-page.scss
#4961 
- Displays the instructors on mobile and tablets as well
- Updates the styling to fix left arrows spacing on mobile/tablet
- Fixes left arrow overlap display issue on mobile
- Add a program page through CMS
- Add instructors within the page
- Load the page and check the instructor's list is showing up fine on mobile/tablets as well as on desktop versions
Program Page
**Desktop Screenshot**
**Mobile Screenshot**
**Mobile Second Item Screenshot**
**Tablet Screenshot**
=> fix: display instructors on mobile as well

grades/factories.py, grades/models.py, grades/models_test.py
https://github.com/mitodl/micromasters/issues/4964
It uses UUID based hashes for certificates to make the URLs unpredictable
Create program and course certificates the hash should be working fine, secondly, the old certificates and their hashes should not be disturbed.
=> use uuid based hashes for certificates

search/management/commands/recreate_index.py, search/tasks.py
#4959 
- It moves the execution of `recreate_index` out of the main thread and puts it to a separate celery task
- Running the command e.g.  `./manage.py recreate_index` should now run separately in a celery task.
(Optional)
Previously we were facing timeouts when running this command with high amount of records.
=> Run recreate index through a celery task

static/js/components/DocsInstructionsDialog.js, static/scss/docs-instructions.scss
#4972 
- Fixes the frame design as per the dialog that is shown when clicked on the course link on the program page.
- Fixes the close event for the dialog
- Setup person price on the dashboard
- Check the dialog spacing
- Check that dialog closes upon closing outside the dialog boundary
- Setting up the personal price in the dashboard. More instructions can be seen on the associated ticket
**Desktop**
**Mobile**
**Reference dialog -- With which the design is matched now**
=> fix: instruction dialog frame design enhancement and closing operation

static/js/containers/DashboardPage.js
fixes #4934 
Handle promise rejections on the /dashboard page
Just visit the dashboard page and see everything is functional
=> Handle promise rejections

static/js/components/ProgressWidget.js, static/js/components/StaffLearnerInfoCard.js
fixes #4950 
Add link to accomplishment letter in the staff view of the learner profile page
Just visit the learners page from the staff user and view the user page
**NOW**
**BEFORE**
=> Add link to accomplishment letter in the staff view of the learner profile page

backends/pipeline_api_test.py, cms/models.py, dashboard/api.py, dashboard/api_edx_cache.py, dashboard/permissions.py, dashboard/permissions_test.py, dashboard/views.py, dashboard/views_test.py, ecommerce/api.py, ecommerce/api_test.py, ecommerce/permissions.py, ecommerce/views_test.py, financialaid/views.py, financialaid/views_test.py, micromasters/serializers.py, micromasters/serializers_test.py, profiles/api.py, profiles/api_test.py, profiles/permissions.py, profiles/permissions_test.py, profiles/serializers.py, profiles/serializers_test.py, profiles/views.py, profiles/views_test.py, search/indexing_api_test.py, seed_data/management/commands/seed_db.py, selenium_tests/management/commands/snapshot_dashboard_states.py, selenium_tests/util.py, ui/views.py, ui/views_test.py
Part of #4989 
This PR removes usages of `get_social_username` in favor of simply using `User.username` so that we can support users with social auth other than edx. I also renamed the existing functions in `profiles/api.py` so it's obvious those are edx-specific.
Generally speaking, nothing should break.
You should still be able to:
- View CMS pages
- Create an account
- Login with an existing account
- View your dashboard
- View your profile
- Edit your profile
- Make a payment
=> Remove usages of get_social_username

static/scss/letter.scss
Ticket #4988 
Removes Footer in Program Letter on Printing/Print Preview
- Create a Program Letter if one does not exist.
- Go to the Program Letter url '/letter/program/<program_letter_uuid>' 
- Verify footer is visible.
- Press CTRL+P to open print preview.
- Verify footer is hidden.
Program Letter page with footer visible.
Print preview with footer hidden.
=> Program Letter: added css to hide footer on print

backends/constants.py, backends/pipeline_api_test.py, dashboard/api.py, dashboard/api_edx_cache.py, dashboard/api_edx_cache_test.py, dashboard/api_test.py, dashboard/models.py, dashboard/views.py, dashboard/views_test.py, ecommerce/api.py, grades/api.py, grades/api_test.py, profiles/api.py, profiles/api_test.py, seed_data/management/commands/seed_db.py
Fix #4992 
Add support of cached enrollements and grades with another courseware backend mitxonline.
Register with edx org and enroll in courses there.
Register and enroll in courses with mitxonline as the courseware backend.
Test that:
Learner with only edxorg course runs can update their dashboard
Learner with only mitxonline course runs can update their dashboard
=> Update Cache for enrollments and grades for mitxonline

dashboard/utils.py, grades/api.py, grades/api_test.py
Fix #5021
Fixes a logic for program letter generation for non FA programs.
Enroll your user in a non FA program. 
Create an elective set for the program with 2 elective courses, and 1 course required. 
Make sure to set the num_of_required_courses for the program to an appropriate number.
Create passing grades for all courses besides one core course. You can use the management command:
`./manage.py alter_data set_to_passed --username username --course-title 'Analog Learning 200'`
There is a post save signal to run `generate_program_letter` on FinalGrade creation, so check to see that no letter was generated. 
Then create a final grade for the last missing core course, and check to see that the letter was generated.
=> Fix generation of program letters for non FA programs

micromasters/settings.py, profiles/models_test.py, requirements.in, requirements.txt
Related to #5026
Remove django-storages-redux
>django-storages-redux was a fork of the original django-storages, because django-storages was unmaintained at the time. django-storages-redux has now become django-storages so now django-storages-redux is deprecated and no longer maintained in favor of django-storages again
=> Remove django-storages-redux

dashboard/views.py, dashboard/views_test.py, micromasters/factories.py
Fixes #5041 
This updates the enrollment API to use the courseware base url for the appropriate backend.
A code review is probably adequate here and RC is setup to test this already. The testing setup to reproduce this locally is a bit complicated.
=> Fix enrollment API backend (#5041)

static/js/components/EducationForm.js, static/js/components/EmploymentForm.js
fixes #5019 
Can't select some countries in pulldowns on phone in portrait mode
Just see the country field on the profile page by adding degree and employment 
**MOBILE**
**TABLET**
**DESKTOP**
=> fix degree and employment form fields

courses/admin.py
#5015 
- Adds Courseware backend filter to course runs list in Django Admin
Once the instance is up:
- Visit `/admin/courses/courserun`
- Make sure you see a courseware backend filter 
- Make sure clicking any backend name in the filter shows filtered runs
=> Add Course backend filter in course run admin list

financialaid/constants.py
In practice, the only program that uses this financial aid system is also the one hosted on mitxonline
- ~~Mobile width screenshots~~
- ~~Migrations~~
- ~~Settings~~
none, but customer support noted the discrepancy on [slack](https://mitodl.slack.com/archives/CUZSS4FQB/p1632240614018300) 
replaces a mention of edx.org to mitxonline.mit.edu 
1. Create a user and submit income information that requires review
2. use the financial air review form to approve the income documentation
3. examine the generated email
=> all DEDP courseware will be on mitxonline

courses/factories.py, courses/models.py, courses/models_test.py, courses/serializers.py, courses/serializers_test.py, courses/views.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/SocialAuthDialog.js, static/js/factories/dashboard.js, static/js/flow/enrollmentTypes.js
Fixes #5051
- Limits the set of `enrollable_courseware_backends` to runs that are currently enrollable.
- Removed `prefetch_course_runs`, since I went to write tests I missed for this previously and discovered it wasn't doing what I thought it was and was probably harming performance if anything.
- Go to a dashboard for a program with past edxorg course runs for a user who doesn't have edxorg auth. You **should not** see the login prompt.
- Go to a dashboard for a program with past edxorg course runs and a future mitx online run for a user who doesn't have mitx online auth. You **should not** see the login prompt.
- Go to a dashboard for a program with past edxorg course runs and a current mitx online run for a user who doesn't have mitx online auth. You **should** see the login prompt.
=> Only prompt for login for enrollable runs (#5051)

dashboard/urls.py, financialaid/urls.py, micromasters/urls_test.py, profiles/constants.py, profiles/views.py, ui/urls.py
Fixes #5056 
Initially I thought this was because we weren't escaping the username, but those should be fine. Instead it was a url matching issue, so this updates the regex we use in the API urls so that it matches on newer username patterns coming from MITx Online. See the [corresponding regex](https://github.com/mitodl/mitxonline/blob/main/users/serializers.py#L30) in MITx Online.
- On `master`, verify you can reproduce the bug by changing your username to contain a `+` character. You should see 404 responses from the APIs
- Checkout this branch and verify the APIs now return 200 and you can load the dashboard and profile pages.
=> URL escape usernames for profile urls (#5056)

courses/models.py, courses/models_test.py
Fixes #5059
(Required)
- Go to `/api/v0/programs/`
- For one program, ensure there is exactly 1 course run configured for mitxonline
- Reloading the API response between changes, verify that in the `enrollable_courseware_backends` array, `"mitxonlin"` is present/absent with the following states for that run:
| `enrollment_start` | `enrollment_end` | `"mitxonline"` appears in `enrollable_courseware_backends` |
| --- | --- | --- |
| `None` | `None` | `False` |
| DATE IN THE PAST | `None` | `True` |
| DATE IN THE PAST | DATE IN THE FUTURE | `True` |
=> CourseRun.objects.enrollable() support null dates (#5059)

dashboard/api.py, dashboard/api_test.py, dashboard/views.py, dashboard/views_test.py, static/js/containers/FinancialAidCalculator_test.js
Fixes #5061 
This fixes the following things:
- Updates the appropriate view test to not make API calls to edX
- Updates the view.py and api.py to conditionally update the dashboard only the dashboard user matches the requesting user
For both of the following verify the UI makes a request for the user's dashboard when viewing the profile page and that it does not error. You can shut down openedx or disable your networking if you're using edx staging to ensure that a request isn't being made.
- As any user, view your dashboard, it should load
- As a staff user, view the profile of any learner
=> Don't refresh learner dashboards for staff (#5061)

static/js/components/CourseListItemWithPopover.js
Closes #5070 
This PR accomplishes the following
-  Updates text to `Learn More`
-  Removed conditional
This PR can be tested the following way
- Create a course run for a course
- Open Program page of a Program with that course.
- Click one of the courses in the sidebar
- Verify the link text is `Learn More`.
=> Updated Link text in course PopUp

courses/admin.py, courses/catalog_serializers.py, courses/models.py, courses/views.py, dashboard/api.py, dashboard/utils.py, ecommerce/api.py, ecommerce/models.py
Fixes #5074 
This removes the implicit `filter(is_discontinued=False)` from the `CourseRun` queryset. Django was pulling this criteria in when querying tables that had FK's into `CourseRun`, which in turn caused psotgres to lock the corresponding `CourseRun` row when doing certain operations that triggered a `select_for_update()` (e.g. `update_or_create()`). The implicit query filter via a custom manager has been replaced with explicit `not_discontinued()` filter calls. These calls were placed in very targeted areas, as the main goal here is to not include those course runs in the dashboard.
- Verify that runs that are discontinued still don't show up in the dashboard and nothing errors.
=> Remove implicit filtering of course runs (#5074)

ui/templates/signin.html
Fixes #5083 
Fixes a typo in the django template for this view that was breaking the url.
For a program that has an mitxonline course run, clink on "create account" on the program page. The link at the bottom of the screenshot below should have the url `/login/edxorg/`.
=> Fix broken link on login page (#5083)

dashboard/models.py
Continuation of #5076 
Removes another spot we had implicit filtering of `is_discontinued` present
The dashboard should load without issue.
=> Remove implicit filter on cached models

static/js/components/dashboard/CourseAction.js, static/js/components/dashboard/CourseAction_test.js
Fix #5087
When checking for a free coupon also check if the user has already paid (has fulfilled order) for the course run, and allow them to enroll in the course.
Create a UserCoupon for a user
Attempt to enroll in a course run when edx/devstack is unreachable in order to have enrollment not be created (Order will still be created)
Attempt to subsequently enroll in the run
=> Check if user paid for course having free coupon

static/js/components/dashboard/courses/ProgressMessage.js, static/js/components/dashboard/courses/ProgressMessage_test.js
fix #5099 
Add course certificate link for staff view
Login as staff and view a learners profile, where the learner passed at course and has a certificate ready for viewing. For a certificate link to be visible the `CourseCertificateSignatories` should be filled out for the program page in the cms.
Make sure that learner's dashboard view is unaffected.
=> Add course certificate link for staff view

package.json, yarn.lock
none
I set up our forked repo (https://github.com/mitodl/iso-3166-2.js) to be published as an npm package (https://github.com/mitodl/iso-3166-2.js/pull/4) so we don't have to include the package from github directly. Doing this will let us upgrade to the newest version of yarn, and do some of the build / CI setup simplifications we've done on other projects.
The features that use this project should work as normal, and tests should pass.
=> switch to depending on our forked iso-3166-2 package

micromasters/settings.py
Fix #5133 
Change the celery beat schedule to run `batch_update_user_data` only once a week on Sunday.
No new tasks `batch_update_user_data` should get scheduled before Sunday
=> Run batch user update only on Sunday

financialaid/templates/review_financial_aid.html
Closes #5048 
Adds search_query param to pagination buttons
- Go to `financial_aid/review/2/`
- Search for a user
- Verify on going to the next page total number of page's does not change
- Verify on going to the previous page total number of page's does not change
- Verify List remains filtered by the entered search param 
The number of users in the screenshots are 3 and less as I had changed the total per page for testing.
=> added search_query to pagination URLS

financialaid/views.py
fixes #4903 
add search by email, username in financial aid review search
Just visit the financial aid page by visiting like
`/financial_aid/review/program-id/pending-docs`
=> add search by email, username in financial aid review search

.github/workflows/ci.yml, Dockerfile-node, package.json, static/js/global_init.js, yarn.lock
part of #5129 
This upgrades our Node version to 14.18.2. This isn't fully updated (current version is 17.x.x) but this will get us to the point where we can upgrade yarn to v3 and run some other upgrades that will then, I think, let us upgrade to a more recent nodejs version and so on. We're climbing the ladder here :)
everything should work!
=> upgrade node to v14

package.json, yarn.lock
- Related to the alert fix PR created by dependabot https://github.com/mitodl/micromasters/pull/4986
- Removed the package `urijs`
While reviewing that PR which was somehow recreating the whole `yarn.lock` file hence in failing `CI build` for JS. Further looked into it and noticed that we are not using this package. So, I created the PR to remove it.
Note that upon merging this PR I'll be closing the other dependabot PR which bumps it. https://github.com/mitodl/micromasters/pull/4986
- Build is successful locally
- Everything in general is working
- Tests are passing
=> chore: remove unused package urijs

requirements.in, requirements.txt
Removes the following two packages:
- PyNaCl
- pysftp
Those were required for the Pearson integration which we no longer have in place.
=> Removed Pearson integration pkgs

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, exams/api_test.py
Fix #5198
Update the algorithm for determining the number of attempts still available to the user and whether they have to pay for the course again.
Take a look at the tests, make sure all cases are covered. Tests should pass.
The new algorithm for determining the number of attempts left:
```
Find all payments before the "first date"
Find the number of used attempts before the "second date"
if the number of used attempts is less than the amount of attempts given:
Compute the carry over amount of attempts, converting them from double attempts to single attempts
if the number of unused attempts (before second date) is 0:
Then we only compute the number of attempts in the new way, i.e. payment = attempt
else
find the number of attempts without the double attempts and subtract that from new …
```
=> Rewrite the algorithm for exam attempts

exams/management/commands/import_edx_exam_grades.py
Related to #5180
Fixes a bug with retrieving user in the import_edx_exam_grades task
Create a csv file that looks like this:
```
studentid,email,username,finalexam,enrollmenttrack,verificationstatus,certificateeligible,certificatedelivered,certificatetype,enrollmentstatus,id_course,experimentgroupvariationab,id_semester,grade,passed,percentage_grade,no_show,flag,score,title,course_id
2,example@email.com,username,0,verified,ID Verified,N,N,N/A,enrolled,310,,spring22,fail,FALSE,0,1,,,Digital Learning 100,9
```
And run the task `./manage.py import_edx_exam_grades temp.csv`
=> Fix a bug in import grades task

micromasters/settings.py
part of #5212 
Stops updating user dashboard data every day. Only updates user dashboard data on Fridays. 
I don't think it can be manually tested
We need to authorize exams on Tuesday 8/16. We don't want the exam authorization task to be slowed down waiting for these dashboard updates.
=> only update user dashboards on Friday

exams/management/commands/list_authorized_exam_learners.py, exams/management/commands/list_currently_enrolled_paid.py
Fix https://github.com/mitodl/mitxonline/issues/960
Adds commands to list users who need upgrade.
1) Run `./manage.py seed_db` to set up the programs and course runs 
2) create your test learner user by creating an account and filling out the profile
3) Run `./manage.py alter_data set_past_run_to_passed --username <username> --program-title Digital --course-title 100`   to enroll your test user in a course run, and create a passing grade and payment record, ( you will see the edx_course_key printed by the command, save it so that you can use it later)
4) Create an exam run and authorize the user for the exam:
```
exam_run = ExamRunFactory.create(course=course, …
```
=> Adds commands to list users who need upgrade

static/js/containers/DashboardPage.js, ui/views.py, ui/views_test.py
Fix https://github.com/mitodl/micromasters/issues/5225
Put  Proctored Exam Card under feature flag
In your .env file set `FEATURE_TURN_PAYMENT_OFF=true`
Go to the Dashboard and make sure the "Proctored Exam Card" doesn't show up
=> Remove the Proctored Exam Card

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, dashboard/utils_test.py, grades/api_test.py, selenium_tests/conftest.py, static/js/components/ProgressWidget.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js
Fix https://github.com/mitodl/micromasters/issues/5227
Updated all usages of the program field `financial_aid_availability`, that are not related to financial aid so much as much as to the existence of exams, combined final grades, and payments on our MM portal for courses.
In the past all of these were attributes of only one program: DEDP. But now that we are switching the payment system off, and financial aid is no longer available.
Run the app, nothing should break. Go the the dashboard make sure everything works. 
You need to create some exam runs for any courses in your program. 
The "Digital Learning" program by default has 'financial_aid_availability' turned on.
```
course = Course.objects.filter(title='Digital Learning …
```
=> Updating usages of fin_aid_availability

ecommerce/constants.py, ecommerce/views.py
#5228 
- Links the Enroll button links to MITxOnline (e.g. Clicking `Pay Now`) will take the user to MITxOnline's Cart
- Updates the checkout to take the user to MITXOnline's Cart page if the courseware backend is MITxOnline
- Switch off the `financial aid availability` for the program you're testing this with
- Set up this PR.
- Click `Pay Now` It should take the user to the MITx Online cart page with that item added to the cart.
- Click `Audit Pay Later` it should enroll the user in Audit mode in MITxOnline (If the courseware backend is set to `mitxonline`) otherwise it should enroll the user in edX.
**NOTE** You need to run MitxOnline app in parallel and make sure to test these:
- Make sure to notice the courseware backend for any course run you're testing with.
- Once the user is …
=> refactor: Enroll button link to MITxOnline (DEDP)

dashboard/utils.py
#5237 
- Adds an additional check on None edx_course_key lookup for has_paid(). We generally have only two possible options for the edx_course_key, (unique or None). So when an `edx_course_key` lookup is `None` it can find multiple courses but for a edx_course_key that is None, we should ideally have no payment for it.
- Enroll in a Program
- Have multiple course runs with `edx_course_key` set to `None` for any course in the program
- Load the dashboard (you should not see any errors and dashboard should load fine)
=> fix: A course is not paid for if edx_course_key is None

.github/workflows/ci.yml
Closes #5259 
Changes ubuntu version used for CI testing from "latest" (now 22.x) to 20.04 
CI tests should pass here
=> Peg python-tests ubuntu version to 20.04 (matching heroku stack)

grades/admin.py
Fix https://github.com/mitodl/micromasters/issues/5256
Add Admin model for Program Letter
Go to django admin and try to create a MicromastersProgramCommendation.
Check the following things:
1. You can filter letters by program
2. you can see creation and update dates
3. you can create a MicromastersProgramCommendation successfully
4. you can search by user email
=> Add Admin model for Program Letter

grades/api.py, grades/api_test.py, grades/models.py
#5257 
- Enhances the logic to generate letters and also activate existing ones
There are a couple of test cases for this:
1. Create an inactive program letter for a **fa** program, Now let's complete the program by passing all the grades and make sure a certificate object is created, also make sure that this existing letter has been activated.
2. Create an inactive Program letter for a **non fa** program, Now let's add final grades for the user and complete the program for the user. The program letter should be activated.
3. Now perform the above two steps without an existing letter, in this case instead of activating, a new letter should be created
4. This is the sum of all above, the logged information should be matched. e.g. the log message should be clear about when a letter is …
=> fix: enhance the program letter generation for active status

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix https://github.com/mitodl/micromasters/issues/5277
Remove status messages from the dashboard that are about exams. Weather passed, failed, about coming up future exams, about eligibility to take an exam.
There are way too many cases to test this manually.
On master, if you have passed a course run and there exists an exam run then you should be able to see a message about exam.
On this branch you should see only messages about the course itself.
=> Remove status messages about exams

dashboard/api.py, dashboard/api_test.py
Related to https://github.com/mitodl/micromasters/issues/5275
In the dashboard api, look for a MM course certificate, if not found look for a certificate on edx. Removing the dependence on existence of exams.
=> Dashboard API: Show any certificate for course

static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js
Fix #5281
Removes just the rendering of the coupon messages
Nothing should break.
=> Remove the display of coupon messages

static/js/components/dashboard/CourseListCard.js, static/js/components/dashboard/CourseListCard_test.js
Fix #5293
Removes pricing messages from course list card
Removes financial aid messages from course list card.
Create coupons for course, and go to the dashboard, there should be not messages about coupons.
You would need to create a Coupon and UserCoupon.
Before:
After:
=> Remove message about coupon pricing from dashboard

dashboard/utils.py, grades/api_test.py
Fix https://github.com/mitodl/micromasters/issues/5299
if the user has a passing FinalGrade for a course run that finished after September 2022.
The tests should pass.
Create a passing final grade for your user for a course run with start date after September 1st 2022. Make sure CourseRunFreezeStatus is 'complete'.
This course should be counted in the towards completion of the program in the ProgressWidget on the right of your dashboard.
=> Count passing final grades since Fall 22

cms/templates/cms/program_page.html
Fix https://github.com/mitodl/micromasters/issues/5245
Show mitxonline logo for programs that run on mitxonline.
Make sure you have the program page setup through wagtail: http://mm.odl.local:8079/cms.
One of the course runs in the Program should have the "courseware backend" set to mitxonline. You can set it through django admin.
Go to view the program page.
Before:
After:
=> Product Page: show correct "delievered on" logo

dashboard/api.py, dashboard/api_test.py, dashboard/utils.py, dashboard/utils_test.py, exams/api.py, exams/api_test.py, seed_data/management/commands/alter_data_test.py, static/js/components/CouponNotificationDialog_test.js, static/js/components/dashboard/courses/StatusMessages.js, static/js/components/dashboard/courses/StatusMessages_test.js, static/js/factories/dashboard.js, static/js/flow/programTypes.js
N/a
Update course status messages to show the message "You passed the course." for recent DEDP courses that that don't have a certificate.
Create a passing FinalGrade for a course run that has a start date after September 1st, 2022.
In the learner dashboard it should show a message the user passed the course.
=> Dashboard: Adding "You passed this course" message with no certificates

exams/admin.py
None
Makes it possible to search for exam authorizations by user email and be able to see is `exam_no_show` and `exam_attempted`. 
go to /admin and try to search for exam authorizations by email.
=> Admin: Make it possible to search exam auths

package.json, yarn.lock
Fix https://github.com/mitodl/micromasters/pull/5311
Opening this PR to upgrade minimist instead of this  https://github.com/mitodl/micromasters/pull/5311
=> Bump minimist from 1.2.3 to 1.2.8

test_requirements.txt
None, The CI fails on the build in multiple apps due to `codecov` being removed from PyPI. Similar PRs were created in xPRO, MITxOnline etc.
- Removes the discontinued `codecov` package
Just check that all the CI checks pass.
=> fix: remove discontinued codecov PyPI package

requirements.in, requirements.txt
N/A
This fixes an issue trying to build the app for heroku deployment. See the trace in the build log:
https://github.com/mitodl/micromasters/actions/runs/4699543907/jobs/8400688419#step:3:29935
The issue here is that heroku appears to have an pre-installed version of `setuptools`. There must've been a recent update that caused this to be upgraded to a version incompatible with how `l18n` invokes it. So I've pinned both `setuptools` (to the version current for Heroku) and `l18n`.
(Required)
- On `master` branch, add `setuptools==67.6.1` to `requirements.in` and run `pip-compile`. This should error with the same error on the failed build linked above.
- Checkout this branch, rebuild your containers, and smoke test that the app still runs.
=> Fix deployments due to conflict with a few library versions.

dashboard/api.py, dashboard/api_test.py, dashboard/tasks.py, dashboard/tasks_test.py, dashboard/views.py, dashboard/views_test.py, static/js/components/SocialAuthReauthenticateDialog.js, static/js/components/SocialAuthReauthenticateDialog_test.js, static/js/components/dashboard/FinancialAidCard_test.js, static/js/containers/DashboardPage.js, static/js/factories/dashboard.js, static/js/flow/dashboardTypes.js, static/js/reducers/dashboard.js, static/js/reducers/dashboard_test.js, static/js/test_constants.js
Fixes #5327 
This updates the dashboard logic to not cause a user to get in a circular login/logout loop if their MITx online authentication is no longer valid. It instead prompts them to reauthenticate with the correct provider.
For both MITx Online and EdX
- Authenticate with the social auth for that provider (`/login/mitxonline` and `/login/edxorg`)
- Go to the dashboard and verify you don't see any messages or alerts.
---
- Update the social auth record for that provider, changing the `extra_data` to have incorrect values for the refresh token and access token, this will simulate an expired or otherwise invalid token.
- Go to the dashboard and verify you get the popup dialog prompting you to login.
- You should be able to opt out of this and dismiss the dialog without authenticating …
=> Prompt learner to reauthenticate witht the correct social auth if invalid

certificates/views.py, dashboard/utils.py, grades/constants.py, grades/models.py
N/A
Updates the Program Record to display new combined final grades correctly, while not having course certificates and actual combined final grades objects.
As a learner go to your dashboard and view the program record link.
Find a course that you have passed, set the start date of the course run to be After Sept1st, 2022. Also, delete the combined final grade for that course if you had any.
Before:
After:
=> Update the Program record to display grades properly

cms/api.py, cms/models.py, cms/urls.py, cms/wagtail_api_test.py, micromasters/settings.py, micromasters/urls.py
Closes [#3711](https://github.com/mitodl/hq/issues/3711)
This PR has changes that integrate wagtail built-in api endpoints so we can retrieve content used in program letters from mit-open.
1. Checkout this branch.
2. If you dont already have some mock data, create a ProgramPage via /cms - make sure it is not sitting in the 'root' (should be a child of the "Micromasters Home" page. Fill out the required fields in addition to the fields starting with "program_letter_*"
3. Save and publish the page
4. navigate to the wagtail endpoint and specify the pagetype and wildcard for the fields http://localhost:8079/api/v0/wagtail/pages/?type=cms.ProgramPage&fields=*
5. See that all the program letter fields are shown (inckuding the list of signatories) in addition to links for the signature images
=> api endpoint for program page config

ui/templates/footer.html
None, Based on https://github.com/mitodl/micromasters-zendesk-theme-updated/pull/1#issuecomment-2016594288
Updates the Link for the Open Learning logo.
- Verify that the Open Learning Logo in the footer redirects to https://openlearning.mit.edu
=> fix: redirect footer logo to the open learning

dashboard/views_test.py
Related to #3878
Updates a test not call edx api and patch the call instead.
The test was not working properly because we didn't patch ExamAuthorization to return no object.
This test is checking to see that a user is authorized before we try enroll them for an exam run.
=> Test should not try to refresh token

cms/templates/cms/program_page.html, ui/templates/header.html
Fix https://github.com/mitodl/hq/issues/3936
Removes the sign in buttons from the DEDP program page. 
I used a hardcoded id for the program since it is never going to change. I didn't see much value in introducing a constant. We are moving away from the micromsters site.
After:
Before:
Make sure other pages are unaffected.
=> Removing sign in buttons from DEDP page

static/js/components/dashboard/CourseListCard.js, static/scss/dashboard/dashboard.scss
Related to https://github.com/mitodl/micromasters/pull/5399
Adding overlay over course rows
=> Adding overlay over course rows

static/js/components/Navbar.js, static/js/components/Navbar_test.js
Fixes https://github.com/mitodl/hq/issues/5685
Direct users accessing learner search to the data platform
The Learners link should open a new tab with  https://bi.ol.mit.edu/superset/dashboard/11/
=> Learner search goes to BI

courses/models.py, courses/models_test.py
Fix https://github.mit.edu/micromasters/micromasters-issues/issues/61
Remove "Coming" from fuzzy start date
Set the Fuzzy start date on a course run. The start date itself should be blank.
Before
After:
=> Remore coming from fuzzy start date

dashboard/api.py
Fix https://github.com/mitodl/hq/issues/6165
Instead of throwing an exception just log. We don't expect all users to have social auth both both backends.
Just look at the code.
Nothing should break.
=> Just log info when user has no social auth

micromasters/settings.py
N/A
This makes the discussions sync crontab configurable via an environment variable. The default is left since ideally that's what we'd use.
Set `CRONTAB_DISCUSSIONS_SYNC` to a crontab expression of your choice (e.g. `*/5 * * * *` for every 5 minutes). https://crontab.guru is a good resource to create a more specific one for testing needs.
=> Make discussions sync crontab configurable
