requirements.txt

upgraded uwsgi for incompatibility with mac env

---

courses/admin.py

Fixes #29 
Adds an admin for courses & programs
admin.py
Click around the admin. It should work just fine.
Based on work for #28  see https://github.com/mitodl/micromasters/compare/course-models-and-api...course-program-admin for real changes

Course program admin

---

bin/post_compile
bin/pre_compile

Closes #38 
This PR adds in the pre and post compile hook straight from TeachersPortal. It allows for running migrations and
See if the PR app (listed in this PR with a squirrel icon) has successfully deployed (meaning the build passed without error). If it deploys, the migration command returned a success signal.
Check if the git hash is being served from the static files on the review app: https://[pr-app].herokuapp.com/static/hash.txt
If the hash is shown, that means the pre_compile hook successfully ran when Heroku was generating the build artifacts, and that static files are configured properly.

Add pre and post compile hooks (migrations and git hash)

---

static/scss/layout.scss
ui/templates/index.html
ui/views.py
ui/views_test.py

homepage first draft

---

static/scss/layout.scss
ui/templates/index.html
ui/views.py
ui/views_test.py

N/A
Just integrates @annagav's work with @giocalitri's work, so we can click login on the homepage and see a username pulled from edx.
index.html
See #47 for info on oauth setup
Go to the homepage. Click sign in. Agree to the edx permissions. Come back and you'll see your username on the page.
It will be nice to demo this tomorrow.
https://github.com/mitodl/micromasters/compare/annagav/basic_homepage...auth-info-in-template--proof-of-concept  -- these are the actual changes relative to Anna's PR.

Auth info in template  proof of concept

---

pylintrc
test_requirements.txt

N/A
Adds [pylint-django](https://github.com/landscapeio/pylint-django)

Added django specific pylint

---

requirements.txt

Upgraded Django to security release

---

runtime.txt

Correct the heroku Python runtime

---

package.json
static/js/actions/index.js
static/js/components/CourseList.js
static/js/constants.js
static/js/containers/Dashboard.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/store/configureStore_test.js
static/js/util/api.js
static/js/util/api_test.js
static/scss/layout.scss

References #52
List available courses in the dashboard.

Implemented course list component

---

requirements.txt
test_requirements.txt

Moved factory libraries to requirements.txt to fix management commands

---

.dockerignore

Updated dockerignore

---

apt.txt

Removed pip from apt.txt, this gets installed separately

---

requirements.txt

Depends on https://github.com/mitodl/django-server-status/pull/23

Updated django-server-status

---

.gitignore
package.json
tox.ini

Fixes #117
Rebased on #115 
Adds istanbul, a javascript code coverage tool. When tests are run it outputs the data to the `coverage/` directory.

Added code coverage for javascript

---

package.json
static/js/actions/index.js
static/js/global_init.js
static/js/reducers/index.js
static/js/reducers/index_test.js

Fixes #128
Removes redux-actions

Removed redux-actions

---

static/js/actions/index.js
static/js/components/Dashboard.js
static/js/components/UserImage.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/api_test.js
static/scss/layout.scss
ui/views.py

Fix #67 
Go to student dashboard.

Display student avatar and name

---

requirements.txt

Updated tox version

---

courses/serializers.py
courses/serializers_test.py
package.json
static/js/actions/index.js
static/js/components/CourseList.js
static/js/components/Dashboard.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/layout.scss

Fixes #123
Updates the `CourseList` component to show the program tables like they are displayed in the UI. There are tests for each case of course status. Currently there is fake data for the dashboard API and real data for the course and program API so you may not be able to get the two to mix well to see the results when testing.
Create some programs, mark all of them live, then look at the dashboard
static/js/util/util.js
This contains the code which maps the course status to the UI to display

Implemented React component for dashboard API

---

courses/management/commands/gen_fake_data.py
courses/management/commands/gen_fake_data_test.py

Fixes #137
Generates CourseRuns when running gen_fake_data
Run `./manage.py gen_fake_data`. Use the Django shell to make a program live. You should see the resulting data in the dashboard and in the front page

Added CourseRun to gen_fake_data

---

static/js/components/Header.js
static/scss/layout.scss

Removed programs link in the header

---

app.json

We'll know this works if the respective environment variables are copied from micromasters-ci to the review app of this PR.
@noisecapella

Added missing configuration for heroku to app.json

---

micromasters/settings.py

Fixes #170 
Moves our pipeline functions to the end of the pipeline
See #170 for instructions on how to reproduce the problem. With this PR you should not see the problem anymore.
I tried writing a test for this but there's not much documentation on writing an integration test involving the pipeline so that we can reproduce the problem.

Moved our pipeline functions down the python-social-auth pipeline

---

static/js/containers/LoginButton.js

Added Profile and Settings links to dropdown menu

---

static/scss/layout.scss

none, but I introduced the change here: #181
makes one css change to eliminate this strange gap.
changes:
modified:   static/scss/layout.scss
make sure it looks right!
before:
after:

Fixed a small bug with the dashboard background image

---

static/js/components/Dashboard.js
static/js/reducers/index.js

Fix #168 
Move default image to react component. Check if profile image from edx exists, otherwise show default.

Fixed bug: default profile image

---

static/js/actions/index.js
static/js/components/PersonalTab.js
static/js/containers/App.js
static/js/containers/ProfilePage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/api_test.js

Part of #149 
Adds an action to PATCH the profile data
Go to the profile, edit a field. Click 'Save and continue' and it will stay on the page. Refresh the browser and see that the changed value is populated in the field
We should probably add a loader at some point.
Also, there is no validation done yet.

Added saveProfile action dispatcher, tests for saveProfile and updateProfile

---

README.md

Issue #77 -  Clean instructions in README for docker-osx-dev
Provide guidance for developers trying run Micromasters.
Open the "Getting Started" section in ``README.md`` and follow the instructions.
Follow the instructions and see if it works.
The setup procedure is more complex for OSX than for Linux.
Added setup documentation to ``README.md``.

Added setup documentation

---

dashboard/api.py
dashboard/api_test.py
static/js/components/CourseList.js
static/js/util/api.js
static/js/util/api_test.js

Fixes #192 
Replaces the mock data with a real call to the dashboard API which is now implemented

Implemented API dashboard function

---

static/js/components/PersonalTab.js
static/js/util/profile_edit.js

Moves arguments around in `boundSelectField` to be consistent with `boundTextField`

Move arguments for boundSelectField for consistency

---

.eslintrc
static/js/actions/index.js
static/js/components/PersonalTab.js
static/js/containers/ProfilePage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/profile_edit.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/layout.scss

Adds support for validation of profile fields in the front end (specifically personal tab for now).
Edit the profile and make all fields blank. When you click 'save and continue' you should see red text next to each field which is required (all of them for now).
preferred name is made required here due to a comment in #149

Added validation to personal page on profile

---

package.json
static/js/components/PersonalTab.js
static/js/containers/ProfilePage.js
static/js/countries.js
static/js/dashboard.js
static/js/language_codes.js
static/js/util/profile_edit.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #149 
Adds current location, birth location and date of birth fields
PersonalTab.js
Go into the profile, save to confirm validation errors. Fill out the new fields and confirm that validation works.

Added country and city fields

---

courses/factories.py
dashboard/api_test.py

Fixes #188 
Adds some fields to the course and program factories to provide random values for testing and when running gen_fake_data

Added fields to factory

---

package.json

Fixed striptags requirement issue

---

micromasters/settings.py

The redirect after the login is to the user dashboard page

After login the user is redirected to dashboard

---

static/js/dashboard.js

Fixes a bug where we do the google analytics update in the wrong place
This is somewhat difficult to test locally. It's probably best to just confirm the fix with the docs for react-router, then merge, then look at the google analytics dashboard for micromasters-ci.

Moved onUpdate from Route to Router

---

profiles/serializers.py

Changes to serializers.py

---

profiles/factories.py
profiles/serializers.py
profiles/serializers_test.py

Tests for serializer

---

dashboard/api.py
dashboard/api_test.py
dashboard/views.py
dashboard/views_test.py

fixes #224
it refactors the structure of the JSON for the dashboard. 
dashboard/api.py
The rest api endpoint for the dashboard should now produce a different output
the dashboard UI will be broken after this until the UI part is done

Dashboard JSON refactored

---

package.json

none
^^ what it says!
Pull it down and make sure it runs the tests!
I moved the JS testing into `package.json` a while ago, and I thought this was working then, but I just tried it and it is not.
This makes it work, so you can do:
```
docker-compose run web npm test
```
to run the JS tests.

Made `npm test` run the tests

---

osx_run.sh

None
Can run commands in the environment, example:
./osx_run.sh ./manage.py migrate profiles

osx_run script

---

package.json

none
this just adds a new script to the `scripts` field of `package.json`.
Usage looks like this:
```bash
docker-compose run npm run-script singleTest path/to/test.js
```
e.g.
```bash
docker-compose run npm run-script static/js/util/util_test.js
```
try it out!

Added `singleTest` to package.json for running a single JS test file

---

static/js/actions/index.js
static/js/components/CourseList.js
static/js/components/CourseList_test.js
static/js/components/Dashboard.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss

Fixes #225 
Updates the frontend to use the updated dashboard API on the backend
See `static/js/constants.js` to understand what changed, then look at `CourseList.js`
The dashboard should function correctly again, and now you should be able to see the program title in the table header.

Updated frontend for changes to dashboard API

---

.eslintrc
static/js/components/EmploymentTab.js
static/js/public/core.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util_test.js

Enforces that semicolons should always be used, and adds an unreachable code rule to guard against the case mentioned here: http://eslint.org/docs/rules/semi

Added semicolon enforcement rule

---

package.json
webpack_if_prod.sh

- Moves the stage1 babel requirement from devDependencies to dependencies so production builds can use it
- Adds `--bail` to webpack command so it returns a non-zero status code on error (surprisingly not the default behavior)

Moved stage1 plugin into production

---

backends/pipeline_api_test.py
profiles/factories.py
profiles/migrations/0011_add_employment_history_table.py
profiles/models.py
profiles/serializers.py
profiles/serializers_test.py
profiles/views_test.py
static/js/components/EmploymentTab.js

https://github.com/mitodl/micromasters/issues/240#issuecomment-215485603
@aliceriot @noisecapella @pdpinch 
- Added a model for employment history tracking.
- Added migration.
- Added data in ''api/v0/profiles/<user>
- see http://192.168.99.100:8079/api/v0/profiles/admin/
- see profiles/modal
- see profiles/serializers.py
- By using http://192.168.99.100:8079/api/v0/profiles/admin/

Created and added employment model in api 

---

courses/factories.py

Updated date to datetime to match CourseRun fields

---

package.json

https://github.com/mitodl/redux-asserts/pull/8
Updates version number to use latest redux-asserts (there is no functional change here)
This is a library for testing so as long as the tests pass, everything should be good

Updated redux-asserts

---

.eslintrc
static/js/components/Dashboard.js
static/js/components/EducationTab.js
static/js/containers/App_test.js
static/js/public.js
static/js/public/components/raty.js
static/js/public/core.js
static/js/public/jquery.raty.js
static/js/public/site.js
static/js/util/api.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

closes #293 
Adds eslint rules enforcing camelCase and the use of `let` or `const` over `var`. I also fixed the violations that it found.
I guess just reviewing the changes overall.
Make sure the changes don't break anything!

Added no-var and camelcase eslint rules

---

static/js/components/CourseList.js
static/js/components/CourseList_test.js
static/js/util/util.js
static/scss/dashboard.scss

fixes https://github.com/mitodl/micromasters/issues/226
fixes https://github.com/mitodl/micromasters/issues/162
- Added button to apply for Master's in the bottom of program.
- Added navigation on Enroll button and Upgrade button on courses inside program.
@pdpinch @giocalitri @aliceriot 
You can start review from dashboard listing. Then you can see utility function that creates course status.
Open dashboard page, click enroll button and upgrade button.
See disabled button at the bottom of each program which states apply for Master's in given program.

Added dashboard links to enroll and upgrade courses, and a disabled button to apply for masters on campus

---

static/js/hello_test.js

Removes hello world test that was part of the cookiecutter we used to create this repository

Removed hello_test.js

---

requirements.txt

Upgraded to latest django

---

static/js/actions/index.js
static/js/actions/ui.js
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/ProfilePage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss
static/scss/layout.scss
ui/templates/base.html

closes #289, closes #255, closes #290 
This implements the new design for the employment step, as seen here:
https://projects.invisionapp.com/share/4E791TKU3#/screens/153562860
There are a lot of changes! So probably just looking at the UI, making sure things look good and work as they should.
Then the additions to `EmploymentTab.js`.
Make sure you can edit work history! it should let you:
- add a new entry
- edit an existing entry
- delete an existing entry
- turn editing the work history on or off
- leave the end date blank (for a current position)
it shouldn't:
- let you 'save' an invalid entry
- let you set an empty start date (and the rest of the required fields)
it should:
- alert you with a little exclamation thing when there's a validation error on a particular entry
- show …

Implemented new employment page design

---

static/js/containers/LoginButton.js

closes #291 
Removes liks to profile and settings in the dropdown menu in any page
`static/js/containers/LoginButton.js`
just check the links are not there any more

Removed not implemented links in dropdown menu

---

static/js/components/EducationTab.js
static/js/components/PersonalTab.js

#281 
Changes the order of the location fields on the personal and education tabs (they were changed in #312 for employment).
The changes are in `PersonalTab.js` and `EducationTab.js`.
Make sure that you can edit the location fields on both of these tabs, and that nothing got mushed up.

Changed location order to Country -> State -> City

---

static/js/components/EducationTab.js

Used state select field for education tab

---

static/js/components/EducationTab.js
static/scss/dashboard.scss

closes #297 
this adds the ability to delete entries in the education tab (using `Array.prototype.slice`).
Check out the changes in `EducationTab.js`!
Try to delete education items! Make sure that only the one you click on gets deleted! etc!

Added 'delete' functionality to education entries

---

static/js/util/api.js
static/js/util/api_test.js

Fixes #296 
Refactors the api tests and adds testing for `fetchJSONWithCSRF`, `getCookie` and `csrfSafeMethods`

Added tests for api functions

---

.eslintrc
static/js/components/CourseList_test.js
static/js/components/Dashboard.js
static/js/components/EducationTab.js
static/js/components/UserImage.js
static/js/public/core.js
static/js/public/jquery.raty.js
static/js/public/site.js
static/js/util/api.js
static/js/util/profile_edit.js
static/js/util/util.js

closes #350 
Adds the `prefer-template` rule to eslint and fixes all lint errors.
Review all the changes, and make sure the newer template literal will produce the same string that the concatenation would have.
Click around and make sure there are no regressions (clobbered spaces, etc).

Added prefer-template eslint rule

---

static/js/containers/ProfilePage.js

Fixed bug introduced by #357 
Fixes clearing of profile edits. This allows the cancel button on the dialogs to revert the state correctly

Fixed clear profile edit bug

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/containers/App.js
static/scss/dashboard.scss

Fixes #320 
Turns on dialog scrollbars, and tweaks CSS to remove border lines from the top and bottom of dialog

Turned on dialog scrollbars

---

backends/edxorg.py

This PR switches over to the new Django OAuth Toolkit settings. @giocalitri

Use Django OAuth Toolkit

---

static/js/components/EmploymentTab.js
static/js/util/util.js
static/js/util/util_test.js

Moved blankWorkHistoryEntry to a function

---

package.json
static/scss/_grid-settings.scss
static/scss/layout.scss
webpack.config.shared.js

Removes node-neat and related imports. `bourbon-neat` was removed in #345 but this was overlooked

Removed node-neat

---

static/js/containers/LoginButton.js

closes #374 
This fixes a bug in the function passed to `connect` in `LoginButton.js`.
Review the changes to `mapStateToProps`.
Navigate to the personal tab, update 'preferred name', click 'save and continue', and confirm that the name in the login button component (top right) has changed to the new value.

Fixed bug with LoginButton not updating preferred name

---

static/js/components/PrivacyTab.js
static/js/containers/ProfilePage_test.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/scss/dashboard.scss

Fixes https://github.com/mitodl/micromasters/issues/335
- Update UI of privacy tab.
- See profile_edit.js
- Open profile and go to privacy.

Updated privacy tab in profile.

---

static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/TermsOfServicePage_test.js
static/js/global_init.js
static/js/util/integration_test_helper.js
static/js/util/util.js
static/js/util/util_test.js

Reverts mitodl/micromasters#314
Accidentally merged PR without squashing commits

Revert "Added highlight approach to missing fields instead of popup"

---

static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/TermsOfServicePage_test.js
static/js/global_init.js
static/js/util/integration_test_helper.js
static/js/util/util.js
static/js/util/util_test.js

fixes https://github.com/mitodl/micromasters/issues/285
- Removed popup message for missing contents in fields
- Added highlight validation.
see Apps.js and utils.js
- Left any filed content missing on profile tab
- Move to last tab and press save and continue
- You will be navigate to profile where you have missing contents.
- The filed with missing contents will be highlight
@aliceriot @noisecapella @pdpinch 
- <img width="1033" alt="screen shot 2016-05-16 at 4 04 11 pm" src="https://cloud.githubusercontent.com/assets/10431250/15287936/e92567ca-1b7f-11e6-9b9a-5e9e4db21c70.png">
- <img width="1279" alt="screen shot 2016-05-16 at 4 04 21 pm" src="https://cloud.githubusercontent.com/assets/10431250/15287937/e928697a-1b7f-11e6-81a3-cefa66521e5d.png">
- <img width="1033" alt="screen shot …

Removed dialog from profile validation

---

static/js/constants.js
static/js/containers/TermsOfServicePage.js
static/scss/dashboard.scss

fixes https://github.com/mitodl/micromasters/issues/328, https://github.com/mitodl/micromasters/issues/280
- Update the existing terms of service.
- See page TermsOfServicePage.js
- Checkout page ``/terms_of_service/``
@pdpinch @aliceriot @nicolaeherrera

Updated the terms of service.

---

static/js/util/profile_edit_test.js

Fixes #412 
Adds JS unit tests to cover some uncovered cases

Added tests to increase coverage

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/containers/ProfilePage_test.js
static/js/global_init.js
static/scss/dashboard.scss

Fixes #331
Refactors the education tab to update its look and feel to match the mockups
EducationTab.js
All existing functionality should work as before. The look and feel should match the comments in the issue #331

Updated style of education tab

---

static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

Fixes #379
Uses the month field to show the label. MM and YYYY are now hint text

Fixed UI for month/year field

---

static/js/containers/App_test.js
static/js/util/integration_test_helper.js

Adds an action we should be listening for. There's no reason to listen for REQUEST_DASHBOARD without RECEIVE_DASHBOARD_SUCCESS
If tests pass, everything should be fine

Added missing action to integration tests

---

README.md
cms/templates/cms/home_page.html
micromasters/settings.py
static/js/components/Header.js
static/js/containers/ProfilePage.js
static/js/util/ProfileTab.js
ui/templates/dashboard.html
ui/views_test.py

Fixes #236 
Ensures that all references to MicroMaster's use an apostrophe

Replaced all references to MicroMasters with MicroMaster’s

---

Dockerfile-node
docker-compose.yml

Fixes #428 
Adds a minimal Dockerfile for the watch image which runs commands as the mitodl user

Added minimal Dockerfile to run tests with

---

static/js/components/PrivacyTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/scss/dashboard.scss

Fixes #416 
Changes the behavior to show radio buttons even when nothing is selected, and adds better tests for it. There is also now a label and error text.
Set gender to null for a user, then go to the personal tab. You should see three options which are all unchecked. Click save, and you should see a validation error in red text below the gender options. You should be able to select an option, click Save, and have it proceed.
We should be more careful on code reviews in the future. There was no code for validation and the tests referenced props that don't exist in the RadioButtonGroup component.

Fixed radio options to be shown if nothing is selected

---

static/js/containers/ProfilePage.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #369
Rebased on #420
Removes tab links, uses SVG to display a profile indicator like in the issue mockup.
static/js/util/util.js
Go to each page in the profile and verify that the progress display looks correct

Added progress indicator to profile

---

static/js/util/validation.js
static/js/util/validation_test.js

Fixes #436 
Skips field of study validation for high school entries
The reviewer should be able to fill in their high school information

Fixed high school validation error

---

static/js/components/CourseList.js
static/js/components/CourseList_test.js

Fixes https://github.com/mitodl/micromasters/issues/373
- Fixed design of apply for master button of the program in dashboard.
- CourseList.js
- Open dashboard and see at the end of a program.

Fixed design of apply for master button on dashboard

---

cms/templates/cms/home_page.html
static/images/mit-logo-ltgray-white@72x38.svg
static/js/components/Footer.js
static/js/containers/App.js
static/scss/homepage.scss

https://github.com/mitodl/micromasters/issues/368
https://github.com/mitodl/micromasters/issues/376
- Adds a button on footer of homepage.
- Adds footer to different locations like dashboard, terms of service, profile.
- Footer component.
- See at the bottom of different pages.

Added footer at dashboard, terms of service, profile and added button on homepage footer

---

static/js/global_init.js

Fixes #448 
Adds a handler for the tests which rethrows the exception so the exception halts the test with a stack trace for the error, instead of timing out.
Put a typo in one of the async tests, then run npm test.

Added handler for rejected promises

---

.travis.yml

Fixes #480 
Uses the --quiet flag to explicitly raise the loglevel to reduce chattiness.
The Travis log should contain fewer than 8000 lines of output

Made npm install quieter

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/util/ProfileFormFields.js
static/js/util/profile_edit.js
static/js/util/validation.js

Part of #433 
The `Tab` classes don't need to inherit from `ProfileFormFields` since they have `Form` components which inherit from `ProfileFormFields` instead. Also, the progress controls were moved into `ProfileProgressControls` for better separation of concerns
Everything should work exactly as before. The reviewer should make sure edits still work in both profile pages

Refactored profile classes

---

static/js/util/courseList.js
static/js/util/courseList_test.js

Fixed bug: No enroll button if edx_course_key is not defined

---

static/scss/dashboard.scss
static/scss/header.scss
static/scss/homepage.scss
static/scss/layout.scss
ui/templates/base.html

closes #434 
this changes the font to [Roboto](https://www.google.com/fonts/specimen/Roboto) everywhere.
Review the css changes. Unfortunately I think we need the `!important` tag to override some styling set by the material design light components :cry: :disappointed: 
I guess just make sure everything looks ok?

Added Roboto font everywhere

---

static/js/util/util_test.js

Fixes a test where certain assertions never ran

Fixed missed test assertions

---

cms/templates/cms/home_page.html

Fixed punctuation for button

---

static/js/actions/index.js
static/js/components/ErrorMessage.js
static/js/constants.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/integration_test_helper.js
static/scss/dashboard.scss

closes #234
Introduces error handling in the dashboard UI
`static/js/util/api.js`
The easiest way is to go to the dashboard, stop edx platform and reload the dashboard.
If you want to test the error code and error message, in `dashboard/views.py` change the get function to:
```
def get(self, request, *args, **kargs):  # pylint: disable=unused-argument, no-self-use
"""
Returns information needed to display the user dashboard for a program.
"""
return Response(
status=500,
data={
'error_code': 'AB123',
'user_message': 'foo message'
}
)
```

Added error handling in the dashboard.

---

static/js/util/courseList.js

Fixes #502 
During the refactor for #489  the `Button` class from react-bootstrap was replaced with the one from react-mdl by mistake, this PR changes it back
View the dashboard with course runs that have buttons. If you go into the `DASHBOARD_RESPONSE` in `constants.js` and set `course_id` to a non-empty string, then adjust `getDashboard()` to return a resolved promise with that constant, you should see the a green enroll button.

Fixed Button style

---

cms/templates/cms/footer.html
static/js/components/Footer.js

this closes #457 
adds `target="_blank"` to a couple of links.
ensure that these links all open in a new tab:
homepage (django template):
- footer: edX link
- footer: ODL link
- footer: Give to MIT button 
- home page: MITx link to https://www.edx.org/school/mitx
dashboard (react component):
- footer: edX link
- footer: ODL link
- footer: Give to MIT button

Made all footer links open in new tab

---

js_test.sh
package.json
static/js/components/EducationDialog.js
static/js/components/EmploymentForm.js
static/js/containers/UserPage_test.js
static/js/global_init.js

closes #524 
This just adds two tests to `UserPage_test.js` which test out the whole
process of adding entries to the Education and Work histories. Some
changes we're necessary to the setup for mocha and jsdom-global in order
to make this work correctly.
Make sure all the tests are passing! confirm that the new tests test for the correct behavior.

Added end-to-end ui tests for adding education and work entries

---

static/js/components/EmploymentForm.js
static/scss/dashboard.scss

closes #476 
This just changes the spacing of the education and work history forms a little bit, so that things are a little more compact (especially when a section of the education form is greyed out).
Review the css and code changes.
Make sure things look smaller!
check the issue.

reduce whitespace on education and work history forms

---

requirements.txt

Bumped django version

---

package.json
static/js/containers/UserPage_test.js

Fixes #615
Updates to redux-asserts 0.0.8 and fixes related test failures.
As long as tests pass everything should be good

Updated to redux-asserts 0.0.8 and fixed related test failures

---

requirements.txt

closes #605 
upgrades the CMS to the latest version

Upgraded to wagtail 1.5.2

---

static/js/components/EducationDialog.js
static/js/components/inputs/FieldsOfStudySelectField.js
static/js/containers/UserPage_test.js

closes #580 
`fullWidth: false` -> `fullWidth: true`
Visit `/users/` or `/profile/education` and open an education form with the fields of study select field (i.e. not high school). Confirm the field is a bit wider.

Changed FieldsOfStudySelectField to use fullWidth: true

---

requirements.txt

Updated edx-api-client requirement

---

cms/templates/cms/program_page.html

Fixes #594 
Adds link to home page from program page logo
Click the MIT MicroMasters logo on the program page

Added link to home page on program page logo

---

static/js/components/PrivacyForm.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/containers/LoginButton.js
static/js/containers/ProfileFormContainer.js
static/js/containers/SettingsPage.js
static/js/containers/SettingsPage_test.js
static/js/containers/UserPage.js
static/js/dashboard_routes.js
ui/url_utils.py
ui/urls.py

resolves https://github.com/mitodl/micromasters/issues/485
Added settings page to change privacy settings
- see SettingPage.js
- click menu icon on top right of user page. From their select settings.
@pdpinch @noisecapella @aliceriot

Added settings page

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/containers/SettingsPage.js
static/js/containers/SettingsPage_test.js

Fixes https://github.com/mitodl/micromasters/issues/650
- Changes the label of ``I'm Done!`` button to ``Save``
- Go to ``SettingsPage.js``.
- Go to url /settings

Changed the label of settings button

---

static/js/components/Header.js
static/js/containers/UserMenu.js
static/js/containers/UserPage_test.js
ui/templates/base_error.html
ui/views.py
ui/views_test.py

Closes #571 
Adds a link in the top right menu to the user's profile page
Log in, click the top-right menu arrow, use the Profile link

Added user page link to dropdown

---

README.md

fixes #486 
Starts a documentation section for the Wagtail CMS.
Try to follow the directions for creating a new program page and granting permission to edit it. 
Let me know if you think a separate documentation page is justified. 
Creating CMS users and granting permission is pretty basic at this point. I added some stories (#685, #687) to make it more sophisticated. If those are worked on, we will need to update these docs.

Updated README with basic CMS docs

---

backends/pipeline_api.py
backends/pipeline_api_test.py
cms/models.py
profiles/api.py
profiles/api_test.py
profiles/serializers.py
profiles/serializers_test.py
test_requirements.txt
ui/views.py
ui/views_test.py

Fixes #704 
Refactors code getting the username.
No changes should be noticed

Added get_social_username, updated existing code to use it

---

static/js/components/ErrorMessage_test.js
static/js/containers/DashboardPage_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/UserPage_test.js

this closes #663 
This moves existing tests for the `ErrorMessage` component into `static/js/components/ErrorMessage_test.js` and also adds some simple unit tests for the component.
Review the changes, make sure no tests got dropped in the shuffle.

Moved ErrorMessage tests into separate file

---

requirements.txt

Fixes the broken build caused by a change in html5lib

Pinned html5lib to fix build

---

requirements.txt

This is a security update.
See: https://www.djangoproject.com/weblog/2016/jul/18/security-releases/

Update to Django 1.9.8

---

static/js/components/PrivacyForm.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/flow/profileTypes.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

closes https://github.com/mitodl/micromasters/issues/733
- Add email preference settings to profile settings form.
- open settings page 
- open profile/settings
@pdpinch

Added e-mail preference settings

---

dashboard/views_test.py

closes https://github.com/mitodl/micromasters/issues/734
- Alter test suit ``dashboard/views_test.py`` and mocked certificate api so that tests can run event of edX instance is not working. Previously one test gets fail if edX platform instance is close.
- see ``dashboard/views_test.py``
- Close edX platform (shutdown server or vagrant box)
- Run test ``docker-compose run web tox -- dashboard/views_test.py``

Mocked certificate api in test suit, So that i can run even if edX instance is shutdown

---

dashboard/factories.py
dashboard/models.py
search/api.py
search/api_test.py
search/signals.py
search/util.py
search/util_test.py

Rebased on #711
Fixes #678
Indexes the Certificate and Enrollment models when they change (the user accesses the dashboard).
Wait 5 minutes if you have accessed the dashboard recently. Then watch the elasticsearch console. Go to the dashboard and refresh the browser. You should see some activity in the console.

Added indexing for Certificate and Enrollment

---

micromasters/utils.py
profiles/management/commands/delete_realistic_search_data.py
profiles/management/commands/gen_realistic_search_data.py
profiles/management/realistic_program_data.json
profiles/management/realistic_user_data.json

Closes #675 
Creates a new Django management command that creates a set of realistic-looking users from a json file that I've added to the codebase.
docker-compose run web ./manage.py gen_realistic_users
If you'd like to delete these test users..
docker-compose run web ./manage.py delete_realistic_users
I have some scripts in a Jupyter notebook that generate the json files that you're seeing here. The scripts are reasonably parametrized/configurable so we can tweak the resulting set of users as we want. It will be easy to generate enrollment/grade data and profile pictures once those are ready to go. Some details about the user data and the parameters I went with:
- randomuser.me was used to generate the basic data for these users
- 60 users in total
- Nationality is split evenly among …

Created management command to generated realistic-looking fake users

---

test_requirements.txt

closes #751 
what it says on the can.

Added bpython to test_requirements.txt

---

npm-shrinkwrap.json
package.json
static/js/actions/ui.js
static/js/containers/UserMenu.js
static/js/containers/UserPage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_variables.scss
static/scss/layout.scss
static/scss/user_menu.scss

this closes #724 
This implements the new design for the user menu. This is just react + css, I removed the bootstrap components from this completely.
Take a look over `UserMenu.js`, read through all the CSS.
Make sure the look and feel matches what's shown in the screenshots in the associated issue.

Implemented new user menu design

---

static/js/actions/index.js
static/js/util/validation.js
static/js/util/validation_test.js

this closes #754 
Small refactor of `static/js/actions/index.js`. Basically just moving some code around and adding type annotations.
Read the code!
Functionality should be totally the same, so probably click around and make sure all the profile and dashboard related functionality is working correctly.

refactor `actions/index.js`

---

ui/views.py
ui/views_test.py

Fixes #708 
Adds the roles assigned for a user to the `SETTINGS` variable
First, add a role to the user. You can do this using something like `Role.objects.create(user=user, program=program, role='instructor')`
Go to the dashboard, then open the browser console. Type `SETTINGS.roles` and verify that there's one role assigned to the right program.

Added roles to SETTINGS

---

Procfile

Added celery start command to Procfile

---

static/js/containers/LearnerSearchPage.js

Fix CSRF handling

---

.eslintrc
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/LearnerSearch.js
static/js/components/Navbar.js
static/js/components/PersonalForm.js
static/js/components/PersonalTab.js
static/js/components/ProfileProgressControls.js
static/js/components/WelcomeBanner.js
static/js/containers/App.js
static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/containers/UserPage_test.js
static/js/flow/profileTypes.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/homepage.scss
static/scss/layout.scss
static/scss/navbar.scss
static/scss/page_layout.scss
static/scss/profile.scss
static/scss/profile_progress_controls.scss
static/scss/user_menu.scss
static/scss/welcome_banner.scss
ui/templates/base_error.html

this closes #769 
This implements the new designs for the profile forms / signup flow. It should be in accordance with what can be found here: https://projects.invisionapp.com/share/9B804AMXA#/screens/178066345
this also reorganizes some stuff a bit. We're leaning here more on CSS for layout and less on the MDL `<Grid>` than we were before.
Overall HTML layout of the app now looks more or less like:
```html
<div id="app">
<div class="micromasters-navbar">
</div>
<div class="page-contents">
</div>
<footer>
</footer>
</div>
```
All of the top-level containers (`#app > *`) are `width: 100%`. All of our page layout happens inside of `.page-contents`. for instance, in this PR I've implemented a `.single-column` class, which places a div in the center of the page. Here's what that looks like …

Implemented new profile form designs

---

static/js/components/TermsOfServiceDialog.js

Passed onRequestClose callback to ToS Dialog

---

webpack.config.dev.js
webpack.config.shared.js

this closes #865 
fixes the configuration for react-hot-loader, following https://gaearon.github.io/react-hot-loader/getstarted/
1. check out the branch
2. restart docker containers
3. visit `/dashboard` in the browser
4. edit the header text in `Navbar.js` (on line 49)
5. confirm that the text changes without a page refresh (takes around 5 seconds on my machine)

Fixed webpack hot-reload config

---

static/scss/dashboard.scss

Fixes #867 
The dashboard user card should match the mockups in #766

Fixed CSS for dashboard user card

---

static/js/components/UserChip.js
static/js/components/UserChip_test.js
static/js/components/search/LearnerResult.js
static/js/util/sanctuary_test.js
static/js/util/util.js
static/js/util/util_test.js
static/js/util/validation_test.js
static/scss/layout.scss
static/scss/search_page.scss
static/scss/user_chip.scss

closes #757 
This adds a little pop-up thingy that shows up when you hover over a result in the search.
Take a look over the code! If you have ideas about how to manage the CSS cascade better (so we can remove some `!important` styles) that would be :100:.
Go to `/learners`. Hovering over any result should cause a little popup to display.

Added UserChip to search results

---

static/js/components/LearnerSearch.js
static/scss/search_page.scss

closes #849 
This just adds a little searchkit component that provides a 'clear all filters' which removes all the filters which are currently applied.

Added 'clear all filters' to learner search

---

static/scss/search_page.scss

closes #877 
this just sets `cursor: pointer` on the expand / collapse icon we show for the facets on the side of the learner search.

Set the cursor to 'pointer' on the filter visibility toggle

---

static/js/dashboard.js
static/js/style.js

Moved material-design-lite CSS import before our CSS imports

---

static/scss/search_page.scss

closes #855 
This makes the profile images in the results round instead of square.

Made LearnerResult avatars round

---

static/js/util/util.js
static/js/util/util_test.js

this closes #820 
This implements the latest design for the profile progress `<svg>` thingy. Pretty much just changing colors and adding check-marks.
Make sure it looks like the mockup! See the issue.

Implemented new design for the profile progress widget

---

static/js/components/LearnerSearch.js
static/scss/search_page.scss

closes #759 
This adds a sorting option to the 'Learners' page. SearchKit provides a sorting component which we're using, we just basically pass it an array of objects describing the fields we want to sort on, their labels, etc.

implement a sort dropdown

---

static/js/components/LearnerSearch.js

closes #852 
removes an unimplemented button
Just make sure the button's absence looks ok!

Remove 'new group from selected' button

---

docker-compose.yml

Celery now loads the environment in Docker

---

.gitignore
static/js/components/LearnerSearch.js
static/js/components/PersonalTab.js
static/js/components/ProfileProgressControls.js
static/js/components/ProgressWidget.js
static/js/components/dashboard/CourseAction.js
static/js/components/search/LearnerResult.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/util/util.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/bound_check_box.scss
static/scss/dashboard.scss
static/scss/general_styles.scss
static/scss/homepage.scss
static/scss/layout.scss
static/scss/navbar.scss
static/scss/page_layout.scss
static/scss/profile.scss
static/scss/profile_progress_controls.scss
static/scss/progress_widget.scss
static/scss/search_page.scss
static/scss/user_chip.scss
static/scss/user_menu.scss
static/scss/welcome_banner.scss

This will be a series of changes to the css. Included in this PR: changed the background color on the body, removed the bgcolor on page-content. Removed the top/bottom margins on the layout columns, removed the bottom-padding on the navbar. 
Look at the changes in the css files and see that nothing looks broken.
This is not related to a specific issue, but I will be making css changes on on ongoing basis, doing a lot of tweaks... some small visual refinements, and some larger layout changes.

Several small css changes

---

README.md
dashboard/tasks.py
dashboard/tasks_test.py
docker-compose.yml
micromasters/settings.py

Fixes https://github.com/mitodl/micromasters/issues/671
- Added a periodic task that runs every 6 hours and update user data like enrollments, certificates and grades from edX platform
- see dashboard/tasks.py
- bottom of micromasters/settings.py
- You can add a logger etc
- cut time from 6 hrs to few mins or sec

Added background task that run every 6 hours and update all MM users data from edx-platform

---

static/scss/navbar.scss
ui/templates/header.html

closes #954
This just makes the MIT and MicroMasters logo in the top left a link which goes to the home page.
Just a few changes, make sure there's no glaring errors?
If you go to `/terms_of_service` and click on the logo in the corner it should take you to the homepage.

Added link to ToS page

---

courses/views.py
courses/views_tests.py
micromasters/urls.py

task 2 of #796
Introduces a rest api to return program enrollment for the logged in user
`courses/views.py`
Enroll the user in one or more programs (at the moment you need to enroll her in a CourseRun) and verify that the programs appear querying the url `/api/v0/enrolledprogram/`

Added Program Enrollment REST API

---

runtime.txt

None, fixes build failure related to #916

Switched Heroku to Python 3.5

---

static/js/actions/email.js

Split long line into multiple lines

---

static/js/actions/email.js
static/js/actions/email_test.js
static/js/actions/enrollments.js
static/js/actions/enrollments_test.js
static/js/actions/index.js
static/js/actions/util.js
static/js/actions/util_test.js
static/js/components/ErrorMessage.js
static/js/components/ErrorMessage_test.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/flow/enrollmentTypes.js
static/js/flow/generalTypes.js
static/js/flow/profileTypes.js
static/js/reducers/email_test.js
static/js/reducers/enrollments.js
static/js/reducers/enrollments_test.js
static/js/reducers/index.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/integration_test_helper.js

Fixes #966 
Part of #796
Adds functions and redux actions/reducers for the new program enrollments API
The dashboard should load fine and you should see the API call in your network tab. You will not be able to test the code which adds enrollments yet, there is no UI work done for this in this PR.
No error handling is done yet

Added code to get and add program enrollments

---

profiles/management/realistic_user_data.json

this fixes #983
We had a trailing comma in the `realistic_search_user` JSON file. This fixes that.
Make sure you can run the `gen_realistic_search_data` management command without errors.

Fixed improper JSON formatting

---

static/js/components/search/LearnerResult.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/search_page.scss

#934
This fixes just some of the css styles for this issue. There are other changes that need to be made that go beyond just changing the styles.
Verify that my css changes are made on the correct classes, etc.
See that the table of results, and the filters are not broken.

Css changes to the user search page

---

static/js/components/LearnerSearch.js
static/js/components/Navbar.js
static/js/components/ProgressWidget.js
static/js/components/UserChip.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/general_styles.scss
static/scss/navbar.scss
static/scss/page_layout.scss
static/scss/profile.scss
static/scss/progress_widget.scss
static/scss/search_page.scss
static/scss/user_chip.scss
static/scss/user_menu.scss
static/scss/user_page.scss

These are general style changes not necessarily for any ticket. I made changes to styles in the dashboard, the user page, and the learner search.
Look at the changes to the css and js files and see that nothing looks broken.
This is an ongoing process of tweaking css styles that will continue.

Various css changes to colors, fonts, margins

---

.sass-lint.yml
.travis.yml
npm-shrinkwrap.json
package.json
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/layout.scss
static/scss/navbar.scss
static/scss/profile.scss
static/scss/program_page.scss
static/scss/progress_widget.scss
static/scss/search_page.scss
static/scss/user_page.scss

closes #998 
This installs [sass-lint](https://github.com/sasstools/sass-lint), which lets us lint our `.scss` files.
This also fixes all the linting errors that existed in the code, and adds an `npm` scripts command:
```
npm run scss_lint
```
well, I guess just make sure everything looks the same.

Installed sass-lint

---

static/js/components/Navbar.js
static/js/containers/App.js
static/js/containers/DashboardPage.js
static/scss/navbar.scss

- Fix some issues from https://github.com/mitodl/micromasters/issues/925 
- Fixes https://github.com/mitodl/micromasters/issues/780
- See ``App.js, Nav.js``
- see ``/dashboard/`` page
@pdpinch @noisecapella @aliceriot

Refactored dashboard page

---

static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/layout.scss
static/scss/responsive_styles.scss
static/scss/search_page.scss

There is not an issue for this.
This PR fixes an issue where the navbar was disappearing at small browser widths. I added a responsive style sheet to fix this. Any other responsive styles should be addressed in this new scss file. I also fixed a few small style tweaks on the user search page. Button style, a few variable color changes, etc.

Fixed css issues

---

dashboard/api.py
dashboard/api_test.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CoursePrice.js
static/js/components/dashboard/CoursePrice_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/constants.js
static/js/flow/programTypes.js
static/scss/_variables.scss
static/scss/dashboard.scss

- Fixes https://github.com/mitodl/micromasters/issues/925
- Fixes https://github.com/mitodl/micromasters/issues/1009
- see course row
- see ``/dashboard/`` page
@noisecapella @pdpinch @aliceriot 
Continuation of https://github.com/mitodl/micromasters/pull/993

Fixed course display on dashboard

---

cms/models.py
cms/templates/cms/home_page.html
ui/views_test.py

Fixes #944 
Adds help text to CMS, increases thumbnail resolution
Update the thumbnail for a program, make sure that the help text in the CMS makes sense

Updated CMS help text, updated thumbnail size

---

dashboard/api.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CoursePrice.js
static/js/components/dashboard/CoursePrice_test.js
static/js/constants.js

Part of #833 
Renames course statuses
No functional changes should be noticed, all tests should still pass

Renamed dashboard API statuses

---

static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/CourseStatus.js
static/js/components/dashboard/CourseStatus_test.js
static/scss/dashboard.scss

Part of #833 
Rebased on #1033
Renames a class
Make sure nothing broke

Rename CoursePrice to CourseStatus

---

static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js
static/js/constants.js
static/js/containers/LearnerSearchPage.js

closes #931 
Sets search facets to be open by default
Check the learner search page. Also ensure that minimizing these facets will persist

Set search facets to be open by default

---

cms/templates/cms/home_page.html
static/js/public.js

Fix #965 
Fix the Mixed Content error.
To test this, go to the home page through this link
https://micromasters-ci-pr-1055.herokuapp.com/.
Try to sign up for the mailing list. On submit the error used to occur (you can see it at https://micromasters.herokuapp.com/)

Fix mailchimp signup bug

---

static/js/components/ProgressWidget.js
static/js/components/ProgressWidget_test.js
static/js/containers/DashboardPage.js
static/js/util/util.js
static/js/util/util_test.js

Fixes https://github.com/mitodl/micromasters/issues/941
- Calculates total number of courses and passed courses and update progress widget.
- ProgressWidget.js
- Open ``/dashboard/`` and switch programs
@roberthouse54 @aliceriot @pdpinch

Made progress widget get values from respective program

---

static/scss/progress-widget.scss

- Fixes https://github.com/mitodl/micromasters/issues/896
- Fixes rotation if progress widget circle
- see dashboard page 
- see progress widget 

Fixed rotation of progress widget circle

---

requirements.txt

Bumped edx-api-client requirement to latest version

---

cms/serializers.py

None
Updates faculty images to crop in the same way as the program thumbnail images

Used fill rule to crop faculty images

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
static/scss/layout.scss
ui/templates/base_error.html

Minor improvements to the HTML templates, primarily for accessibility-related improvements.

Accessibility improvements

---

cms/templates/cms/home_page.html
static/scss/footer.scss
static/scss/homepage.scss
ui/templates/footer.html

@roberthouse54, could you review this please?
Part of #1111
Makes the home page responsive. Does not make any other pages on the site responsive.
Open the home page in your browser, and resize the browser window.
The navigation menu still doesn't quite work right -- it should morph into a hamburger icon when the screen is small. I wanted to get some feedback on the work I've done so far before spending too much time on that.

Responsive home page

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
ui/templates/base.html

Related to #1112,
Using text from #1140
Added `description` and `keywords` meta tags to 'home_page' and 'program_page'.
Changed `h1` header to match the title of the homepage.

Add description, keywords meta tags

---

static/scss/program-page.scss

Small visual tweaks to the style of the carousel.

Tweaks to the style of the faculty carousel

---

financialaid/management/commands/create_tiers.py
financialaid/management/commands/create_tiers_test.py
financialaid/models.py

Closes #1125 
Creates the "create_tier" management command for generating financial aid Tiers and TierPrograms.

Added management command for creating Tiers/TierPrograms

---

cms/templates/cms/program_page.html
static/js/components/FacultyCarousel.js
static/js/components/FacultyTile.js
static/scss/program-page.scss

Making the program page responsive. @roberthouse54, could you review this?

Responsive program page

---

cms/templates/cms/home_page.html

Fix #1140 
Update text on the homepage.

Update homepage text

---

static/scss/homepage.scss
ui/templates/header.html

none
fixes a little bit of copy on the homepage.

remove 'Are you a member?'

---

cms/templates/cms/home_page.html
static/scss/homepage.scss

added reif quote

---

mail/api_test.py

N/A
Fixes some mail tests that were failing in case of environment variable set

Fixed mail tests 

---

requirements.txt

none, but see https://www.djangoproject.com/weblog/2016/sep/26/security-releases/
Updates to django 1.9.10
Did the tests pass?

updated django to 1.9.10

---

financialaid/admin.py

closes #1177 
displays all the fields in the admin's list view of TierProgram 
Create a couple of TierPrograms
I don't want to make any mistakes when we set up or change the financial aid configuration. 
before:
after:

more useful fields in admin list views

---

micromasters/settings.py
micromasters/utils.py
micromasters/utils_test.py

N/A
Introduces a custom exception handler for the `ImproperlyConfigured` exception.
This will help see configuration errors in production

Custom exception handler

---

cms/templates/cms/program_page.html
static/scss/program-page.scss

Related to ##1112
Refactor program page to have the courses widget when the user switches tabs.

Leave Courses on FAQs page

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py

Exposes in the dashboard REST API information about when the documents have been sent

Exposed financial aid documents sent info on MMTrack

---

static/js/components/inputs/DateField.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

None
Creates `DateField` which is not specific to the profile code. I will use this in the UI work regarding #1115
Edit your birthdate and a graduation date in the profile.

Extracted DateField from boundDateField

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
npm-shrinkwrap.json
package.json
static/js/public.js
static/js/style_public.js
static/scss/footer.scss
ui/templates/base.html
ui/templates/footer.html

Related to #1111
Adding Social Media Icons.

Add Social Media Icons

---

static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/ProfileProgressControls.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage_test.js
static/js/reducers/ui.js
static/js/util/validation.js
static/scss/profile.scss

- Fixes https://github.com/mitodl/micromasters/issues/1105#issuecomment-249384593
- Added select program to ``/profile/``
- Personal Tab 
- Should see /profile/ page
@pdpinch @aliceriot @gsidebo

Added select progam to profile tab

---

ui/templates/terms_of_service.html
ui/views.py

Fixes #1181
Adds JS that was lacking to the terms of service page

Fixed terms of service signup and login buttons

---

cms/templates/cms/program_page.html
static/scss/program-page.scss

This centers and adds max-width to the content under the tabs on the program page.

centered the tabs on the program page and added max-width

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
ui/templates/base.html

Improve social links with Google+

---

uwsgi.ini

**Added configurable basicauth to uWSGI**
Added basicauth configuration to uWSGI in order to allow for restricting
access to app in pre-production.

Added configurable basicauth to uWSGI

---

cms/api.py
cms/api_test.py
cms/models.py
cms/templates/cms/program_page.html
static/scss/program-page.scss

Fix ##1179
Add description to courses in the program page. Make course name a link to course page on edx.

Add course description and page link

---

npm-shrinkwrap.json
package.json
static/js/actions/documents.js
static/js/actions/documents_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/flow/programTypes.js
static/js/reducers/documents.js
static/js/reducers/documents_test.js
static/js/reducers/financial_aid_test.js
static/js/reducers/index_test.js
static/js/style.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/util_test.js
static/scss/dashboard.scss

#1115
Fixes #1205 
Implements the button to update documents being sent, and shows the document date for documents already sent
Change the status of your `FinancialAid` to `pending-docs`. You should see a date picker and a submit button similar to the invision mockups. Pick any date and click 'Submit'. The dashboard will refresh and you will see the updated document date.

Implemented document sent date

---

cms/templates/cms/home_page.html
static/scss/homepage.scss

- Fixes https://github.com/mitodl/micromasters/issues/1153
- Fixed Style of mailchimp form in dialog
- home_page.html/ mailchimp dialog
- see home_page.html/ mailchimp dialog

Fixed Style of mailchimp form

---

financialaid/api.py
financialaid/api_test.py
financialaid/views_test.py
static/js/constants.js
static/js/flow/dashboardTypes.js

Closes #1251
Closes #1254
Modifies the course price API to return adjusted price irrespective of financial aid status.

Fixed course price API output

---

npm-shrinkwrap.json
package.json
static/js/public.js
static/js/style.js
static/js/style_public.js
ui/templates/base.html

Fixes #1264 
Includes bootstrap css and jquery in the static directory and updates links on base.html. The bootstrap JS is already included using public.js
Make sure the mailing list button still works, make sure everything looks ok in general

Switched to hosted jquery and bootstrap

---

courses/views.py
courses/views_test.py
dashboard/views.py
ecommerce/views.py
financialaid/views.py
mail/views.py
micromasters/admin.py
micromasters/settings.py
search/views.py

N/A
Added support for token authentication for users

Added support for token authentication

---

ecommerce/permissions.py

Fixes #1239 
Adds logging for signature verification failures due to misconfigurations. Additionally I need this PR build to diagnose this on micromasters-rc

Added logging for IsSignedByCyberSource

---

static/js/components/dashboard/FinancialAidCard.js
static/scss/dashboard.scss

closes #1098 
This adjusts the copy a little bit and adds in a 'skip and pay full price' link.
Somehow get a financial aid going for your user with `status = 'pending-docs'`. Then go to `/dashboard`. You should see the right copy (from the issue) and a 'skip' link. The skip link should work the same way as elsewhere.

Fixed verification required display

---

cms/models.py
financialaid/views.py
static/js/zendesk_widget.js
ui/templates/base.html
ui/views.py

- Fixes https://github.com/mitodl/micromasters/issues/1270
- Removed zendesk widget from homepage
- see zendesk_widget.js

Removed zendesk widget from homepage

---

financialaid/constants.py

Closes #1265 
Adds a dollar sign before the personalized course price in emails sent to learners informing them of their financial aid outcome.

Dollar sign for personalized course price in financial aid email message

---

static/js/components/ErrorMessage_test.js
static/js/components/UserChip.js
static/js/components/UserChip_test.js
static/js/components/dashboard/DashboardUserCard.js
static/js/components/dashboard/DashboardUserCard_test.js
static/js/containers/UserMenu.js
static/js/containers/UserPage_test.js
static/js/dashboard_routes.js
ui/templates/base_error.html
ui/urls.py
ui/views.py
ui/views_test.py

Closes #1288
Changes the url /users/<username> to /learner/<username>.

Changes /users/<username> to /learner/<username>

---

static/js/components/ProfileProgressControls.js

closes #1280 
changes button order
Make sure that the button order matches this on the 2nd and 3rd profile steps:

Switched profile button order

---

financialaid/management/commands/update_exchange_rates_test.py

Fixes #1320 
Fixes currency exchange rate command test bug.

fix the failing currency exchange rate command test

---

static/js/components/dashboard/FinancialAidCard.js

closes #1302
this just updates the address copy a little bit.

Updated financial aid document address slightly

---

financialaid/api_test.py
financialaid/serializers.py
financialaid/views_test.py

#1311 
Fixes a bug where the incorrect tier is assigned if submitted currency is not USD.  Also adds new and fixes existing tests to test for this case.

Fixed bug in financial aid request for determining tier

---

financialaid/api_test.py

Closes #1334 
Adds a few test cases to existing tests for testing auto-approval when income == income threshold and updated the test docstring for clarity.
This is a very simple update with no changes to functionality.

Added financial aid auto-approval test cases

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
static/js/components/FacultyTile.js
static/scss/_variables.scss
static/scss/homepage.scss
static/scss/program-page.scss

This PR adds a gradient overlay to the faculty carousel tiles.

Adds a gradient overlay on the faculty carousel

---

static/scss/user-menu.scss

closes #1338
Just adds a `max-width` to the user menu.
before:
after:

fix user menu wideness

---

static/js/components/dashboard/CourseAction.js

None
Adds a missing `key` attribute

Fixed console warning

---

cms/models.py
micromasters/settings.py
micromasters/wsgi.py
npm-shrinkwrap.json
package.json
requirements.txt
static/js/sentry_client.js
test_requirements.txt
tox.ini
ui/templates/500.html
ui/templates/base.html
ui/views.py
ui/views_test.py
webpack.config.shared.js

**Added sentry and coveralls to app**
Began adding Sentry to API and JS for error monitoring.

Added sentry to app

---

static/scss/dashboard.scss
static/scss/homepage.scss
static/scss/program-page.scss

Fixes the hero image to not scroll on the home page. (On mobile it still scrolls).

Fixes hero image to not scroll on home page

---

requirements.txt

Upgrade wagtail to 1.6.3

---

cms/templates/cms/program_page.html
static/scss/page-layout.scss

This fixes the footer to the bottom of the viewport if the page content is short. This is a 2 line PR.

Fixes footer to page bottom if page content is short

---

cms/models.py
financialaid/views.py
ui/views.py
webpack.config.shared.js

None
Fixes the path to zendesk_widget.js
Create a program page in the PR build and verify that the zendesk button appears there

Fixed path to zendesk_widget.js

---

static/js/containers/DashboardPage.js

- fixes https://github.com/mitodl/micromasters/issues/1370
- Removed learners near me card
- static/js/containers/DashboardPage.js
- open ``/dashboard/`` and see below progress widget

Removed learners near me card

---

static/js/actions/index.js
static/js/actions/index_test.js
static/js/actions/order_receipt.js
static/js/actions/order_receipt_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/ProfilePage_test.js
static/js/flow/programTypes.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/reducers/order_receipt.js
static/js/reducers/order_receipt_test.js
static/js/reducers/ui_test.js
static/js/util/test_utils.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss

Fixes #1242 
Handles the race condition by waiting and polling the dashboard API until the API shows the course as being passed
I'll set up the PR build for this, talk to me to walk you through this
After 30 seconds...

Fixed order fulfillment race condition

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfilePage.js
static/js/util/util.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/profile.scss
static/scss/program-page.scss
static/scss/responsive-styles.scss
static/scss/welcome-banner.scss

This PR is the first step in defining responsive styles for the app. Mainly, it sets some basic responsive layout styles for the dashboard and the Sign up pages.
There are also some unrelated CSS style fixes in this PR related to font styles, spacing, and colors in the Sign Up pages.
Follow up PRs should address:
- making modal dialogs responsive
- changing the nav items in the top nav bar to be in a mobile/ material side drawer navigation.
- finishing other style changes for responsive layouts for the app generally.

Partial Fix for Responsive Styles in Dashboard

---

mail/admin.py

Closes #1377 
Adds a Django admin model for the financial aid email audit model.

Adds email audits to Django admin

---

static/js/components/dashboard/FinancialAidCard.js
static/js/containers/FinancialAidCalculator.js

closes #1361 
This makes some copy changes to the financial aid calculator, and also adds in the max and min prices for the current program.
Make sure the copy looks right, and make sure that the same max and minimum prices that show up in the `FinancialAidCard` show up in the calculator.

Copy changes, add min and max cost to calculator

---

dashboard/api.py
dashboard/api_test.py

N/A
If the user did not have any enrollment, the current grades in the cache were not created leading to possible problems (the code expects entries with `null` data anyway).

Fixed bug with current grade refresh and no enrollments

---

static/js/faculty_carousel.js

Fixes #1322
Adds a check to make sure the faculty carousel div exists before populating it

Fixed console warning for faculty carousel

---

.travis.yml
static/js/components/CourseListItemWithPopover.js
static/js/components/CourseListWithPopover.js
static/js/flow/programTypes.js
static/js/util/popover_animation.js
travis-docker-compose.yml

closes #715 
this adds flow to travis and also fixes some flow errors that were introduced relatively recently.
Make sure that the changes haven't introduced any regressions. In particular, make sure that the popovers on the program page still work.

add flow to travis

---

cms/templates/cms/faqs_page.html
static/js/public.js
static/scss/program-page.scss

Fix #1415
Restore accordions for faqs on the program page.

Added FAQs accordion

---

app.json

**Updated the app.json to include required env vars**
Updated `app.json` to include the environment variables that should be
present for running the app. This will fix issues with PR apps not
including the necessary settings from the CI environment.

Updated the app.json to include required env vars

---

micromasters/settings.py
test_requirements.txt

N/A
Adds the `nplusone` library to profile bad queries when the app is running in DEBUG mode

Added nplusone library for query profiling in app DEBUG mode

---

seed_data/__init__.py
seed_data/apps.py

Fix for a problem we're seeing on Heroku. @blarghmatey, can you test this out?

Add app config for seed_data app

---

static/js/components/Footer.js
ui/templates/footer.html

Fix #1351
Make MIT logo in the footer link to main MIT website.

Make footer mit logo a link

---

static/js/components/search/FilterVisibilityToggle.js
static/js/components/search/FilterVisibilityToggle_test.js

- fixes https://github.com/mitodl/micromasters/issues/1362
- hid facets when they have no hits
- /static/js/components/LearnerSearch.js
- see ``/learners/`` as staff with data
- see ``/learners/`` page as staff with no data **OR**
- see ``/learners/`` page as student then you will data have no 

hid facets when they have no hits

---

profiles/factories.py

[Faker](http://faker.readthedocs.io/en/master/) has some nifty generators that we might as well take advantage of, for generating realistic-looking fake data.

Improve profile factories using Faker library

---

static/js/components/CropperWrapper.js

Fixes #1401
Fixes image upload for IE11 and edge

Fixed IE11 support for image upload

---

static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/util.js

Fixes #1439 
Removes the filler-text tooltip from the financial aid card

Removed filler-text tooltip

---

static/js/language_codes.js

fixes https://github.com/mitodl/micromasters/issues/1411
- Fixed preferred Language options
- static/js/language_codes.js
- open /profile and go to preferred lang

Fixed preferred Language options

---

npm-shrinkwrap.json
package.json
static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/Navbar.js
static/js/components/Navbar_test.js
static/js/components/NewEnrollmentDialog_test.js
static/js/containers/App.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_breakpoints.scss
static/scss/layout.scss
static/scss/navbar.scss
static/scss/responsive-styles.scss

this closes #1414 
This implements a side drawer navigation for mobile devices, following the mockups.
You can either use the pr review app (https://micromasters-ci-pr-1460.herokuapp.com/) on a mobile device or use the device simulator in Chrome or similar to check out the mobile view. 
Basically, you should be able to navigate around the site using the sidebar.
you should be able to:
- click the hamburger to open the sidebar
- visit different links
- navigate as usual on the desktop view of the app
the sidebar and mobile nav stuff should:
- not be visible when using a desktop-size (> 900px wide) view
- be dismissable by either clicking outside of the navbar or by swiping to the left on it
- hide itself after you click a link
- hide the program switch on the `/learner`, `/profile`, and …

Implemented sidenav

---

micromasters/settings.py
ui/context_processors.py
ui/templates/base.html

Fix #1474
Add SmartLook tracking.
For testing,  set an environment variable `SL_TRACKING_ID`. Then check in the header that the code for smartlook is set with the correct value.

Add Smartlook tracking

---

cms/models.py

None
Remove `ProgramTabPage` from subtypes.

Remove subtype for ProgramPage

---

static/js/components/CropperWrapper.js
static/js/components/ProfileImageUploader.js
static/scss/profile-image-uploader.scss

fixes https://github.com/mitodl/micromasters/issues/1428
Fixed image upload error message position and size of image upload container
see static/js/components/ProfileImageUploader.js
- open user profile and click user pic, a dialog will appear

Fixed size of image upload container

---

static/js/components/LearnerSearch.js

Clarify title for average grade filter

---

static/js/containers/SignupDialog.js

All images must have an `alt` attribute.

Add alt text to logos

---

courses/models_test.py
dashboard/api.py
requirements.txt

None
Refactors the tests in `courses/models_test.py` to use `ddt` for parameterized testing
Look at the code and make sure the same cases are being covered as before.

Refactored course tests

---

static/scss/footer.scss
ui/templates/footer.html

This is a quick fix of a layout (margin) problem with the footers.

fixed layout bug with footer Give to MIT buttons

---

cms/templates/cms/home_page.html
static/scss/general-styles.scss
static/scss/homepage.scss

Marketing changes requested by Maria, so she can send the live site around for final copy approval.
See: https://docs.google.com/document/d/1qvuiTVEOR-sYMOpvDocQKTs5H5Aym1aSekewAQO_ma4/edit

Copy changes per maria's request

---

dashboard/serializers.py
dashboard/serializers_test.py
roles/models.py
search/api.py
search/api_test.py
search/indexing_api.py

fixes https://github.com/mitodl/micromasters/issues/1367
- Omits staff from search results on learners page
- see /search/api.py
- go to /learners/ page and see if staff of program is in list or not
@pdpinch @giocalitri @noisecapella

Omitted staff from search results

---

tox.ini

Remove detect_missing_migrations.sh from build temporarily

---

static/js/components/SkipFinancialAidDialog.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/LearnerSearchPage_test.js
static/js/reducers/financial_aid.js
static/js/reducers/financial_aid_test.js

closes #1558 
fixes a lil bug with the financial aid calculator. I introduced it when I merged https://github.com/mitodl/micromasters/pull/1534
Make sure you can add a new financial aid object to your user with no problems (in the UI).

fix financial aid calculator imports

---

requirements.txt
test_requirements.txt

None
Moves ddt, a library for parameterized testing, into test_requirements.txt

Moved ddt into test_requirements.txt

---

financialaid/admin_test.py
financialaid/api_test.py
financialaid/factories.py
financialaid/tasks_test.py
financialaid/views_test.py
mail/views_test.py
profiles/factories.py

Part of #1468 
Uses ddt to split financial aid tests

Refactored financial aid tests

---

static/scss/program-page.scss

Fix #1561
Fix x scroll that appears under the tabs on the program page.

Remove x scroll on program page

---

npm-shrinkwrap.json
package.json

Bumped redux-asserts version to 0.0.9

---

roles/models.py

So it's more readable in the Django admin.

Add a __str__() for Role

---

npm-shrinkwrap.json
package.json

moar redux asserts

---

static/js/components/dashboard/CourseDescription.js

Fixes https://github.com/mitodl/micromasters/issues/1555
- Fixes edX course url construction on dashboard page.

Fixed View on edX url inside dashboard

---

cms/templates/cms/home_page.html
static/js/components/Navbar.js

Changes the app header from "MicroMasters" to "MITx MIcroMasters"

Small PR to make header say MITx MicroMasters

---

search/views.py
static/js/components/LearnerSearch.js
static/js/components/search/CustomNoHits.js
static/js/components/search/CustomNoHits_test.js
static/scss/search-page.scss

- fixes https://github.com/mitodl/micromasters/issues/1391
- fixes https://github.com/mitodl/micromasters/issues/1390
- fixes https://github.com/mitodl/micromasters/issues/1366
Displayed message when no search results.
- see static/js/components/LearnerSearch.js
- open `/learners/` page when no results or no users to program

Shown message when no search results

---

static/scss/_button.scss
static/scss/page-layout.scss
static/scss/responsive-styles.scss
static/scss/signup-dialog.scss

This adjusts the width of modal dialogs for mobile devices, and removes some of the margin in the signup dialog.

Small change to width of modals on mobile

---

app.json

closes #1396 
Adds cybserource setting names to app.json. If all works as expected, PR builds will pull the values for these settings from the CI server. 
Did the PR build get the appropriate settings?

added cybersource settings to app.json

---

static/scss/search-page.scss

- fixes https://github.com/mitodl/micromasters/issues/1512
- Fixed alignment of **Current Residence** facets like **Country of Birth**.
@pdpinch @aliceriot @roberthouse54

Fixed alignment of Current Residence on search page

---

static/js/containers/UserPage_test.js
static/js/dashboard_routes.js

Fixes #1630
Fixes tests which were disabled

Fixed pending JS tests

---

travis/Dockerfile-travis-web

Make sure `pip install` is run as root for travis container

---

static/js/components/ProgramSelector_test.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/inputs/inputs_test.js
static/js/components/search/CustomResetFiltersDisplay_test.js
static/js/components/search/FilterVisibilityToggle_test.js
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerSearchPage_test.js
static/js/util/util_test.js

Because I might be _slightly_ obsessive about this.

Chai lengthOf

---

ecommerce/models.py
ecommerce/models_test.py

Fixes #1410.
The Sentry ticket was caused by a user setting `is_valid` to `True` for a given `course_run` when one already existed. The goal here is to present the user with an informative error message rather than hit a 500 page.
This adds a `clean()` implementation for `CoursePrice` that raises a `ValidationError`. This approach trades off less code for an extra query on what my understanding is a fairly infrequent administrative action. I left similar validation code in `save()` because that method is within an atomic transaction which enforces the rule that no two `CoursePrice`s with the same `course_run` can have `is_valid == True`. An alternative approach would've been to handle the exception already raised in `save()` but that would've required overriding the admin view which I …

Added model validation to CoursePrice to fix #1410

---

static/js/components/EmploymentForm.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

Fix #1508
In the employment form change 'Company name' to 'Name of Employer'.

Change Company Name field

---

micromasters/settings.py
micromasters/urls.py
test_requirements.txt
tox.ini

N/A
Adds Django Debug Toolbar
rebuild the web container then verify that the toolbar works

Added Django Debug Toolbar in Debug mode

---

static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/containers/UserPage_test.js
static/js/util/integration_test_helper.js

Fix #756
When user moves between tabs scroll up to the step progress element.

ProfilePage scroll top between steps

---

static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage_test.js

Fixes #1672 
Fixes the bug where program enrollments were not being shown
Go to `/profile` and see the list of programs available

Fixed program enrollment listing bug in signup page

---

requirements.txt

Upgrade Wagtail to 1.7

---

npm-shrinkwrap.json
package.json
static/js/components/Loader.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage.js
static/js/containers/UserPage.js
static/scss/layout.scss

Fixes #1350
Replaces the existing spinner with a material design spinner
Load a page and look at the spinner while it's loading.

Removed react-loader, use react-mdl react

---

requirements.txt
ui/urls.py

Upgrade Django to 1.10.3

---

dashboard/apps.py
financialaid/views_test.py
micromasters/celery.py
profiles/apps.py
roles/apps.py
search/apps.py
seed_data/management/commands/alter_data.py
test_requirements.txt

Also fixing the new errors that the new version of Pylint discovered. Pulling this out of #1649, to make that pull request smaller.

Upgrade pylint to 1.6.4

---

static/js/components/Navbar.js
static/js/containers/UserMenu.js

- fixes https://github.com/mitodl/micromasters/issues/1614
- Now getting username for profile page url from SETTINGS object
@noisecapella @pdpinch

Loaded username param of profile page url from SETTINGS

---

static/js/containers/App.js
static/js/util/util.js
static/js/util/util_test.js

- fixes https://github.com/mitodl/micromasters/issues/1602

Allowed annoAnonymous users to see public profiles

---

ui/templates/header.html

Use <button> for header log in/sign up

---

backends/pipeline_api.py
backends/pipeline_api_test.py
static/js/components/PersonalForm.js
static/js/containers/UserPage_test.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

Fix #1521
On first login set preferred name to be same as first name. 
Change the name of the field to "Nickname / Preferred Name".

Change "preferred name" to "Nickname / Preferred Name"

---

app.json

none
Adds missing quotes to app.json
Did the PR build work?
Rebase a broken PR build on it and see it works now.

PGBOUNCER_DEFAULT_POOL_SIZE, PGBOUNCER_MIN_POOL_SIZE need to be strings

---

app.json

**Added conn max age and ssl settings to app.json**
In order for PR apps to work added db_conn_max_age and disable_ssl
settings to app.json for being copied to review apps.

Added conn max age and ssl settings to app.json

---

static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js

Fixes #1717 
Fixes a rare race condition bug which results in an error message (see screenshot in #1717)
I'm not sure, it only happened to me once and I've been having trouble reproducing it. I just enrolled in a new program using the enroll link in the program selector.

Fixed race condition bug with FinancialAidCalculator

---

static/js/components/search/HitsCount.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/footer.scss
static/scss/general-styles.scss
static/scss/navbar.scss
static/scss/page-layout.scss
static/scss/profile.scss
static/scss/search-page.scss
static/scss/user-chip.scss
static/scss/user-page.scss

- Changes the button color to be more inline with the MIT red.
- Tightens up the spacing in the learner search, the user chip hover.
- Adds a hover state for the learner search rows
- changes the color of the grade histogram
- changes the color of the "Clear Filters" background
- Changes the color of the "Email Learners" button and add a hover state
- Changes the background color of the sort by dropdown
- Changes the color of the financial aid box
Especially see if there are any buttons in the old color, or hover state color problems.

Various style changes

---

cms/templates/cms/home_page.html
static/scss/homepage.scss

Fixes #1688.
Makes the program list on the program home page more accessible, particularly to screen readers.
Examine the HTML to make sure the structure makes sense. Load the home page in your browser to make sure it looks good visually.
I recommend installing a screen reader like [ChromeVox](http://www.chromevox.com/) to experience the page the way a non-sighted user would, and make sure that going through the page element by element makes sense.

Program list on homepage: use semantic HTML, improve element order for screen readers

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js

No need to go through curly braces.

Pass strings to React directly

---

Dockerfile
Dockerfile-node
travis/Dockerfile-travis-watch-build

https://github.com/docker/docker/pull/25466

MAINTAINER is deprecated in Dockerfiles

---

static/scss/program-page.scss

This styles the Course description popover on the Program page. From the home page click on a program, then click on a course link in the right column.
- Adds more padding to the popover
- changes the font sizes
- changes the box-shadow

A small style change to the course description popover

---

static/scss/terms-of-service.scss
ui/templates/terms_of_service.html

This PR is some small style tweaks to the Terms of Service page:
- Adds drop shadow to the mdl card
- tweaks the font of the page title and the text in the card
- changes the padding in the card

Small style changes to the Terms of Service page

---

static/js/components/SkipFinancialAidDialog_test.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/global_init.js

part of #1575 
Adds some more test coverage to financial aid frontend code.

More financial aid tests

---

static/js/actions/ui_test.js
static/js/components/Navbar_test.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/App_test.js
static/js/containers/FinancialAidCalculator.js
static/js/lib/api_test.js
static/js/reducers/index_test.js
static/js/reducers/ui_test.js

Fixes #1575
Adds or fixes tests to increase the test coverage
In addition to adding tests this also removes some dead code from `FinancialAidCalculator`, so make sure the skip links still work.
Run `npm run coverage` and verify that the relevant cases in #1575 are covered.

Increased test coverage

---

.dockerignore
.travis.yml
README.md
js_test.sh
npm-shrinkwrap.json
package.json
static/js/components/search/FilterVisibilityToggle_test.js
test_requirements.in
test_requirements.txt
tox.ini
travis-docker-compose.yml
travis/codecov_python.sh
travis/js_tests.sh

Fixes #1441 
Fixes #1834
Changes settings to upload results to codecov.
This shouldn't touch any non-test code so it shouldn't need manual testing.
To look at the coverage results, go to the root for this github repository, switch to branch `gs/codecov6` and click on the coverage button. You should see both javascript and python files in the files listed.
- The `.dockerignore` change is necessary because we need to copy `.git` so `codecov` can make use of it. 
https://twitter.com/JoachimHolmer/status/799602767081848832/photo/1

Setup codecov

---

static/js/containers/UserPage_test.js
static/js/global_init.js

Clean up use of SETTINGS in tests

---

static/js/components/EducationForm.js
static/js/components/EducationForm_test.js
static/js/components/EmploymentForm_test.js
static/js/components/inputs/StateSelectField.js
static/js/lib/currency.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #1839 
Sorts fields of study
View the fields of study in the education dialog and confirm that they're in alphabetical order

Sort fields of study

---

static/js/components/PersonalTab.js
static/js/components/inputs/SelectField.js
static/js/containers/FinancialAidCalculator.js

This is a simple PR that removes the "x" on the react select component in the Sign Up forms.

Removes the x in the react select component

---

dashboard/serializers.py
dashboard/serializers_test.py
mail/views.py
mail/views_test.py
search/api.py
search/api_test.py

- fixes https://github.com/mitodl/micromasters/issues/1781
- Applied email preference (profile. email_optin) on emails recipients, when staff emails students in bulk
@pdpinch @noisecapella @giocalitri

Applied email preference when staff emails students in bulk

---

static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseGrade.js
static/js/components/dashboard/CourseGrade_test.js
static/js/components/dashboard/CourseRow.js
static/js/constants.js

- fixes https://github.com/mitodl/micromasters/issues/1841
@roberthouse54 @pdpinch @aliceriot

Re-label  'Current Grade' on the dashboard to 'Course Progress' and link to EDx Progress tab

---

ecommerce/api.py
ecommerce/api_test.py

Fixes #1726 
Adds Cybersource fields which may be useful in reporting
Nothing should break. You can test this by clicking the pay button for a course and verifying that you are redirected to Cybersource

Added merchant_defined_data fields

---

npm-shrinkwrap.json
package.json
static/js/components/dashboard/CourseDescription_test.js
static/js/constants.js
static/js/containers/FinancialAidCalculator_test.js
static/js/lib/api.js
static/js/lib/api_test.js

None
Uses `Object.freeze` on the test data so that we get errors when they are modified.
Only test constants should be affected

Deep freeze for test constants

---

npm-shrinkwrap.json
package.json
requirements.txt

Raven is the error-reporting client for [Sentry](https://sentry.io).
* [Python Changelog](https://github.com/getsentry/raven-python/blob/master/CHANGES)
* [JS Changelog](https://github.com/getsentry/raven-js/blob/master/CHANGELOG.md)

Upgrade Raven

---

static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/ProfileImage_test.js
static/js/containers/ProfilePage_test.js
static/js/global_init.js
static/js/reducers/image_upload_test.js
static/js/reducers/index_test.js
static/js/util/integration_test_helper.js
static/js/util/util_test.js

Fixes #1869 
Fixes `SETTINGS.username` reference that we forgot to remove earlier, adds tests to cover that case

Remove SETTINGS.username, update tests

---

static/scss/dashboard.scss

Fixes #1871
Removes some padding so a four digit price will show up properly

Decrease padding for button within course action column

---

static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss
static/scss/general-styles.scss
static/scss/navbar.scss
static/scss/program-page.scss
static/scss/progress-widget.scss
static/scss/search-page.scss

This is a small PR that changes the color of a few elements on the site:
- the progress card to white, and the bar itself to a lighter shade of the MIT brand color.
- the link color slightly lighter blue
- the button color to blue
Also, a slight tweak to the material card box-shadow

Change a few colors

---

micromasters/celery.py

Adds sentry error handling to Celery tasks
celery.py
Verify that exceptions fired from celery tasks end up in Sentry
Added configuration to register hooks in Celery for Sentry to track
any errors.

Adding sentry hooks to Celery

---

backends/pipeline_api_test.py
backends/utils_test.py
courses/serializers_test.py
dashboard/api_edx_cache_test.py
dashboard/api_test.py
dashboard/signals_test.py
dashboard/tasks_test.py
dashboard/utils_test.py
dashboard/views_test.py
ecommerce/api_test.py
ecommerce/permissions_test.py
ecommerce/views_test.py
financialaid/management/commands/update_exchange_rates_test.py
financialaid/tasks_test.py
micromasters/tests/test_settings.py
profiles/views_test.py
search/base.py
search/indexing_api_test.py
ui/views_test.py

fixes #1914 
completes the work started on #1903 and not finished because the docker image used in travis was not rebuilt.
if the tests pass in travis, this should be good to go

Actually removed any reference to third party Mock library

---

npm-shrinkwrap.json
package.json
static/js/components/CropperWrapper.js
static/js/entry/dashboard.js

- fixes https://github.com/mitodl/micromasters/issues/1866
- test photo upload on safari, chrome, firefox, ie.

Fixed file upload on safari

---

static/js/components/dashboard/CourseAction.js
static/scss/dashboard.scss

Fixes #1871 
Adds a bit more padding, removes the hyphen
Look at it with a window that's not full screen

Fixed Pay now button for IE

---

cms/templates/cms/home_page.html
static/scss/footer.scss

https://github.com/mitodl/micromasters/issues/1920
This fixes #1920

Makes footer button responsive

---

static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js

Fix #1590
Cannot test this until this #1697 is fixed.

Increase order fulfillment timeout

---

static/js/containers/UserPage_test.js
static/js/util/test_utils.js

Fixes #1930 
Adds a regression test for #1926
Revert the commit for #1926 and verify that the tests fail

Added integration tests for about me

---

static/js/components/UserInfoCard.js
static/scss/user-page.scss

Remove email icon from user profile

---

static/js/components/UserInfoCard.js
static/js/components/UserInfoCard_test.js
static/js/containers/UserPage_test.js

Fix #1494
If the user is viewing his own profile, remove the email icon and information.

Remove email info from personal profile

---

cms/models.py
cms/templates/cms/categorized_faqs_page.html

Fix #1828
Add a template for CategorizedFaqsPage, so that the user can preview the page.

Added cms template for CategorizedFaqsPage preview

---

static/js/util/profile_edit_test.js

Fixes #1774 
Cleans up some tests

Refactored profile_edit_test tests

---

RELEASE.rst
micromasters/settings.py
static/js/components/DocsInstructionsDialog.js
static/js/components/dashboard/FinancialAidCard.js

Release 0.25.1

---

financialaid/views_test.py
ui/views_test.py

None
Adds tests to assert that the proper JS bundle links are being rendered on the right pages

Added tests for bundles

---

static/js/entry/zendesk_widget.js

Fixes #1962 
Checks that the element and label exist before settings the display
This error doesn't seem to be easily reproducable. Hopefully the changes are simple enough to not cause problems though

Check element and label in case they're undefined

---

RELEASE.rst
courses/models.py
courses/models_test.py
courses/serializers_test.py
micromasters/settings.py

Release 0.25.2

---

search/views_test.py

None
Adds a test to cover uncovered code in search/views.py: https://codecov.io/gh/mitodl/micromasters/src/a13e15315f0fb929157d6a82ff4220c6f5c32d61/search/views.py#L37
This only touches test code so no manual testing should be necessary

Add test for user without staff or instructor role

---

RELEASE.rst
micromasters/settings.py
static/js/components/CropperWrapper.js
static/js/containers/ProfileImage.js

Release 0.25.3

---

app.json

Fixes #1975
Adds configuration to allow for integration with rediscloud
Log into the PR build. If login worked this should be fine

Enabled integration with rediscloud

---

cms/templates/cms/home_page.html
ui/views_test.py

Remove alt text from course images

---

static/js/components/PersonalForm.js
static/scss/_variables.scss
static/scss/profile-form.scss

Add warning about legal name requirement

---

RELEASE.rst
micromasters/settings.py
static/js/components/PersonalForm.js
static/js/components/ProfileImageUploader.js
static/js/containers/ProfileImage_test.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js
static/scss/_variables.scss
static/scss/profile-form.scss

Release 0.27.0

---

RELEASE.rst
backends/edxorg.py
backends/edxorg_test.py
micromasters/settings.py

Release 0.27.1

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
ui/templates/base_error.html
ui/templates/footer.html
ui/templates/terms_of_service.html

Fixes #1917. Improves our usage of semantic HTML elements, which improves accessibility. There should be no user-visible changes in this pull request.
It may be helpful to add `?w=1` to the GitHub URL when reviewing this pull request, so that GitHub does not display changes that are only whitespace.

Use HTML elements that are more semantic

---

static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

closes #1951 
This rewrites the profile validation code in a more functional style, which lets us have a greater degree of code reuse and, hopefully, readability.
Read over the changes, and make sure they make sense.
Well, I think just make sure there aren't any regressions in the validation UX, when filling out the profile.

refactor profile validation code

---

RELEASE.rst
micromasters/settings.py
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

Release 0.28.1

---

static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

double revert, what does it mean
to test this, delete your photo and ensure you can get past the first page of the profile flow.

Revert "Revert "Changed profile validation to not require a photo""

---

static/js/entry/public.js

Fix  #1823
For testing, try adding some links in program page content through cms, and make sure those links open in a new tab.

Open external links in new tabs on public pages

---

static/js/components/EmailCompositionDialog_test.js
static/js/components/UserInfoCard_test.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/CourseSubRow_test.js

None
Code cleanup on tests, specifically using `sinon.sandbox.create()` and using render functions instead of defaultProps
The tests should still pass and code coverage should not change much. Since there are only changes in tests you shouldn't need to do any manual tests

Used render methods for tests, use sandbox for sinon

---

static/scss/search-page.scss

Fixes #2054 
Fixes left indentation for our course facets
Load the learners search page

Fixed search facet left indentation

---

cms/templates/cms/home_page.html

Fix #1864
Updated the MM image in the facebook sharing tags.

Updated Facebook sharing image

---

static/js/entry/public.js

Just removes some rules and fixes the three errors that cropped up.
There shouldn't be any functional change from this.

Remove some linting rule disables on `entry/public.js`

---

RELEASE.rst
micromasters/settings.py
static/js/entry/public.js
static/js/entry/zendesk_widget.js

Release 0.30.1

---

static/js/components/EducationForm.js
static/js/components/ErrorMessage_test.js
static/js/components/PersonalTab.js
static/js/components/ProgramSelector_test.js
static/js/components/inputs/DateField.js
static/js/components/inputs/inputs_test.js
static/js/containers/App_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage.js
static/js/containers/SettingsPage_test.js
static/js/containers/UserPage_test.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/validation/profile_test.js
static/js/reducers/financial_aid_test.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/reducers/ui.js
static/js/util/popover_animation.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/profile_history_edit.js
static/js/util/test_utils.js
static/js/util/util_test.js

Fixes #2041 
Replaces `Object.assign` with ES6 spread syntax
Make sure nothing broke
There are minor changes here and there other than swapping `Object.assign`, for example I removed some clones which seemed redundant. There shouldn't be anything that should cause a change in behavior though.

Replace Object.assign with spread syntax

---

.istanbul.yml

None
Excludes `*_test.js` files from test coverage
Look at the codecov output

Filter out *_test.js files from test coverage

---

static/scss/homepage.scss

Display tagline on mobile

---

static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js

- fixes https://github.com/mitodl/micromasters/issues/2052

Added do not set income tax statement by email instruction message

---

static/js/components/CropperWrapper.js

Fixes #2112
Fixes a flow check error
This shouldn't affect anything outside of the flow check

Added cropper to object types

---

cms/templates/cms/home_page.html
static/js/entry/public.js

Fix #1863
Add twitter description tag with shorter text.

Made twitter description tag shorter

---

static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/reducers/financial_aid.js
static/js/reducers/financial_aid_test.js
static/scss/calculator.scss

Part of #1752
Disables financial aid application button during API activity
Apply for financial aid. The save button should become a spinner temporarily.

Disables financial aid application button during API activity

---

static/js/actions/programs.js
static/js/components/Navbar.js
static/js/components/NewEnrollmentDialog.js
static/js/components/NewEnrollmentDialog_test.js
static/js/components/ProgramSelector.js
static/js/containers/App.js

Part of #1752 
Disables the save button for the new program enrollment dialog during API activity

Disable program enrollment button during API activity

---

static/js/components/ConfirmDeletion.js
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/UserPage_test.js
static/js/util/profile_history_edit.js

Part of #1752
Disable employment and education delete buttons during API activity

Disable employment and education delete buttons during API activity

---

static/js/components/EmailCompositionDialog.js
static/js/components/EmailCompositionDialog_test.js
static/js/components/LearnerSearch.js
static/js/containers/LearnerSearchPage.js
static/js/containers/LearnerSearchPage_test.js

Part of #1752
Disables the send button in the email dialog during API activity

Disabled send button during Email

---

roles/api.py
roles/models.py

Fixes #2036 
Moves `NON_LEARNERS` variable into `Role`

Moved NON_LEARNERS inside Role class

---

dashboard/fixtures/current_grades.json
dashboard/serializers.py
dashboard/serializers_test.py
dashboard/utils.py
dashboard/utils_test.py
search/indexing_api.py
static/js/components/LearnerSearch.js

fixes https://github.com/mitodl/micromasters/issues/810
@pdpinch

Added Facet on number of courses completed

---

package.json
webpack.config.dev.js
webpack.config.prod.js
webpack.config.shared.js
yarn.lock

This adds two babel plugins which are supposed to optimize React a little bit. Look at the relevant issue: https://github.com/mitodl/micromasters/issues/2163 to see some results comparing this branch with `master`.

Add two new babel plugins

---

static/js/containers/App.js
static/js/containers/UserPage_test.js

- fixes https://github.com/mitodl/micromasters/issues/1837
- Copy learners page link i.e http://192.168.99.100:8079/learner/amirq
- open it in incognito or any process we MM session is not in progress.

Fixed errors when viewing profile as anonymous user

---

RELEASE.rst
config/nginx.conf.erb
micromasters/settings.py
static/js/containers/App.js
static/js/containers/UserPage_test.js
travis/Dockerfile-travis-watch

Release 0.36.0

---

financialaid/tasks_test.py

Remove CELERY_ALWAYS_EAGER overrides where it already matches the default

---

static/js/containers/UserMenu.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #2214 
Uses the medium size profile image URL in all profile images
View your profile image and confirm that it's 128x128

Use image_medium for profile images

---

profiles/serializers.py
profiles/serializers_test.py
static/js/components/PersonalForm.js
static/js/constants.js
static/js/flow/profileTypes.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/scss/profile.scss

- fixes https://github.com/mitodl/micromasters/issues/2134
- If first name or last name is not in cp-1252 ask user to add romanized name
- romanized name can only be in cp-1252. Added validation for it.
@pdpinch

Ask users with non-Latin names to enter a Latin first name and last name

---

find_test.sh

None
Just a shell script to use wildcards in looking up test names for JS tests

Added find_test.sh

---

courses/urls.py
dashboard/urls.py
ecommerce/urls.py
financialaid/urls.py
mail/urls.py
micromasters/urls.py
micromasters/urls_test.py
profiles/urls.py
search/urls.py

Fixes #2245 
Breaks up `micromasters/urls.py` and creates `urls.py` for each app which defines views
I made the tests and the refactoring separate commits. You can verify that there is no change to the URLs by checking out the test commit, running the tests, then checking out the refactor commit and running the tests again.

Split up URLs into respective apps

---

profiles/serializers.py
profiles/serializers_test.py
profiles/views_test.py

Fix #1838
Try to reproduce the bug as described in the issue.

Add image to ProfileLimitedSerializer

---

courses/utils.py
courses/utils_test.py
dashboard/serializers.py
dashboard/serializers_test.py
requirements.in
requirements.txt
search/indexing_api.py
static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js
static/js/components/search/PatchedMenuFilter.js

Closes #1710 
Adds the course semester facet to the learner's search
dashboard/serializers.py, courses/utils.py, then static/js/components/LearnerSearch.js
1. Seed the DB with your user as staff
1. Recreate index
1. Go to learner's search page
There are a couple hacks in here to get searchkit working properly. I'll add details in the comments.

Added course semester facet

---

mail/api.py
mail/api_test.py
mail/views.py
micromasters/settings.py
profiles/util.py
profiles/util_test.py

- fixes https://github.com/mitodl/micromasters/issues/1791

For staff mail to learners, pointed the return address to be help desk

---

static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js

Fix #859
Add facet by degree (education level)
Go to learner's search page as staff for a program.

Added Facet by Degree

---

cms/factories.py
courses/factories.py
ecommerce/factories.py
financialaid/factories.py
profiles/factories.py

Switch from [`LazyAttribute`](http://factoryboy.readthedocs.io/en/latest/reference.html#lazyattribute) to [`LazyFunction`](http://factoryboy.readthedocs.io/en/latest/reference.html#lazyfunction) where it makes sense to do so.
This should not require any manual testing. If the automated tests pass on Travis, it's good to go.

Factory Boy: LazyFunction

---

static/js/components/search/CountryRefinementOption.js
static/js/components/search/CountryRefinementOption_test.js
static/js/lib/currency.js
static/js/lib/currency_test.js
static/js/lib/location.js
static/js/lib/location_test.js
static/js/util/util.js
static/js/util/util_test.js

- Fixes https://github.com/mitodl/micromasters/issues/2273
- To reproduce it just make country code of a profile null. This error is because of data inconsistency 
@pdpinch

Fixed learner search for DEDP fails issues

---

cms/factories.py
courses/factories.py
ecommerce/factories.py
financialaid/factories.py
profiles/factories.py

[`factory.Faker`](http://factoryboy.readthedocs.io/en/latest/reference.html#faker) is really nice.

Use factory.Faker()

---

.travis.yml

Explicit is better than implicit.

sudo: false for Travis CI

---

dashboard/utils.py
dashboard/utils_test.py
ecommerce/api.py
ecommerce/api_test.py

Part of #2158 
Rebased on #2282 
Adds functions to `dashboard/utils.py` and `ecommerce/api.py` to test coupon redeemability
There's no user facing piece yet

Added coupon functions

---

js_test.sh
static/js/babelhook.js

fixin a thing
as long as the JS tests run without an error the fix is good

Revert "Deleted .babelrc"

---

static/js/components/LearnerSearch.js

No ticket. Related to #2336 hotfix (PR #2337)
Fixes linter

Fixed unused variable linting error

---

static/js/containers/App.js

Fixes #2344 
This fixes an infinite cycle in the profile validation in `App.js`. It doesn't happen in production currently, but when we add more profile fields users would see it.
`App.js`
Register as a new user, go to the profile page and be sure you can edit your profile.

Fixed infinite loop in profile validation (#2344)

---

ecommerce/models.py
ecommerce/models_test.py

Fixes #2326 
Changes `user_has_redemptions_left` function to return false if another user has already redeemed the `Coupon` at least once, and the `Coupon` is not automatic

Filtered out coupons redeemed by another user

---

static/js/actions/coupons.js
static/js/actions/coupons_test.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/reducers/coupons.js
static/js/reducers/coupons_test.js
static/js/reducers/index.js

Fixes #2322 
Adds coupon actions and a reducer for the new coupon APIs
There is no user facing portion

Added boilerplate for coupon APIs

---

profiles/util_test.py

Fixes #2369 
Removes check for exact timestamp value in filename

Fix intermittent test failures

---

ui/templates/footer.html

- fixed https://github.com/mitodl/micromasters/issues/2333
@pdpinch

Fixed copyright date

---

dashboard/factories_test.py
dashboard/serializers.py
dashboard/utils.py
dashboard/utils_test.py
exams/management/commands/authorization_user_exam.py
exams/signals.py
exams/signals_test.py
exams/util.py
exams/util_test.py
exams/utils.py
exams/utils_test.py
financialaid/api_test.py
grades/api_test.py
seed_data/management/commands/authorization_user_exam.py
seed_data/utils.py
seed_data/utils_test.py

fixes https://github.com/mitodl/micromasters/issues/2077
- When user pay and enroll in course we create ExamProfile and ExamAuthorization
- When user pass the course in grade section we authorize him for exam
- A command to force authorize users who passed course.
@pdpinch @rhysyngsun

Triggered exam authorizations when users enrolled or passed course

---

ui/context_processors.py
ui/templates/adwords.html

@amir-qayyum-khan, can we add this commit to #2410?

APIKEYS.GOOGLE_ADWORDS

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
ui/context_processors.py
ui/templates/adwords.html
ui/templates/base.html

- fixed https://github.com/mitodl/micromasters/issues/2390
- Moved Adwords tag to bottom and given white background.
- Limited Adwords tag only to home and program pages.
@pdpinch @roberthouse54

Removed 13px Adwords iframe height and added Adwords tags to only home page and program page

---

ecommerce/admin.py

Fixes #2400
Rebased on #2388 
Allows creating coupons in the Django admin
Create a coupon in the Django admin

Remove readonly_fields for Coupon admin

---

static/js/components/LearnerSearch.js

I removed almost all of these in
3cd4d880ecb4be0d59349c8350f7fe635eacecb2, but it looks like a few have
snuck back in.
Just confirm that flow is passing.

remove foo: Function annotations

---

dashboard/utils.py

[List comprehensions](https://docs.python.org/3.5/tutorial/datastructures.html#list-comprehensions) are very nice, and you can do dict comprehensions and set comprehensions, as well. This small pull request is just a small improvement to some existing code.

Improve MMTrack code with comprehensions

---

seed_data/management/commands/create_tiers.py
seed_data/management/commands/create_tiers_test.py
seed_data/management/commands/seed_db.py
seed_data/management/commands/seed_db_test.py

None
Fixes handling of CoursePrice and TierProgram in `./manage.py seed_db`

Fixed CoursePrice and TierProgram handling in seed_db

---

dashboard/serializers_test.py
dashboard/utils.py
dashboard/utils_test.py
exams/signals_test.py
exams/utils.py
exams/utils_test.py
grades/factories.py

N/A
Fixed the code to work with the `v1` grade algorithm
Run the tests with the environment variable:
`FEATURE_FINAL_GRADE_ALGORITHM=v0`
and
`FEATURE_FINAL_GRADE_ALGORITHM=v1`
The tests should pass in both cases.

Fixing code to run with v1 grades agorithm

---

ecommerce/views.py
ecommerce/views_test.py

Fixes #2493 
Enrolls a user when they do a $0 purchase
Have a course ready to purchase with a $0 price that exists on edX. Make sure you are not enrolled on edX. Don't click 'Enroll', just click 'Pay now'. Click Continue on the order summary page. You should see a success toast message saying that you enrolled. Verify on edX that you are enrolled.

Enroll user after a $0 purchase

---

exams/signals.py
exams/signals_test.py
exams/utils.py
exams/utils_test.py

- None
- Fixed ripples of #2331
- Refactors update_exam_authorization_cached_enrollment.

Fixed signals for exam authorization trigger

---

static/js/containers/DashboardPage.js

Pull error message & main page content out into separate render functions

Refactor DashboardPage

---

pull_request_template.md

None, this came out of our retrospective.
Updates this template to mark required sections
pull_request_template.md
No way to test ahead of merge.

Marked required PR sections

---

exams/tasks.py
exams/tasks_test.py
exams/utils.py
exams/utils_test.py

Fix #2339
validates `ExamProfile` data before sending it to Pearson. If profile is invalid then sets status on the `ExamProfile` to 'invalid'.
```
user.profile.address=‘中华人民共和国’
user.profile.save()
```
now the ExamProfile status for this user should be set to 'pending'. Now you can the task:
```
from exams.tasks import *
result = export_exam_profiles.delay()
```
Now the ExamProfile status should be set to 'invalid', and the exported file should not contain this profile. The same should happen if any of the fields are not filled out (except for `postal_code` which is optional)

Validate exam profile

---

exams/utils_test.py

Fixes #2544
Adds a version of these tests that explicitly tests v1 and added an override to the old tests to force them to v0.
Run the test suite with `FEATURE_FINAL_GRADE_ALGORITHM=v0` and `FEATURE_FINAL_GRADE_ALGORITHM=v1`.
I basically copied existing tests that work against v0 into a v1 version that creates the `FinalGrade` so that we can just nuke the whole v0 class when we're done with that.

Fixed exam util tests for v0 and v1 (#2544)

---

static/js/actions/ui.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/reducers/ui.js
static/scss/calculator.scss

Fix #2481
Add an extra step in the submission of the financial aid application.
Go through the application process for financial aid, through the FinancialAidCard or course that is open for enrollment. 
(Optional)
(Optional)
(Optional)

Added Confirm Income dialog

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
config/nginx.conf
micromasters/settings.py
static/dnt-policy.txt
ui/context_processors.py
ui/templates/analytics.html
ui/templates/base.html

The "Do Not Track" request header indicates that a user does not wish to be tracked by the website they are visiting. This commit checks the DNT header to respect this wish. See http://donottrack.us for more information.
Note that this pull request may affect our analytics numbers.

Respect DNT request header

---

static/js/containers/DashboardPage.js
static/scss/dashboard.scss

- fixes https://github.com/mitodl/micromasters/issues/2517
- Adds program title to dashboard page.
- http://192.168.99.100:8079/dashboard
@pdpinch

Added program title to dashboard

---

static/js/actions/email.js
static/js/actions/ui.js
static/js/components/LearnerSearch.js
static/js/components/email/EmailCompositionDialog.js
static/js/components/email/EmailCompositionDialog_test.js
static/js/components/email/constants.js
static/js/components/email/hoc.js
static/js/components/email/hoc_test.js
static/js/components/email/lib.js
static/js/components/email/test_constants.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerSearchPage.js
static/js/containers/LearnerSearchPage_test.js
static/js/flow/emailTypes.js
static/js/reducers/email.js
static/js/reducers/email_test.js
static/js/reducers/ui.js
static/js/util/util.js
static/js/util/util_test.js

Closes #2468 
Refactors email front-end code to use a higher-order component and a single rendering of the email dialog.
Use the contact course team link on /dashboard and the search result email link on /learners
/static/js/components/email/EmailCompositionDialog.js
[Facebook docs discussing the pattern](https://facebook.github.io/react/docs/higher-order-components.html#convention-maximizing-composability)

Refactored email front-end code to use HOC pattern

---

static/js/components/LearnerSearch.js

fixes https://github.com/mitodl/micromasters/issues/2157
Rearrage facetes to https://github.com/mitodl/micromasters/issues/2157#issuecomment-268075663
Go to http://192.168.99.100:8079/learners
@pdpinch

Rearranged facets

---

config/nginx.conf
config/nginx.conf.erb

Fix #2502
Redirect to /static/images/favicon.ico
go to /favicon.ico

Redirect favicon.ico

---

ecommerce/api.py
ecommerce/api_test.py
ecommerce/management/commands/validate_db.py

Fix #2497
Create a  management command to validate `course_price`s and `discount_amount` for all live programs.
Run the command: ` ./manage.py validate_price`.
It should print errors if course prices for a live program are not equal to each other, or do not exist. Also, if a TierProgram has a discount that would bring the final price to a negative value.
(Optional)
(Optional)
(Optional)
(Optional)

Validate prices and FA discounts management command

---

financialaid/constants.py
financialaid/management/commands/update_exchange_rates_test.py
financialaid/tasks.py
financialaid/tasks_test.py

N/A
Modifies the way a constant is built in the financial aid putting it in a function.
Run the financial aid tests on master: you should have a failure. Running on this PR they should pass.
We should probably also run tests if the synchronization of the exchange rates still works.

Modified financial aid constant to fix task test

---

README.md

Related to PR #2629
Add the command to README.md
Take a look at README

Add validate_db to README

---

static/js/financial_aid/functions.js

Fixes #2676
Fixes an import and other whitespace changes that my editor did automatically
Go to the financial aid review page (for example `/financial_aid/review/1/` where `1` is the program id). You should not see any console error

Fix import

---

static/js/components/Navbar.js
static/scss/_variables.scss
static/scss/navbar.scss

https://github.com/mitodl/micromasters/issues/2564
This does the style changes required for #2564
Open and close the sidebar. Make sure the links work.
Check that the css looks like it is properly formatted.
This only partly completes #2564. The other thing required to complete that issue is to make the sidebar always visible on the page, and to remove the user dropdown in the navbar.

Restyle sidenav

---

requirements.in
requirements.txt

Fixes #2697.
Upgrades a dependency. There should be no user-visible changes.
Ensure that the app loads correctly. Click around a few pages, and make sure that nothing is broken.

Upgrade Django to 1.10.5

---

static/js/containers/DashboardPage_test.js

Fixing a test failure on master. No idea how we didn't find this before PR #2519 merged.

Fix deepEqual test

---

RELEASE.rst
backends/exceptions.py
backends/utils.py
dashboard/api.py
dashboard/api_edx_cache.py
dashboard/api_edx_cache_test.py
dashboard/api_test.py
dashboard/views.py
dashboard/views_test.py
micromasters/settings.py

Release 0.49.3

---

RELEASE.rst
micromasters/settings.py
search/api.py
search/api_test.py
search/connection.py
search/indexing_api.py
search/views_test.py
static/js/components/LearnerSearch.js
static/js/components/search/CustomSortingColumnHeaders.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/containers/LearnerSearchPage_test.js
static/scss/search-page.scss

Release 0.50.0

---

static/js/reducers/util.js
static/js/reducers/util_test.js

#2785 
Fixes the unauthenticated learner page view.
Go to the associated issue, and follow the steps to reproduce the bug. Probs best to confirm you can reproduce it on master, then checkout this branch and confirm it fixes it.

fix learner page

---

README.md

Update yarn version that needed for MM development

Updated required yarn version in readme file

---

requirements.in
requirements.txt

Fixes #2831.
Upgrades Wagtail. No user-visible changes. except for the enhancements that are now available in the new version of Wagtail. [Release notes are here.](http://docs.wagtail.io/en/v1.9/releases/1.9.html)
Poke around the Wagtail CMS, make sure everything still works just fine.

Upgrade Wagtail to 1.9

---

requirements.txt

None. This is a regular maintenance task.
Updates our unpinned dependencies to the latest versions. There should be no user-visible changes as a result of this pull request.
Ensure that the application loads. Click around a bit, and make sure that everything seems to work.
I did this because Sentry was reporting that we were reporting errors using an outdated version of the Python SDK. I ran the following commands to generate this pull request:
```
rm requirements.txt
docker-compose run web pip-compile --output-file requirements.txt requirements.in
```

Update requirements from pip-compile

---

static/scss/_button.scss
static/scss/dashboard.scss
static/scss/final-exam-card.scss
static/scss/general-styles.scss
static/scss/homepage.scss
static/scss/page-layout.scss
static/scss/responsive-styles.scss

This fixes several small layout issues, mostly on mobile devices:
- Changes the style and color of the disabled enroll button
- Slight changes to padding of Personal pricing box
-Moves Document set button below date field
- Fixes some padding errors in Course card
- Moves enroll button under Course name on mobile
- Changes some font sizes
- Improves layout of the Schedule and Exam button and course list in the Final Exam Card on mobile
- Improves padding in the address section of the Final Exam Card
- Changes the base font size to 14px
- Improves the height of the hero image section on the home marketing page for mobile
Check to see that the changes are working
I verified some of these changes with the help of an android mobile usb debugging environment. Some bugs were visible on my phone …

More small UI layout tweaks for Mobile etc

---

static/js/components/EmploymentForm.js
static/js/util/util.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/bound-check-box.scss
static/scss/calculator.scss
static/scss/dashboard.scss
static/scss/final-exam-card.scss
static/scss/homepage.scss
static/scss/profile-image-uploader.scss
static/scss/profile.scss
static/scss/search-page.scss
static/scss/staff-learner-info-card.scss
static/scss/terms-of-service-dialog.scss

None. The inconsistency annoyed me.
Our code sometimes uses the spelling "gray" and sometimes the spelling "grey". This pull request changes all "grey" spellings into "gray" spellings.
There should be no visible changes as a result of this pull request. Even the [CSS color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Color_keywords) are identical, regardless of spelling.
View the app, and make sure nothing looks crazy.

Gray, not grey

---

cms/templates/cms/program_page.html

Related to #2873
Fix field name in the program_page template.
same as #2873

Fix semeter_name field in the template

---

package.json
static/js/components/StaffLearnerInfoCard.js
static/js/components/inputs/DateField.js
static/js/containers/LearnerPage.js
static/js/lib/sanctuary.js
static/js/lib/sanctuary_test.js
static/js/lib/validation/date.js
static/js/util/util.js
yarn.lock

I was going to do this as part of https://github.com/mitodl/micromasters/pull/2857 but it was a little more involved so I left it off.
This upgrades to the latest version of Sanctuary. Some parts of the API changed a little, so there's some changes to deal with that.
I think just make sure that the app works alright - click around a little and make sure the Learner page is working well, the dashboard is all right, you can edit your profile, etc.

upgrade sanctuary to latest version

---

RELEASE.rst
micromasters/settings.py
package.json
static/js/components/StaffLearnerInfoCard.js
static/js/components/inputs/DateField.js
static/js/containers/LearnerPage.js
static/js/lib/sanctuary.js
static/js/lib/sanctuary_test.js
static/js/lib/validation/date.js
static/js/util/util.js
yarn.lock

Release 0.53.1

---

Dockerfile-node
README.md
package.json
scripts/install_yarn.js
travis/Dockerfile-travis-watch-build

None
Upgrades yarn to latest stable version
Build should pass

Upgrade yarn

---

RELEASE.rst
micromasters/settings.py
profiles/models_test.py
seed_data/management/commands/attach_avatars.py
seed_data/management/commands/attach_avatars_test.py

Release 0.53.3

---

static/js/constants.js
static/js/flow/restTypes.js
static/js/lib/redux_rest.js
static/js/lib/redux_rest_test.js
static/js/reducers/coupons.js

(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
(Optional)

redux api wrapper

---

static/js/components/OrderSummary.js
static/js/components/OrderSummary_test.js

Fix #2922
Update the text on the Order Summary page.

Fixed Order Summary text

---

dashboard/utils.py

N/A
Fixed lint for dashboard/utils that did not appear because of parallel changes
No tests: tests should just pass.

Fixed lint for dashboard/utils that did not appear because of parallel changes

---

RELEASE.rst
micromasters/settings.py
search/api.py
search/api_test.py
search/exceptions.py
search/indexing_api.py
search/indexing_api_test.py
search/signals.py
search/tasks.py

Release 0.53.8

---

RELEASE.rst
micromasters/settings.py
profiles/models.py
profiles/models_test.py
requirements.in
requirements.txt
static/js/components/ProgressWidget.js
static/js/components/ProgressWidget_test.js

Release 0.53.9

---

.flowconfig
package.json
static/js/actions/ui.js
static/js/components/CouponNotificationDialog_test.js
static/js/components/CourseEnrollmentDialog_test.js
static/js/components/EducationForm.js
static/js/components/OrderSummary.js
static/js/components/ProgramSelector.js
static/js/components/SkipFinancialAidDialog_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/FinalExamCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/OrderSummaryPage.js
static/js/containers/SignupDialog_test.js
static/js/flow/dashboardTypes.js
static/js/flow/declarations.js
static/js/lib/pearson.js
static/js/util/test_utils.js
yarn.lock

none, I just noticed we were getting pretty behind on our Flow version.
This updates it to `@latest` and makes sure all the code is passing.
Make sure there are no major regressions, tests pass, and all that.

upgrade Flow to the latest version

---

exams/signals_test.py
exams/utils.py
exams/utils_test.py

fixes https://github.com/mitodl/micromasters/issues/3000
- Removed `SUPPRESS_PAYMENT_FOR_EXAM` flag and its code all across the application.
@pdpinch

Exams: Removed FEATURE_SUPPRESS_PAYMENT_FOR_EXAM feature flag

---

Dockerfile
RELEASE.rst
apt.txt
exams/signals_test.py
exams/utils.py
exams/utils_test.py
micromasters/settings.py
selenium_tests/base.py
selenium_tests/pytest.ini
static/js/actions/course_enrollments.js
static/js/actions/course_prices.js
static/js/actions/dashboard.js
static/js/actions/email.js
static/js/actions/index.js
static/js/actions/profile.js
static/js/actions/programs.js
static/js/components/email/hoc.js
static/js/components/email/hoc_test.js
static/js/components/search/ModifiedSelectedFilter.js
static/js/constants.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/lib/redux_rest.js
static/js/lib/sanctuary.js
static/js/lib/sanctuary_test.js

Release 0.54.0

---

static/js/components/Navbar.js
static/js/components/Navbar_test.js
static/js/containers/App_test.js
static/scss/navbar.scss

fixes https://github.com/mitodl/micromasters/issues/3059
In slide nav, removed the edit photo link. Added profile link to user name and photo
go to slide menu look for edit profile, click ur user name or photo
@pdpinch

Removed Edit Photo from Sidenav. Also, link user photo to profile.

---

test_requirements.txt

N/A
Fixes a regression by an unpinned linter dependency
Rebuild your container and make sure tests pass.

Pinned pylint deps

---

RELEASE.rst
micromasters/settings.py
seed_data/lib.py
seed_data/management/commands/alter_data.py
seed_data/management/commands/alter_data_test.py
static/js/components/dashboard/FinancialAidCard.js

Release 0.55.1

---

static/scss/search-page.scss

fixes https://github.com/mitodl/micromasters/issues/2155
changes in css to add scroll and max height to current residence.
Go to learners page and see facet country resident, you must have more the 7 countries there.
@pdpinch

Added max height and scroll to Current residence

---

static/scss/calculator.scss

fixes https://github.com/mitodl/micromasters/issues/2474
Fixes the layout of  FA calculator.
Open FA calculator on mobile.
@pdpinch

Fixed mobile view of FA calculator

---

RELEASE.rst
financialaid/views.py
financialaid/views_test.py
mail/api.py
mail/utils.py
mail/utils_test.py
micromasters/settings.py
profiles/permissions.py
profiles/permissions_test.py
profiles/views_test.py
static/scss/_variables.scss
static/scss/calculator.scss
static/scss/search-page.scss

Release 0.57.0

---

tox.ini

Fixes #3136 
Adds environment variables to `tox.ini` passenv which are necessary for codecov to upload from Travis
Look at the code coverage results for this PR. Both Python and Javascript files should exist in the results

Pass through code coverage environment variables

---

RELEASE.rst
exams/api.py
exams/api_test.py
micromasters/settings.py

Release 0.57.5

---

RELEASE.rst
dashboard/api.py
dashboard/api_test.py
micromasters/settings.py

Release 0.57.6

---

exams/api.py
exams/signals.py
exams/signals_test.py

Fixes #3161 
Adds a signal for `Order` so we authorize for exam runs if the user paid for the course after grades were calculated.
- Create an ExamRun for a financial aid course
- Enroll in the current course run for that course
- Create a passing `FinalGrade` for the current course run of that course
- Verify you have no `ExamAuthorization` record for that course
- Pay for the course
- Verify you now have an `ExamAuthorization` record for that course

Added signal to authorize for exams on order fulfillment (#3161)

---

static/scss/search-page.scss

https://github.com/mitodl/micromasters/issues/3130
Makes selected search filters bold in the search facets

Make selected search filters bold in learner search

---

RELEASE.rst
micromasters/settings.py
static/js/components/CourseEnrollmentDialog.js
static/js/components/CourseEnrollmentDialog_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseGrade.js
static/js/components/dashboard/CourseGrade_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/containers/DashboardPage.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js
static/scss/dashboard.scss

Release 0.57.8

---

docker-compose.yml
selenium_tests/base.py
selenium_tests/basic_test.py
travis-docker-compose.yml

Fixes #3139 
Switches to the official selenium images
Tests should pass. You can also try running the selenium tests locally:
- First, run `NODE_ENV=prod ./webpack_if_prod.sh` to generate the static assets needed for selenium tests
- Then run `./scripts/tests/run_selenium_tests.sh`

Use official selenium images

---

RELEASE.rst
courses/serializers.py
courses/serializers_test.py
micromasters/settings.py
static/js/components/CouponNotificationDialog_test.js
static/js/components/CourseEnrollmentDialog.js
static/js/components/CourseEnrollmentDialog_test.js
static/js/components/LearnerSearch.js
static/js/components/OrderSummary.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/CourseSubRow.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/components/search/EducationFilter.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerSearchPage_test.js
static/js/containers/OrderSummaryPage.js
static/js/factories/dashboard.js
static/js/flow/checkoutTypes.js
static/js/flow/enrollmentTypes.js
static/js/global_init.js
static/js/reducers/programs.js
static/js/test_constants.js

Release 0.58.1

---

README.md

None
Updates the README
Read the README

Update readme for selenium tests

---

static/js/containers/LearnerSearchPage_test.js

Fixes #3192 
Adds a test for learner search filter labels
None

Added test for filter titles

---

search/indexing_api_test.py

Remove print(...)

---

static/js/containers/LearnerSearchPage_test.js

Fixes a regression introduced by the tests added in #3189 getting regressed by the changes in #3188.
Fixes test regression due to React component change.

Fixed test regression from multi branch merge

---

static/js/components/search/EnabledSelectionRangeFilter.js

Fixes George's [comment here](https://github.com/mitodl/micromasters/pull/3188#discussion_r116864383) that I missed before merging
Adds missing `@flow`

Added missed flow flag

---

dashboard/signals.py

Fixes #3211 
Switches to the pre_delete signal for enrollments so that we have a non-`None` record id.
- Enroll for a course, verify you show up in learner search.
- Delete the enrollment in the django admin, verify you no longer show up in learner search.

Fixed errant enrollment delete signal (#3211)

---

static/js/components/Navbar.js
static/js/components/ProgramSelector.js
static/js/containers/LearnerPage_test.js

Fixes #3221, #3218
Fixes a few navigation issues for anonymous users
For a profile page (e.g. / earners/username):
- Verify that you still get the /dashboard link for the home link when logged in
- Verify if anonymous you get the / url for the home link
- Verify if anonymous you see styled and functional Log In and Sign Up buttons
(Optional)
(Optional)
(Optional)
(Optional)

Fixed anonymous user navigation issues (#3221, #3218)

---

selenium_tests/base.py
selenium_tests/basic_test.py

Fixes #3231
Adds a function to handle `StaleElementReferenceException` during clicks gracefully
N/A

Fix flaky selenium test

---

scripts/test/run_selenium_tests_dev.sh

None, related to #3250 
Fixes the script to run all tests instead of just one
N/A

Fix selenium tests dev script to run all tests

---

static/js/lib/api.js

no ticket, I was just messing around with this and I think it's a bit cleaner.
this rewrites `_fetchJSONWithCSRF` and `_fetchWithCSRF` in `lib/api.js` to be functions declared with the `async` keyword. this lets us, inside the function, write asynchronous code using promises in a straightforward, synchronous-looking syntax (via the `await` keyword).
Basically, instead of something like:
```js
fetch(url, options).then(response {
// response handling code
})
```
we can do something like:
```js
let response = await fetch(url, options);
// response handling code
```
which is nice!
the async/await stuff will all get transpiled away, so there should be no change in functionality. all tests should pass without modification.

rewrite API fetch wrappers to use async/await syntax

---

RELEASE.rst
mail/serializers.py
mail/serializers_test.py
micromasters/settings.py
selenium_tests/base.py
static/js/components/email/lib.js
static/js/components/email/lib_test.js
static/js/constants.js
static/js/flow/emailTypes.js
static/js/lib/api.js
static/js/test_constants.js

Release 0.60.2

---

static/js/components/LearnerSearch.js
static/js/components/Loader.js
static/js/components/Loader_test.js
static/js/containers/LearnerSearchPage_test.js

fixes https://github.com/mitodl/micromasters/issues/3060
- Added a spinner on the learners search table.
- go to search table and try to refresh.
@pdpinch

Added loader to learners search page

---

.travis.yml
README.md
RELEASE.rst
docker-compose.yml
micromasters/settings.py
scripts/envs.sh
scripts/test/run_selenium_tests.sh
scripts/test/run_snapshot_dashboard_states.sh
selenium_tests/base.py
selenium_tests/basic_test.py
selenium_tests/management/commands/snapshot_dashboard_states.py
webpack_dev_server.sh

Release 0.62.0

---

backends/edxorg.py

Fix #1375
Uses `EdxApi` to get user data.
Should be able to login successfully.

Use UserInfo in edx_api to get user data

---

exams/pearson/audit.py

Fixes #3296 
Monkey patches `gnupg` so that it doesn't utf-8 encode the binary data. Note there aren't any tests around this because I couldn't find a way to reliably execute `gpg --decrypt` directly under python, even using `gnupg`.
- Create a zip file in your project root: `echo "test" > test.txt && zip archive.zip test.txt`
- In a shell:
```python
from exams.pearson.audit import ExamDataAuditor
auditor = ExamDataAuditor()
auditor.configure() # this will likely raise an ImproperlyConfigred error, ignore it
auditor.encrypt('archive.zip', 'archive.zip.gpg`)
```
- Back in bash shell: `gpg --output archive2.zip --decrypt archive.zip.gpg`
- Verify the file is a valid zip archive: `zip -l archive2.zip`
- Unzip and verify the integrity of the text file contents

Fixed encoding issue for binary audit files

---

RELEASE.rst
backends/edxorg.py
dashboard/utils.py
exams/api.py
exams/api_test.py
exams/models.py
exams/pearson/audit.py
micromasters/settings.py
selenium_tests/base.py
selenium_tests/management/commands/snapshot_dashboard_states.py

Release 0.62.1

---

dashboard/tasks_test.py
grades/tasks.py
grades/tasks_test.py
micromasters/celery.py
micromasters/settings.py
pytest.ini
requirements.in
requirements.txt

Fix #2696
Upgrade celery to 0.4.2
No tests should fail.

Upgrade to Celery 4.0

---

Dockerfile
backends/utils_test.py
dashboard/views_test.py
requirements.txt

N/A
upgrades some requirements and fixes tests broken by such upgrade.
Tests should just pass in Travis

Upgraded requirements and fixed some tests

---

README.md

Fixes #3287 
Fixes #3288 
Updates the README for selenium test changes and other minor things
Read the README

Update the README for changes in selenium tests

---

static/js/components/ProgressWidget.js
static/js/components/dashboard/CourseRow.js
static/scss/_variables.scss
static/scss/dashboard/course-progress-message.scss
static/scss/dashboard/course-progress.scss
static/scss/dashboard/course-row.scss
static/scss/dashboard/course-status-messages.scss
static/scss/dashboard/dashboard.scss
static/scss/dashboard/grades.scss
static/scss/progress-widget.scss

#3172 
Tweaks some of the margins, font sizes and colors for the Course card layout redesign.
See that the css is valid, and that the styles look inline with the mocks in the original issues (which are linked to from #3172.

Layout and style tweaks to the course card layout

---

static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/factories/dashboard.js

fixes https://github.com/mitodl/micromasters/issues/3263
- calculates regular prices for course and show it in coupon message
create coupon and bind it with user, then see the message on dashboard
@pdpinch

Fixed message for course-level coupon

---

financialaid/templates/review_financial_aid.html
scripts/test/run_selenium_tests_dev.sh
selenium_tests/base.py
selenium_tests/basic_test.py

Fixes #2675 
Adds a selenium test for the financial aid review page
N/A

Added selenium test for financial aid review page

---

static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/scss/dashboard/dashboard.scss

Fix #3308
Add a message to the 'Personal Course Pricing' card.
Go through all the states of the personal course price calculation and make sure the message is there and is styled properly.

Add No Calls massage to FA card

---

static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/factories/dashboard.js

Reverts #3281 
Reverts course message fix PR. The fix is incomplete and we need to do a release before #3345 is ready to merge.

Revert "Fixed message for course-level coupon (#3281)"

---

cms/factories.py
cms/serializers_test.py
cms/templates/cms/program_page.html
selenium_tests/base.py
selenium_tests/basic_test.py
static/js/components/CourseListItemWithPopover.js
ui/views_test.py

Fixes #3068 
Adds a selenium test for the program page, refactors ProgramPageFactory
N/A

Added selenium test for program page, refactored ProgramPageFactory

---

static/js/components/dashboard/FinancialAidCard.js

fixes https://github.com/mitodl/micromasters/issues/3359
updates mailing address
go to `Personal Course Pricing card` and see the mailing address

Updated the mailing address

---

static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/OrderSummaryPage.js
static/js/factories/dashboard.js
static/js/flow/couponTypes.js
static/js/lib/coupon.js
static/js/lib/coupon_test.js

Fixes #3263 
Fixes coupon course message bugs
Run `./scripts/test/run_snapshot_dashboard_states.sh --match coupon` on `master` and this branch, and compare the output. The program messages should be correct in the branch for this PR

Fix course coupon program messages

---

RELEASE.rst
micromasters/settings.py
selenium_tests/base.py
selenium_tests/basic_test.py
selenium_tests/management/commands/snapshot_dashboard_states.py
selenium_tests/redirect_test.py
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/OrderSummaryPage.js
static/js/factories/dashboard.js
static/js/flow/couponTypes.js
static/js/lib/coupon.js
static/js/lib/coupon_test.js
static/js/lib/location_test.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

Release 0.65.0

---

selenium_tests/basic_test.py

None
Disables a test temporarily
N/A

Disable selenium test with intermittent failures

---

RELEASE.rst
micromasters/settings.py
selenium_tests/basic_test.py

Release 0.66.0

---

micromasters/settings.py
micromasters/tests/test_settings.py
requirements.in
requirements.txt

Fixes #3384 
Removes code which uses yaml files for configuration settings. This functionality is unused currently and there are no plans for it in the future.
No changes should be seen

Remove fallback config code

---

grades/management/commands/check_final_grade_freeze_status.py
grades/management/commands/complete_course_run_freeze.py

fixes #3394
Fixes management commands that try to restore a celery task
Ask me

Fixed management commands effected by celery upgrade

---

static/js/actions/index.js
static/js/components/ErrorMessage_test.js
static/js/components/Learner.js
static/js/components/StaffLearnerInfoCard.js
static/js/components/StaffLearnerInfoCard_test.js
static/js/containers/LearnerPage.js
static/js/containers/LearnerPage_test.js
static/js/reducers/util.js

fixes https://github.com/mitodl/micromasters/issues/2862
Show sum of calculated price that learner will pay to his profile.
Only staff can view this.
login as staff and view a learners profile

Displayed course price in staff view of learner's profile page

---

RELEASE.rst
js_test.sh
micromasters/envs.py
micromasters/envs_test.py
micromasters/settings.py
micromasters/tests/test_settings.py
package.json
static/js/components/ErrorMessage_test.js
static/js/components/Learner.js
static/js/components/StaffLearnerInfoCard.js
static/js/components/StaffLearnerInfoCard_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/LearnerPage.js
static/js/containers/LearnerPage_test.js
static/js/factories/dashboard.js
static/js/reducers/util.js
yarn.lock

Release 0.67.1

---

static/scss/_button.scss
static/scss/_variables.scss
static/scss/homepage.scss
static/scss/navbar.scss
static/scss/program-page.scss

This is a small PR that fixes a few fonts, colors, and spacing issues on the marketing site.
Tightens up the size of the navbar, and makes the tabs a bit less tall. The Login and Signup buttons are slightly smaller. Changes the font size for the main paragraphs to be 1 px smaller. Changes the header color in the gray boxes on the program pages (ex. "Courses") from red to dark gray. Changes the link color slightly, as it was too bright. Changed the gray box background to a slightly lighter gray color.

Some style tweaks on the marketing site 

---

RELEASE.rst
micromasters/settings.py
static/js/components/email/EmailCompositionDialog.js
static/js/containers/AutomaticEmailPage_test.js
static/js/containers/DashboardPage_test.js
static/js/global_init.js
static/js/util/integration_test_helper.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/homepage.scss
static/scss/navbar.scss
static/scss/program-page.scss

Release 0.67.2

---

RELEASE.rst
micromasters/settings.py
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/components/ErrorMessage_test.js
static/js/components/PersonalTab_test.js
static/js/containers/App_test.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/LearnerPage_test.js
static/js/containers/ProfilePage_test.js
static/js/flow/profileTypes.js
static/js/lib/location.js
static/js/lib/location_test.js
static/js/util/ProfileFormFields.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/test_utils.js
ui/views.py
yarn.lock

Release 0.68.1

---

RELEASE.rst
micromasters/settings.py
static/js/components/CouponNotificationDialog_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/courses/GradeDetailPopup.js
static/js/components/dashboard/courses/GradeDetailPopup_test.js
static/js/components/dashboard/courses/Grades.js
static/js/components/dashboard/courses/Grades_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerPage.js
static/js/containers/LearnerPage_test.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js
static/js/lib/grades_test.js
static/js/test_constants.js
static/scss/dashboard/grades.scss

Release 0.68.2

---

.eslintrc
RELEASE.rst
dashboard/api.py
dashboard/api_test.py
micromasters/settings.py
static/js/components/CourseEnrollmentDialog.js
static/js/components/CourseEnrollmentDialog_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/entry/zendesk_widget.js

Release 0.68.3

---

RELEASE.rst
cms/migrations/0004_create_homepage.py
cms/migrations/0006_change_homepage_title.py
grades/factories.py
grades/management/commands/adjust_exam_grades_from_csv.py
grades/models.py
grades/models_test.py
micromasters/settings.py
static/js/components/search/WithSearchkitManager.js

Release 0.69.0

---

courses/factories.py
dashboard/api_edx_cache_test.py
dashboard/api_test.py
dashboard/factories.py
dashboard/factories_test.py
dashboard/serializers_test.py
dashboard/tasks_test.py
dashboard/views_test.py
ecommerce/api_test.py
mail/views_test.py

No ticket
Changes up some factory definitions and usages to follow more intuitive patterns and take better advantage of factory-boy features
No need for manual testing

Refactored various factory classes and usages

---

requirements.in
requirements.txt

N/A
Upgrades requirement for jango-server-status and some other dependencies
the server status endpoint should return meaningful statuses

Upgraded requirement for server status

---

RELEASE.rst
dashboard/api_edx_cache.py
dashboard/tasks.py
dashboard/tasks_test.py
dashboard/views.py
ecommerce/api.py
micromasters/settings.py
profiles/api.py
profiles/api_test.py
requirements.in
requirements.txt
selenium_tests/data_util.py
selenium_tests/management/commands/snapshot_dashboard_states.py

Release 0.70.0

---

hot-reload-dev-server.js

None
Fixes hot reloading, at least for CSS styles
Restart the webpack dev server, then go to `general-styles.scss` and change something significant related to `body`. After a few seconds the change should show up in your browser without requiring a browser refresh.

Fix CORS issue with hot reloading

---

config/nginx.conf
config/nginx.conf.erb

[Issue#3453](https://github.com/mitodl/micromasters/issues/3453)
Added nginx configs to increase header and body buffer size to address issue linked above.
Try to preview work in cms with decent amount of information in local dev environment. Zendesk ticket attached to issue has a screenshot of when the issue was encountered.
(Optional)
(Optional)
(Optional)
(Optional)

Added nginx configs to increase header and body buffer size

---

static/js/components/Learner.js
static/js/components/StaffLearnerInfoCard.js
static/js/components/StaffLearnerInfoCard_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/courses/ProgressMessage.js
static/js/components/dashboard/courses/ProgressMessage_test.js
static/js/components/dashboard/courses/util.js
static/js/components/dashboard/courses/util_test.js
static/js/containers/DashboardPage.js
static/scss/dashboard/course-progress-message.scss

closes #3355 
this is a pretty simple change the adapts the `CourseListCard` component for the Learner page by adding a `showStaffView` prop that hides certain pieces of information, changes the title, etc.
take a look at the learner page, and make sure you see some details about programs you are enrolled in. you will need to be a staff user for the card to show up.

redesign learner page

---

ecommerce/api.py
ecommerce/api_test.py

Fix #3472 
Let user go through the payment for a course run that was already payed in the past, when the user has the right amount of failed exam attempts.
Need to get to the state where you have paid for a courserun and have 2 failed exam attempts. Make sure the 2 exam grades are for 2 different exam runs. Then the course status message will ask you to pay and show a PAY button. You should be able to click CONTINUE on the Order Summary page and to actual payment details page.
Login as a learner enrolled in FA program like 'Digital Learning'. Run alter_data command for your user to have passed a course run:
`./manage.py alter_data set_past_run_to_passed --username username --course-title 'Digital Learning 100'`
Then in the django shell set up the exam:
``` …
```

Purchase course run again

---

grades/admin.py

No ticket
Adds admin view for MM certificates
Visit `http://<micromasters_url>/admin/grades/micromasterscoursecertificate/`

Added MicromastersCourseCertificate to django admin

---

RELEASE.rst
grades/api.py
grades/api_test.py
grades/management/commands/check_final_grade_freeze_status.py
grades/tasks.py
grades/tasks_test.py
micromasters/settings.py
static/js/components/dashboard/courses/ProgressMessage.js
static/js/components/dashboard/courses/ProgressMessage_test.js

Release 0.73.0

---

grades/management/commands/check_final_grade_freeze_status.py
grades/tasks.py
grades/tasks_test.py

Fix #3505
Delete failed users when course run grading status is complete
Run the task when there are failed users and when there are not, and the course run grading status is set to complete.

Delete failed users when course run grading status is complete

---

RELEASE.rst
grades/management/commands/check_final_grade_freeze_status.py
grades/tasks.py
grades/tasks_test.py
micromasters/settings.py

Release 0.73.1

---

RELEASE.rst
ecommerce/models.py
ecommerce/models_test.py
micromasters/settings.py

Release 0.74.0

---

requirements.in
requirements.txt

Part of #3475
Updates open-discussions-client, adding add_subscriber, add_contributor, add_moderator 
Nothing in this PR

Updated open-discussions-client

---

Dockerfile-node
discussions/management/commands/backfill_discussion_users.py
discussions/tasks.py
discussions/tasks_test.py
js_test.sh
package.json
requirements.in
requirements.txt
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerSearchPage_test.js
static/js/global_init.js
test_requirements.txt
travis/Dockerfile-travis-watch
travis/Dockerfile-travis-watch-build

N/A
Upgrades yarn and node to the latest version
Everything should keep working as usual
NOTE: I already updated the image on docker hub

Upgraded yarn and Node to the latest version

---

RELEASE.rst
micromasters/settings.py
static/js/components/DiscussionCard.js
static/js/components/DiscussionCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/flow/declarations.js
static/js/global_init.js
static/scss/discussion-card.scss
static/scss/layout.scss
ui/views.py
ui/views_test.py

Release 0.75.2

---

search/tasks.py

Fixes #3568 
Changes a log statement to debug

Changed noisy log.error to log.debug

---

static/scss/certificate.scss

#3565 
This PR makes the "certificate stamps" div in the Program certificate always be at the bottom of the certificate. I also tightened up some of the vertical margins so the certificate is less tall, especially for ones that have many signatories.
See that the layout looks correct, and the css is valid.

Layout changes to the MM Program Certificate 

---

discussions/tasks.py

Related to #3568 
Changes log.error to log.debug
I'm not sure it's worth it for this PR

Change log.error to log.debug for USER_SYNC feature flag

---

static/js/lib/discussions.js
static/js/lib/discussions_test.js

Fixes #3603 
Fixes an issue with API redirect under CORS

Fixed CORS redirect issue with discussions API (#3603)

---

package.json
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/FinancialAidCard.js
static/js/containers/DashboardPage.js
static/js/containers/OrderSummaryPage.js
static/js/dashboard_routes.js
static/js/lib/coupon.js
static/js/lib/pearson.js
static/js/util/test_utils.js
yarn.lock

None
Upgrades eslint configuration, fixes related warnings
N/A

Upgrade eslint configuration and fix throw literal warnings

---

static/js/components/DiscussionCard.js
static/js/components/LearnerSearch.js
static/scss/discussion-card.scss
static/scss/search-page.scss

closes #3597
This fixes a UI bug where the button labels for creating a New Email or a New channel were being clipped at smaller screen widths. I had to tighten up the margins and I also changed the button labels to be shorter. ("Email Selected" and "New Channel").
I also tweaked the style of the Recent Posts card on the dashboard. And made the card title for Recent Posts consistent with the guidelines for card titles in Material UI.
See that the UI does not break.

some css tweaks in mm

---

static/js/entry/zendesk_widget.js

fixes https://github.com/mitodl/micromasters/issues/3602
it updates css select on `zendesk_widget.js`, it appears that zendesk changed style on their end, to match with it i need to change the selector.
login to your MM and see console (Probably on dashboard)
@pdpinch

Fixed failed to execute getComputedStyle on Window error on zendesk script

---

static/scss/certificate.scss

closes #3566
This adds css media queries to make the program certificates printable.
You will need to have a program certificate. Go to the certificate and print it. See that the printed version fits on the page and is laid out correctly.

Print formatting for program certificates

---

RELEASE.rst
micromasters/settings.py
yarn.lock

Release 0.78.1

---

grades/README.md

N/A
Doc for freezing final grades
Probably try to follow the doc and see if you are successful in freezing some grades for a course run.

Doc about how to freeze final grades

---

requirements.in
requirements.txt

None
Removes a dependency that's not needed. The PR #3657 uses jsonpatch, not deepdiff
Lint should pass

Remove accidentally committed dependency

---

Procfile
RELEASE.rst
app.json
discussions/api.py
discussions/api_test.py
micromasters/settings.py

Release 0.79.1

---

package.json
selenium_tests/redirect_test.py
yarn.lock

None
Upgrade redux-hammock to a new version which cuts down on bundle size a little bit
https://media.giphy.com/media/atHI7U3aP3kl2/giphy.gif

Upgrade redux-hammock

---

RELEASE.rst
config/nginx.conf
dashboard/api.py
dashboard/api_test.py
dashboard/tasks.py
dashboard/tasks_test.py
discussions/tasks.py
docker-compose.travis.yml
micromasters/celery.py
micromasters/settings.py
requirements.in
requirements.txt
static/js/components/LearnerSearch.js
static/js/components/channels/ChannelCreateDialog_test.js
static/js/components/email/lib.js
static/js/components/search/ModifiedSelectedFilter.js
static/js/containers/LearnerSearchPage_test.js

Release 0.79.2

---

grades/api.py
grades/api_test.py

Fix #3648
Use current grades and calculating final grade.

get final grade from current grades

---

app.json
docker-compose.yml

Related to #3685 
Makes log level a required environment variable and sets the default to INFO
N/A

Make MICROMASTERS_LOG_LEVEL a required variable and set default to INFO

---

dashboard/tasks.py

Fixes #3659 
Reduces rate of batch refresh by half
N/A

Reduce rate of edX cache refresh requests

---

RELEASE.rst
app.json
dashboard/tasks.py
dashboard/tasks_test.py
discussions/tasks.py
discussions/tasks_test.py
docker-compose.yml
grades/tasks.py
grades/tasks_pytest_test.py
micromasters/locks.py
micromasters/locks_test.py
micromasters/settings.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/courses/StatusMessages.js
static/js/components/dashboard/courses/StatusMessages_test.js
static/js/components/dashboard/courses/util.js
static/js/components/dashboard/courses/util_test.js
static/js/entry/zendesk_widget.js

Release 0.80.0

---

RELEASE.rst
dashboard/tasks.py
micromasters/settings.py

Release 0.80.1

---

static/scss/profile.scss

closes #3697 
This fixes a layout issue with radio buttons on the setting page in micromasters
See that it is no longer broken in Chrome, Safari, Firefox

Fixes layout bug with radio buttons

---

search/tasks.py
search/tasks_test.py

Fix #3655
Fixes the post indexing code to log errors and complete all post indexing work.
N/A

Log failed send_automatic_email and update_percolate_memberships

---

RELEASE.rst
micromasters/settings.py
search/tasks.py
search/tasks_test.py
static/scss/profile.scss

Release 0.81.0

---

RELEASE.rst
discussions/api.py
discussions/api_test.py
discussions/exceptions.py
discussions/views.py
discussions/views_test.py
micromasters/settings.py

Release 0.82.0

---

RELEASE.rst
backends/views.py
backends/views_test.py
dashboard/api.py
dashboard/api_test.py
micromasters/settings.py

Release 0.82.1

---

requirements.in
requirements.txt

fixes #3709 
stop causing these spurious Sentry issues:
fixes MICROMASTERS-1C0
fixes MICROMASTERS-1CA
fixes MICROMASTERS-1C7
fixes MICROMASTERS-1AS
fixes MICROMASTERS-1C9
fixes MICROMASTERS-1AV
fixes MICROMASTERS-1C6
fixes MICROMASTERS-1C3
fixes MICROMASTERS-1C4
fixes MICROMASTERS-1C3
fixes MICROMASTERS-1C2
do tests pass?
This library should probably be updated anywhere else we are using it.

bump psycopg to 2.7.2

---

grades/README.md

None
A user did not get a final grade when the we froze the grades.
Adding some code snippets to help create a final grade for a user.
N/A

Grades: Add useful code snippets to README

---

cms/models.py

None
Fixes a missing migration error caused by the changing of the help text

Use old year in help text

---

cms/templates/cms/home_page.html
static/scss/homepage.scss

Closes #3753
This changes the layout of the "More Programs Coming Soon" on the Micromasters home page.
See that the functionality works and that it matches the design below:

Change layout of "More Programs Coming Soon" on Micromasters home page

---

micromasters/settings.py

Fix #2223
Schedule the freezing of all freezable course runs to run 3 days a week.
N/A

Schedule freeze grades task

---

static/scss/dashboard/dashboard.scss
static/scss/page-layout.scss

Now that we have more actual content on the dashboard, notably the Discussions card, I think we need a slightly wider page width for the double column div. I have increased the max width from 1000px to 1200px.
See that is does not break.

Larger max width on dashboard

---

micromasters/settings.py

Fix #2223 
(Required)
(Required)

Run freeze grades task every day

---

app.json
micromasters/settings.py

Fixes #3765 
Paramiko will only report critical errors (which there should be none of) by default.
Not really possible to test the code itself, verify the app can start without error and that the logging config looks good.

Updating log config to quiet noncritical errors

---

requirements.in
requirements.txt

Fixes #3814 
Installs `certifi` to manage SSL certificates
There's no way to manually test this without merging it first

Install certifi

---

search/indexing_api.py
search/indexing_api_test.py

None
Fixes a missing field in the mapping which was preventing reindexing
Remove the field added in this PR from the mapping and rerun the test. The test will fail

Fix missing field

---

search/api.py
search/api_test.py
search/connection.py
search/indexing_api.py
search/indexing_api_test.py
search/tasks_test.py

Part of #3748 
Removes legacy code supporting Elasticsearch 2.x
View the learner search page, everything should look fine

Remove Elasticsearch 2.x code

---

backends/views.py
cms/factories.py
cms/models.py
courses/models.py
dashboard/models.py
dashboard/permissions.py
dashboard/permissions_test.py
discussions/utils.py
ecommerce/models.py
exams/models.py
financialaid/models.py
financialaid/views.py
grades/models.py
mail/models.py
micromasters/serializers.py
profiles/api.py
profiles/api_test.py
profiles/models.py
profiles/permissions.py
profiles/permissions_test.py
profiles/util.py
profiles/views.py
roles/models.py
seed_data/management/commands/attach_avatars.py
tox.ini
ui/decorators.py
ui/views.py

Part of #3746 
Fixes some deprecation warnings in preparation for the upgrade to Django 2.0

Fix some deprecation warnings

---

backends/pipeline_api.py
backends/views_test.py
certificates/views_test.py
cms/models.py
courses/views_test.py
dashboard/views_test.py
discussions/utils.py
discussions/views_test.py
ecommerce/views_test.py
exams/views_test.py
financialaid/permissions.py
financialaid/views.py
financialaid/views_pytest_test.py
financialaid/views_test.py
mail/permissions.py
mail/views_test.py
micromasters/urls.py
micromasters/urls_test.py
profiles/views_test.py
requirements.in
requirements.txt
roles/api.py
roles/permissions.py
roles/signals.py
roles/signals_test.py
search/permissions.py
search/views_test.py
ui/views.py
ui/views_test.py

Part of #3746 
Updates a couple minor libraries and references in our code

Update rolepermissions and social-auth-django-app

---

static/scss/toast.scss

#2473
This fixes an issue where the toast message was going off the screen in mobile.
See that the toast message no longer goes off the screen in mobile.

Fixes toast layout issue

---

profiles/serializers.py
profiles/util.py
profiles/views_test.py
requirements.in
requirements.txt

Part of #3746 
Updates django server status, django rest framework

Update django-server-status, django rest framework

---

ui/templates/footer.html

closes #3833 
this just adds a lil link to the TOS to the template we use to render the footer.
make sure it shows up! haha.

add link to the TOS to the footer

---

conftest.py
financialaid/views.py
micromasters/settings.py
requirements.in
requirements.txt

**Rebased**
Fixes #3746 
Upgrades to Django 2.0 and the latest version of Raven

Upgrade to Django 2.x, upgrade Raven

---

grades/tasks.py
grades/tasks_pytest_test.py
micromasters/settings.py

None
Set up hourly task to check if any CombinedFinalGrades need to be created.

Schedule task to create CombinedFinalGrades

---

Procfile
docker-compose.travis.yml
docker-compose.yml

N/A, see also mitodl/open-discussions#335
Fixes error output on the celery worker in our travis builds. Example: https://travis-ci.org/mitodl/micromasters/jobs/350367945
You should be able to run celery locally and should see no error output from the celery container in the python job.

Fix travis errors

---

static/js/components/CourseEnrollmentDialog.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/scss/dashboard/dashboard.scss

closes #3804 
changes a little bit of copy to be in line with the image (mainly trying to clarify how coupons interact with personalized pricing)
Make sure that the relevant UI elements are changed in-line with what is in the attached issue

fix coupon / personalized price copy

---

docker-compose.yml

None
Pins nginx, postgres and redis docker images
Some people will need to downgrade to postgres 9.6, which means removing the database and recreating it

Pin docker image versions

---

dashboard/utils.py

Fixes #3510 
- Change n+1 query into an inner SELECT clause
- Use SQL sum instead of Python sum
The dashboard API should be exactly the same as it is on master

Fix n+1 warnings on dashboard API

---

selenium_tests/basic_test.py
static/js/components/LearnerSearch.js
static/js/components/search/NestedAggregatingMenuFilter.js

Fixes #3854 
Fixes filtering of aggregation for country and birth country to show all results
Run the selenium test and add a breakpoint. View it in your browser and confirm that they're all there

Add back size parameter

---

selenium_tests/data_util.py

None
Adds social auth data to profiles so that the learner search page user chips work properly
Add a breakpoint to a learner search test (see bottom of `basic_test.py`) and view `localhost:7000/learners`. You should be able to mouseover the profiles and see the right user chip

Add social auth data for all fake users

---

selenium_tests/data_util.py
selenium_tests/management/commands/snapshot_dashboard_states.py

fixes https://github.com/mitodl/micromasters/issues/3934
it fixes selenium issues which are introduce after model changes.
run `./scripts/test/run_snapshot_dashboard_states.sh`
@pdpinch

Fix selenium issues

---

cms/templates/cms/program_page.html
ui/views_test.py

Fix #3949
If program does not have courses then show a different button to subscribe for mailing list.

If no courses show I'm insterested button

---

static/scss/program-page.scss

none
Makes the text brighter, and improves the padding in mobile for the text over the hero image on the program page
...

brighter font and better spacing in text over hero image

---

cms/templates/cms/program_page.html
static/scss/program-page.scss

none
Un-hides the "I'm interested" button on mobile
See that button displays on mobile

unhide interested button on mobile

---

grades/README.md

closes #3856 
documents the process for adjusting proctored exam grades
RTFM
If you have any thoughts on how to streamline or automate this process, please comment or open new issues.

add proctored exam grades to grades README

---

dashboard/api.py
seed_data/management/commands/alter_data.py
selenium_tests/management/commands/snapshot_dashboard_states.py

fixes https://github.com/mitodl/micromasters/issues/3327#
I marks user passed when he has past passed final grade but the upgrade deadline of that past course is passed
- Program must be final grade
- Course must have 3 runs
- Oldest run pass, marked complete and unpaid.
- old run fail and incomplete and unpaid.
- new run fail and incomplete and unpaid.
- Course upgrade deadline in the oldest run set to past.
- Course upgrade deadline in the old and new run set to null.
@pdpinch

When user has a passed run but upgrade deadline passed

---

static/scss/homepage.scss

Closes #4016
This PR centers the Signup and Login buttons on mobile
See that the buttons are centered as shown

centered sign up/login buttons

---

cms/templates/cms/program_page.html

Fix #4023
Update program page header

Update program page header

---

static/scss/program-page.scss

The header sizes for the program pages were slightly too large. This makes them slightly smaller.

A slight header font size change on the program pages

---

grades/tasks.py
grades/tasks_pytest_test.py

None
Fix the query that finds all users for course that don't have a certificate yet.
Make sure that a user can get multiple certificates for different courses.

Fix course certificate generation task

---

static/js/components/dashboard/FinancialAidCard.js

Fix #3994
Add missing space to the FinalcialAidCard.
You can do it manually through the dashboard or run the snapshot command: 
` scripts/test/run_snapshot_dashboard_states.sh --match 'finaid_docs-sent'`

Add space in FA Card

---

selenium_tests/management/commands/snapshot_learners_states.py

none
clarifies a comment
is the comment clearer now?
(Optional)

fix error in comment

---

backends/pipeline_api.py
backends/pipeline_api_test.py
micromasters/settings.py
ui/templates/verify_email.html
ui/urls.py
ui/views.py

Fix #4072
If user has not verified email on edX redirect to error page.
Try to register on MM without verifying your email on edX.

Check if email is verified before creating account

---

grades/README.md

#4036
adds some more detail to the shell commands for adjusting the proctored exam grades.
You can test this on CI or RC with a one-line csv file
I'd just like a second opinion on the copy-and-paste method. Is there a better way to do this?

update readme with details on how to adjust exam grades

---

courses/utils.py
dashboard/api.py
dashboard/api_test.py
static/js/components/dashboard/courses/GradeDetailPopup.js
static/js/components/dashboard/courses/GradeDetailPopup_test.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js

Fix #4078
Show semester year for a course run instead of course title.

Show semester year in GradeDetailPopup

---

dashboard/admin.py

None. 
- add search in program enrollments admin; 
- use the raw id for user in program enrollments admin instead of drop-down
go to admin/dashboard/programenrollment/
search on a username 
search on an e-mail address
add a programenrollment and set the user by id

improve program enrollments admin

---

selenium_tests/management/commands/snapshot_dashboard_states.py

None
Fixes error when running `scripts/test/run_snapshot_dashboard_states.sh`
Run `scripts/test/run_snapshot_dashboard_states.sh` and make sure there are no errors.

Fix attribute error when running exam states

---

requirements.in
requirements.txt

Ran [safety](https://pyup.io/) against the requirements.txt file and that reported vulnerabilities in three packages. Based on that input, updated package versions that have reported vulnerabilities.

Updated package versions that have reported vulnerabilities

---

cms/templates/cms/home_page.html

fixes https://github.com/mitodl/micromasters/issues/4144
- Updated video URL on home page
- Go to http://micromasters.odl.local:8079 and see video changed
@pdpinch

Changed the source of video on home page

---

grades/tasks.py

fixes https://github.com/mitodl/micromasters/issues/4140
Handles exception of certification task so that function can resume itself
Should log exceptions and `generate_course_certificates_for_fa_students` should not break
@pdpinch

Handle exception in certification creation process

---

selenium_tests/management/commands/snapshot_dashboard_states.py

Related to #4162
Add a state for missed payment deadline for course in progress.
Run `scripts/test/run_snapshot_dashboard_states.sh --match "missed_payment_for_exam"`

Dashboard state: Missed deadline for course in progress

---

dashboard/factories.py
dashboard/fixtures/current_grades.json
requirements.in
requirements.txt

Related to mitodl/edx-api-client#45
Update edx_api_client to 0.6.0
This will be tested on RC with the new Grades v1 API

Update edx_api_client to 0.6.0

---

requirements.in
requirements.txt

none
updates edx-apii-client, requests libraries
If you can log in with edX, it should be ok

upgrade requirements, including bumping edx-apl-client to 0.6.1

---

ecommerce/README.md

supporting docs for #4177 
Adds a README for ecommerce. At this point, it only contains a section on coupons. 
Try the steps for creating, applying and removing coupons.

add README with coupon docs

---

cms/templates/cms/home_page.html
static/images/micromasters_logo_on_programs.svg
static/images/micromasters_logo_programs.svg
static/scss/homepage.scss
ui/templates/background-images.css
ui/templates/footer.html

Fix #4221
Introducing updates described in the issue.
I had to create two new svg files for the header. The font is not identical, but that can be updated if we find the original font.
Make sure all the changes are there

Trademark updates

---

cms/templates/cms/home_page.html
static/js/components/Navbar.js
static/scss/homepage.scss
ui/templates/terms_of_service.html

Fix #4224
Makes more updates to the trademark described in the issue.
Make sure to test authenticated and unauthenticated dashboard pages, and the public homepage. You can find a link to the Terms of Service page in the footer.

Few more trademark updates

---

static/scss/grade_record.scss
ui/templates/grade_record.html

Fix #4229
Adds edX log to Program Record view.

Add edX logo to Program Record

---

requirements.in
requirements.txt

closes #4237
Upgrades django, requests and urllib3
Nothing should change

Upgrade Django and urllib3

---

static/scss/grade_record.scss

A small style fix
Adds the correct color to complete button in the program record .
Take a look at the program grades (View Program Record link in the Progress card). When the program is completed it should be colored green.
Enroll a user in a program, and create a program certificate:
```MicromastersProgramCertificate.objects.create(user=user, program=program)```

Add Completed program style

---

certificates/views.py
dashboard/utils.py
dashboard/utils_test.py
ui/templates/grade_record.html

#4208
Convert grade to letter grade.

Add a letter grade to Program Grades

---

certificates/views.py
static/js/actions/share_grades_dialog.js
static/js/containers/App.js
static/js/containers/CopyLinkDialog.js
static/js/containers/CopyLinkDialog_test.js
static/js/entry/public.js
static/js/reducers/index.js
static/js/reducers/share_grades_dialog.js
static/js/store/configureStore.js
static/scss/grade_record.scss
ui/templates/grade_record.html

Fix #4209
Adds Share button above the transcript that opens a dialog with a copy button.

Share Program Records Link Dialog

---

docker-compose.yml

NA
fix BdbQuit exception while using pdb locally.
Put `import pdb; pdb.set_trace()` in code and run `docker attach micromasters_web_1` to debug code.

update docker compose file for local debugging

---

docs/rfcs/0000-template.md

None
Adds a docs directory and a template for RFCs. 
Check out the [rendered template](https://github.com/mitodl/micromasters/blob/b8880addc9976ac5a9c66f061ebe6d215fb4e27a/docs/rfcs/0000-template.md)
We just started using this approach on [open-discussions](https://github.com/mitodl/open-discussions/tree/master/docs/rfcs)

add RFC template

---

requirements.in
requirements.txt

none
upgrade django to 2.1.7
Do tests pass?

upgrade django to 2.1.7

---

docs/rfcs/0001-congratulations-letter-to-dashboard.md

RFC for #4247 
**Easy on eyes:** [RFC for congratulation letter](https://github.com/mitodl/micromasters/blob/176868ccec14470766e13cbeb3f5b3ce066ee084/docs/rfcs/0001-congratulations-letter-to-dashboard.md)

rfc for congratulation letter on dashboard

---

static/scss/program-page.scss

#4266 
Fix font size of text in tables.
**Older Version:**
**Newer Version:**

fix css on program page

---

discussions/api.py
discussions/api_test.py

Fixes #4197 
Add `order_by` clause in query.
Test should pass.

prioritize the syncing of channel memberships

---

static/scss/letter.scss
ui/templates/program_letter.html

Fixes #4278 
Remove extra logo, fix styles for printing
CMS user should be able to upload logo through CMS.

remove extra mit logo

---

grades/api.py

#4279 
Change log level from error to info

change log level form error to info

---

ui/templates/program_letter.html

fixes #4290
adds the word "program" to the end of the letter 
View a commendation letter (an existing one should be adequate) 
I need to generate a screenshot for SCM's review before this is merged.

add 'program' after 'MITx MicroMasters' in footer

---

static/js/containers/SendGradesDialog.js

N/A
Fix formatting for SendGradesDialog.js

Fix formatting for SendGradesDialog.js

---

requirements.in
requirements.txt

Fixes #4308 
Upgrade version of urllib3
Test should pass.

upgrade urllib3

---

courses/views.py
courses/views_test.py

#4311 
Remove the authentication requirements for the courseruns endpoint.
Manually navigate to the endpoint.

Remove authentication from courseruns endpoint, and update test

---

package.json
yarn.lock

Fixes #4283 
Update code to use our forked version.

use fork of iso-3166-2.js for Kosovo country

---

Procfile

N/A
Enables the workers to use pgbouncer
N/A, will verify in environments

Let the workers use pgbouncer too

---

mail/urls.py
requirements.in
requirements.txt

N/A
Periodic bump of dependency
App should run and still be functional

Bumped DRF version

---

requirements.in
requirements.txt

Upgrde django to 2.1.10

---

static/scss/navbar.scss

Fix #4321
Make the selected program visible when the dropdown menu is open.

Add color to select-placeholder

---

.flowconfig
package.json
yarn.lock

Fixing security alert
Update `nyc` package that in turn updates `handlebars`

Update handlebars to 4.1.2

---

micromasters/settings.py

Need several runs of the task in order to mark the process as `complete`
Update the celery beat schedule to run freeze grades 4 times a night.
Make  sure that the task gets scheduled.

Freeze grades scheduling update

---

courses/serializers.py
courses/serializers_test.py
static/js/components/CourseListItemWithPopover.js
static/js/flow/programTypes.js

Fix #4385
Add tags to courses on the ProgramPage
Create electives for the program you are testing with, and go to the program page to check the courses are marked correctly.

Add elective tags to program page courses

---

runtime.txt

Updated python version in runtime.txt

---

static/js/entry/public.js

Fix #4422
Fixes that behavior where referenced question stays closed.
Create an FAQ page for your program. 
When the user opens a link to a question, the page scrolls to display the question, the question should be open.

Fix bug in anchor tag opening collapsed question

---

dashboard/views_test.py

Fixes #4439 
Fix flaky test.
Build should pass.

fix flaky test

---

cms/models.py
cms/templates/cms/home_page.html
static/scss/homepage.scss

Related to #4429. Modifications described in https://docs.google.com/document/d/1xYmIWqdISNZ74DNfS8ndLelHnsFQeYmBOlxBLP4Swfs/edit?usp=sharing
Modifies the home page to include information about the alumni benefits.
Go to the home page and check that the copy updates are correct and the links to "Benefits" are working.
REQUIREMENT: should have completed all the steps in PR #4432 to setup and publish a "Benefits" page.

HomePage: include information about the alumni benefits

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/config_change_template.md
.github/ISSUE_TEMPLATE/feature_template.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/PULL_REQUEST_TEMPLATE/rfc_template.md
.github/pull_request_template.md

none
Adds issue and PR templates based on our current practices in MIT xPRO
I think we have to merge it and then try creating an issue or a PR.

add github templates copied from mitxpro

---

static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js

Fixes #4431 
Replace fax no with link to DocuSign
Swap columns on the dashboard.
- Enroll in an FA program
- View the dashboard and click "Pay Now"
- Enter an income and country. The income has to be low enough for the country to require documentation.

Replace fax no with link to DocuSign

---

requirements.in
requirements.txt

Fixes #4470 
Update the library so that newer phone numbers are recognized
Run this against the input valid in sentry, it should output `True`:
```python
import phonenumbers
number = "<PHONE_NAME_STR>"
p = phonenumbers.parse(number)
phonenumbers.is_valid_number(p)
```

Update phonenumbers lib

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
grades/api.py
grades/api_test.py
grades/management/commands/generate_program_letter.py
grades/signals.py
grades/signals_test.py
static/js/components/ProgressWidget.js

Fix  #4421
Enable commendation letters for learners in FA programs
Enroll your learner in both FA and non-FA program, get all courses passed (with certificates for FA program). Check the dashboard to see if the progress widget has a link to the letter.
If it an FA program the learner must have a program certificate.

Commendation Letter for FA program

---

static/scss/letter.scss

- NA: ~~Mobile width screenshots~~
None (yet) 
Decreases the padding so we can fit 3 signatures on the letter. 
Create a letter for yourself, with three signatures.

decrease the padding to allow for 3 signatures

---

static/scss/grade_record.scss
ui/templates/grade_record.html

Related to #4485 
Fix a bug in program records electives tags, and adjust the style a bit.
View a Program record for a learner in a program with electives

Fixing the Grade record view

---

profiles/management/commands/retire_users.py
requirements.in
requirements.txt

Fix https://github.com/mitodl/micromasters/network/alert/requirements.txt/Django/open
Upgrades django to 2.2.9, wagtail to 2.5, and jsonfield

Upgrade Django, Wagtail, and jsonfield

---

static/js/components/CourseListItemWithPopover.js
static/scss/program-page.scss

Fix style bug on program page.
Adds column layout to the program page content with courses. Also fixes the course info popover.
Go to program page, the program courses should be to the right side of the content about the program. Test the course popover.

Fix program page styles

---

.flowconfig
package.json
ui/templates/base.html
ui/views_test.py
webpack.config.dev.js
webpack.config.prod.js
yarn.lock

Update webpack to v4

---

static/js/containers/SendGradesDialog.js
static/scss/dashboard/dashboard.scss
static/scss/general-styles.scss

related to mateial-ui upgrade
Fix styles for the send grades dialog

Fix styles for share and send grades dialogs

---

grades/admin.py

Fix #4493
Add raw_id_field to FinalGradeAdmin and ProctoredExamGradeAdmin.
In django admin try to modify FinalGrade and ProctoredExamGrade instances.

Fix FinalGradeAdmin timeout error

---

static/scss/letter.scss
ui/templates/program_letter.html

Fix #4507
Adjust styles for the program letter
View an existing program letter, and try to print it.

Program letter: print on one page

---

static/js/containers/SendGradesDialog.js
static/js/util/util.js

Fix #4336
Sort partner schools for sending grades. MIT should come first.

SendGrades: sort partner schools, MIT comes first

---

Dockerfile
docker-compose.yml

N/A
Fixes travis tests by updating the postgres version, and updates docker-compose setup similar to https://github.com/mitodl/mitxpro/commit/5b6b4e790f505683e799c84e9b36cbd5061911ec
Website should load fine, tests should pass

Upgrade postgres version in docker-compose

---

cms/templates/cms/course_team_tab_page.html
static/scss/course-team.scss

https://trello.com/c/OZCcoiTR/25-course-team-styling-fixes
Fix styling on the course team tab page.
Goto any course team tab page under the program page.

course team styling fix

---

static/scss/_button.scss

None
Fix styles for login and signup buttons on the home page
Find all the button that have the styles that are modified in this PR and make sure the look good.
Before
After
┆Issue is synchronized with this [Trello card](https://trello.com/c/JZ8HzKVb) by [Unito](https://www.unito.io/learn-more)

Home page: login button fix

---

runtime.txt

None
Updates the heroku runtime Python 3.7. The local instance is already at 3.7 and tests are running against that version, so in general we should be safe with this upgrade.
Merge, then check that nothing broke on RC

Update heroku Python runtime to 3.7

---

requirements.in
requirements.txt

[Pillow upgrade](https://trello.com/c/t9ZkhJxN/19-pillow-upgrade)
[Wagtail upgrade](https://trello.com/c/jDiPP3FO/34-upgrade-wagtail-to-27-or-higher)
Upgrades Pillow to `6.2.2` and Wagtail to `2.8`.
Everything should work, nothing should break.

Bump wagtail and Pillow

---

docker-compose.yml

Fixes #4565 
Upgrades the docker redis instance to 5.x, to match our other projects
Run `docker-compose up`. You should see the `discussions-sync-memberships-every-minute` task run successfully in the console output

Upgrade to latest redis

---

cms/templates/cms/home_page.html

#4476 / https://trello.com/c/QDQ0zPEH/43-home-page-title
Add registered trademark to the home page title, header
Just visit the home page.
(Optional)
(Optional)
(Optional)

Add registered trademark to home page title

---

static/js/entry/zendesk_widget.js

#4561 , https://trello.com/c/z0Ygs8sC/343-update-zendesk-widget
fixes #4561, Update ZenDesk widget script
Just see if the widget is loading

update zendesk widget

---

ui/templates/footer.html

fixes: #4630 
Added a Accessibility link in footer.

Added accessiblity link

---

ecommerce/api.py
ecommerce/api_test.py
ecommerce/views.py
ecommerce/views_test.py
requirements.in
requirements.txt

#4631 
Send IP address to cybersource.
- Get the values of cybersource and put into the .env files of your local dev instance.
- Make a payment.
- Check the request for cybersource with user IP address in the console.

send ip address to cybersource

---

package.json
yarn.lock

NA
update serialize-javascript version to fix the security alert
Just build, verify the serialize-javascript version and check everything should be working fine

update serialize-javascript version to fix the security alert

---

README.md

None
Adding instruction on adding electives to a program
[README](https://github.com/mitodl/micromasters/blob/9009234f433721936e1accf32423eda8fd72e202/README.md)

Adding instruction on adding electives to a program

---

package.json
yarn.lock

fixes https://github.com/mitodl/micromasters/issues/4653
Adds the latest master branch's commit of iso-3166-2
On micromaster do the following steps:
1. Log in and go to /profile/personal
2. Under "Where are you currently living" set the Country to "Philippines" 
3. Open the drop-down for "State or Territory"
4. Search for state "Rizal", you will see "Rizal", while previously it was "Risal".
Before:
After:

upading iso-3166-2 branch to latest master branch's commit

---

cms/templates/cms/home_page.html

No issue, but this was noted in [ZenDesk #79859](https://odl.zendesk.com/agent/tickets/79859)
Fixes an incomplete sentence.
Take a look at the home page.

Fix an incomplete sentence on the home page

---

cms/serializers.py
cms/serializers_test.py
courses/serializers.py
courses/serializers_test.py
static/js/components/CourseListItemWithPopover.js
static/js/components/CourseListWithPopover.js
static/js/entry/public.js
static/js/flow/programTypes.js
static/scss/dashboard/course-row.scss
static/scss/program-page.scss

Fixes #4660 
This PR updated the design for elective courses on the program details page. Added required elective courses count details.
Go to micromasters home page and select a program. See if the design matches the one provided in the associated ticket. 
**New desktop screenshot:**
**Old desktop screenshot:**
**New mobile screenshot:**
**Old mobile screenshot:**

Added design changes for elective labels

---

exams/management/commands/populate_edx_exam_coupons.py

Fix #4669 
Update populate_exam_coupons command to parse course number
Run the command with the new file that has the course number in the column "Catalog Query".

Update populate_exam_coupons command to parse course number

---

profiles/util_test.py
requirements.in
requirements.txt

https://github.com/mitodl/micromasters/network/alert/requirements.txt/Pillow/open

Update the pillow version

---

static/js/actions/coupons.js

fixes https://github.com/mitodl/micromasters/issues/4435
adds an error message to coupon assignment failure
Try to use an invalid coupon which for course purchase

add error message to coupon assignment failure

---

grades/admin.py

fixes #4426
admin for program certificates

admin for program certificates

---

exams/admin.py

Fixes https://github.com/mitodl/micromasters/issues/4723
Adds an entry to admin panel for ExamAuthorization
Go to admin panel and search for Exam Authorizations to test how it functions.
Admin Panel:
List View:
Detail View:

adding admin panel entry for ExamAuthorization

---

selenium_tests/util.py

fixes #4536 
Fix selenium tests running locally
Just run selenium tests locally

Fix selenium tests running locally

---

exams/management/commands/import_edx_exam_grades.py

NA
Update the management command for importing exam grades.
Some of the updates include:
- different filel names
- the file contains grades for all courses that had exams
- adding the "no_show" boolean field
Run `./manage.py import_edx_exam_grades file_name`
with a provided file

Update command import_edx_exam_grades

---

exams/management/commands/import_edx_exam_grades.py

na
Handle missing authorization in import_edx_exam_grades.
Run `./manage.py import_edx_exam_grades <file>` with provided data

Import grades task: handeling missing authorization

---

dashboard/api_test.py
requirements.in
requirements.txt

fixes: https://github.com/mitodl/micromasters/issues/4744
Use the flaky module in tests.
Run the tests in `dashboard/api_test.py`

Flaky test module integration

---

cms/templates/cms/home_page.html
static/js/entry/public.js

NA
fix the build
Just see the build is passing

fix the build

---

cms/templates/cms/benefits_page.html
cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
static/js/entry/public.js
static/js/entry/zendesk_widget.js
ui/templates/adwords.html
ui/templates/base.html
ui/templates/base_error.html
ui/templates/certificate.html
ui/templates/grade_record.html
ui/templates/header.html
ui/templates/social_buttons.html
ui/templates/terms_of_service.html
ui/templatetags/render_bundle.py
ui/templatetags/render_bundle_test.py

fixes #4773
Defer JS to enhance performance

Defer JS to enhance performance

---

app.json

Apps in CI/RC/Prod all running the `heroku-20` stack. This just updates the app.json file

Updated heroku stack

---

dashboard/utils.py
dashboard/utils_test.py
static/js/components/dashboard/courses/StatusMessages.js
static/js/components/dashboard/courses/StatusMessages_test.js
static/js/global_init.js
ui/views.py
ui/views_test.py

Related to #4627
- removing ENABLE_EDX_EXAMS
- refactoring course status messages
- updating tests for status messages
Nothing should break.

Remove ENABLE_EDX_EXAMS feature flag

---

static/js/containers/FinancialAidCalculator_test.js

None
Fixes some flaky tests which time out at 2 seconds

Increase timeout for FinancialAidCalculator tests

---

exams/README.md

none
adding documentation for edX exam management commands
read the file

adding documentation for edX exam management commands

---

static/scss/certificate.scss
ui/templates/certificate.html

Fix #4852
Modified the text of the certificate and added more information to the footer.
Create a program certificate for your user, and in the cms create program certificate signatories for the user. Then go to the user dashboard to view the certificate.

Modifications to program certificate

---

static/scss/certificate.scss

Release 0.190.1 Fixing scss lint errors in certificate.scss
Fixing scss lint errors in certificate.scss

Fix scss linting errors

---

dashboard/api_test.py

Fix deployment issue
Fixes a test due to formatting of an exam date

Fix exam date schedulable test

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
selenium_tests/data_util.py
static/js/components/ProgramSelector.js
static/js/containers/LearnerPage_test.js
ui/templates/header.html
ui/views_test.py

fixes: #4860 
Standardize Log In / Sign Up buttons
----------------------

Standardize Log In / Sign Up buttons

---

Procfile
docker-compose.yml
micromasters/celery.py

Related to #4880
make separate celery queue for exams tasks
N/a

Adding celery queue for exams

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md

adjust PR template to remove autotag

adjust PR template to remove autotag

---

package.json
yarn.lock

https://github.com/mitodl/micromasters/issues/4899
Bumps `redux-hammock` to `0.3.3` (latest)
- Checking the tests
- A general look around the application would be suffice

Update redux-hammock to 0.3.3

---

exams/README.md
grades/README.md

Fix #4862
Updating some instructions for populating exam grades
read README

Exam grades readme updates

---

.github/workflows/ci.yml
docker-compose.selenium.yml
docker-compose.yml

fixes #4900 
Upgrade to Postgres 12
- Just take the backup of your data
- remove the old postgres docker image and volume
- then build and run the containers
- restore your data
that should use the update Postgres version to run the apps

Upgrade to Postgres 12

---

ui/templates/404.html
ui/templates/base_error.html

#4915 
- Adds the FAQ footer link to `404`, `500` error pages
To test it locally you will need to set `DEBUG` to false and then generate any of 404 or 500 error pages.

Added faq on error pages

---

certificates/views.py
certificates/views_test.py
ui/templates/grade_record.html

https://github.com/mitodl/internal/issues/31
raise 404 for anonymous users on records
Just anonymously access some records, it should be giving 404.

raising 404 for records

---

yandex_44cad5270f1c13a2.html

None 
Verifies micromasters.mit.edu for a couple of search engines.
It has to be released, and then I can check to see if we have ownership of the site in each search engine's webmaster tools.

verify micromasters.mit.edu on Yandex

---

static/js/containers/FinancialAidCalculator_test.js

None
Increases timeout for `FinancialAidCalculator` tests from 5 to 10 seconds

Increase timeout for FinancialAidCalcultor tests

---

micromasters/settings.py

#4908 
Add compression support for Redis
Just check that everything is up and running

add compression support for redis cache

---

static/js/containers/DashboardPage_test.js

Adds a 10 second timeout to DashboardPage tests

Address flaky tests on DashboardPage

---

package.json
static/js/components/ProgramFilter.js
static/js/components/search/CustomNoHits.js
static/js/components/search/CustomNoHits_test.js
static/js/components/search/CustomSearchBox.js
yarn.lock

fix #4383 
searchkit version bum to fix axios sercurity alert
Just check everything is up

searchkit version bump to fix axios sercurity alert

---

requirements.in
requirements.txt

Reverts mitodl/micromasters#4951

Revert "Bump wagtail from 2.12.4 to 2.12.5"

---

docker-compose.selenium.yml

N/A
Fixes the selenium tests breaking because broken selenium containers were pushed to docker hub

Fix broken selenium tests

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
dashboard/utils_test.py
static/js/components/ProgressWidget.js
static/js/components/ProgressWidget_test.js
static/js/components/StaffLearnerInfoCard.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js
static/js/test_constants.js
static/js/util/util.js
static/js/util/util_test.js

Fix #5022
Update the circular progress component to show a number of courses that the user passed towards the completion of the program.
Create an ElectivesSet for your program that your user is enrolled in.
Have your user pass all the courses in the elective set, or at least more than what is required.
Check to see the dashboard that all the required number of courses is reflected on the dashboard.

Update the circular progress to show passed courses

---

static/js/components/EmploymentForm.js

NA
update employment form design city field fix on tablet
Just visit the Employment form on the profile page
**NOW**
**BEFORE**

update employment form design city field fix

---

cms/templates/cms/home_page.html

fixes #5068 
Home page - text tweak to refer to MITx Online

Home page - text tweak to refer to MITx Online

---

ecommerce/urls.py
ecommerce/views.py
ecommerce/views_test.py
ui/url_utils.py

fixes #5113 
fix Cybersource cancellation or success redirect failures

fix Cybersource cancellation or success redirect failures

---

package.json
static/js/components/LearnerSearch.js
static/js/components/inputs/CountrySelectField.js
static/js/components/inputs/StateSelectField.js
static/js/components/inputs/inputs_test.js
static/js/lib/location.js
yarn.lock

none
I managed to forget to remove the old package when doing #5122!
tests should pass, app should work, etc

remove old iso-3166-2 package

---

search/tasks.py

fixes #5114 
update index users tasks to acks late so that last unfinished didn't get ignored
just test everything is working and the build is passing

update index users tasks to acks late so that last unfinished didn't get ignored

---

grades/README.md

none
Adds instructions on how to update final grade for user
View it [here](https://github.com/mitodl/micromasters/blob/1b7d5a0759549b9baab383d87e14c0c9decaae4f/grades/README.md)

Readme: how to update final grade for user

---

static/scss/letter.scss

fixes #5008 
print program letter in portrait mode
Just create a program letter and view it in Chrome preview
**NOW**
**BEFORE**

print program letter in portrait mode

---

static/robots.txt

fixes #5160
disallow letter link to prevent program letters from search engines indexing

disallow letter link to prevent letters from search engines indexing

---

grades/README.md

Update the grades readme
- updated instructions for importing exam grades
- fixed a markdown typo 
View the readme

Updated instructions for importing exam grades and fixed markup typo

---

micromasters/settings.py

This reverts commit 1ac99916cfdd9496983856e830aa8fac640912e2.
none 
Reverting back to the original schedule

Revert "Run batch user update only on Sunday (#5138)"

---

ecommerce/views.py

N/A
This makes the payment callback csrf exempt so that it doesn't fail.
- We'll test this in RC since local testing is time consuming.

Make the payment callback csrf exempt

---

app.json
micromasters/settings.py
requirements.in
requirements.txt

Closes #5185
- Updates redis and sets a number of additional settings for redis to keep the # connections down.
Celery tasks should still run and tests should still pass.
[Slack discussion](https://mitodl.slack.com/archives/G1VK0EDGA/p1649162310337079)

Configurable max redis connections

---

backends/utils.py
dashboard/views.py
dashboard/views_test.py
ecommerce/api.py
requirements.in
requirements.txt

https://github.com/mitodl/micromasters/issues/5193
- Updates edx-api-client to use from git until a new package is posted in PyPI
- Updates the enrollments to be `Verified` instead of `Audit`
- All the parts that include the enrollment
- I haven't been able to test it directly because of my local broken edX/MM configuration
More details can be seen at https://github.com/mitodl/micromasters/issues/5193
(Optional)
(Optional)
**Reviewer Note:**
This depends upon a new version of https://github.com/mitodl/edx-api-client to be published.

Update enrollments to be Verified instead of Audit

---

exams/management/commands/list_authorized_exam_learners.py

Related to #5221 
Update the management command `list_authorized_exam_learners`
1) Run `./manage.py seed_db` to set up the programs and course runs 
2) create your test learner user by creating an account and filling out the profile
3) Run `./manage.py alter_data set_past_run_to_passed --username <username> --program-title Digital --course-title 100`   to enroll your test user in a course run, and create a passing grade and payment record, ( you will see the edx_course_key printed by the command, save it so that you can use it later)
4) Create an exam run and authorize the user for the exam:
```
exam_run = ExamRunFactory.create(course=course, authorized=True, …
```

Update list learners eligible for enrollment upgrade

---

cms/templates/cms/home_page.html
cms/templates/cms/resource_page.html
courses/models.py
dashboard/api.py
dashboard/api_test.py
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js
static/js/util/util.js
static/js/util/util_test.js

Fix https://github.com/mitodl/micromasters/issues/5226
Remove mention of edx.org
Checkout the dashboard of your learner.
Before:
After:

Remove mention of edx.org

---

static/js/components/ProgressWidget.js
static/js/components/ProgressWidget_test.js

Fix https://github.com/mitodl/micromasters/issues/5227
Show the records link if the feature is on, and there is a link
Test the dashboard of your learner to have a records link when they have completed the program and when they are still in progress.

Show grade records if there is link

---

cms/templates/cms/home_page.html
dashboard/utils_test.py

Fixes https://github.com/mitodl/hq/issues/2286
remove quote from previous MIT president 
Take a look at the homapage and make sure it looks good.

Remove President's quote

---

ui/templates/header.html

Fix https://github.com/mitodl/hq/issues/3801
Correct the link in the header logo
Click the the header logo. The link should work.

Correct the link in the logo

---

cms/templates/cms/program_page.html
static/scss/_button.scss
ui/views_test.py

see https://github.com/mitodl/hq/issues/3936#issuecomment-2103361040
"ENROLL ON MITX ONLINE" => "ENROLL ON MITx ONLINE"

make "MITx Online" mixed case
