mitodl/micromasters

docker-compose.yml
micromasters/settings.py
micromasters/urls.py
requirements.txt

fixes #16 
This is dependent on the release of `django-server-status==0.3`
Adds the `django-server-status` app to Micromasters
`micromasters/settings.py` and then `micromasters/urls.py`
add an entry for the status token in your .env file, rebuild the web container and then test that `/status/?token=<your token>` works

Added Servers status app

---

backends/edxorg.py
backends/edxorg_test.py

Fixes #50 
Fetches information from edx for user's profile
edxorg.py
Same as https://github.com/mitodl/micromasters/pull/47 , but the user should be created with the correct username. If you're already logged in (as superuser), that account will be associated to you.
Status codes are [handled](https://github.com/omab/python-social-auth/blob/master/social/backends/base.py#L228) by python-social-auth.

Fetch information for user profile from edX

---

.dockerignore

Fixes #101 
Adds a .dockerignore file which lets us skip copying certain directories and files from the host to the docker container on build. The main offender here is `node_modules` which should not be dealt with at all during `docker-compose build`

Added dockerignore

---

micromasters/urls.py
profiles/factories.py
profiles/permissions.py
profiles/permissions_test.py
profiles/serializers.py
profiles/serializers_test.py
profiles/views.py
profiles/views_test.py
pylintrc

Fixes #18
- Adds a REST API for viewing and editing user profiles: `/api/v0/profiles/<username>/`
- Updates ProfileFactory to have randomized values for all fields
profiles/serializers.py
- In the Django shell, run
from profiles.factories import ProfileFactory
user = User.objects.create_user(username="user", password="pass")
profile = ProfileFactory.create(user=user, account_privacy="public")
This will create a user named `user` with `account_privacy` set to `public`. Keep the shell open so we can edit profile later.
- Create a superuser and login as that superuser via Django Admin.
- View `/api/v0/profiles/user/`. You should see 12 key value pairs, including `bio` and `country` for example, but not `mailing_address`.
- In the Django shell run …

Added REST API for profiles

---

tox.ini

Fixes #108 
Updates tox.ini to use site packages. Since we only have one environment which is exactly the same as the docker container, this should not cause any problems, and it speeds up builds a little bit.

Use sitepackages=True so tox reuses the same packages in the docker environment

---

LICENSE

From the 3 clause BSD license template [here](https://en.wikipedia.org/wiki/BSD_licenses) it seems like this should be our organization, not the Micromasters name specifically.

Fixed LICENSE organization

---

static/js/containers/LoginButton.js

closes #99
change the log out button on the dashboard to, you know, log out. we just need to set the `href` prop on the `MenuItem` react bootstrap component.
`static/js/containers/LoginButton.js`
make sure it logs out!

Made log out button on dashboard log user out

---

micromasters/settings.py
ui/views.py
ui/views_test.py

this closes #98
this adds a simple redirect check when hitting `/dashboard`. if
`request.user` is not authenticated, we redirect to `/`.
in `/ui/views.py`
1. log in to micromasters
2. check that you can visit `/dashboard`
3. click the (brand new!) logout button
4. visit `/dashboard`
5. confirm
first python commit!

Added redirect, "/dashboard" -> "/" if user not logged in

---

micromasters/settings.py
ui/context_processors.py
ui/templates/base.html

closes #135
this adds google analytics to the base template for the ui app.
first, this adds a template tag for the ui app that lets us pull values
out of `settings.py` (we store the google analytics id there).
then we can just pop the google analytics JS snippet into the `<head>`
of our base template, and pull in the analytics id using the template
tag. Nice!
`/ui/templatetags/ui_extras.py` <- this is the thing I'm least sure
about.
we can generate a throwaway google analytics account, set the
environment variable `GA_TRACKING_ID` to the tracking id for that
account (in the micromasters `.env`), and then confirm that visiting any
page results in a page view being registered.
I was a little unsure as to how to get the environment variable defining
our tracking ID into the template. this …

Added google analytics to base ui template

---

package.json
static/js/mocha.opts
tox.ini

this closes #140
This moves our JS testing commands into npm scripts (defined in
`package.json`).
I'd take a look at `tox.ini` and `package.json` first.
pull down the branch and make sure the tests are running.
This is a nice change because:
1. it's a bit cleaner to package all the JS stuff together, then when we
want to run the JS tests in `tox` we just do `npm run-script coverage`.
2. when we're running inside of a `package.json` script we have access
to the executables installed in our `node_modules` directory, so we
don't need to provide the absolute path to, say, `mocha`. this is nice
because we get nicer looking commands, without having to install a bunch
of JS modules globally.
3. now we have an `npm test` command that just runs the JS tests,
without a coverage report, which is …

Moved JS tests to npm scripts

---

pytest_minimal.ini

this just adds a new `py.test` config that runs only the tests (no pep8, no coverage, etc). makes it a little faster to get feedback when developing.
if you want to use it you do `docker-compose run py.test -c pytest_minimal.ini`.

Added a minimal pytest for quick feedback

---

package.json
static/js/containers/LoginButton.js

none, this fixes a bug I noticed.
this adds a library called react-router-bootstrap that is designed to
make react-router and react-bootstrap play nicely together.
basically, we were getting a JS warning that looks like this:
```
warning.js:45 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See LoginButton > MenuItem > SafeAnchor > a > ... > Link > a
```
this is occurring because we had the following code:
```javascript
<MenuItem>
<Link to="/profile">
Profile
</Link>
</MenuItem>
```
`MenuItem` comes from `react-bootstrap`, and `Link` is a `react-router`
link. basically, the problem is that `MenuItem` implicitly includes an
`<a ..></a>` element, and places `this.props.children` inside that
element.
hence, we get a console warning about improperly nesting `<a>` …

Fixed a JS console warning, react-router and react-bootstrap

---

.eslintrc
static/js/components/PersonalTab.js
static/js/containers/App.js
static/js/containers/ProfilePage.js
static/js/reducers/index_test.js
static/js/util/util.js

none.
updates the eslint config to properly lint ES6 / JSX code, sets a few options, and deals with the errors the linter points out.
`.eslintrc`, and then review the changes made to pass linting.
Make sure none of the style changes broke anything!
Originally I just wanted to enable the `no-unused-vars` option, but quickly discovered that we didn't have `eslint-plugin-react` configured quite right, so when enabling `no-unused-vars` eslint would complain that the following code wasn't using `React`, for instance:
```
import React from 'react';
class Foo extends React.Component {
...
}
```
using the right configuration base (setting `extends: [ "plugin:react/recommended" ]`) gave us that easily.

Updated eslint configuration

---

.eslintrc
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/containers/ProfilePage.js
static/js/dashboard.js
static/js/util/profile_edit.js

#150 
This
1. adds a tab where the user can fill out their employment history
2. sets up using react-router to transition between the tabs in the profile screen
3. pulls form <-> store communication logic out into a shared file
4. automatically redirects from `/profile/personal` to `/profile/professional` when you click 'save'
The changes in `static/js/components/PersonalTab.js`, `static/js/containers/ProfilePage.js`, and `static/js/dashboard.js` are probably the biggest ones.
check out the branch and make sure that everything is working (you can change fields and they update, etc).
I ran into a couple of issues with react-router and passing props down to `this.props.children`. relevant issue here: https://github.com/reactjs/react-router/issues/1857

React-router for profile tabs, basic employment tab

---

static/js/components/PersonalTab.js
static/js/dashboard.js

none
This removes the employment route placeholder from our router. We
probably aren't going to have the employment tab ready in time for the
demo, and we'd rather not show off the placeholder.
modified:   static/js/dashboard.js
This just removes the route for the `EmploymentTab` component.
modified:   static/js/components/PersonalTab.js
This sets the `PersonalTab` component to redirect to `/dashboard` on
save, instead of to `/profile/professional`.
Make sure nothing is wacky with react-router.

Deleted the `employment` route placeholder

---

static/js/components/CourseList.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss

Fixes #105
Adds a column to the dashboard display and draws a circle based on the course status. 
Add some courses with different statuses (or change `api.getDashboard()` to use the `DASHBOARD_RESPONSE` constant). Then view them in the UI. A course which is passed has a full circle, a course which is verified but not passed has a half circle, and all other courses have a empty circle. Each circle should connect exactly with the circles above and below it.

Added course progress indicator for dashboard

---

docker-compose.yml

This removes the `node rebuild node-sass` step which was introduced here: https://github.com/mitodl/teachersportal/pull/43. I don't think anyone uses the OS X libsass library so I believe this isn't useful.
Make sure `docker-compose up` still works fine

Removed node-sass rebuild step

---

dashboard/api.py
dashboard/api_test.py
dashboard/fixtures/certificates.json
dashboard/fixtures/user_enrollments.json
dashboard/views.py

Takes in account certificates in the dashboard
dashboard/api.py
In Micromasters, the course needs to be "past", meaning the end date should be past.
In EDX, you need to create a verified enrollment and certificate for the micromaster course for a user.
To manually create a certificate for a user `bob` for a course `course-v1:odl+GIO101+CR-FALL15`:
```
from certificates.models import CertificateStatuses
from certificates.tests.factories import GeneratedCertificateFactory
from opaque_keys.edx.keys import CourseKey
bob = User.objects.get(username='bob')
course_key = CourseKey.from_string('course-v1:odl+GIO101+CR-FALL15')
GeneratedCertificateFactory.create(user= bob, course_id=course_key, status=CertificateStatuses.downloadable, mode='verified', …
```

Certificates taken in account in dashboard

---

.gitignore
osx_start.sh

Fixes #142
Provides a script to let OS X users (and Linux users) run the webserver and webpack dev servers from the host environment instead of within Docker.
This requires a whole lot of manual installation steps compared to Docker setup, but it should make the development process easier:
- Postgres must be installed and its binaries added to the `$PATH`
- The postgres user must have the password 'postgres'
- Python 3 should be installed
- Node JS 4.x or later should be installed
- All dependencies of the various Python libraries need to be installed first. (There are many here.)
After the manual installation is done, the user should just need to run `./osx_start.sh`. The python and npm dependencies will be installed, then the servers will start. The script will trap SIGTERM and SIGINT …

Added script to run development server on OS X without docker

---

static/js/components/PersonalTab.js
static/js/util/ProfileTab.js

none
this creates a utility class called `ProfileTab` which lets us cut down on boilerplate a little (when setting up the profile tabs).
we just write components that inherit from `ProfileTab`, and the `boundTextField` and so on functions are already bound to `this` (just remember to call `super(props)`in your constructor!).
read the new class (`static/js/util/ProfileTab.js) and review the changes to the personal tab (`static/js/components/PersonalTab.js`).
Make sure this doesn't clobber any existing behavior.
my name is alice and I hate boilerplate.

Added ProfileTab utility class

---

requirements.txt

fixes #231
changes the `edx-api` client from dev to named release

Pointing the edx-api-client requirement to release

---

static/js/containers/App.js
static/js/containers/TermsOfServicePage.js

none
React router throws up a console warning if you grab `history` out of
`this.props` instead of importing the history provider (e.g.
`browserHistory` or `hashHistory`) and calling `.push` on that.
This just makes that change, so the warning doesn't show up!
`static/js/containers/App.js` and `static/js/containers/TermsOfServicePage.js`
- update your profile so that `agreed_to_terms_of_service == False`
- visit `/dashboard`
- click 'agree'
- confirm no JS console warning
original warning (can repro by following the 'manual testing' steps on master):

Fixed JS console error with react-router history

---

static/js/components/Dashboard.js
static/js/containers/LoginButton.js
static/js/reducers/index.js
static/js/reducers/index_test.js

Removes the unused `authentication` reducer, and uses the name from the profile instead. Now the name updates in the header immediately after the profile is saved

Removed unused authentication state, use profile state instead for name

---

.babelrc
package.json
static/js/actions/index.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/containers/ProfilePage.js
static/js/dashboard.js
static/js/dashboard_routes.js
static/js/reducers/index_test.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss
static/scss/layout.scss
webpack.config.shared.js

closes #150 
this adds an 'employment' tab to the profile editing page.
There are a lot of changes. I would start by reviewing the changes to the `bound${inputType}Field` methods in `util/profile_edit` and the changes to the validation logic (in `util/util`).
Pull down the branch, and make sure you can edit all the fields on the employment and personal tabs, and that they are all correctly validated.

Build employment tab

---

static/js/actions/index.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/integration_test_helper.js

Fixes #237 
Removes unused calls to `/api/v0/programs/` and `/api/v0/courses/` from the frontend
Everything should work the same as before, but there should not be these requests in the Network tab

Removed calls to programs and courses APIs in frontend

---

static/js/actions/index.js
static/js/containers/TermsOfServicePage_test.js
static/js/reducers/index_test.js

Fixes #272
Instead of assigning the profile in edit to be the profile on successful PATCH, use the return value from the PATCH. This is necessary so we can keep track of the id number
Add a new work history item to your profile and save it. Then, without refreshing, look at your redux state and verify that the work history item in your profile has an id number.

Updated profile PATCH code to use return value as new profile

---

dashboard/api.py
dashboard/api_test.py
dashboard/fixtures/user_enrollments.json

fixes #219 
the old not-passed runs now are added to the list of runs for a course together with the next one to take or with the current one
dashboard/api.py
the rest api interface should show multiple runs. the additional ones can be only `passed` or `not-passed`
the UI will most likely not work properly until #223 is done

Old not passed courses in dashboard API

---

backends/pipeline_api.py
backends/pipeline_api_test.py
static/js/components/EmploymentTab.js
static/js/components/PrivacyTab.js
static/js/dashboard_routes.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js

Fix #215 
Add Privacy tab to profile. Set account privacy default value to be 'private'.
PrivacyTab.js
Go to Privacy tab. For a newly created account the value should be set to 'private'. For already existing accounts the value was set from the edx profile on creation of the mm account, and is public by default.

Added Privacy tab to profile

---

static/js/components/Header.js
static/js/containers/LoginButton.js

fixes https://github.com/mitodl/micromasters/issues/292
- Removed ```dashboard link``` from dashboard page.
- Added same link to dashboard on clicking user name on dropdown
- Change dropdown button to avoid navigation by mistake.
-  Header.js and LoginButton.js
- see the header of program dashboard
@pdpinch @noisecapella @aliceriot

Removed ``dashboard link`` from dashboard page and added this link to username on dropdown

---

package.json
static/js/components/EducationTab.js
static/js/components/PersonalTab.js
static/js/dashboard.js
static/js/dashboard_routes.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

Fixes #277 
Adds material-ui so we can use the AutoComplete component to replace our select fields. Also updates `boundStateSelectField` to call `boundSelectField` instead of implementing duplicate behavior
Go to the profile and edit the gender field, or the state/country fields. You should notice these behaviors:
- the autocomplete now only matches prefixes (case insensitive)
- when user is not actively typing in the autocomplete, it should always show the currently selected item or a blank string.
- when the user types some text and presses enter and they have something in the autocomplete, the first item in the autocomplete menu will become the selected item
- when the user types some text which doesn't match anything and presses enter, it should revert back to whatever was previously …

Added material-ui AutoComplete 

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #276
Uses the textfields to bring up month and year fields. Both fields should validate the numbers provided
`profile_edit.js`
There shouldn't be any odd behavior (at least in the UI):
- There should be two text fields and a label which look like this: Label MM / YYYY
- you should be able to edit either textbox independently. If one is blank, there should be a validation error when you click save. After the validation error you should be able to save if you fill in proper values for each textbox.
- Only numbers 1-12 and 1-9999 should be accepted by the field. You should be able to type in text but it will cause a validation error

Added field for month/year

---

static/js/util/util.js

fixes https://github.com/mitodl/micromasters/issues/323#event-661031580
- Fix url of enroll button. point it to about/ instead of info/
- Assuming that the edX url in ```.env``` is like  ``http://192.168.33.10:8000``. [Took assumption from bottom of readme](https://github.com/mitodl/micromasters/blob/master/README.md).
- See ``utils.js``.
- Click on enroll button in course on a program (Dashboard).
@pdpinch @aliceriot @noisecapella 
This was issue that was ripple of https://github.com/mitodl/micromasters/pull/282.

Fixed urls for enroll and upgdate course in a program

---

static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

Fixes #319 
The onBlur and onNewRequest callbacks were modifying the same copy of `profile`. This removes `onBlur` which means the field will not show the currently selected state anymore when a user focuses away from the field. It will fix the down key behavior however
I filed #327 to provide a better fix for this

Removed onBlur callback from AutoComplete

---

backends/edxorg.py
backends/pipeline_api.py
backends/utils.py
backends/utils_test.py
dashboard/views.py
dashboard/views_test.py
micromasters/settings.py
static/js/util/api.js

closes #278 
fixes mitocw/edx-platform#217
switches the backend to use the new edX oauth toolkit library and implements the OAUTH2 refresh token.
first `backend/pipeline_api.py`
then `backend/edxorg.py`
then `dashboard/views.py`
you need to create in your edx instance a new application in the section `django oauth toolkit`, then update `client_id` and `client_secret` in your `.env` file.
Until the current edx PR#12435 gets merged, the  endpoint for Django OAUTH Toolkit cannot be used (the certificates rest api will not work).
In the meantime it woks with the old library (that turned out to support refresh tokens as well)

Implemented refresh token

---

courses/admin.py

fixes #324 
Adds edx_course_key to the courserun list display in admin.
Changes the order of fields in course list display, to make it consistent with other admin lists.
By the time the reviewer starts, they will be done. 
Take a look at /admin/courses/courserun/ and /admin/courses/course/
There's a lot of courseruns with the same name, so we need some way to differentiate them in list view.

added edx_course_key to courserun list display in admin

---

static/js/components/PersonalTab.js

closes #288 
This adds a requirement that the `state_or_territory` and `birth_state_or_territory` fields be filled out on the personal tab. We're currently already requiring the equivalent fields on the employment and education tabs.
Changes in `PersonalTab`.
Change the profile record in the database to have `state_or_territory = None`, save it, and then reload the dashboard. When you try to advance past the personal tab you should see a warning that the `state_or_territory` field is required. Same thing should happen for `birth_state_or_territory`.

Added requirement for state_or_territory on PersonalTab

---

static/js/components/CourseList.js
static/js/components/Dashboard.js
static/js/components/EducationTab.js
static/js/components/Header.js
static/js/components/UserImage.js
static/js/containers/DashboardPage.js
static/js/containers/LoginButton.js
static/js/containers/TermsOfServicePage.js

closes #330 
This moves all class properties to the newer class property syntax, which uses the `static` keyword and looks like this:
```js
class Foo {
static someClassProperty = 12;
}
```
as opposed to the older syntax:
```js
class Foo {
...
}
Foo.someClassProperty = 12;
```
the newer syntax moves the class properties into the body of the class declaration, meaning that the property declarations are closer to the code they relate to. On classes that extend `React.Component` we can declare our `propTypes` and `defaultProps` as class properties:
```js
class Foobar extends React.Component {
static propTypes = {
foobar:  React.PropTypes.func.isRequired,
}
static defaultProps = {
foobar: () => console.log("FOOBAR");
}
}
```
It's a bit more readable and just generally nicer to work with. This …

Changed all class properties to use es7 class property syntax

---

static/js/actions/index.js
static/js/containers/ProfilePage.js
static/js/reducers/index_test.js

Fixes #270
When we add `catch` to a `Promise` without returning another rejected `Promise`, future promises are resolved with that return value. This meant that even when the API function returned the rejected promise, the action dispatcher function returned a resolved promise.

Fixed profile submission to wait for a 200

---

dashboard/views.py
dashboard/views_test.py

fixes #337 
Filters the programs in the dashboard to show only live ones
Create a program with live property set to false and check it does not appear in the dashboard

Only live programs are available in dashboard

---

static/js/constants.js
static/js/containers/App_test.js

Fixes #343 
The warning came from using fake value `"filled in"` to populate employment fields. The error came from when moment.js parsed this field as a date. This adds fake employment and education data to `USER_PROFILE_RESPONSE` and updates the tests to use one of the default 
I noticed that we test that redirecting to the work history field on validation error works but we don't have tests for this for the education tab. Not sure if #314 will make this unnecessary

Added fake values for employment and education constants

---

profiles/serializers.py
profiles/serializers_test.py
static/js/containers/ProfilePage_test.js
static/js/global_init.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js

Fixes #233 
If the user clicks the save button on a profile page, it will send a `filled_out`: false along with the rest of the data, which will force them to complete the rest of the profile. When they get to the last tab and click Save, it will send `filled_out`: true and `email_optin`: true.

Marked profile as incomplete when it's being filled out and complete when past the last tab

---

.eslintrc
package.json
static/js/actions/ui.js
static/js/components/CourseList.js
static/js/components/CourseList_test.js
static/js/components/Dashboard.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/containers/ProfilePage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/dashboard.scss

Fixes #223 
Shows course runs in dashboard and handles the not passed behavior more accurately. 
Add a course which is not passed to your local server, then view the dashboard. You should see a red circle next to the course, and a expander link which would allow you to see individual runs.

Implemented UI for showing course runs in dashboard

---

static/js/actions/index.js
static/js/actions/ui.js
static/js/components/EducationTab.js
static/js/containers/ProfilePage.js
static/js/reducers/index.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js

closes #329 
This moves the reducers and actions relating to the education step of the profile to the UI reducer.
Read through all the new actions, make sure they all make sense. Read the changes to the `EducationTab` class - this no longer is connected directly to the store but receives a bunch of setters (and the `ui` object) from it's parent.
Make sure there are no regressions on the education step.

Moved education reducers and actions into `ui`

---

static/js/actions/index.js
static/js/containers/App.js
static/js/containers/DashboardPage.js
static/js/containers/LoginButton.js
static/js/containers/ProfilePage.js
static/js/containers/TermsOfServicePage.js
static/js/reducers/index.js
static/js/reducers/index_test.js

Required for #216 
Renames the `userProfile` reducer to `profiles` and changes the structure and related actions to use the profile username so we can store multiple profiles.
Everything should work as before

Refactored profiles reducer to handle multiple profiles

---

static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/TermsOfServicePage_test.js
ui/decorators.py
ui/decorators_test.py
ui/url_utils.py
ui/urls.py
ui/views.py
ui/views_test.py

closes #227 
Redirects the user to the profile page if the profile is not complete
`ui/decorators.py`
uncheck `Filled out` and `Agreed to terms of service` from the user profile and test that the user is redirected first to the terms of service and then to the profile.

Redirect to profile if the profile is not complete

---

package.json
static/js/components/AutoComplete.js
static/js/util/profile_edit.js

Fixes #327 
Forks the AutoComplete component from material-ui and makes these changes:
- When the user tabs onto the field with the keyboard, the menu does not open anymore. Instead the user has to type text first.
- When the user clicks the field the entire set of choices will be shown rather than the choices which match the text in the textbox. After the user edits text in the textbox, the choices will be filtered to match that text.
- The onBlur handler is now not invoked when the user presses enter, down, or escape. This means the user can navigate through the menu with their arrow keys to select an option.
Other changes to our code:
- Added back the onBlur handler to show the selected value when the user removes focus from the textbox, but not when the user presses down, enter, or …

Fixed AutoComplete quirks

---

micromasters/settings.py

Fixes #169 
When the user logs into a server and clicks 'Cancel', they currently get a 500 error on micromasters. This will cause it to redirect to the home page instead.
Run your local instance with `DEBUG = False`. Log into the sandbox or your devstack and cancel the authorization when it asks for read and write scope. You should be redirected to `/` instead of getting a 500 error
This will silence oauth authorization exceptions in general

Added middleware to redirect canceled authorizations

---

static/js/components/AutoComplete.js

Fixes #380 
When the user selected an item the onBlur handler cleared the item that was selected immediately afterwards. This change causes the onBlur handler not to be invoked if the user just selected a menu item.
`this.timerTouchTapCloseId` is set after the user selects a menu item, so we are using this in the onFocus callback to determine if the loss of focus was caused by clicking a menu item
We should be thorough in testing all different scenarios. For each item below notice these things:
- unless you are actively typing there should never be text in the text field that doesn't match the currently selected item.
- If an item should be selected, the country text field should have the text of the item, and when you click Save, it should pass validation. You should be able to click the …

Removed AutoComplete onBlur handling when user has clicked a menu item

---

webpack_if_prod.sh

Noticed this bug when running `npm install` locally. The -u flag requires env variables to be set. There's no reason for us to require that (at least not that I know of). Now that this script is going to be run in OSX host machines as well as Docker containers, this change was necessary

Fixed webpack_if_prod script to make it OSX-friendly

---

static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js

Fixes #383 
Clear state field state when the country changes. This prevents a subtle bug where the state field appears to clear but its state keeps the previous state/territory
Change the country in the employment and education and the birth place and current place of the personal tab. In each case don't touch the state field, then try to save it. You should see a validation error for the state indicating that it wasn't selected. (We require the state field for each of these cases, right?)

Cleared state field when country field changes

---

static/js/components/Jumbotron.js
static/js/containers/DashboardPage.js
static/js/containers/ProfilePage.js

closes #367 
this modifies the `Dashboard` component to be useful on the profile as well as on the main dashboard page.
Basically, now it takes an `onProfile` prop, which when `=== true` means that we put the requisite message in the banner, and don't draw the course display.
Review the changes to `Dashboard.js`, `DashboardPage.js`, and `ProfilePage.js`.
When you're viewing one of the profile steps (personal, education, etc) you should see the stata center banner image, and some welcome text:
when visiting `/dashboard`, you should see the current behavior:

Added Dashboard splash to profile tabs

---

package.json
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/constants.js
static/js/dashboard.js
static/js/util/ProfileTab.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util.js
static/js/util/util_test.js

Rebased on #401 
Fixes #378
Removes react-datepicker, changes boundMonthYearField, and adds a date textbox
This is only present in the date of birth field in the personal tab. You should see this behavior:
- a validation error should be shown after save if the date is missing or invalid
- If the user clears one text field, all fields should clear at the same time
- The user should be able to save a valid date
- When the user refreshes the browser the date should show up correctly
- The label should show up above the text fields
- There should be MM DD YYYY hint text in the text fields

Replaced react-datepicker with textfields

---

static/js/components/PersonalTab.js
static/js/util/profile_edit.js
static/scss/dashboard.scss

Fixes #217 
Restyles the personal tab according to mockups.
Note that the email consent text is part of the terms of service so it's not present in the personal tab
Make sure that the personal tab still works as expected, it matches the mockups in the linked issue, and it's consistent with the other tabs.

Updated personal tab to match mockups

---

static/js/components/EducationTab.js

Fixes #332 
Removes the field of study text field from the high school education edit dialog
Look at the education dialog for high school and for a different education level. The high school dialog should be missing the field of study text field but otherwise look and act the same

Removed field of study for high school education

---

static/js/components/AutoComplete.js

Fixes #419
Focuses the text field after selecting an item. This should let the user tab after pressing enter
In an AutoComplete component, type some text. Press the down key and highlight an option you want to select. Press enter. The item should be selected and the text field should be focuses. When you press tab you should go to the next field. Also try pressing backspace after pressing enter to select an item, and verify that the behavior is expected.

Changed AutoComplete to focus on text field after selecting an item

---

static/js/components/PersonalTab.js

fixes https://github.com/mitodl/micromasters/issues/381
- Replace text "MicroMaster's certificate" with "MicroMaster's credential".
- Personal Tab
@aliceriot @pdpinch @noisecapella 
- open /profile, see header of personal tab.

Replace MicroMaster's certificate text with MicroMaster's credential in app

---

backends/pipeline_api.py
backends/pipeline_api_test.py
backends/utils_test.py
cms/models.py
dashboard/views.py
dashboard/views_test.py
profiles/serializers.py
profiles/serializers_test.py
profiles/views.py
profiles/views_test.py
static/js/containers/LoginButton.js
static/js/containers/ProfilePage.js
static/js/util/util.js
static/js/util/util_test.js
ui/decorators_test.py
ui/views.py
ui/views_test.py

Fixes #239
Uses the username stored in the social auth model instead of the one attached to the `User` model. In logging we still use `user.username` but in all other places we should use the one attached to the edx social auth model instead. Tests are updated to provide a different username for the social auth model.
Also, the logic to show either the username or preferred name was moved out of the server into the JS in the function `getPreferredName`.
backends/pipeline_api.py
- Find a user who has an account on edX but who has not yet logged into edX via MicroMaster's. If necessary, delete an existing user from MM using the Django shell first.
- Create a new user using the Django admin, or the shell, or using createsuperuser. Do not create it by logging in. The user must have the same …

Switched to social auth username

---

static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/containers/ProfilePage_test.js
static/js/util/ProfileFormFields.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/scss/dashboard.scss

Closes #375 
adds the 'previous' button to appropriate profile pages. this accounts for a new profile navigation along with #369 
fill out a profile starting with /profile/personal and use the "Previous" and "Save And Continue" buttons

Added previous button to profile pages

---

Dockerfile
apt.txt
test_requirements.txt
tox.ini

fixes #458
Switches docker to python 3.5
everything should work as is but using python 3.5: one way to test is to run `docker-compose run web tox`

Docker with python35

---

static/js/components/CourseList.js

none
I noticed two JS console warnings that were introduced (near as I can tell) in https://github.com/mitodl/micromasters/commit/1dcaf65475ea61ba0c2e8ddc3e3ba932ec2d2af7
if, on master, you visit `/dashboard`, you get these errors in the JS console:
check out the changes.
Make sure the JS warnings are gone, and that there are no regressions.

Fixed two JS console warnings

---

static/js/actions/ui.js
static/js/components/CourseList_test.js
static/js/components/PersonalForm.js
static/js/components/PersonalTab.js
static/js/components/User.js
static/js/components/UserPagePersonalDialog.js
static/js/containers/ProfileFormContainer.js
static/js/containers/UserPage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js

closes #391 
This PR adds the ability to edit personal information by clicking the 'edit' button on the users page. This entails:
- moving the personal form fields to a new class (`PersonalForm`)
- creating a shim class to place the `PersonalForm` in a dialog (`UserPagePersonalDialog`)
- actions and reducers to show / hide the dialog
I would review the changes to `User` and the new `PersonalForm`.
Make sure there are no regressions in the ability to edit at `/profile/personal`. Make sure you can edit everything in the same way on `/users/${username}`.

Made personal info editable on user page

---

backends/edxorg.py

closes #456 
closes #460
changes the OAUTH backend URLs to the old ones, given that edX just merged the PR https://github.com/edx/edx-platform/pull/12595
you need to have the latest edX master, then using the Django Oauth Toolkit credentials, verify that the login works.

Switched to old OAUTH endpoints for edX

---

static/js/util/validation.js
static/js/util/validation_test.js

Fixes #490 
Fixes bug in `checkFieldPresence` to combine errors correctly. Currently it uses `Object.assign` which won't combine nested values correctly
Open a new education, then click save without typing anything. All fields should be marked as needing validation

Fixed handling of multiple validation errors for education and work history

---

apt.txt

Related to #458 
When we installed python3-dev it pulled in python 3.4 dependencies. In the `python:3.5` image these are already installed so this PR gets rid of this step. Note that python2.7 is also installed but it's required by `lsb-release` which we probably don't want to get rid of
The build should succeed

Removed python3-dev which points to a python 3.4 package

---

README.md
js_test.sh
package.json

Removes `singleTest` script from package.json and moves the test command into a separate script `js_test.sh`. This allows the user to run `npm test` to run all JS tests or `npm test ./static/js/...` for a single file.
It looks like parameter substitutions like `$1` don't work in `package.json`. It ignores them and appends all parameters to the end of the line instead, so we can't do the fancy bash default parameters inside `package.json`, it has to go in a separate file.

Removed singleTest command

---

static/js/actions/ui.js
static/js/components/ConfirmDeletion.js
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfileFormContainer.js
static/js/containers/UserPage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/ProfileFormFields.js

closes #439 
This adds a confirmation dialog that pops-up when clicking the 'delete'
icon for a work or education history entry. This entails some associated
reducers and actions, and a new class called `ConfirmDeletion` which
will, hopefully, be generally useful for this sort of thing.
Most of the key stuff ends up being implemented as instance methods on
`ProfileFormFields` and `ProfileFormContainer`.
Make sure that any deletion action causes a confirmation dialog to appear, and make sure that the buttons ('yes' , 'no') do what they should.
This should work on `/users` and on `/profile`.

Added confirmation dialog when deleting education and work entries

---

static/js/components/PrivacyTab.js
static/js/util/ProfileFormFields.js
static/js/util/profile_edit.js
static/scss/dashboard.scss

Resolved https://github.com/mitodl/micromasters/issues/477
- Moved hint of radio button of privacy tab inside profile page to the new line.
- profile_edits.js
- open /profile/privacy

Moved profile privacy hint to new line

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/components/User.js
static/js/containers/UserPage_test.js
static/js/util/util.js
static/js/util/util_test.js

closes #415 
This adds a little utility function called `userPrivilegeCheck`, which
basically just checks that the username on the profile in question is
the same as `SETTINGS.username`. We pass a callback in to
`userPrivilegeCheck`, and `userPrivilegeCheck` returns the value of
executing that callback if the usernames match, else it returns an
optional second argument or, if that isn't provided, it returns
undefined.
Make another profile on your dev box. Check two things:
- you should see edit icons on your own profile, and be able to edit normally
- you shouldn't see any edit icons on another user's profile

Added check to only show edit buttons for a user's own profile

---

static/js/constants.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/ProfileFormFields.js
static/js/util/util.js
static/js/util/util_test.js

Fixes #507 
Populates switches with the level of attainment from edX. If none is found all switches are on by default.
static/js/util/util.js
Log in, go to `/profile`, navigate to the education, then verify that the switches are:
- always on if there is one or more education items in the card, regardless of anything else, or
- all on if no edx_level_of_education is set in the profile, or
- on only if the level of education is less or equal to the card's level of education
You should be able to change the level in the profile model and refresh to see the different states.

Used level of attainment from edX to set default switch values

---

static/js/components/EducationDialog.js
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/User.js
static/js/containers/UserPage_test.js
static/js/util/editEducation.js
static/scss/dashboard.scss

closes #498 
This adds a different display component for the education history which we can use on the `/users` page.
Review the new components (`EducationDisplay` and `EducationDialog`) and the changes to `EducationForm`.
Visit `/users`. You should see your education history, and be able to delete and add new entries. On a different user's page, the edit, add, and delete buttons should be hidden. There should be no regressions on the education profile step.

Collapse education on `/users/`

---

static/js/actions/index.js
static/js/components/EducationDialog.js
static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/components/UserPagePersonalDialog.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage_test.js
static/js/reducers/index_test.js
static/js/util/editEducation.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/validation.js
static/js/util/validation_test.js
static/scss/dashboard.scss

Fixes #433 
Rebased on #508 
Adds validation for switches for education and employment, so that a validation error will be produced if:
- the switch is on but there is nothing in the card
- the switch is off but there's something in the card
static/js/util/validation.js
In the profile pages, start at personal and go forward to the education tab. You should not get a validation error on the personal page. In the education page leave some cards blank and go forward. For all cards which are blank you should see a red validation error which has the label of the card within it. If you turn off a card or add an item to another card and continue, the validation error should go away.
Go back to the education page and add an item to one of the cards if necessary. Close the tab and click 'Save and …

Added validation for employment and education switches

---

static/js/constants.js
static/js/util/validation.js
static/js/util/validation_test.js

Fixes #403 
Rebased on #504 
Handles the three validation cases mentioned in the issue
- Verify that an error occurs if you change your date of birth to a date in the future and click Save
- In a work history entry try to add a year but not a month for the end date. Verify that the error message is: "Please enter a valid end date or leave it blank". If you remove both year and month, everything should work fine since that means you are currently working there.
- In a work history entry verify that you get an error if your end date is before your start date. Verify that the message is: "End date cannot be before start date"
- Also in work history, remove the start date, click 'Save' and verify that the error message is "Please enter a valid start date"
- In an education entry verify that …

Added extra validation for dates

---

npm-shrinkwrap.json
package.json
static/js/components/CourseList_test.js
static/js/containers/App_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/TermsOfServicePage_test.js
static/js/containers/UserPage_test.js
static/js/global_init.js
static/js/reducers/index_test.js
static/js/reducers/ui_test.js
static/js/util/api_test.js
static/js/util/courseList_test.js
static/js/util/integration_test_helper.js
static/js/util/profile_edit_test.js
static/js/util/util_test.js
static/js/util/validation_test.js

Fixes #475 
Replaces `assert` with `chai` and `chai-as-promised`. Tests are changed to always return a promise. Tests that have a rejected promise will use `assert.isRejected` instead.
Just check that the tests pass

Used chai to assert Promise behavior

---

cms/templates/cms/home_page.html
static/scss/homepage.scss
ui/views_test.py

Fixes #453 
Adds a test to make sure the program link exists if ProgramPage was created for it, and moves the existing link from the program title to the program card
Go to the home page and make sure you can click the card to go to the program page

Moved program link from title to entire card

---

static/js/components/EmploymentForm.js

closes #516 
Removes a `componentWillMount` lifecycle callback on `EmploymentForm` which was setting the switch to default to 'off' (in the case that a user has not yet entered any work history).
Now the switch should always initially have the default value from the store, which is `true`.

Set work history switch to be on by default

---

static/js/components/EducationDialog.js
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/containers/UserPage_test.js

this closes #527 
This removes the little popover menu for adding education entries on the `/users` page. Instead, now we can pass a prop (`showLevelForm`) in to the `EducationDialog` component. When that's `true`, we should a menu that lets the user pick the degree level (high school and so on). When false, we hide it.
Look over the changes to `EducationDisplay` and `EducationDialog`.
Make sure you can add any kind of degree type on `/users`. Make sure you can add all degree types (and they don't show the degree type dropdown) on `/profile/education`.

Removed popover from EducationDisplay on /users

---

.babelrc
.eslintrc
.flowconfig
Dockerfile-node
npm-shrinkwrap.json
package.json
static/js/actions/ui.js
static/js/components/EducationDialog.js
static/js/components/EducationDisplay.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/User.js
static/js/components/UserPagePersonalDialog.js
static/js/flow/declarations.js
static/js/flow/generalTypes.js
static/js/flow/profileTypes.js
static/js/industries.js
static/js/language_codes.js
static/js/reducers/index.js
static/js/reducers/ui.js
static/js/store/configureStore.js
static/js/util/ProfileFormFields.js
static/js/util/courseList.js
static/js/util/editEducation.js
static/js/util/profile_edit.js
static/js/util/util.js
static/js/util/validation.js

closes #522 (I guess?)
This adds the flow typechecker to our project. This comprises a few changes:
- adding the package for the typechecker itself (flow-bin)
- a babel plugin to automatically strip out flow type annotations
- two eslint plugins to handle imported types correctly
- adding a bunch of type annotations to our code
Make sure nothing is broken! I think I only added annotations and didn't change any functionality, but it's a little hard to be sure.
You'll need to rebuild your docker containers for the typechecker to work, once you have you should be able to do:
```
docker-compose run watch npm run-script flow
```
to type-check the code.

Added flow typechecking for JS

---

static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/User.js
static/js/util/ProfileFormFields.js

this closes #533 
This removes the switch from the user page, by adding a boolean prop to `EmploymentForm` which we can set to `false` whenever we want to hide the switch.
Make sure there no regressions in adding items and so on (on `/profile/professional`, the user page will not be usable until #540 is merged).

Hide switch on user page

---

static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js

closes #550 
Passes the correct profile object into the `<Jumbotron>` component from `ProfilePage`.
Make sure that all pages with a Jumbotron (`/dashboard`, `/terms_of_service`, `/profile`) display the pretty printed ID.

Fixed bug with MM id in Jumbotron

---

static/js/components/CourseList.js
static/js/constants.js
static/js/constants_test.js
static/js/util/courseList.js
static/js/util/courseList_test.js

Fixes #473
Uses the `sr-only` CSS class to show some text only for screen readers, specifically which run the button applies to. Also refactored the `DASHBOARD_RESPONSE` constant to have all possible course status cases so we can see them at a glance.
Also switches the bootstrap chevron icon with the menu one
static/js/util/courseList.js
Stub in `DASHBOARD_RESPONSE` in the `getDashboard()` function in `api.js`. View the dashboard. You should see `ENROLL` and `UPGRADE TO VERIFIED` buttons, one of each. If you inspect each button and look at the text inside the element there should also be the run title.
http://stackoverflow.com/questions/19758598/what-is-sr-only-in-bootstrap-3

Made enroll and upgrade buttons accessible

---

static/scss/layout.scss

Fixes #465 
Sets the container div for the loader to use relative positioning so the inner spinner will be centered within that, rather than centered inside the entire page.
In `api.js` replace `getUserProfile` with this:
export function getUserProfile(username) {
return new Promise(resolve => {
setTimeout(() => {
resolve(mockableFetchJSONWithCSRF(`/api/v0/profiles/${username}/`));
}, 100000);
});
}
This will delay the load of the user page for 100 seconds. Go to `/users/` and see that the spinner is where it should be. You should be able to resize the browser without affecting the position of the spinner.

Fixed spinner positioning

---

npm-shrinkwrap.json
package.json
webpack.config.shared.js

Fixes #609 
Requires `babel-polyfill` for the `dashboard.js` required code. This is required for certain new pieces of the standard library like `Object.assign`
Download the IE11 virtual machine from IE11 and run the micromasters site from it.

Added babel-polyfill to support IE11

---

static/js/containers/ProfilePage.js

this closes #581 
very little :P 
Go to `/profile/personal`. Note that `preferred_name` in the banner up top matches the entry in the form. Update the form (append `'_test'` or something) and click 'save and continue'. The 'preferred name' displayed up to should update.

Fixed bug with preferred name not updating on Jumbotron

---

README.md
cms/templates/cms/footer.html
cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
micromasters/settings.py
static/js/components/Footer.js
static/js/components/Header.js
static/js/components/PersonalTab.js
static/js/containers/ProfilePage.js
static/js/containers/TermsOfServicePage.js
static/js/util/ProfileFormFields.js
ui/templates/dashboard.html
ui/views_test.py

Fixes #557 
Removes apostrophe from MicroMaster's to become MicroMasters. Some apostrophes are left if they make sense in context
Grep through the code base to make sure all existing uses are updated, if relevant to the context

Removed apostrophe from MicroMaster's

---

.gitignore
README.md

Closes #450 
Updates our README to reflect updated edX docs, the new auth process, and a couple other minor details
If you feel particularly enterprising, you can run through the entire README to confirm the accuracy of these instructions

Updated documentation to reflect edX changes

---

cms/models.py
cms/templates/cms/program_page.html

fixes #528 
Puts the courses tab before the FAQ one in the program page
`program_page.html`
Create a program page in the CMS and verify that the tabs are in the right order
To fix the issue was enough to change the order of the Nav tabs. I changed the order of the rest just to be consistent and to avoid confusion in the future.

Swapped courses and faq in program page

---

static/js/components/EmploymentForm.js
static/js/flow/declarations.js
static/js/util/sorting.js
static/js/util/sorting_test.js

closes #584 
This adds a function to `util.js` that takes an `Array<EmploymentEntry>` and returns a sorted array (in resume order). Then we can just call this on `profile.work_history` before we draw the UI to get things in the right order.
Check out the changes to `util/util.js` and make sure the tests all look legit.
Add a variety of employment entries, with and without end dates, and check that the following sort order is displayed on `/users` and on `/profile/professional`:
- 'current' entries (w/out an end date) should be displayed first, as a group
- 'current' entries should be ordered by start date
- 'non-current' entries should appear after all 'current' entries
- 'non-current' entries should be ordered by end date

Sorted employment entries in resume order

---

static/js/actions/ui.js
static/js/components/ConfirmDeletion.js
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js

closes #482 
This adds a pop-up dialog that asks you to confirm deleting entries when toggling switches on the work history and education forms. Basically, this means that if you have entries saved and you try to turn the switch off you have to either affirm your intention to delete all the entries, or cancel turning off the switch. It shouldn't be possible get into a state where there are invisible history entries which will be saved upon clicking 'save and continue'.
I guess start with the changes to `EmploymentForm`, `EducationForm`, and `ConfirmDeletion`.
Visit `/profile/professional` and `/profile/education`. On the former
- confirm that you can freely toggle the switch when no work history is entered
- confirm that entering a work history entry causes the pop-up to appear upon …

Added 'confirm delete all entries' when closing switches

---

static/js/dashboard.js
static/js/style.js

Fixes #620 
Moves the react-mdl CSS back into dashboard.js. It overrides many common style rules which is why we're seeing different styles with it included. We're only using bootstrap CSS on the 404 page currently so this shouldn't cause any problems.
First, turn on DEBUG mode so we can view the 404 page. You can do this by setting `DEBUG=False` in `settings.py` and adding your host name to the `ALLOWED_HOSTS` list.
Then run `NODE_ENV=production ./webpack_if_prod.sh` in your terminal to generate static assets. Next, run `docker-compose run web ./manage.py collectstatic` to copy static assets into `staticfiles/`.
After that, look at the two screenshots for the program page in #620. Go to a program page and verify that it looks like it did before, more or less. Go to `/xyz/` and verify the …

Fixed style regression

---

micromasters/urls.py
ui/templates/500.html
ui/urls.py
ui/views.py
ui/views_test.py

closes #487 
Adds a custom 500 page
`ui.views` and then '500.html'
to see the the 500 template, just go to `/500/`.
To actually test that a 500 is returned for a error, you need to:
- set the debug to False in your `docker-compose.yml`
- run `node node_modules/webpack/bin/webpack.js --config webpack.config.prod.js --bail` to build the static assets
- run `docker-compose run web ./manage.py collectstatic` 
- raise any exception in a view like `ui.views.dashboard`

Added custom 500 page

---

static/js/components/AutoComplete.js

Fixes #547 
When the user clicks an autocomplete field, it should show all options. If the user types text it filtered based on that text, but when they click again it shows all options. This PR changes the behavior to continue to show filtered results in this case.
Go to the /users/ page and find an AutoComplete field. Then look for these scenarios:
- Clear the select field, focus away from field. Click on field again and make sure you see all entries. Type text and verify that it shows only entries whose prefix matches the text. Click on the text field and verify that the options you see haven't changed.
- Select an option and focus away from field. Click on the text field and verify that you see all options. Click again and you should see only the filtered fields.
- Select an option …

Fixed filtering text to remain if textbox clicked

---

profiles/permissions.py
profiles/permissions_test.py
profiles/serializers.py
profiles/serializers_test.py
profiles/views.py
profiles/views_test.py

fixes https://github.com/mitodl/micromasters/issues/483#issuecomment-225736543
- Raised 404 exception when user wants to access someones profile whose privacy mode is set tp private
- see ```profiles/views.py```
- Open api for user whose [**account_privacy = private**](http://ip:8079/api/v0/profiles/{user_name}/)
@pdpinch  @aliceriot  @giocalitri 
- In case **account_privacy = private**:
- In case **account_privacy = public_to_mm**:
- In case **account_privacy = public**:

Raised 404 from users API for users with privacy setting set to "private" 

---

static/js/components/PrivacyTab.js
static/js/containers/ProfilePage_test.js

closes #576 
removes validation of the education and work history UI state when saving on the `PrivacyTab`.
Follow the description of the repro for the problem on the issue: #576, and confirm that you can successfully save on `/profile/privacy`.

Removed UI validators from PrivacyTab validator callback

---

static/js/util/profile_edit.js

Fixes #577
Removes padding inserted on the date field. I think I added this padding to make space for the validation text, but the text fields should already have this space
In the users page go to the graduation date in the education dialog, the start date in the employment dialog and the date of birth in the personal dialog. Cause a validation error in each case and make sure that everything still looks fine.

Removed padding from date field

---

.flowconfig
package.json
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/UserPage_test.js
static/js/util/sorting.js
static/js/util/sorting_test.js
static/js/util/validation.js

closes #583 
Adds a little function to sort education entries by `graduation_date` in resume order, which we can use in `EducationDisplay` and `EducationForm`.
Make sure that:
- on the user page all education entries are presented in a single list in resume order, and you can add/delete/edit entries as usual.
- on `/profile/education` make that that, for each degree level, the degree entries within that level are sorted by resume order, and, again, that you can do all the normal actions on entries.

Added resumeOrder to education entries

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfilePage_test.js
static/js/util/validation.js
static/js/util/validation_test.js

Fixes #532 
Updates the validation text, and changes the CSS class to have validation text line up with title text.
Cause a switch validation error in education and employment pages

Updated validation text

---

static/js/containers/TermsOfServicePage.js
static/js/containers/TermsOfServicePage_test.js

Fixes #633 
Shows the same text on the terms of service page that we show on the profile page.
Create a new user on edX, login to MicroMasters with it and view the terms of service page. It should have the 'Welcome username, let's complete...' text. Note: it's important to have a brand new user to make sure that we handle the empty preferred name case correctly.

Added text to JumboTron for terms of service

---

static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js

Fixes #587 
Adds a spinner to the dashboard page when it is loading, and moved some dashboard tests from `App_test.js` into new `DashboardPage_test.js`
View the dashboard over a slow connection. To simulate a slow connection replace the function in `api.js` with this:
export function getDashboard() {
return new Promise(resolve => {
setTimeout(() => {
resolve(mockableFetchJSONWithCSRF('/api/v0/dashboard/', {}, true));
}, 3000);
});
}

Added spinner for dashboard

---

static/js/containers/LoginButton.js
static/js/containers/UserPage_test.js
static/js/global_init.js
ui/url_utils.py
ui/urls.py
ui/views.py
ui/views_test.py

Fixes #481
Fixes #630 
Fixes two problems:
- If a user goes to `/user/missing` (or some user who is invisible due to permissions), they will get a 404 page
- Anonymous users may now look at the users page for a particular user
ProfileFormContainer.js
- Go to `/users/<name>` with a name that doesn't match an account on the server, and verify that it shows the 404 page
- Log out, then view that users page again. You should see a users page with a sign in button, with no ability to edit fields.

Redirected to 404 if user goes to a missing user page

---

.flowconfig
package.json
static/js/actions/ui.js
static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/Jumbotron.js
static/js/components/PersonalTab.js
static/js/components/PrivacyForm.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage.js
static/js/dashboard_routes.js
static/js/flow/profileTypes.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/util.js
static/js/util/util_test.js
static/js/util/validation.js
static/js/util/validation_test.js
ui/urls.py

closes #627 
This changes the way we progress through the initial profile form sequence. Currently, there's a separate url for each component (`/profile/personal -> PersonalTab`, etc), with the `/profile` route rendering the `ProfilePage` component and the tab component routes nested inside. This changes things so that:
- there's a redux action added to the ui reducer to keep track of what step the user is on (`profileStep`)
- `ProfilePage` pays attention to this bit of state and selectively renders the right tab component
- `ProfilePage` also passes in `nextStep` and `prevStep` callbacks (which either update the store or cause a react-router route transition) which the tab components can pass to `ProfileProgressControls`
- generating props for child components on `ProfileFormContainer` …

Removed routing from initial profile flow

---

static/js/actions/index.js
static/js/constants.js
static/js/containers/DashboardPage_test.js
static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/reducers/index.js

Fixes #588 
If the profile page is loading it should show a spinner while it loads. If the page is errored you should see an error alert box with the appropriate text.
static/js/containers/ProfilePage.js
To test the spinner, replace the function in `api.js` with this function:
export function getUserProfile(username: string) {
return new Promise(resolve => {
setTimeout(() => {
resolve(mockableFetchJSONWithCSRF(`/api/v0/profiles/${username}/`));
}, 3000);
});
}
This will cause a 3 second delay before any loading is done giving you time to see the spinner.
To test the error page, replace the same function with this code:
import { ERROR_RESPONSE } from '../constants';
export function getUserProfile(username: string) {
return Promise.reject(ERROR_RESPONSE);
}
This will cause the page to …

Added spinner and error message for profile page

---

cms/templates/cms/program_page.html

closes #604 
Makes the FAQ collapsed by default
it is a one line change
verify that the FAQ are collapsed by default in the program page

FAQ collapsed by default

---

static/js/containers/UserPage_test.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util.js
static/js/util/validation.js
static/js/util/validation_test.js

closes #585 and closes #586 
This changes the text fields in `boundDateField` so that they only accept characters that can comprise valid inputs. So, no non-numerical characters, no characters beyond the number required for the field in question, etc.
Review the changes to `profile_edit.js` and `validation.js`. 
Make sure you can edit and save valid dates for all date fields we have.
Also, check for the following behavior, which this PR implements:
month field:
- should accept only 2 characters
- should not accept non-numerical characters
- should only allow input of 1-12
- input of numbers larger than 12 should correct to 12
day field:
- should accept only 2 characters
- should not accept non-numerical characters
- should only allow input of 1-31
- input of numbers larger than 31 should …

prevented non-numbers from being entered in date fields

---

static/js/containers/UserMenu.js
static/js/util/util.js
static/js/util/util_test.js

this closes #529 
This changes the `getPreferredName` function from `util.js` so that it accepts a second positional argument (a boolean) that, if true, causes it to return the first and last name (provided the profile passed in has a last name on it).
Make sure you get first and last name on `/dashboard`, `/terms_of_service`, `/settings`, and `/profile`. If you set `last_name` to be `None` on your profile you should still see your first name in those places.

Changed preferred name display

---

static/js/containers/App.js
static/js/containers/TermsOfServicePage_test.js
static/js/flow/profileTypes.js

closes #634 
This adds an additional check to the `requireCompleteProfile` method on `App.js`, which ensures that we don't get a race condition relating to the terms of service page.
The race condition emerges when a user is signing in to micromasters for the first time. They get shown the terms of service page, and when they agree the following happens:
- we dispatch an asynchronous action to `PATCH` the updated user profile (with `filled_out === true`)
- the `profiles.username` object is updated (`patchStatus: FETCH_PROCESSING`)
- the store change triggers `componentDidUpdate` on `App.js`
- we call the `requireCompleteProfile` method on `App.js` from the `componentDidUpdate` method
- the pathname is still `/terms_of_service` (remember that the asynchronous `PATCH` response hasn't yet …

Fixed bug where validation errors showed up on first login

---

static/js/actions/ui.js
static/js/components/EducationDialog.js
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/PersonalForm.js
static/js/components/PersonalTab.js
static/js/components/PrivacyForm.js
static/js/components/PrivacyTab.js
static/js/components/ProfileProgressControls.js
static/js/components/User.js
static/js/components/UserPagePersonalDialog.js
static/js/components/inputs/CountrySelectField.js
static/js/components/inputs/SelectField.js
static/js/containers/ProfileFormContainer.js
static/js/containers/UserPage_test.js
static/js/flow/generalTypes.js
static/js/flow/profileTypes.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/ProfileFormFields.js
static/js/util/editEducation.js
static/js/util/profile_edit.js

this closes #549 
This changes the validation setup so that when the user fixes a validation error (fills out a required field, enters a valid date, etc) the error will be removed automatically. Really, we're just re-validating the profile.
Review the changes to `actions/ui.js` and the changes to `setWorkHistoryEdit` on `EmploymentForm.js`, and the changes to `setEducationDegreeInclusions` on `EducationForm.js`.
There are also some changes comprising adding types (esp `props` declarations) to files or classes which didn't previously have them.
Visit `/users` and `/profile`. For every input on those pages (and in all stages of filling out the profile) the following should hold:
- make an invalid input (empty text field, invalid selection for 'preferred language', etc)
- click save
- …

Updated validation state when editing fields

---

static/js/actions/ui.js
static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage.js
static/js/flow/generalTypes.js
static/js/flow/reduxTypes.js
static/js/reducers/index.js
static/js/reducers/ui.js
static/js/util/redux.js
static/js/util/redux_test.js

this closes #712 
Just abstracts out a little bit of boilerplate. We had a lot of helper methods on `ProfileFormFields` like the following:
```js
dispatchSomeAction: Function = (arg: someType): void => {
const { dispatch } = this.props;
dispatch(someAction(arg));
};
```
this abstracts that pattern, so instead we do:
```js
createActionHelper: Function = (actionCreator: Function): (...args: any) => void  => {
const { dispatch } = this.props;
return (...args) => dispatch(actionCreator(...args));
};
createActionHelper(someAction);
```
We can do this for most of the action creator helpers we had on `ProfileFormFields`, although anything with more specialized logic than the example above (e.g. `saveProfile`) needs to be left alone.
Read over the changes.
Make sure there are no regressions on …

Refactored ProfileFormContainer to remove boilerplate

---

static/js/components/Jumbotron.js
static/js/components/ProfileImage.js
static/js/components/User.js
static/scss/dashboard.scss

closes #735 
This just adds a small utility component that takes a `Profile` and displays the user's profile image.
Take a look at the new class, make sure it makes sense.
You should still see the same profile image when you go to the dashboard or to the `/users` page.
I want to use profile images in a couple more places in the searchkit and user menu PRs, this is just a small atomic change in that direction.

Added new ProfileImage component

---

static/scss/navbar.scss

closes #741 
just sets `box-shadow: none !important` on the navbar.
Make sure the navbar doesn't have a shadow. I couldn't get the styling to apply without `!important`, if you know of a sneaky way to avoid using the important keyword that would be :100: (I think some of the difficulty is because some styles are applied via JS by material design lite).

Removed box-shadow from Navbar

---

static/js/components/EducationDialog.js
static/js/components/EmploymentForm.js
static/js/components/UserPagePersonalDialog.js

closes #748 
We need to pass a username to the `clearProfileEdit` action helper because redux has to know the username for which it should clear the `edit` object. We weren't doing so, which meant that validation errors that should have been removed by `clearProfileEdit` were hanging around and doing some strange things.
Read over the code!
Currently, on master, if you do the following:
1. go to `/users`
2. create a validation error on the personal info form
3. click 'save'
4. click 'cancel'
you should see the `clearProfileEdit` action being dispatched, but if you inspect the redux state you'll note that the `edit` object is actually still there (`profiles -> ${username} -> edit`). The same holds for editing a work history or education history entry.
Basically, these changes should ensure …

pass the username to clearProfileEdit

---

static/js/components/EducationDialog.js
static/js/components/EmploymentForm.js
static/js/components/PersonalTab.js
static/js/components/PrivacyTab.js
static/js/components/UserPagePersonalDialog.js
static/js/components/ValidationAlert.js
static/js/containers/UserPage_test.js
static/scss/layout.scss
static/scss/validation-alert.scss

this closes #635 
This adds a visual indicator to the profile dialogs which lives right above the 'cancel' and 'save' buttons. If there's a validation error it will look like this:
Otherwise it looks as it currently does on master.
Read the changes!
Go to `/users` and do the following:
1. open the personal info dialog
2. enter something invalid (like deleting your last name)
3. click 'save'
4. confirm the message shows up
5. fix the error (add a last name)
6. confirm the error message goes away
then do the same thing for the education and work history dialogs as well.

implemented ValidationAlert to alert user to problems in form dialogs

---

static/js/containers/ProfileFormContainer.js
static/js/util/redux.js
static/js/util/redux_test.js

closes #788 
Removes the call to `.name` on anonymous functions, because this value isn't invariant under minification (the variable name the function is bound to changes to `a` or something).
Make sure that there are no changes in any of the profile functionality.

Removed .name call on anonymous functions for createActionHelper

---

static/js/components/inputs/SelectField.js
static/js/containers/ProfileFormContainer.js
static/js/containers/UserPage_test.js
static/js/global_init.js
static/js/util/integration_test_helper.js
static/js/util/profile_edit.js
static/js/util/util.js
static/js/util/util_test.js

closes #561 
This adds a little bit of code that basically does two things.
1. Sets a class (`.invalid-input`) on a profile input field that currently has a validation error.
2. Whenever we save the profile we find the first such input (`document.querySelector` to the rescue) and call `.scrollIntoView` on it.
On a bigger screen this has no visual effect. However, on a shorter screen (e.g. one where the content in the dialog box might overflow and have an invisible scrollbar) it will cause that div to scroll to the location of the invalid field, prompting the user for their input.
1. go to `/users`
2. open dev tools or otherwise make your viewport really short
3. open the 'personal' dialog
4. delete your last name
5. scroll down to the bottom of the dialog content
6. click 'save'
when you …

added 'jump to error'

---

profiles/permissions.py
profiles/permissions_test.py
profiles/views.py
profiles/views_test.py

Fixes #89 
Enforces permissions on the profiles API
profiles/permissions.py
Create two users and a program if necessary. One user should have `account_privacy` set to private and be assigned to the program in the `ProgramEnrollment` model. The other user should have an instructor or staff role added for the same program using the `Role` model.
Log in as the instructor or staff, then view the profile of the other user by going to `/api/v0/profiles/username/`. You should see everything that that user can see for their own profile. For example you should see `agreed_to_terms_of_service` which is not shown even in public profiles to other students.

Enforced permissions on profiles REST API

---

search/api.py
static/js/components/LearnerSearch.js
static/scss/search_page.scss

Fixes #785
Replaces the country facets with a hierarchical facets
LearnerSearch.js
Run `./manage.py recreate_index`. Then go to the learner search and try faceting on a state or territory
`profile` and `program` don't need to be nested because there is only one of them, so these are now indexed as `object`. We don't have checkboxes for now because there's no equivalent `itemComponent` prop available for `HierarchicalMenuFilter`. Also, countries and states are translated in the Javascript, but we may want to change our indexing to store with their full names in the future.
`birth_country` was left alone because we're planning on removing `birth_state_or_territory` in the near future: #737

Replaced filtering with hierarchical filtering

---

micromasters/urls.py
roles/api.py
roles/api_test.py
search/base.py
search/permissions.py
search/permissions_test.py
search/views.py
search/views_test.py
static/js/containers/LearnerSearchPage.js

closes #701 
Introduces a REST API to proxy requests to elasticsearch, enforce permissions and limit results to allowed ones
`search.views`
In your `.env` you should set the variable
`ELASTICSEARCH_URL=http://elastic:9200` (not sure about the actual value for not Mac users) 
To check that the rest API actually works, access its url `/api/v0/search/`
To verify that searchkit works, edit your `.env` file and include/edit the entry
`CLIENT_ELASTICSEARCH_URL=http://<your_ip>:8079/api/v0/search/`
You should also verify that the user cannot see students from programs he is not supposed to.
To do that, load fake users with the proper management command and make your user `Staff` of only one of these programs.
This PR does not take care of setting a basic filter for the program at the SearchKit …

Search REST API Proxy

---

static/js/components/EmploymentForm.js

this closes #835 
I had inadvertently stopped passing a `key` prop to the JSX returned from the `jobRow` method on `EmploymentForm`. We map across the work history objects with this method (`work_history.map(entry => this.jobRow(entry)`), which is what triggered the warning.

fixed JS console error ('key' prop required)

---

static/js/components/ErrorMessage_test.js
static/js/components/search/CountryRefinementOption_test.js
static/js/components/search/FilterVisibilityToggle_test.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/constants.js
static/js/flow/programTypes.js
static/js/flow/searchTypes.js

Closes #681 
Adds the program grade average to search results (when it exists). Also made a minor refactor to a few assertions in other JS test cases
static/js/components/search/LearnerResult.js
Go to the search tab and observe the grades. It will help to have users in your DB with actual grades, so the realistic user set is useful here.
w/r/t the assertion refactor: i just saw test cases that could use a more accurate assertion in the same file that i was editing, so i fixed those. it was easy enough to search for other examples in the codebase, so i fixed those too. when these test fail, it now prints out a more helpful message
https://66.media.tumblr.com/tumblr_megu6kysDx1rg0w3to1_500.gif

Added program grade to search result UI

---

static/js/components/LearnerSearch.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/scss/_variables.scss
static/scss/search_page.scss

Closes #731 
Adds the program grade range filter to the search page
Load up the search page and mess around with the range filter. Note that learners with no program grade should be shown _only_ when the range filter is set to the full range

Added program grade filter and histogram to UI

---

package.json

Fixes the webpack build for node 5.11 which heroku uses

Replaced var with let

---

static/js/actions/email.js
static/js/actions/email_test.js
static/js/actions/ui.js
static/js/components/EmailCompositionDialog.js
static/js/components/EmailCompositionDialog_test.js
static/js/components/LearnerSearch.js
static/js/containers/LearnerSearchPage.js
static/js/containers/UserPage_test.js
static/js/reducers/email.js
static/js/reducers/email_test.js
static/js/reducers/index.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/test_utils.js
static/scss/_button.scss
static/scss/email_composition_dialog.scss
static/scss/layout.scss

this closes #719 
This adds the ui for sending email to users based on a search query. The API isn't there yet, so for now we just dump the email on the floor when you click send.
Read over the new changes, especially the `EmailCompositionDialog` component and the new email reducer.
Go to the `learners` page. Click 'Email Selected', then you should see a dialog box. The 'recipient count' in the box should match what is shown in the normal search interface. You should be able to edit the 'subject' and 'body' fields in the email. Editing these fields should dispatch redux actions. You should be able to click the 'send' button, but it will just `console.log` the email for now.
Also, if you inspect the redux store, you should see the search query stringified in there, so we'll have it ready …

UI for sending learner email

---

static/js/util/integration_test_helper.js

Passes an enzyme wrapper as the first argument of `renderComponent` instead of the React component. We don't actually use the component anywhere at the moment so this shouldn't cause any problems

Switched to use enzyme in IntegrationTestHelper

---

static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage.js
static/js/util/validation.js
static/js/util/validation_test.js

closes #821 
This removes all of the validation code relating to the 'yes' / 'no' switches on the education and work history forms. The switches are still there, we just do not validate their position any longer.
When navigating the profile (e.g. on the education step), having a switch switched to 'yes' shouldn't cause a validation error when you click 'Next'.

Removed switch validation from profile flow

---

static/js/actions/email.js
static/js/actions/email_test.js
static/js/components/EmailCompositionDialog.js
static/js/components/EmailCompositionDialog_test.js
static/js/components/LearnerSearch.js
static/js/containers/LearnerSearchPage.js
static/js/reducers/email.js
static/js/reducers/email_test.js
static/js/util/validation.js
static/js/util/validation_test.js
static/scss/_variables.scss
static/scss/email_composition_dialog.scss

this closes #888 
This adds a new function to `util/validation.js` to check the email fields, and then adds some UI to show the validation errors if they are present.
Read over the changes to `util/validation.js`. I had to refactor the email reducer a bit as well, probably important to look that over closely.
Go to the learners search. Click the 'Email Selected' button. If you then click 'send' you should see two validation errors (no subject and no body).
These errors should go away as you fix the problems. You shouldn't be able to 'send' the email (currently `send === console.log`) until the validation errors are cleared away.

added validation to the email composition dialog

---

static/js/actions/index.js
static/js/actions/ui.js
static/js/flow/dashboardTypes.js
static/js/flow/reduxTypes.js
static/js/util/api.js
static/js/util/redux.js

Fixes #908 
Adds a type to the `Dispatcher` so different dispatcher types can be distinguished when flow is run

Added generic type to Dispatcher

---

js_test.sh
static/js/util/profile_edit.js
static/js/util/util.js

Fixes #910 
Fixes #909
Fixes some React warnings and adds a check to fail the build if they come up again
js_test.sh
Try undoing one of the fixes and running the tests. All tests should pass but the command should return a non-zero value due to the warning, failing the tests overall.

Fixed react warnings, added check to error on React warnings

---

micromasters/settings.py
ui/views.py
ui/views_test.py

Fixes #839 
Removes CLIENT_ELASTICSEARCH_URL setting, this should always point to `/api/v0/search/` now
You should be able to remove CLIENT_ELASTICSEARCH_URL from `.env` and restart Docker. Search should be unaffected.

Removed CLIENT_ELASTICSEARCH_URL environment variable

---

static/scss/layout.scss
static/scss/terms_of_service.scss
ui/templates/header.html
ui/templates/terms_of_service.html
ui/url_utils.py
ui/urls.py
ui/views.py
ui/views_test.py

this closes #948
This PR adds a new standalone page to display the terms of service. It's a django template with the same look-and-feel as what we have on the dashboard pages.
For this I also implemented a new header partial, which we'll hopefully be able to use on the homepage.
Read over the code, make sure it makes sense?
You should be able to visit `/terms_of_service`, when logged in or no, and see there ToS there.

Added new terms of service page

---

.gitignore

I believe there are plans to fix this issue, but I think we should add this until we sort out the fix.

add celerybeat-schedule to gitignore

---

search/base.py

Fixes #721
- Adds `MockedESTestCase` to mock Elasticsearch to speed up tests which don't use it
There shouldn't be any non-testing code changed

Added test case to mock out Elasticsearch to speed up tests

---

static/js/actions/email.js
static/js/components/EmailCompositionDialog.js
static/js/components/EmailCompositionDialog_test.js
static/js/components/LearnerSearch.js
static/js/containers/LearnerSearchPage.js
static/js/flow/emailTypes.js
static/js/reducers/email.js
static/js/reducers/email_test.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/validation.js

Closes #889 
Hooks up the micromasters front end to the mail API endpoint
Probably static/js/util/api.js, static/js/actions/email.js, and static/js/reducers/email.js
Use the 'Email Selected' button on the search to send an email. Since this PR doesn't implement the actual sending of the email, you can effectively stub out the sending functionality by replacing the body of mail.views.MailgunViews.post with this:
```python
if request.data['email_subject'].startswith('error'):
status = 400
else:
status = 200
return Response(
status=status
)
```
That will allow you to test an error in the view if you use something that starts with 'error' in the subject line. If you'd like to send an actual email, you'll need the Mailgun API key.

Hooked up front end to mail API endpoint

---

profiles/serializers.py
profiles/serializers_test.py
profiles/views.py
profiles/views_test.py

Fixes #847
If `filled_out` is true or is being set to true, it does some extra validation on the profile data. See the issue to see what is being validated and what is skipped.
In the user page for your own user, try clearing the end date for some field of employment. You should still be able to.
Then, go to `/api/v0/profiles/your_user_name_here/`. Try to PATCH a profile to clear a field, eg
{
"country": ""
}
You should see 'This profile may not be blank'

Added some server side verification for profiles

---

dashboard/factories.py
dashboard/serializers_test.py
dashboard/signals.py
dashboard/signals_test.py
search/indexing_api_test.py

Part 5 of #796
`CachedEnrollment` and `CachedCertificate` no longer automatically create `ProgramEnrollment`s when they are created. To create a `ProgramEnrollment` the user must now use the REST API
Delete all `ProgramEnrollment` using the Django shell or admin. Go to the dashboard. Wait five minutes, refresh the dashboard. Verify that there are still no `ProgramEnrollment`s in the database. Then add back the `ProgramEnrollment`s you created in the first place using the shell.

Removed signals creating or deleting a ProgramEnrollment

---

static/js/util/api.js
static/js/util/api_test.js

Fixes #973 
Fixes a bug where the search request API param was named incorrectly when passed to the mail API endpoint.
Go to the search page, apply a filter or two, and send an email with MAILGUN_RECIPIENT_OVERRIDE set in your .env. You should see the correct intended recipients in the email body

Fixed key name for search request API param

---

profiles/factories.py
profiles/serializers.py
profiles/serializers_test.py
profiles/views_test.py

Fixes #971
Makes edx_level_of_education readonly to prevent users from overwriting its value, and to fix a `filled_out` validation error when it was blank
In the Django shell set your `Profile`'s `edx_level_of_education` to `None`. Then try to edit your profile. No validation errors should be seen and you should get a 200 back from the server.

Made edx_level_of_education read only

---

courses/views_test.py

Fixes #977
Renames `courses/views_tests.py` to `courses/views_test.py` and fixes the test failures in the test
Look in the Travis output and make sure that there are tests being executed under `courses/views_test.py` and that they all pass.
I think we should get rid of the courses and programs API altogether since we don't use them: #237

Fixed course tests

---

courses/views.py
courses/views_test.py

Part of #969
Filters out program enrollments for programs that aren't live. We filter this in the REST API when the user POSTs to create the program enrollment but there's still the possibility a program may stop being live at some point in the future, so we should filter on GET too.
Go to `/api/v0/enrolledprograms/`. Make sure there is at least one enrollment there. In the Django shell set `live=False` for that program. Go to `/api/v0/enrolledprograms/` and see that this program enrollment no longer appears in the API.

Filtered out programs which are not live from program enrollments API

---

dashboard/admin.py
micromasters/settings.py
search/indexing_api.py

closes #782
Adds authentication key for elasticsearch.
It also adds a new admin (I needed to do some tests and I left it), but this is not necessary for this PR.
The key is not mandatory and is used only if set. 
If the backend is not set up to handle authentication, even if the key is set, everything will keep working.
`search/indexing_api.py`
This part is tricky: the docker elasticsearch should keep working. The actual authentication should be tested against the elasticsearch cluster when @blarghmatey finishes to set it up

Added elastisearch auth

---

static/js/actions/enrollments.js
static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/Navbar.js
static/js/components/NewEnrollmentDialog.js
static/js/components/NewEnrollmentDialog_test.js
static/js/components/ProgramFilter.js
static/js/components/ProgramSelector.js
static/js/components/ProgramSelector_test.js
static/js/components/Toast.js
static/js/containers/App.js
static/js/containers/DashboardPage.js
static/js/reducers/enrollments.js
static/js/reducers/enrollments_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/dashboard.scss

Fixes #796 
Adds a dialog box which opens when the user clicks 'Enroll in a new program'. This dialog is used to add a new `ProgramEnrollment` for the user.
Make sure you are not enrolled in every live program. Then you should see the link in the program selector. Note that:
- If you select the 'Enroll in a new program' option, it should not change the currently selected program displayed in the dropdown.
- If you click 'Cancel' the dialog should close and nothing should change.
- If you click 'Enroll' without a program selected you should get a validation warning. (The warning should disappear if you close and open the dialog again.)
- You should see only programs you have not yet enrolled in.
- When you select a program and click 'Enroll', it should close the dialog immediately and POST …

Added enrollment dialog

---

static/js/util/profile_edit.js
static/js/util/sanctuary.js
static/js/util/sanctuary_test.js
static/js/util/util.js
static/js/util/util_test.js
static/js/util/validation.js
static/js/util/validation_test.js

closes #985 
This PR disables the runtime type checking (see [this](https://github.com/sanctuary-js/sanctuary-def)) for Sanctuary in production. Optionally, it could be disabled in development as well, by editing a file. This significantly speeds up the date fields (which are using sanctuary's `Maybe` type constructor).
I think we want to keep the runtime type-checking in development, because if you're using the sanctuary stuff at all it's actually super helpful. However, it's pretty slow, so I think we should definitely turn it off for production.
Make sure the changes look legit. I was following along with what the sanctuary repo recommends here: https://github.com/sanctuary-js/sanctuary#type-checking
Pull down the code. Go to a profile editing page (either `/users` or `/profile`) and …

Disabled SanctuaryJS run-time type checking in production

---

static/js/components/PrivacyForm.js
static/js/containers/SettingsPage.js
static/js/containers/SettingsPage_test.js
static/js/util/profile_edit.js
static/scss/_button.scss
static/scss/profile.scss

Fixes https://github.com/mitodl/micromasters/issues/936
- See settingpage.js 
- From menu go to settings page
@aliceriot @pdpinch @gsidebo

Fixed settings page styling

---

dashboard/api.py
dashboard/api_test.py
profiles/management/realistic_program_data.json
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CoursePrice.js
static/js/components/dashboard/util.js
static/js/flow/programTypes.js
static/scss/_button.scss
static/scss/dashboard.scss

this closes #937 
These things:
- new boolean field on `Program` (`personalized_pricing`) which represents whether a program has a personalized pricing scheme or not.
- some new functions in `CourseListCard.js` which will show the right UI if a program does have `personalized_pricing === true`.
- tests n stuff
- I also changed the program data in `realistic_program_data.json` to have `personalized_pricing = true` on the digital learning program
Pull down the code and then do this:
1. blow away your search data:
```zsh
./manage.py delete_realistic_search_data
```
2. add new search data:
```zsh
./manage.py gen_realistic_search_data --staff-user ${username}
```
3. navigate to `/dashboard`. You should see the financial aid box when you have the `digital learning` program selected, but not …

Added personalized pricing to the dashboard

---

.travis.yml

closes #1030 
this basically adds an `install` section to `travis.yml`, and puts a command to build the docker containers in there, and the command to install JS packages. This basically results in the output of these commands being collapsed by default when you look at the build output, which means it's a lot shorter to scroll through (and it's easier to see the tests!).
Make sure the build is still passing and all that.

change travis.yml around a little

---

dashboard/api.py
dashboard/api_test.py
dashboard/views.py
dashboard/views_test.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CoursePrice.js
static/js/components/dashboard/CoursePrice_test.js
static/js/constants.js
static/js/flow/programTypes.js
static/scss/dashboard.scss

Fixes #1032
- Removes the course status from the dashboard API. From now on the first run will have the appropriate status. If there are no runs 'Coming soon...' will be displayed, from [this mockup](https://projects.invisionapp.com/share/NB7VM1GSG#/screens/185611170)
- The `not-offered` status is removed because it was only used with the course status, not the run status.
- Handle case where there are no runs to display
If there are no future course runs for a given course (this is the default for the realistic fake data we have) then you should now see 'Coming soon...' similar to the screenshot. Otherwise all data should be the same as before.

Removed course status

---

roles/models.py
roles/models_test.py
ui/views_test.py

closes #1034
Enforces the existence of only one role type per user
`roles/models.py`
try to assign `Staff` and `Admin` to the same user in the django Admin
This is a limitation of the library we are using and given that there are thoughts to create a new `reviewer` role, it makes sense to be sure there is not confusion on this front.
There is a known issue with this code: even if in the Admin you get an error, there will still be a confirmation message. AFAIK this cannot be removed because the confirmation message is generated after the error message. I do not think this is a problem given that only people who access the Admin can see it.

Only one role per User can be assigned

---

static/js/components/LearnerSearch.js

closes #986 
Allows a user to select multiple values for the "Place of Birth" facet. Those values are treated in an 'OR' fashion - any user that matches any one of the values selected will be in the search results
Run the app and navigate to the learner's search page. Test with multiple values for Place of Birth
Due to some searchkit limitations, we've decided not to pursue the same change for Current Location (see issue comments for details)

Set "Place of Birth" facet to accept multiple values

---

README.md

Looks like the installation documentation is missing a step. [Here's the traceback that results when you don't migrate before recreating the index.](https://gist.github.com/singingwolfboy/3daa650b11aa790c389139b8495b08a1)

Improvements to installation process documentation

---

profiles/management/commands/delete_realistic_search_data.py
profiles/management/commands/gen_realistic_search_data.py

Closes #1038 
Fixes #1073 
As stated above, closes #1038 and applies a few other fixes. For example, ProgramEnrollment creation changed fundamentally since this script was written and this PR adjusts for that
Run `delete_realistic_search_data`, then `gen_realistic_search_data`. I'd recommend you run `gen_realistic_search_data` with a `--staff-user` argument to set up your own user with the proper enrollments and permissions (run `gen_realistic_search_data --help` for details)

Realistic user fixes for social username and program enrollments

---

npm-shrinkwrap.json
package.json
static/js/components/LearnerSearch.js
static/js/components/search/CustomPaginationDisplay.js
static/js/components/search/CustomPaginationDisplay_test.js
static/js/components/search/CustomResetFiltersDisplay.js
static/js/components/search/CustomResetFiltersDisplay_test.js
static/js/components/search/CustomSortingSelect.js
static/js/components/search/CustomSortingSelect_test.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/flow/eventType.js
static/js/util/util.js
static/js/util/util_test.js
static/scss/search-page.scss

- Fixes https://github.com/mitodl/micromasters/issues/934
- #851
- #854
- /learners/
- run ./webpack_dev_server.sh --install
- See LearnerSearch.js
@aliceriot @pdpinch @gsidebo

Fixed learners layout

---

static/js/actions/enrollments.js
static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/constants.js
static/js/containers/App.js
static/js/flow/generalTypes.js
static/js/reducers/enrollments_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js

Required for #904 
Makes the Toast component independent of enrollments
Unenroll in a program by removing a program enrollment from your user. Then add it back via the UI. You should see a Toast with check mark saying that the enrollment was a success.

Refactored Toast component

---

courses/factories.py
ecommerce/api.py
ecommerce/api_test.py
ecommerce/views.py
ecommerce/views_test.py
static/js/constants.js
static/js/constants_test.js
static/js/containers/App.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/flow/generalTypes.js
static/scss/dashboard.scss
ui/views.py

Fixes #904 
Fixes #905 
Handles showing the user a temporary toast message to indicate a successful order or a cancellation.
This deviates from the mockup a bit in that there's no link to the course page in the toast.
Ask me for the test credentials for Cybersource and go through the order process

Added order receipt and cancellation UI

---

cms/api.py
cms/api_test.py
cms/models.py
cms/templates/cms/program_page.html
courses/models.py
courses/models_test.py
ui/views_test.py

Fix #922 
Update the courses widget on program page to display start/end date, and enrollment information.
Create a program with few courses. For each course create a course run with the following possible parameters:
1. start date in the future, enrollment start date in the future
2. start date in the future, enrollment start date has past, enrollment end date in the future
etc.

Display courses with enrollment status on ProgramPage

---

dashboard/api.py
dashboard/api_test.py
dashboard/views_test.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CourseStatus.js
static/js/components/dashboard/CourseStatus_test.js
static/js/constants.js

No ticket
Renames misleading course statuses and matches the values to the names
Make sure the dashboard works

Changed names and values for course statuses

---

dashboard/api.py
ecommerce/api.py
ecommerce/api_test.py
ecommerce/exceptions.py
ecommerce/views.py
ecommerce/views_test.py

Fixes #918 
After a successful course purchase, the user is enrolled in the audit track for that course on edX. We also update `CachedEnrollment` locally so the user sees the new state in the dashboard.
Talk to me, we will need to use the PR build here. Also we should test and merge #1085 first so that we can verify that the dashboard button updates are immediate.

Implemented enrollment after course purchase

---

backends/pipeline_api.py
backends/pipeline_api_test.py
static/js/components/Navbar.js
static/js/components/Navbar_test.js
static/js/global_init.js

Fixes #903
- The Micromasters link in the navbar now points to either /dashboard or /learners depending on if you have a Instructor or Staff role
- When the user logs in they are directed to /dashboard or /learners depending on if they have an instructor or staff role
Log in and out as a staff and a student and verify that the new page matches the expected one based on the description above. Also click the image on the upper left to test that the link is updated too.

Set default staff page to learner search

---

npm-shrinkwrap.json
package.json
static/js/actions/financial_aid.js
static/js/actions/financial_aid_test.js
static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/inputs/SelectField.js
static/js/containers/DashboardPage.js
static/js/containers/FinancialAidCalculator.js
static/js/reducers/financial_aid.js
static/js/reducers/financial_aid_test.js
static/js/reducers/index.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/currency.js
static/js/util/redux.js
static/js/util/validation.js
static/js/util/validation_test.js
static/scss/calculator.scss
static/scss/layout.scss

closes #1097 
This adds the financial aid calculator. This comprises:
- function to hit the REST API
- new reducer for financial aid stuff (and actions)
- UI components to render the calculator
- validation code for the calculator form
- a little bit of code to deal with countries -> currencies
Read over the changes?
You should be able to go `/dashboard` and click 'Calculate your cost' to open the calculator. Fill in a salary amount and select `USD` ('United States Dollars') from the currency list. Then submitting the form should create a financial aid object for your user and program combo.

Added financial aid calculator

---

cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
micromasters/settings.py
ui/templates/base.html

Related to #1112
Added meta tags for Facebook Open Graph and Twitter Cards. Twitter Card requires a property `twitter:site` which is `@username for the website used in the card footer`. This requires an account for the website, so this is left as `@site_account`.
Note: Some Twitter card tags are not present because:
```When the Twitter card processor looks for tags on your page, it first checks for the Twitter property, and if not present, falls back to the supported Open Graph property.```
https://micromasters-ci-pr-1134.herokuapp.com/

Add social meta tags

---

ecommerce/models.py
ecommerce/views.py
ecommerce/views_test.py
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/reducers/index_test.js
static/js/util/util_test.js

Part of #1058 
The checkout API is changed to create a new order for financial aid programs, and to return a URL to edX for non-financial aid programs. 
Set one program to have financial aid and one to not have it. Have one course run in each to be enrollable. Click enroll on the financial aid program's course and verify that you're directed to Cybersource. Click enroll on the non-financial aid program's course and verify that you're directed to edX, to the relevant course page.

Refactored checkout API to work with non-financial aid programs

---

financialaid/api.py
financialaid/api_test.py
financialaid/views.py
financialaid/views_test.py
mail/api_test.py
micromasters/urls.py
static/js/actions/index.js
static/js/components/ErrorMessage_test.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/flow/dashboardTypes.js
static/js/reducers/index.js
static/js/util/api.js
static/js/util/api_test.js
static/js/util/integration_test_helper.js

Closes #1151 
- Adds a new API view to get course prices for _all_ of a user's enrolled programs
- Adds a call to that API at the app level on the front end; this puts course price info in the application state (a la dashboard data)
Probably static/js/containers/App.js and financialaid/views.py
1. Remove staff permissions for 1 or more programs for your user
1. Make sure you have relevant course price information in your data (I did this simply by adding a relevant `CoursePrice` record)
1. Run the app and check your network tab to make sure the `course_prices` endpoint is being called and the response contains relevant data
Note that this data isn't being used anywhere on the front end yet. That's for later issues

Added course price API call to front end

---

ecommerce/api.py
ecommerce/api_test.py
financialaid/models.py

Part of #1058 
Uses personal price when charging user.
Talk to me first to set up the Cybersource test environment variables
- Create a `TierProgram` for some program with some discount amount if you don't have one already. 
- Create a `FinancialAid` with status `approved` referencing that `TierProgram`.
-  Create a `CoursePrice` on some `CourseRun` which has `is_valid=True`. Make sure that the price is more than the discount you set. Set up `CourseRun` such that the enroll button shows up in the dashboard (soon to be replaced with a Pay button)
- Click the enroll button. You should be directed to Cybersource. The total being requested should be equal to the price in `CoursePrice` minus the discount amount.
- Go into the Django shell and verify that an `Order` is created for this course …

Implemented personal pricing for ecommerce

---

dashboard/views.py
dashboard/views_test.py

Fixes #1193
Removes the filter on program enrollments. The dashboard API will again show programs the user is not currently enrolled in.

Removed filter on program enrollments in dashboard API

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
dashboard/utils_test.py

Exposes the financial aid object ID in the Dashboard REST API
It also adds one missing test for the financial aid documents sent date

Exposed the financial aid obj ID in dashboard API

---

dashboard/tasks.py
dashboard/tasks_test.py

closes #763
Adds bach refresh for current grades. It also fixes a missing refresh for users who never accessed the dashboard.

Added batch refresh of current grades

---

static/js/public.js

Fix ##1191
Set a unique hash in the url for tabs in the Program page.
The user can directly go to desired tab having the correct hash in the url. If hash is invalid then the hash defaults to the panel that is active.

Set unique URL for tabs in program page

---

ecommerce/api.py
ecommerce/api_test.py
financialaid/api.py
financialaid/api_test.py
financialaid/views_test.py
mail/api.py
mail/api_test.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/CourseStatus.js
static/js/components/dashboard/CourseStatus_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/flow/dashboardTypes.js
static/js/flow/programTypes.js
static/js/reducers/index.js
static/js/util/test_utils.js
static/js/util/validation_test.js
static/scss/dashboard.scss

Closes #1102 
- handles financial aid and course price information coming from our APIs
- covers the pre-enroll states outlined in #1102 (full invision design [here](https://projects.invisionapp.com/share/NB7VM1GSG#/screens/185611170))
static/js/components/dashboard/CourseAction.js
FYI: I have a few code snippets that create the states needed for this. If you'd like to use them, let me know and I'll tidy them up and send them over
First you'll need to set up some data:
1. CoursePrice records for any programs you intend to test
1. No previous enrollments in the CourseRuns you want to test for your user
1. For any CourseRun you want to test, set it to have a future start_date and enrollment_start_date
Second, you'll need to satisfy the following conditions to test the 3 states in #1102:
1. …

Added pre-enroll dashboard course states

---

static/js/containers/SignupDialog.js
static/scss/signup-dialog.scss
ui/templates/header.html

Fixes #1113
Changes the login link to act the same as sign up, and the dialog box will contain a link to the terms of service again

Add back terms of service link in dialog, and change Log in link to act the same as signup

---

static/js/actions/financial_aid.js
static/js/actions/financial_aid_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/FinancialAidCard.js
static/js/containers/DashboardPage.js
static/js/containers/FinancialAidCalculator.js
static/js/reducers/financial_aid.js
static/js/reducers/financial_aid_test.js
static/js/util/api.js
static/js/util/api_test.js
static/scss/dashboard.scss

part of #1076 
This adds a 'skip' link which skips the financial aid system. We record this, so we know that the user has already opted-out of financial and and we can show different ui.
read over the code!
delete the financial aid object on your user for a program which has financial aid enabled. Then visit the dashboard. clicking on the 'skip this and pay full price' link should cause the ui to update (now showing course prices) and should also create a financial ad object attached to your user.

financial aid skip API code

---

static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/SkipFinancialAidDialog.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/FinancialAidCalculator.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/_button.scss
static/scss/calculator.scss
static/scss/dashboard.scss

this closes #1076 
This adds a little confirmation dialog when you're going to skip financial aid.
Read over the code changes!
Go delete any financial aid objects on your user and then navigate to `/dashboard`. Then clicking `'Skip this and pay full price'` on either the main page or in the calculator dialog should open up the skip dialog. Clicking 'Cancel' should, well, cancel, and clicking on 'Pay full' should correctly mark you as wanting to pay in full. Your user should now have a financial aid object with `status === skipped` on it.

add confirmation dialog for financial aid skipping

---

cms/models.py
ui/templates/base_error.html
ui/templates/header.html
ui/views.py

- Fixes https://github.com/mitodl/micromasters/issues/1227
- Takes staff to learners page  on clicking 'My dashboard'.
- Take suer to dashboard page  on clicking 'My dashboard'.
- Same thing for 404 and 500 error pages
- see cms/models.py
- see ui/templates/header.html
- see base erorr page
- open home page as staff and common user, click ``My dashboard`` link

Updated my dashboard link

---

financialaid/models.py
financialaid/models_test.py

Fixes #1229
Adds to_dict function to FinancialAid objects so that FinancialAidAudit objects are stored as searchable dicts. Note that this is a slight content change; here is the data now stored in FinancialAidAudit.data_before and .data_after:
{'country_of_income': 'USA',
'date_exchange_rate': None,
'id': 34,
'income_usd': 39000,
'original_currency': 'USD',
'original_income': 39000,
'status': 'created',
'tier_program': 2,
'user': 117}

fixes FinancialAidAudit JSONfields

---

courses/models.py
dashboard/api.py
dashboard/utils.py
ecommerce/api.py
financialaid/api.py

N/A
Given that we have a custom exception handler that intercepts all the `ImproperlyConfigured` exceptions, we need a way to track when the error happens, so we should `log.error` before any `ImproperlyConfigured` is raised.

Added log.error for every ImproperlyConfigured exception raised

---

financialaid/admin.py

Addresses #1198.
Makes FinancialAidAudit objects not editable in the Django Admin interface. Note that there is not currently a way to disable editing on objects in the Django admin while still having them appear in the interface (https://code.djangoproject.com/ticket/8936). As a result we just set all of the fields to be read_only.

makes fields read_only in django admin for financialaidaudit objects

---

dashboard/views.py
dashboard/views_test.py
micromasters/urls.py

N/A
Introduces a REST API to enroll audit users in a course run

Added REST API to enroll audit an user in a course run

---

static/js/actions/documents.js
static/js/actions/enrollments.js
static/js/actions/financial_aid.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/DashboardPage.js
static/js/containers/FinancialAidCalculator.js
static/js/reducers/documents_test.js
static/js/reducers/enrollments_test.js
static/js/reducers/financial_aid_test.js

Fixes #1231 
Fixes #1238 
Calls `fetchDashboard` and `fetchCoursePrices` after each successful API call that modifies the server in a relevant way. This also moves some existing function calls into the reducer to make them easier to test.
Have at least one program enrollment which needs to be added. Add it in the program selector in the dashboard. The dashboard should refresh and you should see the new program.
Remove the program enrollment via Django shell and go to `/profile`. Select the program and continue through the signup flow. The dashboard should be refreshed with the course selected and you should see no error.
You should also test that these things still work:
- adding a new financial aid request
- submitting the document date for the financial aid request

Fetch course prices and dashboard after every relevant change on the server

---

dashboard/api.py
dashboard/api_test.py
dashboard/tasks.py
dashboard/views.py

N/A
Limited the course grade cache refresh to the enrolled runs and not for all the runs in MM, given that an user cannot have a grade if she was not enrolled in the first place

Limited the course grade cache refresh to the enrolled runs

---

static/js/containers/DashboardPage.js
static/js/util/currency.js
static/js/util/currency_test.js

closes #1048 
This guesses what a user's currency should be when they start the financial aid calculator process, based on the `country` value in their profile.
read over the code!
1. Delete any financial aid objects on your user
2. go to `/dashboard`
3. open the financial aid calculator
when you do the appropriate currency for the country on your profile should already be selected.

set default currency in UI

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/scss/dashboard.scss

Fixes #1101
Shows 'passed' for passed courses similar to the mockup
Set a course to have status passed (or mock api.js accordingly), then look at the dashboard for that course

Implemented passed course display

---

financialaid/templates/review_financial_aid.html
financialaid/views.py

Closes #1283 
Moves the "Show:" text outside of the filter dropdown.
Also wraps the table below with `<div class="table-responsive"></div>` for better mobile experience.
The massive-looking changes to lines 116 - 266 in `review_financial_aid.html` is just wrapping with the new `<div>` with indent changes.
…responsive

Moved "Show:" outside the dropdown on financial aid review page label and made table responsive

---

static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CourseRow.js
static/scss/dashboard.scss

- https://github.com/mitodl/micromasters/issues/1225
- Enabled 'View on edX' link on dashboard according to [mock](https://projects.invisionapp.com/share/NB7VM1GSG#/screens/185611170)
- see components/dashboard/CourseDescription.js
- see ``/dashboard/``
cc @pdpinch @aliceriot @noisecapella

Enabled 'View on edX' link on dashboard

---

financialaid/exceptions.py
financialaid/tasks.py
financialaid/tasks_test.py

Fixes #1267.
Adds error handling for API calls made to Open Exchange Rates (openexchangerates.org) for currency conversion; includes error handling for maximum monthly API calls exceeded.

adds error handling for syncing exchange rates with API

---

static/js/actions/image_upload.js
static/js/actions/image_upload_test.js
static/js/components/ProfileImageUploader.js
static/js/containers/ProfileImage.js
static/js/reducers/image_upload.js
static/js/reducers/image_upload_test.js
static/scss/profile-image-uploader.scss

part of #1273 ?
This restricts the drop area component to only accept image files, and if the user tries to upload a different MIME type it will show a little message letting them know what's up.
read over the changes
Go to `/dashboard` and click on the little camera icon in the corner of your profile image. Select a different file, like a PDF or something. You should see a little red error message that says something like 'pick an image'. Then if you pick an image it should go away and let you crop it.

only photos allowed

---

static/js/actions/enrollments.js
static/js/actions/enrollments_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/containers/DashboardPage.js
static/js/flow/enrollmentTypes.js
static/js/reducers/enrollments.js
static/js/reducers/enrollments_test.js
static/js/util/api.js
static/js/util/api_test.js

Fixes #1223
Implements the enroll link on the course row
Unenroll from a course on edX. Then click the enroll link for that same course on micromasters. Go back to edX and verify that the course is enrolled again.
I noticed that we show the enroll link even if the user is currently enrolled when they need to upgrade, but I figured that's outside the scope of this PR

Implemented enroll links

---

static/js/components/ErrorMessage.js
static/js/components/ErrorMessage_test.js
static/js/global_init.js
ui/templates/404.html
ui/templates/500.html
ui/views.py
ui/views_test.py

Fixes #1329
Uses `EMAIL_SUPPORT` in place of the hard coded support email
Go to `/404/` and `/500/` and verify that the email matches the environment variable or the default value set in `settings.py` for `EMAIL_SUPPORT`. Go to the dashboard, add a `raise Exception()` somewhere in `UserDashboard`, refresh, and verify that the error message contains the same email address.

Replaced hard coded support email

---

cms/serializers.py
cms/serializers_test.py
static/js/components/FacultyTile.js
static/scss/program-page.scss

Fixes #1292 
Updates the size to 500x385 to match the help text on the CMS, and also fixes some CSS to allow the user to click the buttons on the left and right sides

Fixed image size for faculty carousel

---

static/js/components/Navbar.js
static/js/components/ProgramSelector.js
static/js/components/ProgramSelector_test.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseListCard_test.js
static/js/containers/App.js

closes #1298 
This makes it so that the program selector drop-down is hidden on urls matching `/profile` and `/settings`.
Make sure that it doesn't show up on `/profile` and `/settings` and that it does show up on `/dashboard`, `/learners`, etc.

Hide program drop down on `/profile` and `/settings`

---

financialaid/admin.py

Closes #1323 
Updates the permissions on financial aid objects in the Django admin interface such that deleting a financial aid object is not allowed.

Disallows deletion of financial aid objects in django admin

---

cms/models.py

Fix #1279
Allow only ProgramPage type to be added as a child to HomePage in cms.
To test this try to add a child page to the homepage.

Limit HomePage to have only ProgramPage as a child page

---

dashboard/utils.py
dashboard/utils_test.py

Fixes #1379
Adds a filter to make sure the `MMTrack` user has the `Order`
Create a purchasable course run on a financial aid program and two users. Pay with one user and verify that the other user remains unpaid

Fixed paid course filtering

---

micromasters/settings.py

Fixes #1384 
There was a typo in the celery task configuration for syncing currency exchange rates.
Not really sure if there's a better way than just merging this one line change and then checking to see if the `CurrencyExchangeRate` objects are updated daily.

Fixed celery scheduling for currency exhange rate updates

---

static/js/signup_dialog.js
webpack.config.shared.js

closes #1353 
closes #1343 
This fixes the code for adding the `onclick` handler to the 'Log In' and 'Sign Up' buttons, and makes sure that `babel-polyfill` is always on the page.
Well, get ahold of a windows machine and look at the PR build in Edge and IE11. Make sure you can open the signup dialog on all relevant pages, and that there are no regressions.

Fixed IE/Edge pop-up issues

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/util/date.js
static/js/util/date_test.js
static/js/util/test_utils.js

closes #1294 
This deals with invalid dates in the `CourseDescription` and `CourseAction` components, basically by testing to see if the date is valid before we try to format and display it.
What I did was alter the `getDashboard`, `getProgramEnrollments` and `getCoursePrices` functions in `api.js` to return their respective constants (from `constants.js`). Then you can alter relevant courseRuns in order to make invalid dates, to test that every case is covered. A good string to use is `'1999-13-92'`.

Handle invalid dates

---

uwsgi.ini

#1393 
Removes basicauth from cybersource callback and decreases initial process count at startup
Trying to go through checkout flow with HTTP_AUTH_CREDENTIALS env var set
Trying to go through checkout flow with HTTP_AUTH_CREDENTIALS env var set
- Exempted CyberSource callback from basicauth
- Decreased initial count of processes using `cheaper` config

Updated process count and basicauth exemption

---

cms/models.py
ui/views_test.py

Fixes #1290 
Sorts programs in id order
Create a couple live programs and view the thumbnails on the home page. They should be in the order they were created. Change the first program's id number to come after the second program, then refresh. The programs should swap in the home page.

Sorted programs in id order

---

courses/views.py
courses/views_test.py

N/A
Modified the program enrollment rest API to not return an error in case an enrollment for the same program already exists.

Program enrollment does not return error if already exists

---

profiles/factories.py
profiles/models.py
profiles/models_test.py

fixes #1399
Changes the code for assigning a student id to the user profile. Now the profile pk is used.

Changed logic to assign the student ID

---

static/js/faculty_carousel.js
static/js/sentry_client.js
static/js/signup_dialog.js

Fixes #1398
Sets `__webpack_public_path__` on bundles where it is missing. This helps enable hot reloading, a dev feature
Change the color in some CSS and verify that there is not a full page refresh

Added webpack_public_path

---

ui/views.py

Fixes #1383 
Adds `tracking_id` so the template warnings are silenced

Added tracking_id to silence warnings

---

static/js/constants.js
static/js/flow/declarations.js
static/js/util/profile_edit_test.js
static/js/util/validation.js
static/js/util/validation_test.js

closes #1405 
this fixes the year validation for the profile. basically, the range of allowed years `n` now looks like `x - 120 <= n <= x` where `x` is the current year. when `x = 2016` the range is `1896 - 2016`.
look over the logic and test changes.
go to `/learner` and open the basic info dialog. edit your birthday. you should only be able to enter years in the range above. years greater than or less than the bounds should be corrected to the closest bound (so that `1700 -> 1896`, and `2250 -> 2016`, for instance).

Fixed error in year validation logic

---

micromasters/settings.py

Previously, every time the micromasters application started up, it would display this warning in the terminal:
```
Performing system checks...
October 05, 2016 - 15:13:18
Django version 1.9.10, using settings 'micromasters.settings'
Starting development server at http://0.0.0.0:8079/
Quit the server with CONTROL-C.
System check identified some issues:
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in
Django 1.8 and the TEMPLATES dictionary takes precedence. You must put
the values of the following settings into your default TEMPLATES dict:
TEMPLATE_CONTEXT_PROCESSORS.
System check identified 1 issue (0 silenced).
```
This pull request fixes this warning. It should have no effect on the functionality of the website.

Remove deprecated TEMPLATE_CONTEXT_PROCESSORS setting

---

static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/DocsInstructionsDialog.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/DashboardPage.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/dashboard.scss
static/scss/docs-instructions.scss
static/scss/layout.scss

this closes #1358 
This adds a popup to the dashboard which contains all the info you could ever want about financial aid (specifically about income verification). There's a link in the `FinancialAidCard` which opens the dialog.
Use the django shell or something to ensure your user has a financial aid object with `status = 'pending-docs'`. Then navigate to `/dashboard`, and you should see a link to 'Read Complete Instructions'. Clicking on that should open the pop-up.

Add complete financial aid instructions

---

Procfile
micromasters/settings.py

Adds persistent DB connections by default and adds the beat scheduler to the Celery worker
Using the locust load testing tool to validate performance improvements
When this config is absent a new connection is made to the DB for every transaction which adds significant overhead. Adding this setting reduces latency and I/O for improved performance and capacity.
- Added var for setting DB persistent connections
- Added Celery beat and extra_worker to Procfile for task scheduling

Added persistent connection settings for DB

---

courses/models.py
courses/models_test.py

Fix for #1408. Restores the correct logic from the `get_course_enrollment_text()` function in 89d844044e578a179de3bce01067a927e618c872.

Fix a bug in course enrollment text

---

static/js/components/NewEnrollmentDialog.js

Fixes #1281
Makes the select take up the full width of the dialog

Make program selector use full dialog width

---

dashboard/utils_test.py
financialaid/factories.py
financialaid/models.py
financialaid/models_test.py
micromasters/utils.py
micromasters/utils_test.py

Part of #1421 
Creates a general serializer method for models
Checkout master and make a financial aid request using the UI. Verify that `FinancialAidAudit` has information in `data_before` and `data_after` matching the most recent request. Then checkout this branch and in the UI skip financial aid. Verify that the information in `FinancialAidAudit` is substantially the same. `data_before` for the most recent entry and `data_after` for the second most recent entry should match up almost exactly. The formatted datetime output may differ slightly and there will be extra fields, but nothing else should change.

Added serialize_model, replaced to_dict

---

cms/templates/cms/home_page.html
courses/models.py
courses/models_test.py
dashboard/api.py
dashboard/api_test.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js
static/js/components/dashboard/CourseGrade.js
static/js/components/dashboard/CourseGrade_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseRow_test.js
static/js/components/dashboard/CourseSubRow.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/util.js
static/js/components/dashboard/util_test.js
static/js/constants.js
static/js/containers/FinancialAidCalculator.js
static/js/util/test_utils.js
static/scss/dashboard.scss

Closes #939 
Fixes #1121 
Fixes #1122 
Handles courses with multiple runs per state. This is relevant in cases where the user has failed or missed an upgrade deadline for a course and we want to show them a future run, and also when the user has taken the course before multiple times.
Probably CourseRow.js as well as dashboard/api.py where a few important changes were made
Here's a [gist](https://gist.github.com/gsidebo/478920b3ead11b4de742c076c2e8d64c) with some functions to help set up test data. Let me know if anything is confusing or doesn't work. Check #939 for the designs that these states should match

Added past course run UI to dashboard

---

static/scss/program-page.scss

#1477 
This is a very quick fix to the line-height and spacing in the courses box on the Program page.
Look at the layout of the Courses text in the gray box on the program page. Make sure the text is long enough so it breaks to 2 lines.

Line-height fix for Course list on program page

---

README.md

This pull request adds a note to the README, explaining that `flow` can't be run through Docker.
@aliceriot: I think this is why I was seeing an error when trying to run `flow`. For reference, here's the error I'm seeing:
```bash
$ docker-compose run watch npm run-script flow
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
npm info lifecycle micromasters@0.0.0~preflow: micromasters@0.0.0
npm info lifecycle micromasters@0.0.0~flow: micromasters@0.0.0
> micromasters@0.0.0 flow /src
> flow check
/src/node_modules/flow-bin/vendor/flow: 1: /src/node_modules/flow-bin/vendor/flow: Syntax error: word unexpected (expecting ")")
npm info lifecycle micromasters@0.0.0~flow: Failed to exec flow script
npm ERR! Linux 4.4.24-boot2docker
npm ERR! argv …
```

Note Flow incompatibility within Docker

---

static/js/components/dashboard/DashboardUserCard.js
static/js/components/dashboard/DashboardUserCard_test.js
static/scss/dashboard.scss

fixes https://github.com/mitodl/micromasters/issues/1472
- Removed mm id from user card on dashboard 
- see DashboardUserCard
- open dashboard

Removed mm id from dashboard

---

static/js/components/LearnerSearch.js
static/scss/search-page.scss

- fixes https://github.com/mitodl/micromasters/issues/1413
- removed empty space at the top of the learner search card.
- see /learners/ page
@pdpinch @roberthouse54 @aliceriot

Updated style: removed top pedding from searched page

---

static/js/components/EducationDialog.js
static/js/components/inputs/DateField.js
static/js/util/currency.js
static/js/util/date_validation.js
static/js/util/date_validation_test.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/sanctuary.js
static/js/util/sanctuary_test.js
static/js/util/validation.js
static/js/util/validation_test.js

closes #1462 
This refactors our code for validating dates, to accomplish two goals:
1. Employment shouldn't allow an end date that is in the future
2. Education should allow an end date that is in the future
Well, run through the two things above and make sure they work!
Also make sure there are no regressions in date related code.

Refactor date validation

---

static/js/components/Navbar.js
static/scss/navbar.scss

- fixes https://github.com/mitodl/micromasters/issues/1394
- open profile page ``/profile`` click MM logo or test, you will not navigate
- open settings page, user page and then click on same on header, you will be navigated dashboard or learners page respectively.

Removed dashboard links from profile page header

---

ecommerce/migrations/0008_protect_audit.py
ecommerce/migrations/0009_protect_audit.py
financialaid/migrations/0019_protect_audit.py
mail/migrations/0003_protect_audit.py

Fixes #1450 
Adds postgres rules for `OrderAudit`, `FinancialAidAudit`, and `FinancialAidEmailAudit` to prevent `UPDATE` or `DELETE` of the table.
You should be able to run the migrations and reverse the migrations successfully. Any attempt to edit and save an existing instance of one of the audit models will cause an exception. For example, try saving an `OrderAudit` instance in the Django Admin. If you reverse the migration, you should be able to save the `OrderAudit` instance again without error.

Protected audit tables

---

micromasters/utils.py

None
Logs the `ImproperlyConfigured` exception which is raised sometimes
In `courses/serializers.py` add a field name to the `fields` list which obviously doesn't exist. Go to `/api/v0/programs/`. You should see the `ImproperlyConfigured` exception response. Look in your console output and you should see an exception about a field name along with an accurate stack trace.

Logged exception being handled in custom_exception_handler

---

courses/models.py
courses/models_test.py

Fixes #1541 
Considers both blank ('') and null edx_course_key values as null for CourseRuns
Add multiple course runs with blank edx course keys Django admin
Django admin tries to insert a blank string instead of `null` when adding a new course run

Fixed course run edx key save issue

---

cms/templates/cms/faqs_page.html
cms/templates/cms/program_page.html

Fix  #1543
On the program page show only published child pages.
To test this, unpublish an existing faqs page, and check if it has disappeared from the the program page.

Show only published children pages on the ProgramPage

---

seed_data/management/commands/seed_db.py
seed_data/management/commands/unseed_db.py

None
Mutes the signals which index the profiles as they are created. Instead they are bulk indexed via `recreate_index` after all profiles are created.
Run `./manage.py seed_db --staff-user staff` and verify that you can see the profiles which are created in the learner search at `/learners`.
The `mute_signals` will also prevent profiles from being created automatically with the `User`, so there's a new `Profile.objects.create(...)` added to fix this.

Use bulk indexing for seed_db

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/util/date.js

No associated issue
Fixes the CourseAction bug that was breaking the dashboard
Load the dashboard, preferably with a course that has course run with a `null` value for all date fields

Fixed course description JS bug

---

ecommerce/api.py
ecommerce/views.py
ecommerce/views_test.py

Related to #1550 
If the enrollment failed, the order would fail. This is changed to not fail the order but to just log the enrollment failure instead.
Purchase a course without having a course key which exists on the edX instance. It should go through successfully

Prevented an enrollment failure from failing the order

---

courses/serializers.py
courses/serializers_test.py
courses/views.py
courses/views_test.py
micromasters/urls.py

Part of #1195
Removes `/api/v0/courses/` and associated views
Nothing uses this API so there should be no change of behavior

Removed course run view

---

detect_missing_migrations.sh

None
Feeds `no` to `./manage.py migrate --fake` so that it won't hang on the content type question

Protected detect_missing_migrations.sh against hanging for console input

---

docker-compose.yml
travis-docker-compose.yml

fixes #1579 
Pins elasticsearch (in docker) to version 2.4.1 instead of just pulling the latest version. This avoids a breaking change in the CLI of elasticsearch 5.0.
Try `docker-compose up` and `docker-compose up --build` on your existing docker build. Hopefully nothing changes. 
Try a clean build without this change, e.g. `docker-compose rm -f` and then `docker-compose up --build` It should fail with the elasticsearch error mentioned in the inssue. 
Try a clean build with this change. It should work. 
This was a quick fix, and it seems like a good idea to pin the version. However, it may make more sense to figure out the new CLI in elasticsearch 5 and move forward.

pins elasticsearch in docker to 2.4.1

---

cms/serializers.py
courses/serializers.py
courses/serializers_test.py

Part of #1195
Adds `programpage_url` to `/api/v0/programs/`
Go to `/api/v0/programs/` and you should see the programpage urls for programs with CMS pages, or null if they don't have a connected page.

Added programpage_url to /api/v0/programs/

---

detect_missing_migrations.sh
tox.ini

None
Adds back `detect_missing_migrations.sh` and fixes its behavior to run migrations without `--fake`

Fixed detect_missing_migrations.sh

---

courses/serializers.py
courses/serializers_test.py
courses/views.py

Part of #1195
Adds enrolled field to ProgramSerializer
Look at `/api/v0/programs/` and verify that the `enrolled` field matches the programs you are enrolled in

Added enrolled field to ProgramSerializer

---

static/js/components/ConfirmDeletion.js
static/js/components/DocsInstructionsDialog.js
static/js/components/EducationDialog.js
static/js/components/EducationDisplay.js
static/js/components/EducationForm.js
static/js/components/EmailCompositionDialog.js
static/js/components/EmploymentForm.js
static/js/components/NewEnrollmentDialog.js
static/js/components/ProfileImageUploader.js
static/js/components/SkipFinancialAidDialog.js
static/js/components/UserPagePersonalDialog.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/SignupDialog.js
static/js/containers/UserPage_test.js
static/js/util/test_utils.js
static/scss/dashboard.scss
static/scss/responsive-styles.scss
ui/templates/base.html
ui/templates/dashboard.html

Fixes #1452. This pull request does the following things to make the modals in our application more consistent:
* Applies a "dialog" class to every modal window
* Ensures that every modal has a title
* Applies a "dialog-title" class to every modal title
* Unified button styles for all buttons in dashboard modals
However, not all modals are created equally. The "Sign Up" modal on the landing page does _not_ have a title. This is intentional, and was specifically requested by @roberthouse54.
Note that the `className` property on the `<Dialog>` element applies the class name to the wrapper div around the modal window, which is used as an overlay for the entire page to catch people clicking outside of the modal to clear it. The `contentClassName` property applies the class name to the div …

Make modals more consistent

---

detect_missing_migrations.sh

None
Switches to `./manage.py makemigrations --dry-run` so the detect script doesn't actually run migrations, which may be disruptive to dev environments.
Rename a field and run the script. It should error and show a migration which could be created. No migration should actually be generated.

Made detect_missing_migrations.sh use makemigrations --dry-run

---

static/js/entry/zendesk_widget.js

Fixes #1487. This change hacks the Zendesk Web Widget API to detect when we can modify the DOM of Zendesk's modifications to the page, and then goes in and changes the background color of the button.

Set background color of Zendesk button

---

seed_data/lib.py
seed_data/management/commands/__init__.py
seed_data/management/commands/alter_data.py
seed_data/management/commands/seed_db.py
seed_data/utils.py

Closes #1497 
Adds a series of management commands that can fine-tune data so our various course states can be tested.
Seed the DB and make sure you have tiers created and some enrolled programs for your user. You can see some general option details by running `docker-compose run web ./manage.py alter_data --help`, and some example commands can be found by running `docker-compose run web ./manage.py alter_data --usage`. Try out some of those commands and check your dashboard to see the effects.
1. **For now, these commands are only designed to work for non-FA programs**
1. There is some cleanup that can be done, but keep in mind that we're only going to be using these commands for testing. I'm not planning on adding unit tests for this reason.

Added management commands for fine-grained course state control

---

courses/models.py
courses/models_test.py
dashboard/api.py
dashboard/api_test.py
dashboard/views.py
micromasters/settings.py

part of #1454
handles the N+1 queries in the dashboard
loading the dashboard api, you should not see the nplus1 messages anymore. everything else should be the same.

Handling n+1 queries in dashboard

---

static/js/actions/course_enrollments.js
static/js/actions/course_enrollments_test.js
static/js/actions/programs.js
static/js/actions/programs_test.js
static/js/components/ErrorMessage_test.js
static/js/components/Navbar.js
static/js/components/Navbar_test.js
static/js/components/NewEnrollmentDialog.js
static/js/components/NewEnrollmentDialog_test.js
static/js/components/ProgramSelector.js
static/js/components/ProgramSelector_test.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/ProfileFormContainer.js
static/js/flow/enrollmentTypes.js
static/js/reducers/course_enrollments.js
static/js/reducers/course_enrollments_test.js
static/js/reducers/financial_aid_test.js
static/js/reducers/index.js
static/js/reducers/programs.js
static/js/reducers/programs_test.js
static/js/util/integration_test_helper.js

Part of #1195
Splits `enrollments` reducer into `courseEnrollments` and `programs`. There should be no change in functionality.
Make sure that if you click the 'Enroll' link, it makes a POST to the course enrollment API. Also make sure that the programs list is fetched correctly (you should see your enrolled programs in the selector) and that you can still enroll in a new program.

Split enrollments reducer into programs and courseEnrollments

---

roles/api.py
search/api.py
search/api_test.py
search/views.py
search/views_test.py

fixes #1588 
Fixes a bug that allowed staff users to see students of program where the staff user was not staff.
This PR also removes the GET request handling support from the ES proxy
the bug has been fixed in
`search/api.py`
all the rest is work to fix the reason why this bug did not come out from the tests before.
Make sure the staff user can see only the students in the programs where she is staff

Staff users can see only students they are allowed to

---

static/scss/search-page.scss

- fixes https://github.com/mitodl/micromasters/issues/1538
- Fixes padding of search header when facets selected.
- see /learners page
@pdpinch @roberthouse54 @aliceriot

Fixed header of search page

---

.travis.yml
static/js/containers/UserPage_test.js
travis-docker-compose.yml
travis/Dockerfile-travis-watch
travis/Dockerfile-travis-watch-build
travis/Dockerfile-travis-web
travis/js_tests.sh

closes #1593 
A bunch of stuff! The goal is to reduce the CI build time. Before this PR our builds range between 13 and 20 minutes in length. A good chunk of that is taken up by building the docker containers and performing other setup steps, and all the tests are run sequentially.
This PR changes things around, without making any code changes, to get the build time down to about 5-6 minutes. I did that by:
- pushing pre-built containers to docker hub (https://hub.docker.com/r/mitodl/mm_watch_travis/ and https://hub.docker.com/r/mitodl/mm_web_travis/) which we pull on travis
- separating JS and Python tests into separate jobs (which run simultaneously)
- removing the `watch` container from `travis-docker-compose.yml`
- building the web, elastic, etc containers only for the python tests
- …

Speed up CI builds

---

cms/models.py
cms/serializers.py
cms/serializers_test.py
courses/serializers_test.py
micromasters/serializers.py
micromasters/serializers_test.py
profiles/serializers_test.py
profiles/views_test.py
search/indexing_api.py
search/indexing_api_test.py
ui/views.py

The Serializer classes in Django REST Framework have `to_representation()` methods that are intended to be overridden by subclasses, but not called directly. This changes the codebase to use DRF's intended API for serializing instances to Python primitive datatypes.
According to [the official tutorial](http://www.django-rest-framework.org/tutorial/1-serialization/#working-with-serializers), Serializer classes work in the following two ways:
* To serialize a model instance to Python primitives, pass the instance to the Serializer constructor, and access the `.data` property of the Serializer object
* To deserialize Python primitives (data) into a model instance, pass the data to the Serializer constructor as a `data` keyword argument. Check if the data is valid by calling `.is_valid()` on …

Use DRF API correctly

---

seed_data/lib.py
seed_data/management/commands/alter_data.py
seed_data/utils.py

Fixes #1612 
Fixes #1613 
For the course_info convenience method, prints out a localized datetime (since that's what moment.js does)
Just run the `alter_data` command with the `course_info` action and some relevant parameters to find a program, course, and user, eg: `manage.py alter_data --action=course_info --username=staff --program-title='Digital' --course-title='100'`

Fixed course date issue in alter_data command

---

dashboard/models.py
dashboard/serializers.py
dashboard/serializers_test.py
search/indexing_api.py
search/indexing_api_test.py
static/scss/search-page.scss

Closes #1600 
I initially thought we could optimize the queries to retrieve cached data for the User on a ProgramEnrollment in dashboard/serializers.py. It turns out that we pretty much optimal. I poked around this area of the code and found that (a) a User's Profile could be fetched in a single query using select_related, eliminating 1 query per user serialized, and (b) cached model serialization only needed the data property. Both of these changes can probably be extended to other areas of the code
Make sure you can still recreate the index and the dashboard API still works. You can also count the queries executed by search.indexing_api.index_users on master, then with the same users on this branch

Made small optimization to user serialization for search results

---

requirements.txt

The latest version of the [New Relic Agent for Python](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes) has some nice features, including better integration with Postgres via `psycopg2`, and better integration with Django 1.10 (#1636). This might make it easier to do performance testing. [Release notes are here.](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes)

Upgrade NewRelic to 2.72.1.53

---

requirements.txt

Django REST Framework is one of the core frameworks that this project uses. It's better to do smaller, more frequent upgrades than to wait until bugs or deprecations force us to do larger, infrequent upgrades. [ChangeLog is here.](http://www.django-rest-framework.org/topics/release-notes/)

Upgrade Django REST Framework to 3.5.2

---

requirements.txt

[ChangeLog is here.](https://github.com/omab/python-social-auth/blob/master/CHANGELOG.md) Based on a quick skim, there seem to be some security-related updates -- not sure if we're vulnerable, but probably a good idea to upgrade regardless.
In addition, Django 1.10 (#1636) depends on this upgrade.

Upgrade python-social-auth to 0.2.21

---

requirements.txt

Wagtail 1.7 (#1635) updates the version of [Willow](https://pypi.python.org/pypi/Willow) that it depends on. I figured it would make sense to also make sure that the underlying Pillow library was up to date. [ChangeLog is here.](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst)

Upgrade Pillow to 3.4.2

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/UserPage_test.js

Fixes #1498
Changes the education dialog titles to 'Add Education' and 'Edit Education' and changes the employment title to 'Edit Employment' when the employment is being edited
Edit and add employment and education entries

Changed education and employment titles

---

static/js/components/inputs/DateField.js
static/js/containers/UserPage_test.js
static/js/util/profile_edit_test.js

Fix #1529
Keep a leading zero in a month and date field if the user entered it.

Save leading zeros in month and date field

---

profiles/serializers.py
profiles/views_test.py

Fixes #1658
Fixes bug where education and employment entries were cleared when uploading a profile image
Create employment and education entries, then upload a profile image. The employment and education entries you created should still be there.

Fixed education/employment deletion when uploading images

---

static/js/components/ProfileImageUploader.js
static/scss/dashboard.scss

- fixes https://github.com/mitodl/micromasters/issues/1427
- when user selects photo then updates ``save button`` classes. so that user can save photo. 
@pdpinch @roberthouse54 @aliceriot

Allow to use save button only if photo is selected on 'photo upload dialog'

---

static/js/components/FacultyTile.js
static/js/components/FacultyTile_test.js

Fixes #1560. The faculty carousel should now be able to display faculty even if some of them don't have an image set.
Create a ProgramPage in Wagtail with one or more faculty. Make sure that at least one of these faculty members does _not_ have an image set. View the program page in the browser, and verify that all faculty show up in the faculty carousel at the bottom.

Correctly handle faculty without images

---

Dockerfile
docker-compose.yml
micromasters/settings.py
travis-docker-compose.yml
travis/Dockerfile-travis-web

This upgrades our [Docker Compose](https://www.docker.com/products/docker-compose) file to the [version 2 syntax](https://docs.docker.com/compose/compose-file/#/versioning). This new syntax allows you to specify named volumes and mount them onto containers. This pull request creates a named volume for holding Django media and mounts it onto the `web` container. Previously, every time the `web` container was rebuilt, Wagtail lost all of its uploaded images; with this change, uploaded images live in this named volume, and will persist even if the developer rebuilds the `web` container.
There should be no user-visible changes from this pull request.

Docker Compose version 2

---

travis/update-docker-hub.sh

This is just a little script to automate building new docker images and pushing them to the [mitodl organization](https://hub.docker.com/u/mitodl/dashboard/) on docker hub. In order to use it you'll need to be logged in to a docker hub account which has permissions to push to the mitodl organization.
I just used it to push new images, so I guess if the builds are still passing it works! hahaha.

Script to update docker hub images

---

backends/utils_test.py
dashboard/tasks_test.py
dashboard/views_test.py

This is necessary to upgrade Django to 1.10 (#1636).

Use dicts for Python-Social-Auth instead of strings

---

micromasters/settings.py

I discovered a problem when running Django 1.10.3 via Docker: it forbids access based on the IP address, even while `DEBUG=True`. [This change to Django was introduced in 1.10.3.](https://docs.djangoproject.com/en/1.10/releases/1.10.3/#dns-rebinding-vulnerability-when-debug-true)
Because we never debug against production data, we can safely disable this protection. Doing so will allow us to run within Docker and use [Docker-Machine](https://docs.docker.com/machine/overview/).

Allow all hosts while in DEBUG mode

---

travis/Dockerfile-travis-watch-build
travis/Dockerfile-travis-web

Fixes #1698 
The travis build failure for the release was caused by the Python source shipping in the base docker image not matching the source in the git checkout. To fix this this PR removes the source from `/src` before the new source is checked out
After the new docker images are uploaded, restart the travis build for the release. It should pass without errors.

Fixed use of /src in docker images

---

static/js/components/PersonalTab.js
static/js/components/PersonalTab_test.js
static/js/containers/ProfileFormContainer.js
static/js/reducers/ui.js

- fixes https://github.com/mitodl/micromasters/issues/1517
- Loads enrolled program for returning user on personal tab profile page.
@pdpinch @aliceriot @noisecapella 
**Note this PR is only for user who already filled his profile and returned back to profile page for next time**

Profile: Load existing program enrollments for returning user

---

package.json

Because I'm tired of `npm install` complaining every single time.

Add repository and license fields to package.json

---

bin/post_compile

The `manage.py migrate --list` command is removed in Django 1.10. It has been replaced with the `manage.py showmigrations` command. https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-showmigrations

Switch to `manage.py showmigrations`

---

cms/templates/cms/home_page.html

Fixes #1686. Changes the "Learn More" links on the home page to "More about <program name>", so that a screenreader user can easily understand each link in isolation.

Add program name to links on home page

---

static/js/containers/ProfileImage.js
static/scss/profile-image.scss

Fixes #1684. Sets an accessible description for the camera icon on the user profile page, and uses a `<button>` element to indicate that clicking on the camera will open a dialog.

Make camera icon accessible

---

static/js/components/EmploymentForm.js
static/scss/profile.scss

Fix #1458
If error is present for end date, push the 'end date hint' down to make space for the error.

Employment Form: make space for date field error

---

ecommerce/views.py
ecommerce/views_test.py

Fixes #1336
Sends emails if the order fulfillment failed, or if the enrollment failed afterwards
Set up mailgun's environment variables, in particular `MAILGUN_RECIPIENT_OVERRIDE` should point to an email address you control. Start a purchase of a course and in Cybersource click 'cancel'. You should get an email saying that there was an order fulfillment failure. Make sure the recipient email matches `EMAIL_SUPPORT` in `settings.py`.
Next, change the course key for the course run you purchased to something invalid. Go through a purchase workflow and you should see the order fulfillment fail in the UI due to the enrollment in the course not working. You should get an email saying that the enrollment failed and a stack trace.

Implemented sending emails on order errors

---

ui/templates/base.html
ui/templates/footer.html

Fixes #1563
Makes the footer disappear while the javascript loads, then adds it back afterwards by toggling the display of the footer element.
Refresh the browser and see if you notice the footer during the refresh
I'm not sure if there's a better way to toggle visibility but it seems simple enough

Fixed footer display while JS loads

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/util/util.js
static/js/util/util_test.js

- fixes https://github.com/mitodl/micromasters/issues/1605
- open your profile ``/learner``.
- open other user profile with no work history and education``/learner``.
- open other user profile with work history and education ``/learner``.
- open your ``/profile`` and see education and work tabs

Removed empty education and work history cards on learners page

---

cms/models.py
static/js/entry/public.js
ui/views_test.py

Follow-up from #1628. Removes unnecessary, duplicated content from the `SETTINGS` Javascript object on the programs page.

Clean up unnecessary JS references in program page

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js

Fixes #1705. Right now, this is the simplest possible fix: changing the `<a>` tags into `<button>` tags. It's now much clearer that these are actions that the user can take, but it's not particularly pretty. @roberthouse54, do you want to style this up nicely?

Turn profile links into buttons

---

static/scss/profile.scss
static/scss/select-field.scss

This PR styles the react select field to look more-or-less like the material UI fields. So I changed the react select label, the spacing and margins of the field, the color of the bottom-border. I also removed the bold style for the program selector on page 1 of the sign up, and removed the "x" icon to clear the selection. This last one is pending discussion with Ferdi who said he thought having the x was useful.

Style the react select field to look like material ui field

---

financialaid/api.py
financialaid/api_test.py
financialaid/serializers.py
financialaid/views_test.py
mail/views_test.py

Fixes #1341
Auto-approves the user if they are below the income threshold for their country but they are matched with a $0 discount anyway.
Configure the tier program to have a $0 discount level that's lower than the income threshold for your country of residence (this is $75k for US). Then apply for financial aid with an income slightly above the $0 discount tier program level

Implemented auto approve for TierProgram where discount is $0

---

profiles/views.py
profiles/views_test.py
ui/urls.py

fixes https://github.com/mitodl/micromasters/issues/1731
- create fake data ``docker-compose run web ./manage.py gen_realistic_search_data --staff-user <staff user name>
``
- Open admin panel,  go to profile of user e.g``fake.blanca.rojas`` and make profile public.
- Copy same user name e.g ``fake.blanca.rojas``
- Go to url ``http://192.168.99.100:8079/learner/fake.blanca.rojas`` as staff or learner and see profile.

[learners profile] Allow period in url param

---

ui/views.py

closes #1749 
When I merged #1719 I didn't get things correct on the ToS page - should have been including the `style_public` and `public` bundles there.
Make sure you can open the login popup and stuff like that on the terms of service page.

make sure that the JS bundles are included on the page everywhere we

---

static/js/actions/financial_aid.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/reducers/financial_aid.js
static/js/reducers/financial_aid_test.js
static/scss/_variables.scss
static/scss/calculator.scss

closes #1285 
This adds a little error message display to the financial aid calculator!
The easiest way to generate error messages is to not have have the currency conversion set-up on your computer. Then submitting the form with anything other than USD will result in a 400 error.

add error display to financial aid calculator

---

static/scss/_variables.scss

This is a one-lie change that only changes the link color. Just look to see that all links use this color. (I made this change as the previous maroon link was too close to the error text color, so going back to blue.)

Very small PR- changes link color

---

static/scss/_button.scss
static/scss/navbar.scss

This is a very small PR that styles the mm-minor-action button on the learner profile to look like a link.  I also fixed a very minor spacing bug that was introduced with yesterday's PR styling the react select component. This fixes the program selector in the navbar, which uses the react select component.
Closes #1757

Small PR - styles mm-minor-action button to look like a link

---

courses/factories.py
dashboard/factories.py
dashboard/serializers.py
dashboard/serializers_test.py
dashboard/utils.py
dashboard/utils_test.py
financialaid/api_test.py
financialaid/views_test.py
mail/views_test.py

fixes #1632
Adds support for the financial grade final grade serialization for the search.
It also refactors many factories because of specific needs for this PR
`dashboard/serializers.py`
You need a course run in a financial aid program where the user is enrolled mmtrack (meaning is enrolled and paid for the course run).
Once this is done, the easiest way is to modify the course run CachedCurrentGrade object for the user to something like 
```
{
"course_key": <course run edx key>,
"passed": True,
"percent": 0.77,
"letter_grade": "Pass",
"username": <your user's username>
}
```
Then recreate the index and you should be able to see the final grade in the search result.
the `seed_db` command does not help much for the test: there is another issue open to add support for financial aid …

Final grade serialization

---

static/js/components/PrivacyForm.js
static/js/containers/SettingsPage.js

The privacy form has to have a `validator` on `this.props` in order for the `boundRadioGroupField` to pull it out.

pass validator into PrivacyForm

---

static/js/components/Navbar.js
static/js/containers/ProfileImage.js
static/scss/navbar.scss

Better fix for #1684
Sets `aria-hidden="true"` on the Material Icon tags. This will cause screen readers to not read out "camera_alt" when encountering the camera icon, for example. This is OK because we already have alternate text labels set using the `sr-only` class.
Load up [ChromeVox](http://www.chromevox.com/) or [VoiceOver](https://help.apple.com/voiceover/info/guide/10.12/), tab to the icons in the application, and verify that the screen reader reads text that is helpful and understandable. There is a camera icon as a badge on the user's profile image when viewing their own profile, and there are images in the menu drawer when the application is in a mobile layout.

Hide icon text from screenreaders

---

static/scss/_button.scss

Should have caught this in #1772 
Fixes a spot where we were using the old syntax for `linear-gradient`.
Just check there's no warning from `postcss` showing up in the JS console.

fix gradient syntax error warning

---

static/js/components/ErrorMessage_test.js
static/js/components/NewEnrollmentDialog_test.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/containers/UserPage_test.js
static/js/flow/reduxTypes.js
static/js/flow/sinonTypes.js
static/js/util/integration_test_helper.js

Fixes #1655
Delays loading the dashboard API until the user looks at the dashboard page. The user will load the dashboard API when they click next and enroll in a program, but this shouldn't block anything on their end.
Load `/profile` and verify that no request to `/api/v0/dashboard/` is loaded and that the user still sees programs they can enroll in.
Also, go to `/settings` and refresh the browser. Verify that `/api/v0/dashboard/` is not loaded. Then click the logo on the upper left to direct you to the dashboard. Verify that the dashboard loaded properly.

Moved dashboard API call to DashboardPage

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/containers/FinancialAidCalculator.js
static/scss/_button.scss

Adds `primary-button` and `secondary-button` CSS classes, and uses `<button>` for accessibility (#1222)

Correct buttons on cost calculator

---

static/js/components/EducationForm.js
static/js/components/PersonalForm.js
static/js/components/PersonalTab.js
static/js/components/inputs/DateField.js
static/js/components/inputs/SelectField.js
static/js/containers/ProfilePage.js
static/js/containers/UserPage_test.js
static/js/util/integration_test_helper.js
static/js/util/profile_edit_test.js
static/scss/layout.scss
static/scss/profile-form.scss
static/scss/profile.scss

This pull request does the following things, all related to the profile form:
* Replace `<div class="section-header">` elements with `<h3>` elements
* Add accessible `<label>` elements to the date fields and the select fields
* Ensure that every select field has a unique ID, so that we can use `aria-describedby` attributes to label error messages in a future pull request
* Pull Sass related to the profile form out into its own `profile-form.scss` file, for organizational purposes
To test this pull request, I suggest using [ChromeVox](http://www.chromevox.com/) or [VoiceOver](https://help.apple.com/voiceover/info/guide/10.12/). To activate/deactivate VoiceOver on a Mac, press Command + F5. Different browsers & screen readers work differently; for example, when reading the "Date of birth" …

Making profile form more accessible

---

financialaid/api_test.py
financialaid/serializers.py
financialaid/views.py
financialaid/views_test.py
micromasters/utils.py
micromasters/utils_test.py

Fixes #1777
Adds a filter to prevent reset `FinancialAid`s from being seen in `FinancialAidSkipView`
Create a financial aid, set it to `RESET` in the Django admin. Then attempt to skip financial aid in the UI.

Filtered out reset FinancialAid statuses

---

static/scss/search-page.scss

This sets a min-width on the Sort By dropdown. It also makes the pagination buttons a bit less wide, and makes the sort less tall, so it looks less like a button.
Closes #1802

Fixes the sort by dropdown layout

---

README.md
search/indexing_api.py

Fixes #1742 
Adds SSL parameters to the ES connection (see [the docs](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch) for details)
First, you'll need to delete the line in `docker-compose.yml` that sets `ELASTICSEARCH_URL` in the `web` service. I don't know why this is here instead of just getting it from `.env` like other settings vars. 
Make sure you can run the `recreate_index` command with no changes to .env and not see a warning. Then, in your `.env` file, set your `ELASTICSEARCH_URL` and `ELASTICSEARCH_HTTP_AUTH` variables to the values in micromasters-rc. You can find these by connecting to -rc via the `heroku` CLI command, running a django shell, and importing `settings`. Copy those values over to your local `.env` and make sure you can still run …

Added SSL parameters to Elasticsearch connection

---

requirements.in
requirements.txt
test_requirements.in
test_requirements.txt

Fixes #1745 
Changes `factory-boy` and `faker` to be normal app requirements rather than test requirements
Check to see that the `seed_db` or `unseed_db` management commands work on the PR builds
I moved the `factory-boy` and `faker` requirements from `test_requirements.in` to `requirements.in` and ran `pip-compile` on both files

Changed seed_db requirements

---

static/js/components/UserInfoCard.js
static/js/constants.js
static/js/containers/UserPage_test.js

closes #1604 
This ensures that if the `UserInfoCard` receives a `Profile` which lacks an email it will not show the email icon.
Read over the changes and ensure they make sense.
If you visit your own profile you should see an email icon and your email. If you visit another user's profile you shouldn't see an email icon (given that you have a student role).
before:
after:

Hide email from UserInfoCard if it is not present

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/components/inputs/SelectField.js
static/js/components/inputs/SelectField_test.js
static/js/components/inputs/StateSelectField.js
static/js/components/inputs/inputs_test.js
static/js/util/test_utils.js

closes #1519 
This adds support to adding a custom entry to our `SelectField` component. In order to turn this on, you just pass a boolean `allowCreate` prop.
Read over the changes to `components/inpust/SelectField.js`.
On the profile everything should have all of it's normal functionality.
The new thing is if you're adding a work history or education history element. 
- If you type in something which is not in the list, you should see an option which says `'Create option "your input so far"'`.
- If you press tab or click on this your input should be the new selected value of the field.
- If you clear the field, the entry you entered should appear as an option you can re-select.
- If you reload the app and go to the same entry, the custom entry you saved should appear.
I think that's it?

Allow the user to create new entries in 'industry' and 'field of study'

---

micromasters/settings.py

Fixes #1533 
Sets `AWS_QUERYSTRING_AUTH` to false. When query string auth is disabled it will no longer set an expiration in the URL.
In the attached PR build upload a profile image. Verify that the profile image comes from S3 without any query parameters

Turn off querystring auth so we don't expire S3 asset links

---

static/js/DashboardRouter.js
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/PersonalTab_test.js
static/js/components/ProfileProgressControls.js
static/js/constants.js
static/js/containers/App.js
static/js/containers/App_test.js
static/js/containers/ProfilePage.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/js/util/util.js
static/js/util/util_test.js
ui/url_utils.py
ui/urls.py
ui/views_test.py

Fixes #1363 
Reintroduces named urls for the personal/education/professional tabs on the profile setup.
Take a look at `PersonalTab` (other tabs are similar) and the routes in `dashboard_routes.js`. Also look at `currentOrFirstIncompleteStep()` in `util/util.js`.
Sign up with a new account, verify you're directed to /profile/personal by default and that you're redirected there, particularly if trying to reach one of the later steps (e.g. /profile/education or /profile/professional). You shouldn't be allowed into those later steps until you've completed the personal tab.
We previously had named urls for each of these tabs, this PR reintroduces them, but also addresses the [original issue](https://github.com/mitodl/micromasters/issues/627) for the [PR that removed …

Fixed browser history for profile tabs

---

static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/util/util.js
static/js/util/util_test.js

- fixes https://github.com/mitodl/micromasters/issues/1712
- On search page, instead of showing preferred name of learners, it shows first and last name pair.

Set learners name on search to first and last name pair

---

static/js/components/inputs/SelectField.js
static/js/components/inputs/inputs_test.js

closes #1854 
This ensures that when opening an existing education or work history entry (which has a custom entry) the user will see the value in the field.
1. edit work history -> industry or educatoin -> field of study
2. save a custom option (e.g. 'Salmon psychology' or something)
3. open the entry again (w/ the edit button)
4. confirm that the custom entry is in the field still

Fix bug with custom entry

---

.coveragerc

This increases the precision of the reports generated by `coverage` from 0 to 2 (87% => 87.25%). We have enough code now that unless you're adding a huge the lack of precision hides any delta short of passing a rounding threshold.
Run `docker-compose run web tox` and verify you see the extra precision in `htmlcov/index.html`.

Increased coverage reporting precision to 2

---

static/scss/dashboard.scss

Fixes #1599 
Removes border between row and sub rows
I set up the PR build to have past runs, so you should be able to see the fix there, under Digital Learning. There should be no border between the past run message and the current run.

Remove border between row and sub rows

---

cms/templates/cms/home_page.html
static/scss/homepage.scss

Fixes #1559. Changes the CSS so that course cards tile correctly, even without course images and with variable course description lengths.

CSS fallbacks for home page

---

courses/serializers.py
courses/serializers_test.py

Fixes #1003
Changes the program serializer to return the external URL if it exists, instead of the CMS URL
Create a program page in the CMS and set the external URL to something. Go to `/api/v0/programs/` and confirm that the URL there is the one you typed in, not the link to the CMS page.

Use external URL if one exists

---

static/js/components/inputs/CountrySelectField.js
static/js/components/inputs/inputs_test.js

closes #541 
Makes sure that the label is different for the US and the British virgin islands.
Go to `/profile` or similar and make sure that two distinct options come up if you type in 'Virgin Islands' into a country select field
Check that the values updated in the profile are the correct country code for the US and British islands.
helpful:
https://en.wikipedia.org/wiki/United_States_Virgin_Islands
https://en.wikipedia.org/wiki/British_Virgin_Islands

fix Virgin Islands labels

---

static/js/components/PersonalTab.js
static/js/components/PersonalTab_test.js
static/js/constants.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfileImage.js
static/js/containers/ProfileImage_test.js
static/js/containers/UserPage_test.js
static/js/flow/profileTypes.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js
static/scss/profile-image.scss

closes #1762 
This PR adds a new requirement to the signup process, which is that the user add a profile image.
First,check that the validation is working correctly:
1. use the django shell or similar to delete your user's profile image (if present)
2. visit `/profile/personal`
3. click 'next'
there should be a validation error, which will disappear when you add a profile image. Then you should be able to proceed with the rest of the signup flow.
The other thing to check is that the edit state for the personal form is persisted when updating the profile image. This was a bit tricky to get working, because the currently edited `profile` is what we check via validation, and the user may have started editing the form before adding an image.
1. visit `/profile/personal`
2. make some edit to …

make profile photo required during signup

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js

Fixes #1676 
Makes sure that the day countdown to a future course run ignores the time of day. For example, if a course starts in 3 calendar days, but the time of day for the start date is less than the current time of day, the countdown will still show 3
You can use the `alter_data` command to set a course to be enrolled and in the future:
`alter_data --action=set_course_to_enrolled --email=YOUR_EMAIL --program-title='Analog' --course-title='100' --in-future`
After that, you can run a django shell and edit the course run's `start_date` to set the time behind/ahead of the current time. The `Course starts in X days` message on the dashboard should show the same number.

Fixed future course start date display

---

static/js/components/ProfileImageUploader.js

#1875 
Basically just ensures that if there isn't a photo selected we don't try to call the function to issue the request.
Open the photo upload dialog, and click 'save' without selecting a photo. You shouldn't see any errors in the JS console.

Fix 'save photo' exception

---

static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js

closes #1850 
Firefox puts a red border around `<input>` tags which are targeted by the `:required` pseudo selector. This switches from `required` to `aria-required` to remove the effect.
Make sure that the red border is gone!
Before:
after:

Fix red border around calculator salary on Firefox

---

static/js/components/UserInfoCard.js

Improve accessibility text for edit profile button
Activate VoiceOver or ChromeVox, and tab to the edit buttons on your user profile page. The screen reader should clearly explain what these buttons do.

Improve accessibility text for edit profile button

---

static/js/entry/zendesk_widget.js

Zendesk changed the HTML that they use for their launcher button. As a result, the JS that I wrote to change the background color of the button broke. This pull request restores the background color that we want for the launcher button.

Update selector for Zendesk launcher button

---

.gitignore
cms/models.py
cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
financialaid/templates/review_financial_aid.html
financialaid/views.py
micromasters/settings.py
npm-shrinkwrap.json
package.json
requirements.in
requirements.txt
ui/templates/base.html
ui/templates/base_error.html
ui/templates/dashboard.html
ui/templates/terms_of_service.html
ui/templatetags/render_bundle.py
ui/templatetags/render_bundle_test.py
ui/views.py
webpack.config.dev.js
webpack.config.prod.js
webpack.config.shared.js

Part of #1662
Bundles now have a hash concatenated on the filename for production builds. This will allow us to set a far future expiration header for these assets which will make it easier to deploy on a CDN.
This also removes `get_bundle_url` and uses a template tag in its place
ui/templatetags/render_bundle.py
Make sure that the JS bundles are still properly rendered for each page, for both development and production builds. Nothing should break. Hot reloading should still work.

Turned on webpack stats generation, use stats for filenames, use templatetags

---

backends/pipeline_api_test.py
courses/serializers_test.py
courses/views_test.py
ecommerce/admin_test.py
mail/utils_test.py
micromasters/serializers_test.py
profiles/api_test.py
profiles/permissions_test.py
test_requirements.in
test_requirements.txt

The [`mock`](http://www.voidspace.org.uk/python/mock/) library is bundled in Python 3 as [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html), so we don't need to install the library from PyPI.

Replace mock with unittest.mock

---

dashboard/views.py
dashboard/views_test.py
micromasters/exceptions.py
micromasters/utils.py
micromasters/utils_test.py
tox.ini

closes #1817 
Sends `ImproperlyConfigured` exceptions (and subclasses of it) to Sentry even if they are handled.
configure the `SENTRY_DSN` environment variable, try to make an enrollment for a course with closed enrollments on edX but open on micromasters and verify that the exception appears on Sentry.

Send ImproperlyConfigured exceptions to Sentry

---

static/scss/_button.scss
static/scss/dashboard.scss

This fixes the issue with a drop shadow showing on dialog buttons and the profile icon buttons. Fixes #1910.

Fixes button drop shadow problem

---

docker-compose.yml

Fixes #1909 
Runs Celery asynchronously on docker
Go into the Django shell and delete a `ProgramEnrollment`. There should be no exception regarding connecting to Celery

Run celery tasks asynchronously

---

npm-shrinkwrap.json
package.json
static/js/entry/zendesk_widget.js

Refs #1262. Hides the "name", "email", and "Micromasters program" fields in the Zendesk widget. Note that this will hide the fields ~~every time, regardless of whether they are pre-filled or not~~ that have values pre-set, and display the others.

Hide name, email, program fields in Zendesk

---

app.json
cms/templates/cms/home_page.html
cms/templates/cms/program_page.html
docs/styleguide-wording.md
static/js/components/ProgressWidget.js
static/js/components/ProgressWidget_test.js

I've noticed that different parts of the website use different phrasing to refer to a "master's degree". We should be consistent in our phrasing, to avoid confusing students who are trying to figure out what a master's degree is.
I don't know if what I've put into this styleguide is correct, but if it isn't, we should decide on what *is* correct, and standardize on that instead.

Add basic styleguide for wording

---

static/js/components/PersonalTab.js

closes #1895 
Just ensures that we put the right class name on the profile image card if it is invalid, so that the `scrollIntoView` function which finds invalid fields will work.
- Delete your user's profile image (set `user.profile.image` to `None` in the django shell) and visit `/profile/personal`. 
- either use the browser dev tools or squash the window to make the viewport short (so you won't be able to see the image field when scrolled down)
- scroll down and click on 'next'
it should scroll you up to the image card.

add scroll-to-error functionality to the profile image requirement

---

cms/models.py
financialaid/views.py
financialaid/views_test.py
ui/templates/footer.html
ui/views.py
ui/views_test.py

Fixes #1923 
Fixes #1925 
- Sets `has_zendesk_widget` to true on program pages which will cause the zendesk script tag to be included again
- Changes checks for the removed `public_src` to use `is_public` instead
- Tests
Make sure the share links appear on the bottom of the pages where they should appear, and the zendesk widget should appear on program pages.

Fixed javascript links

---

static/scss/homepage.scss

The DEDP program thumbnail caption currently wraps on the home page. This will hopefully fix that. Note on the live site (herokuapp) the name has been changed to "Data, Economics & Development Policy", using "&" instead of "and"

fixes program thumbnail title wrapping on home page

---

dashboard/api.py
dashboard/api_edx_cache.py
dashboard/api_edx_cache_test.py
dashboard/api_test.py
dashboard/models.py
dashboard/serializers.py
dashboard/serializers_test.py
dashboard/tasks.py
dashboard/tasks_test.py
dashboard/utils.py
dashboard/utils_test.py
dashboard/views.py
ecommerce/api.py
seed_data/lib.py

No issue - done as a precursor to #933 
**Rebased on #1890 (to help with testing)**
Streamlines user edX data fetching and avoids potential bugs 
dashboard/api_edx_cache.py and dashboard/models.py
Most of these changes are naming changes and repetitive changes to parameters, etc. The most significant functional change is the addition of [CachedEdxUserData](https://github.com/mitodl/micromasters/compare/master...refactor_user_edx_data_fetching#diff-54f823943ee528710d6f9d178443a994L18) and 
To test that the dashboard API still works correctly:
1. Unseed and seed the database, specifying `--staff-user=YOUR_USERNAME` when you run `seed_db`
1. Check the /dashboard page and make sure 'Digital Learning' and 'Analog Learning' look right
1. Enroll in a non-FA course using the `alter_data` …

Refactor user edx data fetching

---

micromasters/settings.py

Fixes #1661 
Fixes #1681 
Adds configuration allowing the use of Cloudfront for static assets (this does not currently include S3 hosted assets)
To make sure the URLs are configured properly, set the `CLOUDFRONT_DIST` environment variable to something random in the PR build. Refresh the page and note that the URLs to JS files are coming from cloudfront. (These URLs will not work for the PR build)
On micromasters-rc set the `CLOUDFRONT_DIST` environment variable. Everything should work as it did before, except that the static assets are fetched from cloudfront.net.

Added setting to configure Cloudfront

---

static/js/components/DocsInstructionsDialog.js
static/js/components/dashboard/FinancialAidCard.js

fixes #1952 
Changes the address for income verification documents and updates the FAQ in the calculator to match the ones in the CMS. 
Run the personalized price calculator with an income that requires verification. Check the address for verification and check that the FAQS that pop-up when you click on "Read Complete Instructions" match the first 5 "Questions about personalized course pricing" [FAQS in the CMS](https://micromasters.herokuapp.com/dedp/frequently-asked-questions/)

Updated income verification FAQs and address

---

static/js/reducers/programs.js
static/js/reducers/programs_test.js

Fixes #1942 
Fixes a bug for selection of the currently enrolled program. It previously chose the first one in the enrollment list, but this programs list now has unenrolled programs too. It's been changed to pick the first program the user is enrolled in, if it exists.
- Enroll in the first program that's live (the lowest id number). Make sure some other program is also enrolled.
- Select that program in the UI
- Delete the `ProgramEnrollment` for that program and user
- Refresh the browser. You should see the next program chosen in the program selector.

Fix handling of currently selected unenrolled program

---

courses/models.py
courses/models_test.py
courses/serializers_test.py

Fixes #1961
Uses `CourseRun.enrollment_url` for the `View on edX` link if it's available. Else, construct a URL using the course key as before
Set `CourseRun.enrollment_url` for some course run and look at its program page. The View on edX link should go to the URL you provided.

Use enrollment_url if provided for URL

---

cms/models.py
cms/templates/cms/home_page.html
financialaid/views.py
financialaid/views_test.py
ui/views_test.py

Fixes #1713
Fixes #1934 
- Adds missing `is_staff` context variable for program page and financial aid review page.
- Fixes related object error when accessing missing `ProgramPage` object
This should take care of all template variable warnings except the Django Debug Toolbar ones, though I haven't done an exhaustive search
Make sure you can still view the programs on the home page, and you should be able to click one to go to the program page in the CMS

Add is_staff for program and financial aid review pages and other cleanup

---

npm-shrinkwrap.json
package.json
static/js/entry/zendesk_widget.js

Fixes #1962 
Removes closest polyfill, uses `parentNode.parentNode` which works for now
Go to a programpage and verify that you see a zendesk widget

Remove closest, use parentNode.parentNode if available

---

static/js/components/CropperWrapper.js
static/js/containers/ProfileImage.js

part of #1971 
This changes the encoding when we call `.toBlob` in order to save a `jpg` instead of a `png`. In testing this results in a pretty big decrease in image size. 
Saving a `png` through our image thing actually seems to usually result in bigger images by default. Changing the encoding to `image/jpeg` seems to do a pretty good job of cutting this down.

don't use png, it is too big

---

static/scss/profile.scss
static/scss/user-page.scss

Closes #1937
This fixes a layout bug with the About Me copy on the user page. There are still some weird layout bugs with the user avatar and the user name in the same box, but I think that should be fixed in a separate PR. The problem was an incorrect implementation of flexbox, and widths.
Test this on a few browsers.
Before and after screenshots:

Fix about me width issue

---

static/js/components/ProfileImageUploader.js
static/js/containers/ProfileImage_test.js

Fixes #1990 
Disables save button during a photo upload
While the image is uploaded the  button should be greyed out. Clicking the disabled button should also not do anything.

Disabled photo button during upload

---

static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

1. use the django shell to delete your user's profile image
2. go to `/profile/personal`
3. confirm you can navigate forward without being prompted to add a profile image.

don't require a profile photo

---

backends/edxorg.py
backends/edxorg_test.py

fixes #2011
First and Last name in the EDXORG pipeline are used only to create the Django User object,
but given that we store these informations in the profile, we can remove them from there
and not risk to break the app because they are too long.
Create a name in edX where the string after the first space is more than 30 characters.
The MM app should not break.
You should also test that an user that previously failed to login, should be able to login after this PR is in place.
You should be able to see that the newly created user has no first and last name in the Django Admin/User.

Removed First and Last Name from the edxorg pipeline

---

static/js/components/search/CustomResetFiltersDisplay.js
static/js/components/search/CustomResetFiltersDisplay_test.js

- fixes https://github.com/mitodl/micromasters/issues/1803
- Enable pagination on ```/learners```. You can set ```ELASTICSEARCH_DEFAULT_PAGE_SIZE=10``` to any smaller value on ```.env``` file.
- Navigate between pages, you will not see 'Clear all filters' link.
- Apply filter and navigate, now you will see 'Clear all filters' link.
@pdpinch @noisecapella @aliceriot

Removed 'Clear all filters' link when user switch pages of unfiltered search

---

uwsgi.ini

closes #2001 
Adds a 301 redirect from micromasters.herokuapp.com to micromasters.mit.edu
uwsgi.ini
Edit your /etc/hosts to make micromasters.herokuapp.com resolve to your localhost and try visiting that URL. It should redirect you to micromasters.mit.edu (including the path portion of the request).
Some of our links are pointing to herokuapp.com so we want to make sure that everyone is using the mit.edu domain.
If users are visiting the site at the micromasters.herokuapp.com
domain this will issue a 301 redirect to micromasters.mit.edu

Added redirect when visitors are using the herokuapp domain

---

static/scss/program-page.scss

This fixes an issue where the FAQ "question" was wrapping underneath the toggle-arrow, which looked weird. It also slightly reduces the font size of the question. Closes #1993 
Before:
After:

Fixes a small layout issue on the FAQ tab

---

static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

This should restore the photo requirement. Delete your photo in the django shell, and ensure you can't navigate past the personal stage of the profile flow.

Revert "Changed profile validation to not require a photo"

---

static/js/actions/profile.js
static/js/components/EducationTab.js
static/js/components/EmploymentTab.js
static/js/components/PersonalTab.js
static/js/components/ProfileProgressControls.js
static/js/components/User.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/flow/profileTypes.js
static/scss/_button.scss

Part of #1752 
Disables buttons when updating the profile on the signup page, settings page and user page
This does not handle the user page at all or employment or education dialogs. Those will be a separate PR
Click next or save on the signup and settings page. The button should replace its text with a white spinner for the duration of the API activity.

Disabled buttons on signup and settings pages during profile update

---

dashboard/api_edx_cache.py
dashboard/api_edx_cache_test.py
dashboard/models.py
dashboard/serializers.py
dashboard/serializers_test.py
dashboard/utils.py
dashboard/utils_test.py
roles/api.py
static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js

Closes #933 
Adds the course facet to the learner search page
Probably dashboard/api_edx_cache.py and dashboard/serializers.py
With seed data loaded and your user given staff permissions, run the `recreate_index` command and check the learners search page. The course facet should be at the top.
Mockup: https://projects.invisionapp.com/share/E49IZSEWM#/screens/202316455_Learner_Search
There's a design quirk with this implementation: the facet shows an "All" option, and that option potentially shows a higher count than there are students in the search results. Basically it's a count of all of the unique course enrollments, so if User A is enrolled in 3 courses, it adds 3 to the "All" count. The "All" option is not part of the mockup, but it is added by searchkit and I haven't yet found a …

Created course facet to filter learners by course enrollment

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/containers/ProfilePage_test.js
static/js/containers/UserPage_test.js
static/scss/_button.scss

Part of #1752
Disables buttons for saving during profile upload for Education and Employment dialogs
Verify that the save buttons are disabled and that a blue spinner is shown in the buttons place. This should happen for employment and education, for both add and edit, and for both the signup page and the user page.

Disable buttons on employment and education dialogs during profile update

---

static/js/components/ProfileImageUploader.js
static/js/containers/ProfileImage_test.js
static/js/reducers/image_upload.js
static/js/reducers/image_upload_test.js
static/scss/profile-image-uploader.scss

closes #2020 
this persists the photo edit state if the request is currently in-flight, so that the user is prevented from issuing another request (to upload the profile image) if one is already in-flight. I also added an `<Spinner />` to the save button, which we should while the request is processing (should help with longer requests, I think).
this is how, on master, you can currently initiate multiple requests:
1. throttle your upload speed (gives you more wiggle room, 2G is probably sufficient)
2. add a new profile image, and click 'Cancel' after clicking 'Save'
3. Re-open the photo dialog, and add a new profile image.
if you look in the network tab of your browser's dev tools you should see two requests in flight.
If you follow the same steps here there should be only one, and the …

prevent multiple concurrent image uploads

---

npm-shrinkwrap.json
package.json
static/js/components/CropperWrapper.js

This implements a function that uses `<canvas>` to limit the maximum dimensions of user photos to 1024x1024 (right now, we can use whatever number we want).
Probably just ensure that even if you throttle your connection it is possible to upload an image? hopefully...

Limit user photo uploads to 1024x1024 pixels

---

static/js/components/EducationForm.js
static/js/components/EmploymentForm.js
static/js/components/ProfileProgressControls.js
static/js/components/SpinnerButton.js
static/js/components/UserInfoCard.js
static/js/components/UserPageAboutMeDialog.js
static/js/components/UserPageAboutMeDialog_test.js
static/js/components/UserPagePersonalDialog.js
static/js/containers/UserPage_test.js

Part of #1752
Disable buttons during profile upload for about me and personal info dialogs.
AFAIK these dialogs are only accessible on the user page. Edit the about me and click save, and edit the personal info and click save. A blue spinner should appear in place of the save button and more clicks should not cause the button to get clicked anymore.

Disable buttons during profile upload for about me and personal info dialogs

---

static/scss/user-chip.scss

This fixes a couple small layout issues with the user chip. First, it moves it slightly to the right so it does not cover up the user name as much in the results table. Then it floats the user image to the right side of the user chip. A couple other minor changes to margins etc.
Before:
After:

Fixes minor layout issue with the userchip

---

npm-shrinkwrap.json
package.json
static/js/components/LearnerSearch.js

Fixes #1948 by removing [`react-sticky`](https://github.com/captivationsoftware/react-sticky). The library doesn't have a way to keep a sticky element bounded within a container in the way that we need. Note that this change causes the facets sidebar to scroll with the rest of the page, so that scrolling down through the results causes the facets to hide from view.

Remove React-Sticky

---

dashboard/tasks.py
dashboard/tasks_test.py

part of #1945 
adds a more granular logging to the task handling the refresh of the edX data
`dashboard/tasks.py`
make sure that whatever happens, the refresh of the user cached data will not end up in a killed task.

Refactored task code to refresh users edX data.

---

static/js/util/profile_edit.js
static/scss/profile-form.scss

closes #1849 
Hopefully this makes the gender radio buttons more accessible, by giving them proper labels and so on.
@singingwolfboy I would love to get your feedback on this, since I'm not sure this is the proper way to address this. MaterialUI is a bit frustrating to deal with here.

making the gender radio buttons more accessible

---

static/js/entry/zendesk_widget.js

Fixes #2074. It appears that sometimes, the Zendesk web widget loads with HTTP headers that instruct the browser to increase cross-domain security. When that happens, our Javascript is unable to modify the Zendesk web widget at all, and the browser raises an exception every time it tries. These exceptions go to Sentry, and clog up the exception logs.
This pull request mades the code more defensive, check to see if it can modify the iframe before doing so. If it can't, it doesn't even try. This should prevent these errors from going to Sentry, but it does _not_ solve the underlying problem of being unable to modify the Zendesk web widget.

Check for cross-domain security for Zendesk widget

---

static/js/components/search/FilterVisibilityToggle.js
static/js/components/search/FilterVisibilityToggle_test.js

Fixes #2062 
The course facet queries against a nested field ("enrollments"). Nested field results contain a `doc_count` that equals the total number of docs returned, and an `inner` element that indicates the number of docs that matched the nested query. We didn't have logic for hiding search facets on empty 'inner' results for nested fields. This PR fixes that
1. Seed the db and give yourself staff permissions on the fake programs (`./manage.py seed_db --staff-user=YOUR_USER`)
1. Go into a Django shell and run the following:
```python
from dashboard.models import CachedEnrollment
from courses.models import Program
analog_program = Program.objects.get(title__startswith='Analog')
CachedEnrollment.objects.filter(user__profile__birth_country='ES', …
```

Fixed faulty hiding for facets that use nested fields

---

npm-shrinkwrap.json

fixes this problem: 
https://hackernoon.com/npm-shrinkwrap-allows-remote-code-execution-63e6e0a566a7#.h0me122hf

only use https in npm-shrinkwrap (security vulnerability fix)

---

static/js/components/LearnerSearch.js

this is part of #2038, just taking care of the easier case. we'll come back for the 'current residence' facet later.
copying what I wrote about test data on #2078:
first, save the following as `codes.js`:
```js
var fs = require('fs')
var iso = require('iso-3166-2')
let codes = Object.values(iso.codes)
console.log(codes.join("\n"))
```
then, save the following as `codes.py`:
```py
with (open("codes.txt")) as f:
codes = f.read().splitlines()
for user in User.objects.all():
user.profile.birth_country = codes[user.id % len(codes)]
user.profile.save()
```
Then do:
```sh
node codes.js > codes.txt
```
open the django shell and type:
```py
exec(open("codes.py").read())
```

Limited the birth country facet to 15 options

---

static/js/components/ProgramFilter.js

closes #2090
This ensures that we call the `resetState` method before the `reloadSearch` method in `<ProgramFilter />`. `resetState` clears the current UI state (things selected and so on) and `reloadSearch` causes searchkit to perform a new search.
Go to the search page and select a value for, say, country. You should then be able to switch countries, and the search UI will reset to it's normal state.

ensure that query is reset when changing programs

---

dashboard/api.py
dashboard/api_test.py
static/js/components/dashboard/CourseDescription.js
static/js/components/dashboard/CourseDescription_test.js

fixes https://github.com/mitodl/micromasters/issues/2064
- from admin panel, go to course run and set ``enrollment_url``
- then see course where you are not enrolled. open link it will take you to your entered url.
- then see course where you are enrolled, it will take you to course.
- remove ``enrollment_url`` from same course run on admin panel
- see link will not visible.

Fixed "View on edx" links to wrong URLs

---

backends/edxorg.py
backends/pipeline_api.py
backends/utils.py
ecommerce/api.py
ecommerce/api_test.py
financialaid/api_test.py
micromasters/models.py
seed_data/lib.py

Fixes #1960
Fixes datetime handling to use a specific timezone. It doesn't look like this was causing problems for us since `timestamp()` returns the same value for a naive datetime and one set to `UTC`, but it may prevent problems in the future if we're explicit.
There shouldn't be any change of behavior

Replace utcnow() with now(tz=pytz.UTC)

---

static/js/components/CropperWrapper.js

closes #2096
This fixes an error that I think is related to a subtle race condition with how we take down the photo upload dialog. We pass a callback (`ready`) to the `<Cropper />` component, which is something that fires when the image finishes loading. We do this so that as soon as the user's picture is loaded they can click 'save' in order to save it (without that the user would need to make at least one edit to the picture in order to save it). I think what is happening is that after the upload request is successfully completed, we dispatch the `CLEAR_PHOTO_EDIT` action, which forces a redraw of the `<Cropper />` element (because the `photo` prop passed in to it changes). Then the `ready` callback will be called, but I think what's happening is that the dialog closes at the same time, …

only run the getCroppedCanvas method if this.refs.cropper is defined

---

static/js/components/SpinnerButton_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseListCard_test.js
static/js/components/dashboard/CourseRow.js
static/js/components/dashboard/CourseSubRow.js
static/js/containers/DashboardPage.js
static/scss/_button.scss

Part of #1752 
Disable enroll and pay later button during API activity
Unenroll yourself in a course run via edX, then click the link. It should temporarily turn into a spinner and then disappear after successful enroll.

Disable enroll and pay later button during API activity

---

static/js/components/SpinnerButton.js
static/js/components/SpinnerButton_test.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseListCard.js
static/js/components/dashboard/CourseRow.js
static/js/containers/DashboardPage.js
static/scss/dashboard.scss

Part of #1752 
Disable the 'Pay now' button during API activity
It's probably easiest to mock the methods in `api.js` (see [here](https://gist.github.com/noisecapella/6de5541d42f0334dbae1fa4b45f10b81)) . Once you see the 'Pay now' button, click it. It should show a spinner while it POSTs to the checkout API.
Also verify that the pending enrollment status hasn't changed despite CSS updates. If you're using the mocked data this is the second row from the bottom on Master program

Disable the Pay now button during API activity

---

static/scss/search-page.scss

Fixes #2124. Corrects the spacing around the course search facet to account for course names that wrap to multiple lines.

Correct spacing for course search facet

---

static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/containers/FinancialAidCalculator_test.js
static/scss/_button.scss

Part of #1752
Disables the document sent button during API activity
Apply for financial aid, then click the button which submits the document sent date. It should show a spinner and be unclickable during that time.

Disable document sent button during API activity

---

static/js/components/dashboard/CourseSubRow.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/constants.js
static/scss/dashboard.scss

this closes #1887 
This changes the `CourseSubRow` component so that it will now show the grade for a past `CourseRun` which the user passed.
There's a patch here: https://gist.github.com/aliceriot/d729233d17d33bc0567bd0897de916a7#file-mm_mock_api_12_14_16 which will set things up to test this with the data in `constants.js`. Here's how to use it:
```
curl https://gist.githubusercontent.com/aliceriot/d729233d17d33bc0567bd0897de916a7/raw/610744ad5ad3603622760492e99ed1b1946d7549/mm_mock_api_12_14_16 > mock_api.patch
git apply mock_api.patch
```
then when you visit the dashboard there should be a course in the `Master` program titled `Passed course, most recent run non-passed, older passed`, which will have two past course runs, one passed and one failed.

Show grade for prior passed course runs

---

static/js/components/SkipFinancialAidDialog.js
static/js/components/SpinnerButton.js
static/js/components/SpinnerButton_test.js
static/js/components/dashboard/FinancialAidCard.js
static/js/components/dashboard/FinancialAidCard_test.js
static/js/components/inputs/util.js
static/js/containers/DashboardPage.js
static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js

Part of #1752
- Disable skip financial aid button during API activity
- Disable skip or add financial aid buttons when the other one has API activity going on, without showing a spinner

Disable skip financial aid button during API activity

---

static/js/components/ProfileImageUploader.js
static/js/components/inputs/util.js
static/js/components/inputs/util_test.js
static/js/containers/ProfileImage_test.js

Fixes #1752
Refactors dialog buttons to use the `dialogActions` function we use everywhere else

Use dialogActions for photo upload dialog

---

.editorconfig

Adds a `.editorconfig` file, which informs editors/ides of some basic code styles. In this case I'd only added settings for Python and JS files to be space-indented with 4 and 2 spaces respectively. I also put in no trailing newline at EOF for Python since our linter enforces that too.

Added minimal .editorconfig

---

seed_data/management/commands/alter_data.py

Fix #2044
Added a management command that allows the user to make a past passed course run for a user (in a non FA program)
Enroll in the Analog Learning program.
Run this command and check if you can see the passed course in the dashboard:
`alter_data --action=add_past_passed_run --username=staff --program-title='Analog' --course-title='100' --add-if-exists`

Added add_past_passed_run command in alter_data

---

dashboard/factories.py
dashboard/factories_test.py
dashboard/serializers.py
dashboard/serializers_test.py
search/indexing_api.py
static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js
static/scss/search-page.scss

Closes #1730 
Adds additional Paid/Audit filters to the course facet
dashboard/serializers.py
1. Seed your data and make yourself a staff user
1. Run the code block that I will include in a comment (it's somewhat long, so I didn't want to overwhelm the PR description)
1. Check the course facets for both the Analog and Digital Learning programs for the 100-level course. They should have some Paid and some Auditing users, and applying those filters should work
The change in format for the enrollments nested index was made to support a specific searchkit component.

Created course payment status facet

---

static/js/components/ConfirmDeletion.js
static/js/components/EducationForm.js
static/js/components/EducationTab.js
static/js/components/EmploymentForm.js
static/js/components/EmploymentTab.js
static/js/components/LearnerSearch.js
static/js/components/Navbar.js
static/js/components/PersonalTab.js
static/js/components/ProfileProgressControls.js
static/js/components/ProgressWidget.js
static/js/components/User.js
static/js/components/UserInfoCard.js
static/js/components/UserPageAboutMeDialog.js
static/js/components/UserPagePersonalDialog.js
static/js/components/inputs/CountrySelectField.js
static/js/components/search/CountryRefinementOption.js
static/js/components/search/CustomNoHits_test.js
static/js/components/search/FilterVisibilityToggle.js
static/js/containers/LearnerSearchPage.js
static/js/containers/ProfileFormContainer.js
static/js/containers/UserMenu.js
static/js/containers/UserPage.js
static/js/flow/profileTypes.js
static/js/lib/redux.js
static/js/lib/redux_test.js
static/js/util/ProfileFormFields.js

We had a lot of arrow functions declared on classes, annotated with the `Function` type, like this:
```js
class Foo {
bar: Function = () => (
'potatoes'
);
}
```
Turns out that annotating functions like that is sort of equivalent to annotating them with the `any` type, meaning that the return types and so on aren't checked. Not good!
We had to do this previously because at a certain point Flow didn't properly support annotating that syntax, but now it can.
Anyway, I removed any annotation of an arrow function with `Function` and fixed all the flow errors which cropped up in that process (quite a few).
Read over the changes, make sure my regex to remove the `Function` annotations wasn't messed up somehow, and make sure the changes make sense, in general.
I think just make sure there are no …

Remove `foo: Function = () =>` annotations

---

ui/templates/base.html

`{# this syntax #}` only works for single-line comments, apparently. Fix for a bug introduced in #2161.

Fix django template comment

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/constants.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js

fixes https://github.com/mitodl/micromasters/issues/1568
- show error message when user paid for course but not enroll.

Notified user when enrollment status doesn't match paid status

---

ui/templates/base.html

closes #2162 
just moves the zendesk widget `<script />` tag down, so the request it non-blocking.
Just confirm the zendesk widget still shoes up

Move the zendesk widget tag

---

config/nginx.conf
config/nginx.conf.erb
uwsgi.ini

None
- Updates nginx config to properly handle static assets for production, and removes static asset handling for dev, where Django will handle all static assets
- Removes `static-map` directive for `uwsgi`
When we turned on Cloudfront `STATIC_URL` was changed to an absolute URL from a relative one. This caused Django not to serve static assets anymore, and our nginx config wasn't matching static URLs properly. With this change nginx should handle all static file handling for production.
In the PR build go to https://micromasters-ci-pr-2172.herokuapp.com/cms/. You should see a broken login page and you should see cloudfront URLs for JS static assets in script tags, starting with `FAKE.`
In the PR build go to https://micromasters-ci-pr-2172.herokuapp.com/static/wagtailadmin/js/vendor/jquer …

Fix static asset handling

---

Dockerfile-node
package.json
travis/Dockerfile-travis-watch-build

Fix for a deploy problem on CI, relevant yarn issues:
https://github.com/yarnpkg/yarn/issues/2142
https://github.com/heroku/heroku-buildpack-nodejs/issues/359
https://github.com/yarnpkg/yarn/issues/1981

update yarn to 0.18.1

---

travis/Dockerfile-travis-watch

This undoes a change I introduced in https://github.com/mitodl/micromasters/commit/a5520933512dce04f57ade6ce8a5c179e2ef4828 - I changed things around so that the JavaScript docker file for travis inherited from `mm_watch_travis_yarn`. I changed that so I could push up a new container which had `yarn` in it without messing with master at all.
Since that commit is in master, we don't need this separation anymore, so this PR will point the travis JavaScript dockerfile back at `mm_watch_travis`. I ran the `travis/update-docker-hub.sh` script already, so `mm_watch_travis` has yarn installed.
To review this, just make sure that the tests all pass and everything looks normal on travis.

changed watch travis docker container to point back at mm_watch_travis

---

config/nginx.conf.erb

**Added access control header for static assets**
CMS and Admin are generating CORS errors when served through
cloudfront. Adding access control header for all static assets.

Added access control header for static assets

---

static/js/components/ProfileProgressControls.js
static/js/components/inputs/SelectField.js
static/js/components/inputs/inputs_test.js
static/js/containers/ProfileFormContainer.js
static/js/lib/google_analytics.js
static/js/lib/google_analytics_test.js
static/js/util/profile_edit.js
static/js/util/profile_edit_test.js
static/js/util/util.js

closes #1919 
closes #2040 
This adds a couple of new google analytics events, adding events for profile completion (clicking "I'm done") and for completing each form field.
You'll have to make a google analytics account and then set the `GA_TRACKING_ID` variable to the acocunt it. Then go through filling out the profile, and make sure that events show up which reference the form fields and have your username in the 'label' field.

Add more Google Analytics events

---

requirements.in
requirements.txt

Follow-up to #1635. [ChangeLog is here.](https://github.com/wagtail/wagtail/blob/master/CHANGELOG.txt) Doesn't look like there's any big changes that will affect us in this upgrade.
This pull request is not urgent. It is only to keep us up-to-date on the upgrade treadmill.

Upgrade Wagtail to 1.8

---

profiles/migrations/0025_populate_image_small.py

Fixes #2216
Silences `OSError` if it occurs during an image thumbnail conversion. In this case it leaves the `image_small` field `null` and moves on to the next one.

Check for OSError during image migration

---

config/nginx.conf
config/nginx.conf.erb

Added `$request_uri` suffix to Nginx redirect.
N/A
Fixes regression in redirects from micromasters.herokuapp.com where it is no longer preserving the request URI
config/nginx.conf.erb
Use Charles Proxy to map the PR build to micromasters.herokuapp.com and see if the redirect maintains the path.

Updated redirect to preserve request URI

---

static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/reducers/ui.js
static/js/reducers/ui_test.js
static/scss/user-chip.scss

Part of #2213
Removes CSS hover rule for user chip and replaces it with explicit state in redux. This means the DOM elements are only mounted when the user hovers over the name, which means the image on the UserChip is only loaded on first mouseenter.
Make sure hovering over the name still produces the user chip. Hovering over the user chip itself should also keep the user chip visible.

Implement lazy loading for UserChip

---

micromasters/settings.py

closes #2224 
Adds a setting dictionary that collect all the feature flags passed via environment variable or configuration files.

Added infrustructure for feature flags

---

.eslintrc
package.json
static/js/global_init.js
yarn.lock

closes #2229 
This adds a new eslint plugin (for mocha) and turns on some new eslint rules defined in that plugin. Should catch anyone doing a `describe.only` or similar things.

add eslint rules for mocha

---

static/js/components/EmailCompositionDialog_test.js
static/js/components/SpinnerButton.js
static/js/components/SpinnerButton_test.js
static/js/components/UserPageAboutMeDialog_test.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/ProfilePage_test.js
static/js/containers/SettingsPage_test.js
static/js/containers/UserPage_test.js
static/scss/_button.scss

Fixes #2140
Stores state on whether the button was recently clicked. Only buttons which are recently clicked show the spinner, otherwise the button is disabled.
Set your network throttling to simulate a slow connection, and configure your dashboard to show more than one course which has the enroll link. Mocking the functions in api.js might be useful here. Then click one of the enroll buttons. Only that button should have the spinner, and the other enroll buttons should be disabled. When the API call completes, the buttons should all be enabled again.
The dot on top here is actually part of the spinner

Show spinner only on currently active button

---

exams/pearson.py
exams/pearson_test.py

Fixes casing issue on CDD column name. `ClientCandidateId` -> `ClientCandidateID`.

Fixed casing on CDD column name

---

seed_data/lib.py
seed_data/management/commands/alter_data.py

No tickets. 
Fixes a bunch of outstanding issues with alter_data and adds a few simple new options. Here's a list of the fixes:
1. Changed the 'action' parameter to be a positional argument b/c it's required
1. Added to ability to target specific course runs if that's what the user wants to do. (eg: `alter_data set_to_failed --username=staff --course-run-key='MITx+Analog+Learning+100+Dec_2016'`)
1. Made usage details and example commands more helpful
1. Renamed a bunch of functions/variables to be more clear
1. Got rid of the '--add-if-exists' option for adding past failed/past runs. It wasn't helping, so that's done by default now
Run through a few of the example commands printed by `alter_data examples`, tweak a few arguments here and there, and check on the results either using …

Updated alter_data commands and fixed various issues

---

dashboard/utils_test.py
search/base.py

None
Renames tests to have them run, and fixes ESTestCase to reindex before `setUpTestCase` so that signals can connect to Elasticsearch

Fixed test names

---

package.json
yarn.lock

This upgrade will allow us to use the `R.forEachObjIndexed` function, which @aliceriot suggested I use in an improvement for #2167. [ChangeLog is here.](https://github.com/ramda/ramda/issues/2029) I expect that this is a very low-risk upgrade.
For manual testing, it should be sufficient to load up the application and click around a bit, particularly the Javascript-heavy pages on our site. If everything seems to work, it's probably fine.

Upgrade Ramda to 0.23

---

app.json

Fixes #2258
Turns off the node modules cache for heroku builds which fixes problems with yarn install cache deployment
Make sure deployment worked

Added NODE_MODULES_CACHE

---

micromasters/settings.py

Fixes #2030
Changes the default log level
Go into the heroku shell and load an object from the ORM. You shouldn't see any SQL statements output

Change default log level to INFO

---

README.md
docs/google-api-key.md

Follow-up to #2167. This pull request provides developer-facing documentation for how to get a Google API key, so that they can use features like the Geosuggest element in their own local development setup.

Document how to get a Google API key

---

static/js/components/ProgressWidget_test.js
static/js/util/util.js
static/js/util/util_test.js

- Fixed https://github.com/mitodl/micromasters/issues/2271
- Check past runs of course i.e if we have passed run in past it will count course as passed.
@pdpinch

Fixed progress widget ignores prior (passed) runs issue

---

static/js/components/PersonalForm.js

`address` requires at least a street address, while `geocode` appears to only require some kind of geographical reference -- even references as broad as "United States" are acceptable. https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Use address type rather than geocode type

---

test_requirements.txt

Fixes #2268
Upgrades test dependencies which incidentally fixes a pytest issue. I skipped upgrading Django since that conflicts with `requirements.txt` and it seems like it would require some extra work
Since these are only test dependencies we shouldn't need to do manual testing here, if the tests still pass

Upgrade test dependencies

---

app.json
static/js/components/PersonalForm.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js
ui/views.py

For the time being, we want to go back to using text inputs for the user's address in the profile form. However, we will be using the Geosuggest component in the future. This is a partial revert of #2167.

Revert Geosuggest UI in PersonalForm

---

search/api.py
search/api_test.py
search/views_test.py

Fixes #2301 
Adds filtering so that only `filled_out` profiles are seen via the search API.
With one account, create a profile which is partially filled out. Complete the personal step and go to the next step, but do not go any further.
With a staff account, view the learners search. You should not see any learners in the results.
Log back in with the first account and complete your profile. Then log back in as staff and view the learners search. You should see one learner in the results, the one you just created.

Filter filled_out fields

---

profiles/serializers.py

These fields were introduced in #1862, but they aren't actually necessary. Because these classes inherit from `ModelSerializer`, they automatically generate these fields, so there's no need to specify them (except in the `Meta.fields` list, where they're already specified).

remove extraneous about_me serializer fields

---

cms/serializers.py
courses/serializers.py
profiles/serializers.py

[pylint-django](https://github.com/landscapeio/pylint-django) takes care of suppressing this

Don't need to make pylint disable missing-docstring for serializer Meta

---

dashboard/fixtures/user_enrollments.json

None
Changes the enrollment status in test data from `verified` to `audit` for test data, since this course run is used in FA programs and users are always `audit` on edX for FA programs

Change status for enrollment to audit, since it's used in FA programs

---

pytest.ini

Fixes #2307 
Adds --reuse-db flag to speed up running Python tests locally.
Run the Python tests twice, maybe on a single file. The second run should be notably faster than the first. No tests should fail.

Add --reuse-db flag to speed up running Python tests locally

---

static/js/components/search/LearnerResult_test.js
static/js/constants.js

Fixes #2303 
It adds tests around `<LearnerResult/>` to ensure it doesn't raise an error and cause the whole page to fail to render if profile properties are null or undefined. This should be sufficient to catch errors in the code for existing properties, although there's always a possibility that someone adds code for a new property that isn't null-safe and forgets to add it to the test data here. I don't think there's a good way to test against that.
This is a test-only PR so we want those to pass.

Test learner search against null/undefined props

---

RELEASE.rst
cms/factories.py
cms/serializers.py
courses/factories.py
courses/serializers.py
dashboard/fixtures/user_enrollments.json
ecommerce/factories.py
financialaid/factories.py
micromasters/settings.py
profiles/factories.py
profiles/serializers.py
pytest.ini
static/js/components/search/CountryRefinementOption.js
static/js/components/search/CountryRefinementOption_test.js
static/js/components/search/LearnerResult_test.js
static/js/constants.js
static/js/lib/currency.js
static/js/lib/currency_test.js
static/js/lib/location.js
static/js/lib/location_test.js
static/js/util/util.js
static/js/util/util_test.js

Release 0.39.0

---

courses/models.py
dashboard/api.py
dashboard/api_test.py

closes #2253 
Removes the restriction about the fact that the payment must be done by the end of the course. Now the only limit is the `upgrade_deadline`, if present.
Set the course to `past` and with `upgrade_deadline` in the future and verify that you can still see the pay button.
See the code for special cases with the dates and final grades existence.

Allow users to pay after end of the course.

---

static/js/components/LearnerSearch.js
static/js/components/search/PatchedPagination.js

Fixes #2336 
Fixes missing pagination control. Details in warroom

Fixed missing pagination in learner's search

---

static/js/components/PersonalTab.js
static/js/containers/App.js
static/js/containers/ProfilePage_test.js

closes #2347
This PR fixes a small UI bug with the program selector that we show on `/profile/personal`. 
Basically, if a user returns to `/profile/personal` to change something, and they have already enrolled in a program, we don't want the program selector to be empty. If the program selector is empty, when the user presses 'save' we will show a validation error - if the user is already enrolled in a program this is inappropriate.
I made a change in https://github.com/mitodl/micromasters/commit/72504a58efe6d679e3e3f69f7d76e5a67a83e2f4 that was supposed to address this. My earlier fix made sure that, after we fetch the program enrollments, we check if the user is on `/profile` and, if so, we dispatch the action to pre-set the user's first enrolled program, which would prevent the …

fix program selection

---

ui/templates/base.html

Follow-up from #2263. We should use variable references, not hardcode IDs.

Replace hardcoded Adwords Conversion ID with variable reference

---

static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js

Fixes #2359 
Fixes an infinite loop regarding toast messages. If a toast message is already present other messages will be ignored.
Go to the URL with `/dashboard/?status=receipt&course_key=course_key`, where `course_key` is the edX course key, encoded as a query parameter. The course key can refer to any run which is present in the dashboard API. You should see an order success toast message which goes away after 5 seconds. Also go to `/dashboard/?status=cancel` to verify that the cancellation message works too. If you go to these URLs when you're checked out on master you should get the toast loop which causes the browser to become unresponsive.

Fix toast message loop

---

ecommerce/api.py
ecommerce/api_test.py
ecommerce/models.py
ecommerce/models_test.py
ecommerce/permissions.py
ecommerce/serializers.py
ecommerce/serializers_test.py
ecommerce/urls.py
ecommerce/views.py
ecommerce/views_test.py

Fixes #2237 
Adds REST APIs for getting information about coupons and to attach a user to a coupon.
Create a coupon using the Django shell using the `CouponFactory`. Go to `/api/v0/coupons/`. You should see an empty list. Add the coupon to your user using `UserCoupon.objects.create(coupon=coupon, user=user)` in the shell. Look at `/api/v0/coupons/` again and you should see one coupon.
In the shell delete the `UserCoupon` by running `UserCoupon.objects.filter(user=user, coupon=coupon).delete()`. Go to `/api/v0/coupons/<code>/users/` and POST to that API with `{"username": "your-username-here"}`. In the shell verify that the `UserCoupon` was created via `UserCoupon.objects.filter(user=user, coupon=coupon).exists()`

Added coupon APIs

---

ecommerce/api.py
ecommerce/api_test.py
ecommerce/views.py
ecommerce/views_test.py

Fixes #2321 
Adds functionality for $0 checkouts. These checkouts will be immediately fulfilled and the user will be redirected to the order success page.
Change the price of all courses in a program to $0 (or adjust financial aid to cover all of the cost). Make sure there's one course run to purchase. Click on the button and you should see an order success toast message, and the course run in the dashboard should be shown as purchased.

Implemented $0 checkout

---

.eslintignore
package.json
search/indexing_api.py
search/indexing_api_test.py
static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js
static/js/components/search/ModifiedMultiSelect.js
static/js/components/search/WorkHistoryFilter.js
yarn.lock

Fix #863
Added a MultiSelect 'Company' filter to search for users that currently work at a company.
To test this, run the `recreate_index` command. Go to learners search and test the Company filter.
To test that a user does not appear under company name for a previous position, you can add another previous position for a user who currently works for 'Google':
```
from profiles.models import Profile, Employment
p= Profile.objects.filter(first_name="Rose",last_name="Li")[0]
Employment.objects.create(
profile=u,
city="Delisle", 
state_or_territory="CA-MB", country= "CA", 
company_name="Volvo",
position= "Mechanic", industry="Automotive",
end_date='2014-05-07',
start_date="2013-08-08")
```

Added Facet by Company

---

static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage.js

closes #2376
Makes sure that we scroll to any existing validation errors when the `ProfilePage` component mounts.
Go into the django shell and delete a field on your profile. Then visit `/dashboard`. You should be redirected to the profile page, and the page should scroll to ensure you can see the error.

scroll to error when profile page mounts (handle the redirect properly)

---

static/js/containers/App.js
static/js/containers/App_test.js

#2379 
This displays a toast message when we're going to redirect the user to fill out a missing profile field.
Use the django shell to null out a profile field, and then visit `/dashboard`. You should see a message at the top of the page that describes what's going on.

set the toast!

---

seed_data/lib_test.py
seed_data/management/commands/seed_db.py
seed_data/management/commands/seed_db_test.py
seed_data/management/commands/unseed_db.py
seed_data/management/commands/unseed_db_test.py

No ticket
2 recent changes caused some problems for the `seed_db` command:
1. Omitting users with `filled_out=False` from search results (this exposed a minor bug in the script)
1. Final grade freezing
Unseed and re-seed the db with your user as the `staff-user` parameter (`seed_db --staff-user=YOUR_USERNAME`), and check out the /learners search results. All of the seed data should be there
Details about the bugs being fixed:
- `Profile` deserialization wasn't properly setting `filled_out=True` for all of the test users
- The `FinalGrade` table needed to be cleared of fake course runs before the fake programs could be deleted

Fixed seed_db commands to work with indexing/grade changes

---

seed_data/management/programs.json
seed_data/management/users.json

No ticket. Done in response to #2336 
Rebased on #2316 
Ups the total fake user count to 120, and makes sure that each of the fake programs has over 50 user enrolled. This will ensure that the pagination control should show up.
Unseed, re-seed, reindex, and check /learners. Make sure both fake programs have page-able results

Updated realistic user and program data to add more fake users

---

static/scss/toast.scss

closes #2393 
This just adjusts the CSS for the toast component a little bit.
Remove the phone number for your profile. Go to `/dashboard`. You should be redirected to `/profile/personal`, scrolled to the phone number field, and there should be a toast message visible at the top of the screen.

ensure toast component is visible regardless of scroll position

---

app.json

Fixes #2394 
Adds missing env variables to app.json. I also moved `ADWORDS_CONVERSION_ID` to the correct lexicographical position.
app.json
I set the 5 `EXAMS*` vars in Heroku for the PR build. Connect to the dyno and verify the environment variables are present (`env | grep EXAMS`).

Added SFTP env vars to app.json

---

ecommerce/views_test.py

Fixes #2397 
Verifies that the modification date for `UserCoupon` is updated when the attachment is made. This is important since the most recently clicked link should be given priority, even if it's clicked twice

Added test that REST API updates modification datetime

---

dashboard/api.py
dashboard/api_test.py
dashboard/signals_test.py

fixes #2412 
Adds a feature flag to have different statuses for past course runs. 
in `v0` they need to be checked if the user passed it, in `v1` if the code reaches that place, there is a weird situation with the final grades. 
For a Non Financial aid course run already ended, add a `CachedEnrollment`, `CachedCurrentGrade` and `CachedCertificate` to fake the user has passed the course.
In this branch the course should appear as "Passed" while on master it should appear as "In Progress"
**NOTE**: the changes to `dashboard/signals_test.py` are irrelevant to this PR

Past enrolled courses need to be under feature flag

---

static/js/dashboard_routes.js

fixes #2415 
re-implements the redirect we had before, for redirecting `/learner` to `/learner/:username`.
based on the [react router docs](https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md).
Go to `/learner` and confirm the redirect works.

fix learner redirect

---

exams/pearson/constants.py
exams/pearson/readers.py
exams/pearson/readers_test.py
exams/pearson/writers.py
exams/pearson/writers_test.py

None - this PR is for common work needed in #1797 and #2080.
This PR implements a base TSV file reader in the style of the writers implemented in `exams/pearson/writers.py`.
exams/pearson/readers.py
There is no user-facing code for this yet, so passing tests are all we need here.

Added base reader class for Pearson TSV responses

---

webpack.config.prod.js

This option was set during development / testing and snuck into the merged PR

don't set 'use-credentials'

---

micromasters/settings.py
tox.ini
ui/templatetags/render_bundle.py
ui/templatetags/render_bundle_test.py

Fixes #2368 
Disables webpack loader from scratch
- You should still be able to see the dashboard
- Make `webpack-stats.json` have a JSON error somewhere, so that it can't be parsed. Run the tests in `ui/views_test.py`. The tests should all pass regardless of the error.

Add setting to disable webpack loader functionality for tests

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
dashboard/utils_test.py

- closes #1974
- Uses FinalGrade model to fetch users final grade if he has passed the course.
- To enable sue flag in .env file ``FEATURE_FINAL_GRADE_ALGO='v1'``

Used FinalGrade model to fetch final grade info on mmtrack

---

static/js/components/Toast.js
static/js/constants.js
static/js/containers/App.js
static/scss/toast.scss

Builds off of #2434. When there isn't a `toastMessage` in the Redux state, don't render the `<Toast>` component at all. This pull request also includes the `role="alert"` change from #2434.
This pull request should have no user-visible impact at all. Make sure that you can still get toast notifications through the app.

Don't render closed Toast

---

ecommerce/api.py
ecommerce/api_test.py

Fixes #2325 
- Adds a `RedeemedCoupon` between an order and coupon when the order is created
- Lowers the price in the backend when order is fulfilled
The `RedeemedCoupon` should only prevent other users from purchasing when the order is fullfiled
- Create a coupon locally in the Django shell using `CouponFactory`. Set `content_object` to a relevant run, course, or program which is available for purchase. Make sure that the discount will make the final price $0, to make it easier to test.
- Attach your user to the coupon using the API. POST `/api/v0/coupons/<coupon.coupon_code>/users/` with `{username: 'your_edx_username'}` to do this, or just create `UserCoupon` in the Django shell
- Purchase the course. The price will show up as the regular price of the course (inc financial aid), the …

Redeem coupon during checkout

---

ecommerce/views.py
ecommerce/views_test.py
package.json
static/js/actions/coupons.js
static/js/actions/coupons_test.js
static/js/actions/ui.js
static/js/actions/ui_test.js
static/js/components/CouponNotificationDialog.js
static/js/components/CouponNotificationDialog_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/factories/dashboard.js
static/js/flow/couponTypes.js
static/js/lib/api.js
static/js/lib/api_test.js
static/js/reducers/coupons.js
static/js/reducers/coupons_test.js
static/js/reducers/ui.js
static/js/test_constants.js
static/js/util/integration_test_helper.js
static/scss/dashboard.scss
yarn.lock

Fixes #2323.
When the user visits the dashboard with a `coupon` query parameter in the URL, that query parameter is assumed to be a coupon code. This PR detects that query parameter, and tries to attach the currently logged-in user to that coupon. If the coupon is invalid or doesn't exist, we pop a toast notification that it didn't work. If the coupon exists and is valid for the user, we pop a notification to confirm that they have successfully applied the coupon.
* Try applying a coupon code for a coupon that doesn't exist, and confirm that you get a notification.
* Then make a coupon that is invalid, and confirm you get the same notification when you try to apply it.
* Make a percentage discount coupon that can be successfully applied, and apply it. You should get a confirmation …

Attach user to coupon

---

Dockerfile-node
package.json
travis/Dockerfile-travis-watch-build
yarn.lock

This just upgrades `node-sass` and `sass-loader`, which gets rid of two of the unmet peer dependency errors we were getting with yarn + heroku. We don't _need_ to do this but I think it would be a good idea.

testing out solutions to yarn build problem

---

static/js/actions/email.js
static/js/components/LearnerSearch.js
static/js/components/email/EmailCompositionDialog.js
static/js/components/email/EmailCompositionDialog_test.js
static/js/components/email/constants.js
static/js/containers/LearnerSearchPage.js
static/js/containers/LearnerSearchPage_test.js
static/js/flow/emailTypes.js
static/js/lib/api.js
static/js/lib/validation/profile.js
static/js/reducers/email.js
static/js/reducers/email_test.js

No specific ticket - it is one of two issues that will address #2420 
⚠️️ **REBASED ON #2421** ⚠️️
Restructures the email portion of the app state to accommodate multiple email types
static/js/containers/LearnerSearchPage.js
With `MAILGUN_RECIPIENT_OVERRIDE` set to your email address, send a few emails from the /learners page using the "Email These Learners" button. Try a couple different filters and make sure the email you receive contains the right recipients. Also check for normal behavior of the email dialog
This doesn't change any functionality. I put this up as a separate PR due to the amount of code it changes

Changed front-end handling of emails

---

static/js/containers/SignupDialog.js
static/js/containers/SignupDialog_test.js

Follow-up from #2406. If the URL doesn't have a `next` query parameter, don't set a `next` query parameter when logging into Micromasters.

Don't needlessly set a `next` query param

---

static/js/actions/financial_aid.js
static/js/containers/DashboardPage.js

Related to #2429. If the user receives an API failure when trying to skip financial aid, show a toast notification with an error message.
I'm not sure the best way to write tests for this change. It doesn't seem like the `skipFinancialAid` is tested at all.

Display toast notification for API failure when skipping financial aid

---

static/js/actions/email.js
static/js/components/LearnerSearch.js
static/js/components/email/EmailCompositionDialog.js
static/js/components/email/EmailCompositionDialog_test.js
static/js/lib/api_test.js
static/js/reducers/email_test.js
static/scss/email-composition-dialog.scss

Closes #2420 
⚠️️  REBASED ON #2446 ⚠️️
- Completes implementation for the front-end API for course team emails
- Makes `EmailCompositionDialog` a generic component for use with any type of email (not just search result emails)
Just review the code. The actual end-to-end implementation of the course team email dialog will be in a the PR for #2284. If tests pass and code looks good, this should be ready to merge
This was done as a separate PR to limit the PR size

Completed implementation for front-end course team email API

---

exams/pearson/writers.py
exams/pearson/writers_test.py

Fixes #2463. When exporting a profile for Pearson, fall back on the 'first_name' and 'last_name' fields, if the 'romanized_first_name' and 'romanized_last_name' fields aren't set.

Correctly export user profiles with blank romanized name fields

---

static/js/components/dashboard/FinancialAidCard.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/FinancialAidCalculator_test.js
static/js/util/integration_test_helper.js

this closes #2334 
This checks to see if a user has a 100% off coupon before we show the financial aid card. If they do, we dont show it, and we automatically submit a request to 'skip' financial aid (provided they do not already have a financial aid object).
I think you want to:
1. confirm that without adding a coupon the financial aid card still appears.
2. add a 100% discount coupon to your user and ensure that your user does not currently have a financial aid.
3. visit `/dashboard`.
4. confirm that a request to skip financial aid was issued, and that the financial aid card UI does not show up.
I think that's it!

hide financial aid card if 100% coupon is present

---

dashboard/api.py
dashboard/api_test.py
grades/api.py
grades/api_test.py
grades/exceptions.py

closes #2391 
If the course run has already final grades and the user does not have one for the course run, a final grade freeze is performed synchronously for the user in the course run.
The manual test is pretty complicated. 
Set in your `.env` the variable `FEATURE_FINAL_GRADE_ALGORITHM=v1` 
To really test this, you should create 2 real courses on the edX instance with a real enrollment for your user and connect one to a course on a Financial Aid program and the other to a non Financial Aid program. 
Remember to create a verified enrollment for the non Financial Aid Program.
The reason why you need to create a real course is because the freezing of a grade will trigger a refresh of the cache even if the cache is fresh, so there is no way to avoid the request to edX. …

Freeze grade sync in case the course run has already frozen grades.

---

exams/urls.py
exams/views.py
exams/views_test.py
micromasters/test.py
micromasters/urls.py

Fixes #2173.
Sets up the following redirects:
```
/pearson/success => /dashboard?exam=success
/pearson/error => /dashboard?exam=error
/pearson/timeout => /dashboard?exam=timeout
/pearson/logout => /dashboard?exam=logout
```
Visit those four URLs in your browser, and make sure you are redirected correctly.

Pearson SSO callback views

---

static/js/components/OrderSummary.js
static/js/components/OrderSummary_test.js
static/js/containers/OrderSummaryPage.js
static/js/lib/coupon.js
static/js/lib/coupon_test.js

Fix #2491
This PR changes the the logic behind the display of the discount calculation to be based on an existing coupon, instead of the discount that is applied.
Displays the coupon code in the calculation.
As a learner, try to 'PAY NOW' for a course without any coupons, with a coupon, and with a coupon that gives $0 discount.

Show Coupon code on OrderSummary page

---

cms/models.py
cms/templates/cms/home_page.html
cms/util.py
cms/util_test.py
static/js/containers/App.js
static/js/containers/SignupDialog.js
static/js/containers/SignupDialog_test.js
static/js/entry/public.js
static/scss/toast.scss
ui/views_test.py

Fixes #2405.
If an anonymous user visits the home page with a `coupon` query parameter in the URL, this code will pop a toast-like alert dialog, informing the user that they must log in to use their coupon. If the user does log in, the `coupon` query parameter is retained through the login process, so that it can be automatically applied after the user is logged in.
Log out of the app, and visit the home page with a `coupon` query parameter in the URL. For example: `http://192.168.99.100:8079/?coupon=fake`. Verify that the toast-like notification appears, and that it can be dismissed by clicking the "x". (Unlike other toast notifications in the app, it will not fade away by itself.)
Verify that you can log in, either using the links in the toast-like notification, or using the standing …

Alert anonymous user if they try to use a coupon

---

ecommerce/api.py
ecommerce/api_test.py
static/js/lib/coupon.js
static/js/lib/coupon_test.js

Fixes #2438 
Caps the coupon adjusted price to have a minimum price of $0 and maximum price of the full price.
Create a fixed discount coupon and set it to -987654321. Apply it to the user, then check the dashboard and verify that the price is $0.

Cap coupon-adjusted price to between 0 and the full price

---

static/js/containers/LearnerSearchPage.js
static/js/containers/LearnerSearchPage_test.js

Fixes #2513 
Fixes the bug we were experiencing with sending an email to users that match a search query
Send a search result email from `/learners`, and without reloading the page, change the filters several times and attempt additional search result emails with that new search result set. Confirm that you're getting the expected recipients in the body of the emails you receive

Fixed ES search result email bug

---

dashboard/api.py
dashboard/api_test.py
dashboard/utils.py
dashboard/utils_test.py

N/A
In case there are final grades, they are taken in account in the dashboard before checking anything else. The reason is because we cannot rely on the existence of cached data long term.
Create a final grade for the user in a course run with a verified cached enrollment in a non financial aid program. The user should see if she passed (or not, depending on the final grade you created) the course on the dashboard.

The Frozen grade should be taken in account before enything else in case they exist

---

docker-compose.yml
exams/factories.py
exams/management/commands/simulate_sftp_responses.py
exams/management/commands/simulate_sftp_responses_test.py
exams/pearson/constants.py
exams/pearson/download.py
exams/pearson/download_test.py
exams/pearson/readers.py
exams/pearson/readers_test.py
exams/pearson/sftp.py
exams/pearson/sftp_test.py
exams/pearson/upload.py
exams/pearson/upload_test.py
exams/pearson/utils.py
exams/pearson/utils_test.py
exams/tasks.py
exams/tasks_test.py
exams/utils.py
exams/utils_test.py
micromasters/settings.py

_**Before starting review on this, please message me so I can share the documentation with you**_
---
Fixes #1797 and #2422
This PR primarily adds processing of two types of Pearson result files. Each row in these files is a result of a corresponding row in a file we uploaded. The results are asynchronous and since Pearson only processes our uploads every 12 hours it can be a while between upload and results. You can think of this as RPC-over-SFTP. Pearson places these files on their SFTP server so we have to periodically poll and check for new ones. They also need to be removed once we've processed them.
The two types of files we're immediately interested in:
- VCDC - results to CDD (profile data) files we upload. Corresspond to `ExamProfile` records.
- EAD - results to EAD (exam …

Pearson response processing

---

financialaid/serializers.py
financialaid/views.py
financialaid/views_test.py
static/js/factories/dashboard.js
static/js/flow/couponTypes.js
static/js/flow/dashboardTypes.js
static/js/lib/api.js
static/js/lib/coupon.js
static/js/lib/coupon_test.js
static/js/test_constants.js
static/js/util/util.js

#2523. Related to #2467.
This pull request modifies the course price API to return decimal values as strings rather than floating-point numbers, since Javascript/JSON does not have a decimal primitive type. This pull request also modifies the code that fetches from the course price API to automatically parse these strings into [`decimal.js-light`](http://mikemcl.github.io/decimal.js-light/) instances.
`financialaid/serializers.py` to verify that the back-end API serializes decimals correctly. Then `static/js/lib/api.js` to verify that the front-end code parses the serialized decimals correctly.
There should be **no user-visible changes** as a result of this pull request.

CoursePrice.price is a decimal

---

README.md
courses/models.py
courses/models_test.py
courses/utils.py
courses/utils_test.py
dashboard/utils.py
dashboard/utils_test.py
exams/management/commands/authorization_user_exam.py
exams/management/commands/test_authorization_user_exam.py
exams/signals.py
exams/signals_test.py
exams/utils.py
exams/utils_test.py

- fixes https://github.com/mitodl/micromasters/issues/2445
- Fixed ripples of #2331
- Refactored the code of exam authorization command
- Added exceptions and logging to see behaviour of code
- Added new tests for authorization code.
- In .env add `FEATURE_FINAL_GRADE_ALGORITHM=v1`
- Set program.exam_series_code
- Set course.exam_module
- Pay for course
- Create final grade http://192.168.99.100:8079/admin/grades/finalgrade/
- Run command ```docker-compose run web ./manage.py authorization_user_exam --username=(value) --program-id=(value)```
- Check weather ( ExamAuthoriztion) object created 
- ``docker-compose run web ./manage.py shell``
- ``from exams.models import ExamAuthorization``
-  ``ExamAuthorization.objects.all()``
```docker-compose run web ./manage.py shell```
```shell
from …
```

Fixed exam authorization command and refactoring

---

.coveragerc
.travis.yml
apt.txt
docker-compose.yml
pytest.ini
pytest_minimal.ini
scripts/test/run_selenium_tests.sh
selenium_tests/base.py
selenium_tests/basic_test.py
selenium_tests/pytest.ini
test_requirements.in
test_requirements.txt
travis-docker-compose.yml

Fixes #2414 
Adds a selenium test and runs it on Travis. The selenium test logs in and does a $0 purchase using a 100% off coupon.
Other Python tests should be unaffected. In Travis there will be a third job to run the selenium tests. `pytest.ini` has a directive to ignore `selenium_tests` so you don't have to do anything different to run the Python tests locally.
To run it locally:
- turn off the webpack server to prevent interfering with the `webpack-stats.json` file
- run `NODE_ENV=prod ./webpack_if_prod.sh` to generate the webpack bundles
- run `./scripts/test/run_selenium_tests.sh`. This will run only the selenium tests.

Added selenium testing

---

dashboard/factories.py
dashboard/serializers_test.py
dashboard/utils.py
dashboard/utils_test.py
ecommerce/api.py
grades/api.py
grades/api_test.py

closes #2537
Updates the rule for passing certificates to take in account the status `"downloadable"`.
Other statuses are considered not passing.
set the edx cache last refresh in the future
```
from datetime import timedelta
from dashboard.models import *
refr = UserCacheRefreshTime.objects.get(user__username='<your_username>')
refr.enrollment = refr.enrollment + timedelta(days=2)
refr.certificate = refr.enrollment
refr.current_grade = refr.enrollment
refr.save()
```
for the dashboard:
In a non financial aid program, create a verified cached enrollment and a verified certificate with status different from `"downloadable"` for a past course run. 
The course should be Failed.
Modifying just the status to `"downloadable"` in the cached data should turn the course to be Passed.
for the …

Only certificates with status "downloadable" are passing certificates

---

exams/signals.py
exams/signals_test.py
selenium_tests/base.py

Fixes #2573 
Lowers a single `log.exception` to `log.debug`.
This is just a logging statement and the tests exercise that code, so if they pass we're good.

Lower logging of unexceptional exception to debug

---

static/js/containers/FinancialAidCalculator.js
static/js/containers/FinancialAidCalculator_test.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

- Fixes https://github.com/mitodl/micromasters/issues/2470#issuecomment-279479984
- Throws error when prices entered on 
(Required)
- Open dashboard and then `Cost Calculator`
- Try to input string, alpha numeric
- Try to enter decimal number
- Try to enter special character 
- Try to enter whole numbers

Personal Pricing: Added validation on income so that it can only be an integer

---

static/js/util/util.js
static/js/util/util_test.js

Fixes https://github.com/mitodl/micromasters/issues/2464
- Rounded the nearest cent, or leave off the cents entirely when it's a whole number.
- See order summery or action btn 

Round to the nearest cent, formatPrice util

---

dashboard/api.py
dashboard/api_test.py
static/js/components/CouponNotificationDialog_test.js
static/js/components/dashboard/FinalExamCard.js
static/js/components/dashboard/FinalExamCard_test.js
static/js/factories/dashboard.js
static/js/flow/programTypes.js

closes #2534 
fixes the display for the 'schedulable' state (on the final exam card) so that it will show the titles of the courses for which the user is allowed to schedule an exam.
1. Make an `ExamProfile` for your user with status 'success'
2. find a course run in the program you want to use
3. make sure it has an edx course key
4. add an `exam_module` to the course associated with the run
5. add an `exam_series_code` to the program
6. create an `ExamAuthorization` for the user x course combination
7. set the `status` to be `success` on the authorization.
I think that's it!
then confirm that the final exam card (on the dashboard) shows the title of the course.

fix ready to schedule display

---

.travis.yml
docker-compose.yml
scripts/test/run_selenium_tests.sh
travis-docker-compose.yml

Fixes #2628
Creates a separate selenium container so that the grid container is not pulled with everything else when it's not needed.
Make sure you can run the tests locally and that you can see the website as before

Make separate selenium container for tests

---

static/js/components/dashboard/FinalExamCard.js
static/js/components/dashboard/FinalExamCard_test.js

- fixes https://github.com/mitodl/micromasters/issues/2553
- edits text and html
- make ur self authorized for exam , create ExamProfile and ExamAuthorization entry
- then open dashboard and select the respected program

Exams: HTML edited to exam card on dashboard

---

micromasters/settings.py
static/js/components/dashboard/FinalExamCard.js
static/js/flow/declarations.js
static/js/global_init.js
ui/middleware.py
ui/middleware_test.py
ui/utils.py
ui/views.py
ui/views_test.py

Fixes #2558 
Adds a general mechanism for enabling feature flags per user and implements one for exams ui.
It does so by setting a signed cookie to the bitmask of the feature(s) you've turned on. This is implemented as middleware and I've made an effort to keep the code as minimal and unobtrusive as possible.
**Note:** the middleware uses `django.utils.deprecation.MiddlewareMixin`. I briefly explored upgrading our settings to avoid usage of this, but ran into difficulties and it's probably better dealt with separately anyway. I logged #2565 to address it later and noted the issues I ran into.
- In `.env` set `FEATURE_FLAG_QS_PREFIX=MM`
- Create an `ExamProfile` record for your user.
- Login and go to http://localhost:8079/dashboard/?MM_FEATURE_EXAMS=1
- Ensure you can get redirected to …

Added runtime feature flags via cookie (#2558)

---

.travis.yml
docker-compose.yml
travis-docker-compose.yml

Fixes #2646
Adds a link from the `selenium` container to the `grid` container. This fixes problems with running tests locally.
- Stop all containers
- Run `NODE_ENV=prod ./webpack_if_prod.sh` to generate javascript bundles
- Run `./scripts/tests/run_selenium_tests.sh`

Add link to grid for selenium container

---

ecommerce/api.py
ecommerce/api_test.py
ecommerce/constants.py
ecommerce/views.py
ecommerce/views_test.py

Fixes #2272 
- Ignores duplicate Cybersource cancellation messages
- Doesn't sent email alerting to cancellations
This is difficult to test since we're not sure why Cybersource sends duplicate Cybersource cancellation emails. For the other part of this, it's probably easiest just to test this on RC since all the environment variables and Cybersource configuration is already done there

Don't send email on order cancellations, ignore duplicate cancellations

---

micromasters/settings.py

Fixes #2219 
Reduces the `CONN_MAX_AGE` for postgres connections to 0 so they are immediately closed and don't pile up.
In master, run:
`docker-compose run db watch 'psql -h db -U postgres -c "SELECT client_host, client_port, state FROM pg_stat_activity"'`
And go to the homepage and refresh repeatedly. You should see a bunch of inactive connections from the web app pile up. 
Switch to this branch, refresh repeatedly and you should see those connections not accumulate anymore.

Reduced MAX_AGE for PG connections to 0 (#2219)

---

exams/signals_test.py
exams/utils.py
exams/utils_test.py

fixes https://github.com/mitodl/micromasters/issues/2560
Adds feature flag `FEATURE_SUPPRESS_PAYMENT_FOR_EXAM=True` to suppress the payment check for exam authorization
-Authorize for course after passing it, no need to pay.
@pdpinch

Exams: Added environment variable to suppress payment requirement

---

.dockerignore
.travis.yml

Fixes #2647 
References `travis-docker-compose.yml` which uses a prebuilt micromasters_python image
No manual testing needed, tests just have to pass

Use docker image on travis

---

scripts/test/run_selenium_tests.sh

None
Defines `ELASTICSEARCH_INDEX` when running selenium tests locally, so that running the tests won't clobber your existing index. This change isn't done on `.travis.yml` but it doesn't matter there since there is no other index
Run the selenium tests locally then start the docker container and verify that you can view the `/learners` page without a problem.

Use testindex when running selenium tests

---

test_requirements.txt

N/A
Pins `pytest-pylint` to 0.6.0 to avoid the weird behavior of version `0.7.0`
Run the tests locally: if you have version `0.7.0` the linting should happen all ahead of time.
Rebuilding the web container and removing the `.tox` with this PR should bring the behavior as it was last week.

Pinned pytest-pylint because of weird behavior of 0.7.0

---

dashboard/api.py
dashboard/api_test.py
dashboard/permissions.py
dashboard/permissions_test.py
dashboard/urls.py
dashboard/views.py
dashboard/views_test.py
micromasters/urls_test.py
static/js/actions/course_enrollments.js
static/js/actions/documents.js
static/js/actions/financial_aid.js
static/js/actions/index.js
static/js/actions/programs.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/OrderSummaryPage.js
static/js/lib/api.js
static/js/lib/api_test.js

this closes #2531
This does just the backend work to support fetching dashboard information based on a username URL parameter. For now the only change in the frontend it to the `getDashboard` function and adding `SETTINGS.user.username` in when necessary.
Make sure that the dashboard and all the frontend stuff works fine. If it does, I think things should be good.
If you wanted you could do the following (but I think it's not essential):
1. edit `DashboardPage.js` or `App.js`, adding:
```js
import * as api from '../lib/api';
window.api = api
```
then, from the JavaScript console, call:
```js
api.getDashboard('fake_username');
```
this should return a 404. confirm getting your own username returns a 200.
then, find the username of a real learner in your database, and ensure your user does …

allow fetching dashboard info for other users

---

dashboard/tasks.py
grades/management/commands/check_final_grade_freeze_status.py
grades/tasks.py
grades/tasks_test.py
micromasters/settings.py
requirements.in
requirements.txt

fixes #2659 
Adds a redis django cache backend to have a persistent cache to be used by the asynchronous tasks. 
The async tasks should just keep working (and there are tests for that).
If you want to test the persistence of the cache:
open the django shell, then:
```
from django.core.cache import caches
cache_redis = caches['redis']
cache_default = caches['default']
cache_redis.set('foo1', 'bar1')
cache_default.set('foo2', 'bar2')
```
if you type 
```
cache_redis.get('foo1')
cache_default.get('foo2')
```
both should give the right result back.
if you exit the django shell and enter again (you re-instanciate the docker instance)
```
cache_redis.get('foo1')
```
should give you the right result while the other should return `None`

Added redis django cache backend

---

financialaid/constants.py
financialaid/serializers.py
financialaid/templates/review_financial_aid.html
financialaid/views_test.py
mail/utils.py
mail/utils_test.py
static/js/financial_aid/functions.js

fixes https://github.com/mitodl/micromasters/issues/2117
- Allow staff to reset financial aid review form from `http://192.168.99.100:8079/financial_aid/review/6/auto-approved`
- Go to `http://192.168.99.100:8079/financial_aid/review/6/auto-approved`
- where 6 is `id` of financial aid program.
@pdpinch

Financial Aid: Allowed course team to reset students financial aid review form

---

static/js/actions/course_enrollments.js
static/js/actions/dashboard.js
static/js/actions/dashboard_test.js
static/js/actions/documents.js
static/js/actions/financial_aid.js
static/js/actions/index.js
static/js/actions/index_test.js
static/js/actions/programs.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/FinancialAidCalculator_test.js
static/js/containers/OrderSummaryPage.js
static/js/containers/OrderSummaryPage_test.js
static/js/containers/test_util.js
static/js/reducers/course_enrollments.js
static/js/reducers/course_enrollments_test.js
static/js/reducers/dashboard.js
static/js/reducers/documents_test.js
static/js/reducers/financial_aid_test.js
static/js/reducers/index.js
static/js/reducers/index_test.js
static/js/reducers/programs_test.js

this is a refactor, doing it as the first part of #2672 
this moves the dashboard-related actions and the dashboard reducer into separate files.
Just make sure that tests are passing and that the `/dashboard` loads up ok.

move dashboard actions and reducer into separate files

---

static/js/components/LearnerSearch.js
static/js/components/search/CustomSortingColumnHeaders.js
static/js/components/search/CustomSortingColumnHeaders_test.js
static/js/components/search/CustomSortingSelect.js
static/js/components/search/CustomSortingSelect_test.js
static/js/flow/searchTypes.js
static/scss/search-page.scss

Fixes #2632
Removes the sort select box and adds column headers to do the sorting instead
Go to the learner page and click the column headers. It should sort the results. You should also be able to refresh the browser and preserve the existing sort

Moved sorting UI to column headers

---

ecommerce/models.py
ecommerce/models_test.py

Fixes #2649 
Implements `str(CouponInvoice)`
Go to the Django admin, create a `CouponInvoice`, and verify that the invoice number and description show up in the text

Implement str(CouponInvoice)

---

selenium_tests/base.py
selenium_tests/basic_test.py

Part of #2632 
Fixes #2569
Adds a selenium test for learner search. This will make it easier to detect problems that show up when something's not quite right with searchkit
The test should pass
The test runs migrations in `setUp` which is very slow. Each test takes about 35 seconds just to run migrations. At some point we should dump and restore the database, but that's another PR

Added search test

---

dashboard/utils.py
ecommerce/api.py
ecommerce/api_test.py

Fixes #2561 
Changes the check for redeemable coupons to check enrollments instead of certificates.
With a user that has no certificates (ideally a new user to ensure a clean slate):
- Create a `Coupon` with type of `discounted-previous-course` for a course in a non-FA program
- Enroll that course (or create and enrollment for a previous course run)
- Edit your `CachedEnrollment` so you appear to have paid in edX by setting `data['mode'] = 'verified'`
- You should see a message on the course row indicating you have the discount.
- You should also now see the coupon if you go to http://localhost:8079/api/v0/coupons/

Fixed coupons to check enrollments instead of certs (#2561)

---

dashboard/utils.py

closes #2686
Removes an unnecessary `log.exception`
running a reindex  should not result on many exceptions for final grades.

Removed excessive logging from MMTrack

---

financialaid/serializers.py
financialaid/views_test.py

fixes https://github.com/mitodl/micromasters/issues/2687#issuecomment-282499934
- Save FinancialAid changes in FinancialAidAudit table.
- Reset or perform any other fa action`http://192.168.99.100:8079/financial_aid/review/(id)` and then check `http://192.168.99.100:8079/admin/financialaid/financialaidaudit/11/change/`` 
@pdpinch

[financial_aid/review]Created financialaidaudit objects when financial aid status is changed through ui

---

search/api.py
search/api_test.py
search/views_test.py

Fixes #2685 
Fixes filtering of elasticsearch queries to deal with some quirks in searchkit. Basically:
- The `update_from_dict` is moved to happen first so that server side filtering will overwrite it if necessary
- The root level filter element should actually be post_filter, so one is copied over the other. They seem to have equivalent functionality AFAIK. Searchkit is not using `post_filter` in `0.10.0` but it will switch in the next release to `post_filter` so the code should handle both cases.
Have two programs with users and only have a staff role in one of them. Log in as the staff user. You should see all users when you view the learners page for the program you are staff for, and no users or facets for the other program.
After this, try typing in a common letter in the text box. …

Fixed search filtering involving query parameters

---

micromasters/settings.py

Added the `AWS_S3_CUSTOM_DOMAIN` setting in order for S3 assets
managed via Django Storages library to be served via CloudFront.
Fixed #1922 
Configures Django Storages to use the Cloudfront dist instead of the S3 domain for S3 assets.
Set the `CLOUDFRONT_DIST` environment variable and verify that the links to e.g. profile images are pointed at Cloudfront instead of S3.
`micromasters/settings.py`
(Optional)
(Optional)
(Optional)

Added setting for Django Storage to use Cloudfront for S3 files

---

selenium_tests/basic_test.py

None
Fixes a flaky selenium test. It adds a wait for the react components to load on the page. Previously it just waited for the `body` to be available
Test should pass

Fix flaky test

---

static/images/search-icon.svg
static/js/components/LearnerSearch.js
static/js/components/search/CustomSortingColumnHeaders.js
static/js/components/search/LearnerResult.js
static/scss/_button.scss
static/scss/_variables.scss
static/scss/search-page.scss

#2682 
This fixes a small layout problem on the Learner search page, and makes several small style changes.
Make sure the page looks ok, nothing is broken, css looks correct.
Here are the changes:
- vertically center the Company facet selector text
- lighten font weight for user name
- fix spacing around column headers
- make search box and text smaller
- make user avatars smaller
- tighten row spacing
- remove the "Program Avg grade" copy in table cells.
- changed the column widths
- changed the font of the facet headers

Style changes to the Learner Search page

---

static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js

fixes https://github.com/mitodl/micromasters/issues/2670
Added state on search results
Go to `/learners/` and see data in resident field against US users.
@pdpinch

Search: Added states/regions to search results for US learners

---

exams/pearson/download.py
exams/pearson/download_test.py

Fixes #2716 
We send data to Pearson using the `Profile.student_id`, but we were looking it up by `Profile.id`. Locally this was fine, but in production some early users have those values differ.
Set `FEATURE_EXAM_SYNC=True` in `.env` and run this in a shell:
```python
from exams.models import ExamProfile, ExamAuthorization
from courses.models import Course
from exams import tasks
user = User.objects.get(username=<YOU>)
user.profile.student_id = 1000
user.profile.save()
ep = ExamProfile.objects.create(profile=user.profile)
tasks.export_exam_profiles()
```
Then run:
`docker-compose run web ./manage.py simulate_sftp_responses --poll`
And in the shell again:
```python
tasks.batch_process_pearson_zip_files()
ep.refresh_from_db()
print(ep.status)
``` …

Fixed ExamProfile lookup query (#2716)

---

dashboard/serializers.py
dashboard/serializers_test.py
search/api.py
search/api_test.py

fixes https://github.com/mitodl/micromasters/issues/2689
- Removed `program.email_optin` from search because we are showing it on profile index.
**Run:** `docker-compose run web ./manage.py recreate_index`
- test working of learners page, send emails when some users has email opt-in configure.

Removed program.email_optin from ES index

---

static/js/containers/LearnerPage.js
static/js/containers/ProfileFormContainer.js
static/js/containers/ProfilePage.js
static/js/containers/SettingsPage.js

part of #2456
came up as part of #2530
This refactors `ProfileFormContainer` to be a HOC instead of a class (which we sub-class elsewhere). I decided to go ahead and do this because, as I was working on #2530, I noticed that the `ProfileFormContainer` subclassing made the sub-classes very hard to change and hard to reason about. We had some very confusing indirection, including a method on the parent class which injected props relevant to the profile into the children of the subclass...yeah.
Anyway, this should make things much easier to read and should also clear the way for making the changes I'll need to make for #2530.
We just need to make sure that there are no regressions relating to profile code. I think it would be good to go through the profile flow and the `/learner` page, …

Refactor ProfileFormContainer into a HOC

---

static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

fixes #2721
This ensures that we validate strings composed of just whitespace the same way we do empty strings and null values.
Go to `/profile` and put a whitespace string in any field. You should get a validation error, and it should not make a request to save the profile. You should have to enter a legit value to get it to save.

fix profile validation

---

static/js/components/ProgramFilter.js
static/js/components/email/EmailCompositionDialog.js
static/js/components/email/hoc.js
static/js/components/email/lib.js
static/js/components/email/test_constants.js
static/js/components/search/WithSearchkitManager.js
static/js/containers/DashboardPage.js
static/js/containers/DashboardPage_test.js
static/js/containers/LearnerSearchPage.js
static/js/containers/LearnerSearchPage_test.js
static/js/flow/emailTypes.js
static/js/util/integration_test_helper.js

Fixes #2527 
This passes in searchkit as a prop in the email state so that we don't have to pass it to redux for the dialog to see it. This also refactors the searchkit manager code to live in a higher order class.
Go to the learners page and send an email. Everything should work as it did before.

Use searchkit from props instead of storing it in redux

---

static/js/components/dashboard/FinalExamCard.js
static/js/components/dashboard/FinalExamCard_test.js
static/js/util/util.js
static/js/util/util_test.js

closes #2735
We don't want the preferred name in this situation, we want the full name.
Oh gosh. Get the final exam card to appear, and then confirm that you can see your first and last names, and not your preferred name.
You can use the `mock_api.patch` here: https://github.com/aliceriot/mm_patches
This will set things up so that the 'Last Program' program is set up for showing the exam card.
Then you also need to enable the exam feature flag. You can do this by setting this environment variable:
```
MIDDLEWARE_FEATURE_FLAG_QS_PREFIX=MM
```
and then visiting `/dashboard/?MM_FEATURE_EXAMS=1`
that should do it?

Fix exam card name display

---

backends/exceptions.py
backends/utils.py
dashboard/api_edx_cache.py
dashboard/api_edx_cache_test.py
dashboard/views.py
dashboard/views_test.py

part of #2132
Handles 400 and 401 error coming from edX endpoints during cache refresh even if the access and refresh token are supposed to be valid.
From the admin go to `Home › Python Social Auth › User social auths` and open the social auth for your user. Modify the `"refresh_token"` and `"access_token"` and reload the dashboard.
The browser should redirect to the login page and come back. If you reload the user social auth the modified values should be updated.
`dashboard/api_edx_cache.py`

Modified user dashboard to handle 400 and 401 http errors

---

dashboard/api.py
dashboard/api_test.py

part of #2736 
Fixes 2 problems:
1. If an user has a frozen final grade for a course run BUT she did not pay for the course and the upgrade deadline is still in the future, the course appears as upgradable in the dashboard but the final grade is returned as well.
2. If the above mentioned course run (with exactly the same characteristics) is an old one and the user is currently enrolled in a newer run, the old run is returned with status `can-upgrade` as an old run.
**NOTE: this currently does not work on the dashboard UI but only in the dashboard REST API**
1. for the first part:
In a non financial aid program (for simplicity) take a course with multiple runs, then take the oldest of the runs. Set the upgrade deadline in the future. Then, using the `grade.factories.FinalGradeFactory` …

Added handling of can-upgrade status for past courses

---

exams/pearson/download.py
exams/pearson/download_test.py
exams/pearson/upload.py
exams/pearson/upload_test.py

Fixes #2753 
Adds `EOFError` to the set of errors considered retryable for sftp operations.
Not really a way to manually test this, the `EOFError` potentially gets raised by pysftp during operations. The code changes are minimal and covered in tests here. If they pass, we should be good.

Fixed EOFError (#2753)

---

static/js/components/ErrorMessage_test.js
static/js/containers/App_test.js
static/js/containers/DashboardPage.js
static/js/containers/LearnerSearchPage.js

Fixes #2027 
Removes the error messages if there is no currently selected enrollment. This can happen:
- if there are no programs the user is enrolled in
- when the user first loads the app, before we fetch from the programs API
- if we fail to fetch programs
The first case should not happen because the user must enroll in a program to complete their profile. The second case happens from time to time but is not an error, so we shouldn't show anything special in this case. For the third case we should show an error message. This PR fixes handling of the second case and leaves the handling of the third case as is.
Go to the dashboard. Clear `localStorage.redux` and refresh the page. You should not see any temporary error message. Repeat for `/learners`

Removed error message if there are no enrollments

---

static/js/components/OrderSummary.js
static/js/components/dashboard/CourseAction.js
static/js/components/dashboard/CourseAction_test.js
static/js/components/dashboard/CourseSubRow.js
static/js/components/dashboard/CourseSubRow_test.js
static/js/components/dashboard/util.js
static/scss/dashboard.scss

Fixes #2755 
Fixes the way that course runs are displayed when they are (a) past their end date, (b) passed, and (c) still upgradable (ie: their `upgrade_deadline` is in the future). Users will be able to pay for these courses from the dashboard UI.
For a course with multiple course runs:
1. Set a course run to current and enrolled or enrollable
1. Set another course run to have an `end_date` in the past and a future `upgrade_deadline`
1. Set a `FinalGrade` with a status of 'completed' for the course run in no. 2
1. Load the dashboard and inspect the UI. Click the pay button to make sure it works
CourseSubRow.js
@roberthouse54 spotted some layout tweaks that he wanted when I showed him the dashboard changes, so this PR includes those as well

Fixed dashboard UI to correctly display upgradable past course runs

---

static/scss/search-page.scss

https://github.com/mitodl/micromasters/issues/2682
This is a small PR. 
This was a part of the style changes to the Learner Search that didn't go through because I made the css change in the wrong file. This PR just makes the search box on the learner search smaller, and the font smaller.
Check to see that the layout looks correct.

Small change to size of search box on learner page

---

static/js/flow/profileTypes.js
static/js/lib/validation/profile.js
static/js/lib/validation/profile_test.js

fixes #2765 
This ensures that, for CA and US, the postal code entered is valid.
Go to `/profile` or `/learner`. Make your country the US. Add an invalid postal code. You should see an error message. Fix it, it should go away. Same for Canada.
US codes look like `XXXXX(-XXXX)`, where `X` is in `[0-9]` and the group wrapped in `()` is optional.
Canadian codes look like `YYYYYY`, where `Y` is in `[A-Za-z0-9]`.
The validation behavior should be unchanged for other countries.

Fix postal code validation

---

exams/pearson/download.py
exams/pearson/download_test.py
exams/pearson/exceptions.py
exams/pearson/readers.py
exams/pearson/readers_test.py
ui/middleware.py

Fixes #2761
Adds handling for potential row parsing errors due to bogus row data and bubbles them up to we alert on them. Specifically we were seeing `int()` casting fail on empty cell data, but we could see it for `datetime` parsing too so this was implemented generically.
- Ensure `FEATURE_PEARSON_EXAMS_SYNC=True` in `.env`
- Download the attached file [baddata.zip](https://github.com/mitodl/micromasters/files/817575/baddata.zip) (test file with bad rows we're trying to avoid)
- `cd` to the directory you downloaded it to
- `sftp -P 2022 odl@localhost` (p:`123`)
- `cd results`
- ` put baddata.zip`
- Open a django shell and run (you should not see any errors):
```
from exams import tasks
tasks.batch_process_pearson_zip_files()
```
exams/pearson/readers.py
exams/pearson/writers.py

Fixed TSV parsing to handle parsing errors (#2761)

---

exams/pearson/writers.py
exams/pearson/writers_test.py
requirements.in
requirements.txt

fixes #2766 
fixes the bug with the splitting of phone numbers in country code and actual number by user a proper library.
There is no real way to manually test it, but the unit test `test_profile_phone_number_functions` has been updated with several types of numbers included the ones of the issue that were causing problems.
`exams/pearson/writers.py`

Fixed phone numbers handling for pearson

---

ui/views.py

Fixes #2769 
Adds a feature flag to allow the exams card to be shown in 
- Set `MIDDLEWARE_FEATURE_FLAG_QS_PREFIX=MM` in `.env`
- Create an `ExamProfile` record for your user
- Verify that you can't see an exam card on the dashboard
- Go to http://localhost:8079/dashboard/?MM_FEATURE_EXAMS=1
- Verify you can see the card now
- Go to http://localhost:8079/dashboard/?MM_FEATURE_CLEAR
- Verify card is gone again
- Set `FEATURE_EXAMS_CARD_ENABLED=True` in .env
- Reload dash, verify you can see card
ui/views.py
https://media4.giphy.com/media/Jk8F8BanWi3Is/200w.gif

Added feature flag for showing exam card (#2769)

---

search/indexing_api.py
search/views_test.py
static/js/components/LearnerSearch.js
static/js/components/search/CustomSortingColumnHeaders.js
static/js/components/search/LearnerResult.js
static/js/components/search/LearnerResult_test.js
static/js/containers/LearnerSearchPage_test.js
static/scss/search-page.scss

fixes https://github.com/mitodl/micromasters/issues/2668
Added email and username as search able fields.
**Run:** `docker-compose run web ./manage.py recreate_index`
GO to `http://192.168.99.100:8079/learners/` and in search box add email or user name
@pdpinch

Search: Included username and e-mail address in name search

---

search/api.py
search/api_test.py
search/connection.py
search/indexing_api.py

None
Moves Elasticsearch connection logic to its own module, which will prevent circular imports in a future PR
Learner search page should still work, `./manage.py recreate_index` should work fine

Moved Elasticsearch connection management to own module

---

js_test.sh

No ticket
Changes the `./js_test.sh` script to let us run test cases that match specific test descriptions (ie: the `it`/`describe` strings). If you only want to run one or several tests in a JS test file, this allows you to do that easily
I used this command to test it: `./js_test.sh static/js/components/dashboard/CourseAction_test.js 'shows a message'`. You can test a few other files/descriptions

Configured JS test script to allow for specific test cases to be run

---

static/js/components/Learner.js
static/js/components/Navbar.js
static/js/components/ProgressWidget.js
static/js/components/StaffLearnerInfoCard.js
static/js/components/StaffLearnerInfoCard_test.js
static/js/components/dashboard/FinalExamCard_test.js
static/js/containers/LearnerPage.js
static/js/containers/LearnerPage_test.js
static/js/lib/roles.js
static/js/lib/roles_test.js
static/js/lib/sanctuary.js
static/js/lib/sanctuary_test.js
static/js/reducers/util.js
static/js/reducers/util_test.js
static/js/util/test_utils.js
static/scss/layout.scss
static/scss/progress-widget.scss
static/scss/staff-learner-info-card.scss

closes #2530 
Implements a card to show info about a learner's course stuff to a staff user.
(note: this is just the first part of the card, which incorporates part of the progress widget from the dashboard).
Make yourself a staff user on a program you're enrolled in, and visit your own learner page.

staff learner info card

---

dashboard/utils.py
dashboard/utils_test.py
exams/utils.py

Fixes #2796 
Removes extraneous checks for pass/paid and handles `FinalGrade.DoesNotExist` for exam authorization command.
Setup a course for exams (set `Program.exam_series_code` and `Course.exam_module` to some arbitrary string), enroll in a `CourseRun` for that course. Verify you have no `FinalGrade` in that `Course`. Run `./manage.py authorization_user_exam --program-id=?`
dashboard/utils.py

Fixed authorization_user_exam to authorize and not error (#2796)

---

ui/views_test.py

No ticket
Fixes faulty tests in `ui/views_test.py` that did not properly set a feature flag value
Set `FEATURE_EXAMS_CARD_ENABLED=True` in your `.env` file and run the tests in `ui/views_test.py`. If it works, all is well

Fixed faulty UI view tests

---

selenium_tests/base.py

Fixes #2799 
Filters out zendesk errors from the console assert for selenium tests. Zendesk is failing to load periodically on its own unfortunately, so this is not a good test of our Zendesk-related JS
None

Filter out zendesk errors

---

dashboard/utils.py
dashboard/utils_test.py

Fixes #2783 
The failed status was falling through to the default status where we log an error and return 'invalid'. 'invalid' is correct, but we don't want the logging. I added an assertion to the test for the log call and fixed the logic.
- Create an `ExamProfile` for yourself with `status='failed'` and load the dashboard. You should see no errors logged.
dashboard/utils.py
(Optional)

Fixed erroneous logging of ExamProfile.status (#2783)

---

js_test.sh
static/js/containers/LearnerPage.js
static/js/global_init.js
static/js/util/integration_test_helper.js

Fixes #2801 
The root cause of the intermittent errors was that the react component tree wasn't properly unmounted. This affected some creative use of the DOM by material-ui. To fix we check if the IntegrationTestHelper was used to create a DOM, then unmounts that div specifically in the global `afterEach` function.
To reproduce, check out master. Then go to `DashboardPage_test` and look for the test `without a race condition`. Go to `setTimeout` and comment out `resolve([coupon1])`. Run `npm test` and you should see the single test fail with a stack trace similar to the one in the issue.
Then checkout this branch but make sure that the `resolve([coupon1])` line is still commented out. Run the tests and you should see the test fail with a timeout error instead of the large stack trace. …

Fixed intermittent JS errors

---

js_test.sh

#2815 
Fixes the JS test script to correctly match test files
Run `./js_test.sh` and make sure it's matching all of the test files (should run 926 test cases)

Fixed JS test script to correctly match test files

---

static/scss/homepage.scss
static/scss/search-page.scss
ui/templates/background-images.css
ui/templates/base.html
ui/urls.py
ui/views.py

Fixes #2462
Moves our URL references out of the Sass files and into a file that is processed through the Django Templates system. This allows us to dynamically rewrite this file to point to whatever CDN we're using, if any.
Development: run the project locally, and ensure that the page still loads normally. All assets should continue to have local references, rather than pointing to CloudFront.
Production: set `CLOUDFRONT_DIST=d3o95baofem9lo` in your `.env` file and run the project. The page should appear the same as in development, but if you inspect the page, background images should be pointing to CloudFront. In particular, check the MIT logo at the top left of the page, the hero image on the home page, and the search spyglass icon to the left of the search input box.
This pull request …

Load CSS URLs through Django template

---

static/js/lib/api.js
static/js/lib/api_test.js

fixes #2776 
Forces a logout before the login after a 400 or 401 error from a rest api call.
1.  you need 2 users on edx and one of the 2 should not be a micromasters user.
2. login with the first user on micromasters and visit the dashboard
3. open another tab on the admin of micromasters and open the user social object of the logged in user
4. in another tab of the same browser logout from edx and login with the second user
5. on the micromasters admin, remove the content of the `extra_data` and save 
6. reload the dashboard 
what you should see is the login of the second user.
this is a fix for the issue observed in #2276

Force logout before login after a 400/401 error from rest API

---

search/base.py

Part of #2705
Patches search.tasks instead of search.indexing_api because patches should patch the module where it's invoked rather than the one where it's defined. This worked fine before because `search.indexing_api` functions usually just called other functions, but in a future PR this will not work because the percolate indexing work uses a function in `search.api`
This should only affect tests so no manual review is necessary

Patch search.tasks instead of search.indexing_api

---

exams/pearson/download.py
exams/pearson/download_test.py

Fixes #2803 
If we get a successful response but it has a warning in it we treat that as a failure so we get alerted and fix it.
This isn't easy to test, I suggest just reading the tests and verifying they pass.

Change VCDC processing to treat warnings as errors

---

grades/admin.py
grades/management/commands/check_final_grade_freeze_status.py
grades/management/commands/complete_course_run_freeze.py
grades/management/commands/freeze_final_grades.py
grades/models.py

N/A
Improves the management commands (and adds another one) to better deal with grades freezing.
1. for the `freeze_final_grades` try to freeze a course run with no "freeze grade": you should see a message saying that such date is missing
2. for the `freeze_final_grades` try to freeze a course run with "freeze grade" in the future: you should see a message saying that the grades cannot be frozen
3. for the `freeze_final_grades` try to freeze a course run that has already a "complete" entry in `CourseRunGradingStatus`: you should see again a message saying that the course is already complete.
4. for the `complete_corse_run_freeze`, try to run it for a course with no entry in `CourseRunGradingStatus`: you should see the course set to complete there (you can use the admin view)
5. for the …

Modified management commands for grades

---

dashboard/utils.py
dashboard/utils_test.py

Fixes #2814 
Fixes the dashboard UI so that exam authorizations that were created today and are schedule-able show the button to the user.
Create an `ExamProfile` and `ExamAuthorization` record for your user, both with `success` status. Test with setting `date_last_eligible` to today and then test `date_first_eligible` to the same.

Fix exam auth eligibility date handlingi (#2814)

---

grades/api.py
grades/api_test.py

fixes #2819  (hopefully)
modifies the function `grades.api.freeze_user_final_grade` to be race condition safe
I have not fully understood how users get in this situation: my guess is that the dashboard rest api is slow enough that they reload the page and trigger another request, but I have no proves for this.

Freeze grade modified to be race condition safe

---

mail/api.py
mail/api_test.py
mail/exceptions.py
mail/utils.py
mail/utils_test.py
mail/views.py
mail/views_test.py

Fixes #2749 
- adds tests for error handling for all MailgunClient functions
- adds a `raise_for_status` flag for a few of the functions, which defaults to **True**. This will cause an exception to be raised if the Mailgun response is not in the 2xx range.
- Changes `send_batch` to raise an exception if any of the batch calls raised an exception. There is also `raise_for_status` for this function which defaults to true. The exception is `SendBatchException` which contains a list of the failed email addresses so that we can make use of it later.
Send an email in all the ways that are available in the UI

Refactor MailgunClient for better error handling

---

courses/models.py
courses/models_test.py
static/js/components/dashboard/FinancialAidCard_test.js
static/js/constants.js

Fixes #2820
Changes the dashboard format string for formatting dates. Does _not_ change how months are formatted, e.g. for education and employment.
Verify that dates are formatted in the format described in #2820.

Change date format to be globally accessible

---

mail/views_test.py
search/base.py
search/indexing_api_test.py
search/models_test.py
search/signals.py

Part of #2705
Uses `transaction.on_commit` to workaround database information not being available to the Celery worker until after the transaction commits. Patches are added in tests to force `on_commit` to execute immediately, since all tests are run in a transaction and `on_commit` would delay action until after the test completes.

Add transaction.on_commit on signals

---

static/scss/search-page.scss

https://github.com/mitodl/micromasters/issues/2833
Fixes a gap between the histogram and slider in the grade facet. This was introduced by a searchkit upgrade.
See that there is no gap anymore.
This is a one-line fix.

Fixes layout issue with the Grade Histogram on the Search page

---

static/js/components/LearnerSearch.js
static/js/components/search/FilterVisibilityToggle.js
static/js/components/search/WorkHistoryFilter.js
static/scss/search-page.scss

fixes https://github.com/mitodl/micromasters/issues/2120
- Made facets title clickable, user can expand/hide search facets by clicking facet title
- Go to learners page and click the title of any facet.
@pdpinch

Allowed users to expand/hide search facets by clicking facet title
